### ISSUE TITLE
[BUG] Not working on Angular 10 project

### ISSUE THREAD

**Issue by Sampath-Lokuge** [compodoc/compodoc#1002]
Hi,

I have followed this guidance according to your Tutorial page. https://ionicacademy.com/ionic-code-documentation/

But it shows this error:

```
[19:17:16] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. 
(https://github.com/compodoc/compodoc/issues/new)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! q@1.0.0 compodoc: `compodoc -p tsconfig.json -w -s`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the q@1.0.0 compodoc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sampath\AppData\Roaming\npm-cache\_logs\2020-11-01T13_47_16_727Z-debug.log

```

This is the debug log:

```
 0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'compodoc'
1 verbose cli ]
2 info using npm@6.12.1
3 info using node@v12.13.1
4 verbose run-script [ 'precompodoc', 'compodoc', 'postcompodoc' ]
5 info lifecycle q@1.0.0~precompodoc: q@1.0.0
6 info lifecycle q@1.0.0~compodoc: q@1.0.0
7 verbose lifecycle q@1.0.0~compodoc: unsafe-perm in lifecycle true
8 verbose lifecycle q@1.0.0~compodoc: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\Clients\Ag\q\node_modules\.bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Sampath\bin;C:\Program Files\Java\jdk1.8.0_191\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Git\cmd;C:\Users\Sampath\AppData\Local\Android\Sdk\platform-tools;C:\Users\Sampath\AppData\Local\Android\Sdk\tools;C:\Program Files (x86)\Yarn\bin;C:\Program Files\dotnet;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn;C:\Program Files\Microsoft SQL Server\140\Tools\Binn;C:\Program Files\Microsoft SQL Server\140\DTS\Binn;C:\Program Files\Amazon\AWSCLI\bin;C:\Program Files\PuTTY;C:\Program Files\nodejs;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\150\Tools\Binn;C:\Program Files\Microsoft SQL Server\150\Tools\Binn;C:\Program Files\Microsoft SQL Server\150\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn;C:\Gradle\gradle-6.1.1\bin;C:\Users\Sampath\.windows-build-tools\python27;C:\Users\Sampath\AppData\Local\Microsoft\WindowsApps;C:\Users\Sampath\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Sampath\AppData\Local\Yarn\bin;C:\Users\Sampath\.dotnet\tools;C:\Users\Sampath\AppData\Local\Microsoft\WindowsApps;C:\Users\Sampath\AppData\Roaming\npm
9 verbose lifecycle q@1.0.0~compodoc: CWD: D:\Clients\Ag\q
10 silly lifecycle q@1.0.0~compodoc: Args: [ '/d /s /c', 'compodoc -p tsconfig.json -w -s' ]
11 silly lifecycle q@1.0.0~compodoc: Returned: code: 1  signal: null
12 info lifecycle q@1.0.0~compodoc: Failed to exec compodoc script
13 verbose stack Error: q@1.0.0 compodoc: `compodoc -p tsconfig.json -w -s`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid q@1.0.0
15 verbose cwd D:\Clients\Ag\q
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "compodoc"
18 verbose node v12.13.1
19 verbose npm  v6.12.1
20 error code ELIFECYCLE
21 error errno 1
22 error q@1.0.0 compodoc: `compodoc -p tsconfig.json -w -s`
22 error Exit status 1
23 error Failed at the q@1.0.0 compodoc script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```
**package.json**

{
  "name": "q",
  "version": "1.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --host=0.0.0.0",
    "build": "ng build --prod",
    "lint": "ng lint",
    "compodoc": "./node_modules/.bin/compodoc -p tsconfig.json -w -s"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^10.1.5",
    "@angular/cdk": "^10.2.4",
    "@angular/common": "^10.1.5",
    "@angular/compiler": "^10.1.5",
    "@angular/core": "^10.1.5",
    "@angular/fire": "^6.0.3",
    "@angular/forms": "^10.1.5",
    "@angular/platform-browser": "^10.1.5",
    "@angular/platform-browser-dynamic": "^10.1.5",
    "@angular/router": "^10.1.5",
    "@capacitor/android": "^2.4.2",
    "@capacitor/cli": "^2.4.2",
    "@capacitor/core": "^2.4.2",
    "@capacitor/ios": "^2.4.2",
    "@ionic-native/barcode-scanner": "^5.28.0",
    "@ionic-native/core": "^5.28.0",
    "@ionic-native/screen-orientation": "^5.28.0",
    "@sentry/angular": "^5.25.0",
    "@types/pulltorefreshjs": "^0.1.3",
    "cordova-plugin-ionic": "5.4.7",
    "cordova-plugin-screen-orientation": "^3.0.2",
    "cordova-plugin-whitelist": "^1.3.4",
    "es6-promise-plugin": "^4.2.2",
    "firebase": "^7.23.0",
    "lodash": "^4.17.20",
    "ng-cloudimage-responsive": "^2.1.3",
    "phonegap-plugin-barcodescanner": "^8.1.0",
    "primeflex": "^2.0.0",
    "primeicons": "^4.0.0",
    "primeng": "^10.0.3",
    "pulltorefreshjs": "^0.1.20",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.3",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/architect": "^0.1001.6",
    "@angular-devkit/build-angular": "^0.1001.6",
    "@angular/cli": "^10.1.6",
    "@angular/compiler-cli": "^10.1.5",
    "@compodoc/compodoc": "^1.1.11",
    "@sentry/cli": "^1.58.0",
    "@types/lodash": "^4.14.161",
    "@types/node": "^12.12.67",
    "codelyzer": "^6.0.1",
    "firebase-tools": "^8.12.1",
    "fuzzy": "^0.1.3",
    "inquirer": "^6.2.2",
    "inquirer-autocomplete-prompt": "^1.0.1",
    "open": "^7.3.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "^4.0.3"
  }
}

**Comment by Javaman2** [comment]
Try this in your pacakges.json
```
  "docs": "npx compodoc -p ./src/tsconfig.json -s -r 8085",
```
Then run 
```
npm run docs
```
I'm on Angular 10 and this works on my computer.
