### ISSUE TITLE
[BUG] : Error when launching compodoc

### ISSUE THREAD

**Issue by tonai** [compodoc/compodoc#1029]
Hello I am trying compodoc on a Angular project and currently running into an issue.
I try to run it with command `npx compodoc -p tsconfig.json src -s` or with `package.json` command.
I see it is parsing the file project but then stop and display the following output:
```
[18:37:04] parsing        : [PROJECT]/src/app/user/user-routing.module.ts
[18:37:04] Analysing routes definitions and clean them if necessary
[18:37:09] found          : UserRoutingModule
[18:37:09]                : - imports:
[18:37:09]                : 	- RouterModule
[18:37:09]                : - exports:
[18:37:09]                : 	- RouterModule
[18:37:09] parsing        : [PROJECT]/src/app/user/user.module.ts
[18:37:09] found          : UserModule
[18:37:09]                : - imports:
[18:37:09]                : 	- DesignSystemModule
[18:37:09]                : 	- UserRoutingModule
[18:37:09]                : 	- SharedModule
[18:37:09]                : - declarations:
[18:37:09]                : 	- UsersPageComponent
[18:37:09]                : 	- UsersListComponent
[18:37:09]                : 	- ChangePasswordPageComponent
[18:37:09]                : 	- UserEditProfilePageComponent
[18:37:09] parsing        : [PROJECT]/src/app/view/view-routing.module.ts
[18:37:09] Analysing routes definitions and clean them if necessary
Unhandled Rejection at: Promise {
  <rejected> InvalidOperationError: Expected to find an initializer.
      at InvalidOperationError.BaseError [as constructor] ([PROJECT]/node_modules/ts-simple-ast/dist/errors/BaseError.js:7:28)
      at new InvalidOperationError ([PROJECT]/node_modules/ts-simple-ast/dist/errors/InvalidOperationError.js:8:28)
      at Object.throwIfNullOrUndefined ([PROJECT]/node_modules/ts-simple-ast/dist/errors/helpers.js:96:15)
      at EnumMember.InitializerGetExpressionableNode.class_1.getInitializerOrThrow ([PROJECT]/node_modules/ts-simple-ast/dist/compiler/base/initializer/InitializerGetExpressionableNode.js:25:27)
      at RouterParserUtil.cleanFileDynamics ([PROJECT]/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:5677:80)
      at AngularDependencies.getSourceFileDecorators ([PROJECT]/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:8152:46)
      at [PROJECT]/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:7960:31
      at Array.map (<anonymous>)
      at AngularDependencies.getDependencies ([PROJECT]/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:7949:21)
      at CliApplication.Application.getDependenciesData ([PROJECT]/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:9498:40)
} reason: InvalidOperationError: Expected to find an initializer.
    at InvalidOperationError.BaseError [as constructor] ([PROJECT]/node_modules/ts-simple-ast/dist/errors/BaseError.js:7:28)
    at new InvalidOperationError ([PROJECT]/node_modules/ts-simple-ast/dist/errors/InvalidOperationError.js:8:28)
    at Object.throwIfNullOrUndefined ([PROJECT]/node_modules/ts-simple-ast/dist/errors/helpers.js:96:15)
    at EnumMember.InitializerGetExpressionableNode.class_1.getInitializerOrThrow ([PROJECT]/node_modules/ts-simple-ast/dist/compiler/base/initializer/InitializerGetExpressionableNode.js:25:27)
    at RouterParserUtil.cleanFileDynamics ([PROJECT]/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:5677:80)
    at AngularDependencies.getSourceFileDecorators ([PROJECT]/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:8152:46)
    at [PROJECT]/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:7960:31
    at Array.map (<anonymous>)
    at AngularDependencies.getDependencies ([PROJECT]/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:7949:21)
    at CliApplication.Application.getDependenciesData ([PROJECT]/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:9498:40)
[18:37:13] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! beyond-monitoring-frontend@1.1.0 docs:json: `compodoc -p ./tsconfig.json -e json -d .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the beyond-monitoring-frontend@1.1.0 docs:json script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tocab/.npm/_logs/2021-02-08T17_37_13_635Z-debug.log
```
Is there a way to have more information about the error ?

**Comment by TudorHornaiP5** [comment]
any updates on this?

**Comment by vogloblinsky** [comment]
Can you share `src/app/view/view-routing.module.ts` source code ?

**Comment by liquid-ocelot** [comment]
Hello, I have the same issue and I think it happens because I am using a UrlMatcher in my routes (I tried removing this urlmatcher and it worked after).

```typescript
import { NgModule } from '@angular/core';
import { RouterModule, Routes, UrlSegment, UrlMatcher } from '@angular/router';

import { CardPresenterComponent } from './card-presenter/card-presenter.component';
import { FileExplorerComponent } from './file-explorer/file-explorer.component';

const routes: Routes = [{
  matcher: (url) => {
    console.log("url");
    if (url.length > 0 && url[url.length - 1].path.match(/FS[0-9]+(.[0-9]+)?/)) {
      return{
        consumed:url
      };
    }
    return null;
  }, component: CardPresenterComponent
},
{ path: '**', component: FileExplorerComponent }
];



@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }

```

**Comment by tonai** [comment]
Sorry @vogloblinsky for my late answer.
Here is the content of `src/app/view/view-routing.module.ts` (I skipped imports):
```ts
const routes: Routes = [
  {
    path: '',
    pathMatch: 'full',
    component: LastViewPageComponent,
    canActivate: [IsAuthenticatedGuard, HasProjectAccess],
    resolve: { data: ViewPageDataResolver },
    data: { access: Access.View }
  },
  {
    path: 'create',
    pathMatch: 'full',
    component: ViewCreatePageComponent,
    canActivate: [IsAuthenticatedGuard, HasProjectAccess],
    canDeactivate: [ConfirmationLeaveSaveGuard],
    resolve: { data: ViewPageDataResolver },
    data: { access: Access.Create }
  },
  {
    path: ':viewId',
    pathMatch: 'full',
    component: ViewPageComponent,
    canActivate: [IsAuthenticatedGuard, HasProjectAccess],
    resolve: { data: ViewPageDataResolver },
    data: { access: Access.View }
  },
  {
    path: ':viewId/edit',
    pathMatch: 'full',
    component: ViewEditPageComponent,
    canActivate: [IsAuthenticatedGuard, HasProjectAccess],
    canDeactivate: [ConfirmationLeaveSaveGuard],
    resolve: { data: ViewPageDataResolver },
    data: { access: Access.Edit }
  }
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})
export class ViewRoutingModule {}
```
But it is the last file listed in the log probably because it is the last module of my project.

For information I use dynamic module loading in the main routing file `src/app/app-routing.module.ts` (I skipped some routes because they are many of them):
```ts
const routes: Routes = [
  { path: '', redirectTo: '/projects', pathMatch: 'full' },
  {
    path: 'projects/:projectId/graphs',
    loadChildren: () => import('./graph/graph.module').then((m) => m.GraphModule),
    data: {
      title: routeLabels.graph
    },
    canActivate: [IsAuthenticatedGuard]
  },
  {
    path: 'login',
    loadChildren: () => import('./login/login.module').then((m) => m.LoginModule),
    data: {
      title: routeLabels.login
    },
    canActivate: [IsNotAuthenticatedGuard]
  },
  {
    path: 'projects',
    loadChildren: () => import('./project/project.module').then((m) => m.ProjectModule),
    data: {
      title: routeLabels.projects
    },
    canActivate: [IsAuthenticatedGuard]
  },
  {
    path: 'users',
    loadChildren: () => import('./user/user.module').then((m) => m.UserModule),
    data: {
      title: routeLabels.users
    },
    canActivate: [IsAuthenticatedGuard]
  },
  {
    path: 'projects/:projectId/views',
    loadChildren: () => import('./view/view.module').then((m) => m.ViewModule),
    data: {
      title: routeLabels.views
    },
    canActivate: [IsAuthenticatedGuard]
  },
  { path: '403', component: Error403Component, data: { title: routeLabels.forbidden, isErrorPage: true } },
  { path: '404', component: Error404Component, data: { title: routeLabels.notFound, isErrorPage: true } },
  { path: '**', redirectTo: '/404' }
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule],
  providers: [{ provide: RouteReuseStrategy, useClass: SixbmRouteReuseStrategy }]
})
export class AppRoutingModule {}
```
