### ISSUE TITLE
[BUG] TypeError: Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by tehshin** [compodoc/compodoc#1036]
##### **Overview of the issue**

Compodoc can't parse a specific file in our project and throws an exception.

##### **Operating System, Node.js, npm, compodoc version(s)**

os: win 10
typescript: 3.8.3
compodoc version: 1.1.11
node.js version: v14.15.4

##### **Angular configuration, a `package.json` file in the root folder**

Can't share, closed source.

##### **Compodoc installed globally or locally ?**

Locally

##### **If possible sourcecode of the file where it breaks**

We have a file with the following content:
```
import { DynamicViewField } from './dynamic-view-field.model';
import { DynamicViewRow } from './dynamic-view-row.model';

type GetDataFn<T extends object> = (data: T) => string;

export type FieldPropOptions<T extends object> = GetDataFn<T> | Record<string, string> | string;
export type FieldPropArrayOptions<T extends object> = [string, ...FieldPropOptions<T>[]];
export type FieldOptions<T extends object> =
    | DynamicViewField<T>
    | FieldPropArrayOptions<T>
    | string;

type FieldConfig<T extends object> = {
    [K in keyof T]?: FieldOptions<T>;
};

/**
 * Dynamic view builder shorthand config for rows.
 */
export type DynamicViewBuilderRow<T extends object> = FieldConfig<T> & {
    [k: string]: FieldOptions<T>;
};

export type BuilderConfig<T extends object> = DynamicViewRow<T> | DynamicViewBuilderRow<T>;
```

##### **If possible your terminal logs before the error**

```
Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'text' of undefined
      at ClassHelper.visitTypeName (C:\Development\project-dir\modules\frontend\doc\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:6467:22)
      at ClassHelper.visitTypeName (C:\Development\project-dir\modules\frontend\doc\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:6470:21)
      at ClassHelper.visitType (C:\Development\project-dir\modules\frontend\doc\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:6556:45)
      at parseNode (C:\Development\project-dir\modules\frontend\doc\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8395:56)
      at C:\Development\project-dir\modules\frontend\doc\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8575:13
      at visitNodes (C:\Development\project-dir\modules\frontend\doc\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:14786:30)
      at Object.forEachChild (C:\Development\project-dir\modules\frontend\doc\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:15012:24)
      at AngularDependencies.getSourceFileDecorators (C:\Development\project-dir\modules\frontend\doc\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8155:16)
      at C:\Development\project-dir\modules\frontend\doc\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:7960:31
      at Array.map (<anonymous>)
} reason: TypeError: Cannot read property 'text' of undefined
    at ClassHelper.visitTypeName (C:\Development\project-dir\modules\frontend\doc\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:6467:22)
    at ClassHelper.visitTypeName (C:\Development\project-dir\modules\frontend\doc\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:6470:21)
    at ClassHelper.visitType (C:\Development\project-dir\modules\frontend\doc\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:6556:45)
    at parseNode (C:\Development\project-dir\modules\frontend\doc\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8395:56)
    at C:\Development\project-dir\modules\frontend\doc\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8575:13
    at visitNodes (C:\Development\project-dir\modules\frontend\doc\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:14786:30)
    at Object.forEachChild (C:\Development\project-dir\modules\frontend\doc\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:15012:24)
    at AngularDependencies.getSourceFileDecorators (C:\Development\project-dir\modules\frontend\doc\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8155:16)
    at C:\Development\project-dir\modules\frontend\doc\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:7960:31
    at Array.map (<anonymous>)
[13:57:34] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
```

##### **Motivation for or Use Case**

Our build process for our internal documentation fails.

##### **Reproduce the error**

If the issue is not reproducible for you, we can try to setup a sample project somewhere that includes the above mentioned code.

##### **Suggest a Fix**

My first guess is that ts-simple-ast has problems with certain typescript features that are not available in 2.9.1.

**Comment by vogloblinsky** [comment]
fixed by c7cd839 but need to be completely implemented with #1053
