### ISSUE TITLE
[BUG] InvalidOperationError: Could not find the node's symbol  -> Unhandled Rejection

### ISSUE THREAD

**Issue by Sebastian-G** [compodoc/compodoc#1042]
Running the "compodoc -p tsconfig.json src --hideGenerator --assetsFolder readme" command results in an error.

Please help me fixing it.

```
[11:48:29] Analysing routes definitions and clean them if necessary
Unhandled Rejection at: Promise {
  <rejected> InvalidOperationError: Could not find the node's symbol.
      at InvalidOperationError.BaseError [as constructor] (/top-secret/node_modules/ts-simple-ast/dist/errors/BaseError.js:7:28)
      at new InvalidOperationError (/top-secret/node_modules/ts-simple-ast/dist/errors/InvalidOperationError.js:8:28)
      at Object.throwIfNullOrUndefined (/top-secret/node_modules/ts-simple-ast/dist/errors/helpers.js:96:15)
      at Identifier.Node.getSymbolOrThrow (/top-secret/node_modules/ts-simple-ast/dist/compiler/common/Node.js:131:23)
      at RouterParserUtil.cleanFileDynamics (/top-secret/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:5668:18)
      at AngularDependencies.getSourceFileDecorators (/top-secret/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:8152:46)
      at /top-secret/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:7960:31
      at Array.map (<anonymous>)
      at AngularDependencies.getDependencies (/top-secret/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:7949:21)
      at CliApplication.Application.getDependenciesData (/top-secret/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:9498:40)
} reason: InvalidOperationError: Could not find the node's symbol.
    at InvalidOperationError.BaseError [as constructor] (/top-secret/node_modules/ts-simple-ast/dist/errors/BaseError.js:7:28)
    at new InvalidOperationError (/top-secret/node_modules/ts-simple-ast/dist/errors/InvalidOperationError.js:8:28)
    at Object.throwIfNullOrUndefined (/top-secret/node_modules/ts-simple-ast/dist/errors/helpers.js:96:15)
    at Identifier.Node.getSymbolOrThrow (/top-secret/node_modules/ts-simple-ast/dist/compiler/common/Node.js:131:23)
    at RouterParserUtil.cleanFileDynamics (/top-secret/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:5668:18)
    at AngularDependencies.getSourceFileDecorators (/top-secret/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:8152:46)
    at /top-secret/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:7960:31
    at Array.map (<anonymous>)
    at AngularDependencies.getDependencies (/top-secret/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:7949:21)
    at CliApplication.Application.getDependenciesData (/top-secret/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:9498:40)
[11:48:30] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
```

_Originally posted by @Sebastian-G in https://github.com/compodoc/compodoc/issues/1000#issuecomment-802738099_

**Comment by Sebastian-G** [comment]
I was able to fix my issue by changing the Routes array type 😞 

Related to #525 see following command:
https://github.com/compodoc/compodoc/issues/525#issuecomment-414624459

Please fix this 🐛

**Comment by fstodulski** [comment]
This one works:
```
  {
    path: 'forms',
    loadChildren: () =>
      import('./screens/forms/forms.module').then((m) => m.FormsModule),
  },
  {
    path: 'buttons',
    loadChildren: () =>
      import('./screens/buttons/buttons.module').then((m) => m.ButtonsModule),
  },
  ```
  
  
  this doesn't:
  ```
    {
    path: 'forms',
    loadChildren: async () =>
      (await import('./screens/forms/forms.module')).FormsModule,
  },
  {
    path: 'buttons',
    loadChildren: async () =>
      (await import('./screens/buttons/buttons.module')).ButtonsModule,
  },
  ```

**Comment by fstodulski** [comment]
![image](https://user-images.githubusercontent.com/14015728/116888567-e9bd4a80-ac2b-11eb-898c-41b9d6a7307f.png)

**Comment by Sebastian-G** [comment]
We are already using the `import(...)..then(...)` Promise. 
And the issue occurred.

```typescript
{
    path: RouteEnum.MY_MEASUREMENTS,
    loadChildren: () => import('./measurements/my-measurements').then(mod => mod.MyMeasurementsModule),
    ...
  },
```

**Comment by Sebastian-G** [comment]
Any news?

**Comment by Sebastian-G** [comment]
I was able to fix the issue by adding `<ENUM>.ofValue()` to all Roles. 👎

In addition it seems only to be an issue if the Enum is imported by ts shorted paths. e.g `import {Role} from '@shared/models';` on another file, we used the direct import (see `import {Role} from '../shared/models';`), which didn't require the `.ofValue()`

**Comment by ArtifexEt** [comment]
I have seen few bugs closed with this problem.  `.ofValue()` or change files to direct import is not a solution. Please think about fixing this problem instead of closing bugs.

**Comment by sgabb** [comment]
Same error for me (Angular 11.2, compodoc 11.1.1):

`
[] parsing: /path/src/app/modules/main/main-routing.module.ts
[] Analysing routes definitions and clean them if necessary
Unhandled Rejection at: Promise {
  <rejected> InvalidOperationError: Could not find the node's symbol.
      at InvalidOperationError.BaseError [as constructor] (/path/node_modules/ts-simple-ast/dist/errors/BaseError.js:7:28)
      at new InvalidOperationError (/path/node_modules/ts-simple-ast/dist/errors/InvalidOperationError.js:8:28)
      at Object.throwIfNullOrUndefined (/path/node_modules/ts-simple-ast/dist/errors/helpers.js:96:15)
      at Identifier.Node.getSymbolOrThrow (/path/node_modules/ts-simple-ast/dist/compiler/common/Node.js:131:23)
      at RouterParserUtil.cleanFileDynamics (/path/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:5668:18)
      at AngularDependencies.getSourceFileDecorators (/path/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:8152:46)
      at /path/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:7960:31
      at Array.map (<anonymous>)
      at AngularDependencies.getDependencies (/path/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:7949:21)
      at CliApplication.Application.getDependenciesData (/path/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:9498:40)
} reason: InvalidOperationError: Could not find the node's symbol.
    at InvalidOperationError.BaseError [as constructor] (/path/node_modules/ts-simple-ast/dist/errors/BaseError.js:7:28)
    at new InvalidOperationError (/path/node_modules/ts-simple-ast/dist/errors/InvalidOperationError.js:8:28)
    at Object.throwIfNullOrUndefined (/path/node_modules/ts-simple-ast/dist/errors/helpers.js:96:15)
    at Identifier.Node.getSymbolOrThrow (/path/node_modules/ts-simple-ast/dist/compiler/common/Node.js:131:23)
    at RouterParserUtil.cleanFileDynamics (/path/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:5668:18)
    at AngularDependencies.getSourceFileDecorators (/path/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:8152:46)
    at /path/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:7960:31
    at Array.map (<anonymous>)
    at AngularDependencies.getDependencies (/path/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:7949:21)
    at CliApplication.Application.getDependenciesData (/path/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:9498:40)
[17:20:50] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
`

Routing module is something like:

`
const routes: Routes = [
  {
    path: '',
    component: MainComponent,
    canActivate: [Guard1, AuthGuard],
    children: [
        {
            path: '',
            canActivateChild: [AuthGuard],
            children: [
                {
                  path: environment.urlApp.url1,
                  loadChildren: () => import('./m1/m1.module').then(m => m.M1Module)
                },
                {
                  path: environment.urlApp.url2,
                  loadChildren: () => import('./m2/m2.module').then(m => m.M2Module)
                },
                {
                  path: environment.urlApp.url3,
                  loadChildren: () => import('./m3/m3.module').then(m => m.M3Module)
                }
            ]
        }
    ]
  }
];
@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})
export class MainRoutingModule { }
`

**Comment by vogloblinsky** [comment]
Fixed for these syntaxes :
```
{
        path: 'about',
        loadChildren: './about/about.module#AboutModule'
}
{
        path: 'about',
        loadChildren: (): Promise<AboutModule> => import('./about/about.module').then(m => m.AboutModule)
}
{
        path: 'about',
        loadChildren: () => import('./about/about.module').then(m => m.AboutModule)
}
{
        path: 'about',
        loadChildren: async () => (await import('./about/about.module')).AboutModule
}
```

**Comment by roma2341** [comment]
Error still happen in Compodoc v1.1.22

**Comment by robmanganelly** [comment]
Got the same bug while using compodoc + storybook + @nx/angular

one of the elements on my routes is a spreaded array generated from a function

```typescript

function authRoutes<T,K>(a:Type<T>, b:Type<K>):Route[]{ ... }

export const appRoutes: Routes = [
{
 path: 'foo',
 component: FooComponent,
},
...authRoutes(LoginComponent, LogoutComponent,NotFoundComponent),
]

```
I do not execute compodoc directly, the execution is part of the `storybook` target
