### ISSUE TITLE
[BUG] When generating a document

### ISSUE THREAD

**Issue by nareshsystembind** [compodoc/compodoc#1045]
Getting below error when using this tool

Unhandled Rejection at: Promise {
  <rejected> InvalidOperationError: Expected to find an initializer.
      at InvalidOperationError.BaseError [as constructor] (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\ts-simple-ast\dist\errors\BaseError.js:7:28)
      at new InvalidOperationError (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\ts-simple-ast\dist\errors\InvalidOperationError.js:8:28)
      at Object.throwIfNullOrUndefined (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\ts-simple-ast\dist\errors\helpers.js:96:15)
      at EnumMember.InitializerGetExpressionableNode.class_1.getInitializerOrThrow (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\ts-simple-ast\dist\compiler\base\initializer\InitializerGetExpressionableNode.js:25:27)
      at RouterParserUtil.cleanFileDynamics (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:5677:80)
      at AngularDependencies.getSourceFileDecorators (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8152:46)
      at C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:7960:31
      at Array.map (<anonymous>)
      at AngularDependencies.getDependencies (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:7949:21)
      at CliApplication.Application.getDependenciesData (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:9498:40)
} reason: InvalidOperationError: Expected to find an initializer.
    at InvalidOperationError.BaseError [as constructor] (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\ts-simple-ast\dist\errors\BaseError.js:7:28)
    at new InvalidOperationError (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\ts-simple-ast\dist\errors\InvalidOperationError.js:8:28)
    at Object.throwIfNullOrUndefined (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\ts-simple-ast\dist\errors\helpers.js:96:15)
    at EnumMember.InitializerGetExpressionableNode.class_1.getInitializerOrThrow (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\ts-simple-ast\dist\compiler\base\initializer\InitializerGetExpressionableNode.js:25:27)
    at RouterParserUtil.cleanFileDynamics (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:5677:80)
    at AngularDependencies.getSourceFileDecorators (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8152:46)
    at C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:7960:31
    at Array.map (<anonymous>)
    at AngularDependencies.getDependencies (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:7949:21)
    at CliApplication.Application.getDependenciesData (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:9498:40)
[21:20:04] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)

**Comment by everdev** [comment]
I got the same issue

**Comment by vogloblinsky** [comment]
Can you share the sourcecode of the file where Compodoc breaks ?
