### ISSUE TITLE
[BUG] Problem during parsing or generation of the documentation

### ISSUE THREAD

**Issue by Atom1er** [compodoc/compodoc#1051]
Error when running npx compodoc -p src/tsconfig.app.json
SyntaxError: Invalid regular expression: path/to/project/root/: Unmatched ')'

Any help will be appreciated!

**Comment by vogloblinsky** [comment]
Can you share the context of your issue ?

**Comment by bertutron** [comment]
Hi, i have the same problem, the file content where it occurs is as followed:

```typescript
import { CategoryObject, SpotifyObject } from './spotify-objects.rest-reply';

const EndPoint2ResponseType: { [x in ApiEndPoints]?: SpotifyObject } = {
  'http://api.spotify.com/v1/browse/categories': CategoryObject,
};
type ApiBrowseEndPoints =
    'browse/new-releases' |
    'browse/featured-playlists' |
    'browse/categories' |
    `browse/categories/${string}` |
    `browse/categories/${string}/playlists` |
    'recommendations' |
    'recommendations/available-genre-seeds';

type ApiBaseUrlV1 = 'http://api.spotify.com/v1';

type ApiEndPoints = `${ApiBaseUrlV1}/${ApiBrowseEndPoints}`;

export default {
  EndPoint2ResponseType,
};
```

the error text is

> 10:52:07] parsing        : C:/repos/angular-spotify-et-al/src/app/spotify/_types/api-routes.type.ts
Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'text' of undefined
      at ClassHelper.visitTypeName (C:\repos\angular-spotify-et-al\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:6467:22)  
      at ClassHelper.visitTypeName (C:\repos\angular-spotify-et-al\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:6470:21)  
      at ClassHelper.visitType (C:\repos\angular-spotify-et-al\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:6525:45)      
      at parseNode (C:\repos\angular-spotify-et-al\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8395:56)
      at C:\repos\angular-spotify-et-al\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8575:13
      at visitNodes (C:\repos\angular-spotify-et-al\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:14786:30)        
      at Object.forEachChild (C:\repos\angular-spotify-et-al\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:15012:24)
      at AngularDependencies.getSourceFileDecorators (C:\repos\angular-spotify-et-al\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8155:16)
      at C:\repos\angular-spotify-et-al\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:7960:31
      at Array.map (<anonymous>)
} reason: TypeError: Cannot read property 'text' of undefined
    at ClassHelper.visitTypeName (C:\repos\angular-spotify-et-al\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:6467:22)    
    at ClassHelper.visitTypeName (C:\repos\angular-spotify-et-al\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:6470:21)    
    at ClassHelper.visitType (C:\repos\angular-spotify-et-al\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:6525:45)        
    at parseNode (C:\repos\angular-spotify-et-al\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8395:56)
    at C:\repos\angular-spotify-et-al\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8575:13
    at visitNodes (C:\repos\angular-spotify-et-al\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:14786:30)
    at Object.forEachChild (C:\repos\angular-spotify-et-al\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:15012:24) 
    at AngularDependencies.getSourceFileDecorators (C:\repos\angular-spotify-et-al\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8155:16)
    at C:\repos\angular-spotify-et-al\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:7960:31
    at Array.map (<anonymous>)

hth

**Comment by Jakob-em** [comment]
I am experiencing the same problem when using template literal types

**Comment by marleypowell** [comment]
I also have the same issue with template literal types.

**Comment by marleypowell** [comment]
```ts
export type ThemePalette = 'primary' | 'secondary' | 'accent' | 'warning';

export type ButtonTypes = 'icon-and-text' | 'small' | 'block' | 'add';

export type ButtonThemePalette = ThemePalette | ButtonTypes | `${ThemePalette} ${ButtonTypes}`;

```

```
[09:58:40] parsing        : C:/Users/marley.powell/source/repos/exclaimercloud-ui-library/exclaimer/libs/types/components/theme-palette.ts
Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'text' of undefined
      at ClassHelper.visitTypeName (C:\Users\marley.powell\source\repos\exclaimercloud-ui-library\exclaimer\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:6467:22)
      at ClassHelper.visitTypeName (C:\Users\marley.powell\source\repos\exclaimercloud-ui-library\exclaimer\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:6470:21)
      at ClassHelper.visitType (C:\Users\marley.powell\source\repos\exclaimercloud-ui-library\exclaimer\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:6525:45)
      at parseNode (C:\Users\marley.powell\source\repos\exclaimercloud-ui-library\exclaimer\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8395:56)
      at C:\Users\marley.powell\source\repos\exclaimercloud-ui-library\exclaimer\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8575:13
      at visitNodes (C:\Users\marley.powell\source\repos\exclaimercloud-ui-library\exclaimer\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:14786:30)
      at Object.forEachChild (C:\Users\marley.powell\source\repos\exclaimercloud-ui-library\exclaimer\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:15012:24)
      at AngularDependencies.getSourceFileDecorators (C:\Users\marley.powell\source\repos\exclaimercloud-ui-library\exclaimer\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8155:16)
      at C:\Users\marley.powell\source\repos\exclaimercloud-ui-library\exclaimer\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:7960:31
      at Array.map (<anonymous>)
} reason: TypeError: Cannot read property 'text' of undefined
    at ClassHelper.visitTypeName (C:\Users\marley.powell\source\repos\exclaimercloud-ui-library\exclaimer\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:6467:22)
    at ClassHelper.visitTypeName (C:\Users\marley.powell\source\repos\exclaimercloud-ui-library\exclaimer\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:6470:21)
    at ClassHelper.visitType (C:\Users\marley.powell\source\repos\exclaimercloud-ui-library\exclaimer\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:6525:45)
    at parseNode (C:\Users\marley.powell\source\repos\exclaimercloud-ui-library\exclaimer\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8395:56)
    at C:\Users\marley.powell\source\repos\exclaimercloud-ui-library\exclaimer\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8575:13
    at visitNodes (C:\Users\marley.powell\source\repos\exclaimercloud-ui-library\exclaimer\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:14786:30)
    at Object.forEachChild (C:\Users\marley.powell\source\repos\exclaimercloud-ui-library\exclaimer\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:15012:24)
    at AngularDependencies.getSourceFileDecorators (C:\Users\marley.powell\source\repos\exclaimercloud-ui-library\exclaimer\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8155:16)
    at C:\Users\marley.powell\source\repos\exclaimercloud-ui-library\exclaimer\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:7960:31
    at Array.map (<anonymous>)
[09:58:40] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
error Command failed with exit code 1.
```

**Comment by lacolaco** [comment]
I'm in the same situation. Anyone found any workaround?

**Comment by Jakob-em** [comment]
@lacolaco The current workaround that I am using is excluding the file which contains the template type from the compodoc run via the tsconfig. I moved the type to a separate file to keep the related components in the generated documentation.
