### ISSUE TITLE
[BUG] Generation of the documentation

### ISSUE THREAD

**Issue by gabrycasu** [compodoc/compodoc#1061]
Hello,
I report an error occurred while generating the Documentation of an Angular project.
The Project has no errors so I can't understand the problem.
Below I attach the Log of the error:

Unhandled Rejection at: Promise {
<rejected> { SyntaxError: JSON5: invalid character '+' at 1:108
npm verb node v10.15.1
npm verb npm  v6.4.1
npm ERR! code ELIFECYCLE
npm ERR! errno 1

The versions of the project are as follows:
Angular: 11.0.9
compodoc: 1.1.11

**Comment by TanMichael** [comment]
Same error.
Firstly, I tried to fix the Lazy loaded routes are not documented issue. By applying the workaround that  @headonkeyboard  mentions in https://github.com/compodoc/compodoc/issues/954#issuecomment-708987583 
Then I got the JSON5 error:

Unhandled Rejection at: Promise {
  <rejected> SyntaxError: JSON5: invalid character '(' at 1:188
      at syntaxError (/Users/***/node_modules/json5/lib/parse.js:1083:17)
      at invalidChar (/Users/***/node_modules/json5/lib/parse.js:1028:12)
      at Object.value (/Users/***/node_modules/json5/lib/parse.js:287:15)
      at lex (/Users/***/node_modules/json5/lib/parse.js:78:42)
      at Object.parse (/Users/***/node_modules/json5/lib/parse.js:25:17)
      at loopInsideModule (/Users/***/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:5370:52)
      at loopRoutesParser (/Users/***/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:5403:29)
      at loopRoutesParser (/Users/***/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:5408:21)
      at RouterParserUtil.constructRoutesTree (/Users/***/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:5412:9)
      at AngularDependencies.getDependencies (/Users/***/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:8038:50) {
    lineNumber: 1,
    columnNumber: 188
  }

**Comment by vogloblinsky** [comment]
Please, provide code example for reproduce the error.
