### ISSUE TITLE
[BUG] NotImplementedError during generating

### ISSUE THREAD

**Issue by jsparidaans** [compodoc/compodoc#1065]
> Overview of the issue

`compodoc -p tsconfig.doc.json src` results in NotImplementedError

> Operating System, Node.js, npm, compodoc version(s)

Compodoc version: 1.1.11

TypeScript version used by Compodoc : 2.9.1

TypeScript version of current project : 4.1.2

Node.js version : v14.15.2

Operating system : Windows 10

> Angular configuration, a package.json file in the root folder

`package.json`
```json 
{
  "name": "portalv2",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "compodoc": "compodoc -p tsconfig.doc.json src"
  },
  "private": true,
  "dependencies": {
    "@angular-material-components/color-picker": "^5.0.2",
    "@angular/animations": "^11.2.10",
    "@angular/cdk": "^11.2.1",
    "@angular/common": "~11.2.1",
    "@angular/compiler": "~11.2.1",
    "@angular/core": "~11.2.1",
    "@angular/flex-layout": "^11.0.0-beta.33",
    "@angular/forms": "~11.2.1",
    "@angular/google-maps": "^11.2.3",
    "@angular/material": "^11.2.1",
    "@angular/platform-browser": "~11.2.1",
    "@angular/platform-browser-dynamic": "~11.2.1",
    "@angular/router": "~11.2.1",
    "@ngneat/until-destroy": "^8.0.4",
    "@types/file-saver": "^2.0.1",
    "bootstrap": "^4.6.0",
    "chart.js": "^2.9.3",
    "file-saver": "^2.0.5",
    "jquery": "^3.5.1",
    "ng2-charts": "^2.3.0",
    "popper.js": "^1.14.3",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "uuid": "^8.3.2",
    "zone.js": "~0.11.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1102.1",
    "@angular/cli": "~11.2.1",
    "@angular/compiler-cli": "~11.2.1",
    "@compodoc/compodoc": "^1.1.11",
    "@types/jasmine": "^3.6.9",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "ng2-charts-schematics": "^0.1.7",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.1.2"
  }
}

```

`tsconfig.json`
```json 
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "module": "es2020",
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false
  }
}

```
> Compodoc installed globally or locally ?

locally installed as dev dependency

> If possible sourcecode of the file where it breaks

```

[14:35:17] parsing        : C:/Users/jsparidaans/PhpstormProjects/portalv2/src/app/vehicle/vehicle.component.ts
[14:35:17] Empty metadatas, trying to find it with imports.
```

> Error

```
Unhandled Rejection at: Promise {
  <rejected> NotImplementedError: Not implemented feature for syntax kind 'ArrayBindingPattern'.
      at NotImplementedError.BaseError [as constructor] (C:\Users\jsparidaans\PhpstormProjects\portalv2\node_modules\ts-simple-ast\dist\errors\BaseError.js:7:28)
      at new NotImplementedError (C:\Users\jsparidaans\PhpstormProjects\portalv2\node_modules\ts-simple-ast\dist\errors\NotImplementedError.js:8:28)
      at Object.getNotImplementedForSyntaxKindError (C:\Users\jsparidaans\PhpstormProjects\portalv2\node_modules\ts-simple-ast\dist\errors\helpers.js:76:12)
      at VariableDeclaration.BindingNamedNodeInternal.class_1.getNameNode (C:\Users\jsparidaans\PhpstormProjects\portalv2\node_modules\ts-simple-ast\dist\compiler\base\name\BindingNamedNode.js:24:34)
      at VariableDeclaration.BindingNamedNodeInternal.class_1.getName (C:\Users\jsparidaans\PhpstormProjects\portalv2\node_modules\ts-simple-ast\dist\compiler\base\name\BindingNamedNode.js:28:25)
      at findFunc (C:\Users\jsparidaans\PhpstormProjects\portalv2\node_modules\ts-simple-ast\dist\utils\compiler\getNodeByNameOrFindFunction.js:7:71)
      at Function.ArrayUtils.find (C:\Users\jsparidaans\PhpstormProjects\portalv2\node_modules\ts-simple-ast\dist\utils\ArrayUtils.js:38:21)
      at Object.getNodeByNameOrFindFunction (C:\Users\jsparidaans\PhpstormProjects\portalv2\node_modules\ts-simple-ast\dist\utils\compiler\getNodeByNameOrFindFunction.js:10:36)
      at SourceFile.StatementedNode.class_1.getVariableDeclaration (C:\Users\jsparidaans\PhpstormProjects\portalv2\node_modules\ts-simple-ast\dist\compiler\statement\StatementedNode.js:312:28)
      at ImportsUtil.findValueInImportOrLocalVariables (C:\Users\jsparidaans\PhpstormProjects\portalv2\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:4916:64)
} reason: NotImplementedError: Not implemented feature for syntax kind 'ArrayBindingPattern'.
    at NotImplementedError.BaseError [as constructor] (C:\Users\jsparidaans\PhpstormProjects\portalv2\node_modules\ts-simple-ast\dist\errors\BaseError.js:7:28)
    at new NotImplementedError (C:\Users\jsparidaans\PhpstormProjects\portalv2\node_modules\ts-simple-ast\dist\errors\NotImplementedError.js:8:28)
    at Object.getNotImplementedForSyntaxKindError (C:\Users\jsparidaans\PhpstormProjects\portalv2\node_modules\ts-simple-ast\dist\errors\helpers.js:76:12)
    at VariableDeclaration.BindingNamedNodeInternal.class_1.getNameNode (C:\Users\jsparidaans\PhpstormProjects\portalv2\node_modules\ts-simple-ast\dist\compiler\base\name\BindingNamedNode.js:24:34)
    at VariableDeclaration.BindingNamedNodeInternal.class_1.getName (C:\Users\jsparidaans\PhpstormProjects\portalv2\node_modules\ts-simple-ast\dist\compiler\base\name\BindingNamedNode.js:28:25)
    at findFunc (C:\Users\jsparidaans\PhpstormProjects\portalv2\node_modules\ts-simple-ast\dist\utils\compiler\getNodeByNameOrFindFunction.js:7:71)
    at Function.ArrayUtils.find (C:\Users\jsparidaans\PhpstormProjects\portalv2\node_modules\ts-simple-ast\dist\utils\ArrayUtils.js:38:21)
    at Object.getNodeByNameOrFindFunction (C:\Users\jsparidaans\PhpstormProjects\portalv2\node_modules\ts-simple-ast\dist\utils\compiler\getNodeByNameOrFindFunction.js:10:36)
    at SourceFile.StatementedNode.class_1.getVariableDeclaration (C:\Users\jsparidaans\PhpstormProjects\portalv2\node_modules\ts-simple-ast\dist\compiler\statement\StatementedNode.js:312:28)
    at ImportsUtil.findValueInImportOrLocalVariables (C:\Users\jsparidaans\PhpstormProjects\portalv2\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:4916:64)
```

**Comment by vogloblinsky** [comment]
@jsparidaans can i have sourcecode of vehicle.component.ts ?

**Comment by vogloblinsky** [comment]
@jsparidaans any news ?

**Comment by jsparidaans** [comment]
Im so sorry, I haven't had the time to address this yet, will get back to you soon!

**Comment by vogloblinsky** [comment]
Ok
