### ISSUE TITLE
[BUG] Errors when parsing custom route matchers

### ISSUE THREAD

**Issue by martinsotirov** [compodoc/compodoc#1066]
These are my routes for one of my modules:

```
const routes: Routes = [
  {
    path: '',
    component: GalleriesComponent,
    data: {
      title: 'Bildergalerien'
    }
  },
  { path: ':slug', component: GalleryComponent },
  {
    matcher: url => {
      if (url.length === 2 && url[1].path.match(/^\d+$/g)) {
        return {
          consumed: url,
          posParams: {
            slug: new UrlSegment(url[0].path, {}),
            page: new UrlSegment(url[1].path, {}),
          }
        }
      } else {
        return null
      }
    },
    component: GalleryComponent
  },
  { path: ':slug/:imageSlug', component: GalleryImageComponent },
]
```

This is the error I get while `compodoc`ing my app:

```
Unhandled Rejection at: Promise {
  <rejected> InvalidOperationError: Expected to find an initializer.
      at InvalidOperationError.BaseError [as constructor] (/Users/martin/my-project/node_modules/ts-simple-ast/dist/errors/BaseError.js:7:28)
      at new InvalidOperationError (/Users/martin/my-project/node_modules/ts-simple-ast/dist/errors/InvalidOperationError.js:8:28)
      at Object.throwIfNullOrUndefined (/Users/martin/my-project/node_modules/ts-simple-ast/dist/errors/helpers.js:96:15)
      at PropertySignature.InitializerGetExpressionableNode.class_1.getInitializerOrThrow (/Users/martin/my-project/node_modules/ts-simple-ast/dist/compiler/base/initializer/InitializerGetExpressionableNode.js:25:27)
      at RouterParserUtil.cleanFileDynamics (/Users/martin/my-project/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:5677:80)
      at AngularDependencies.getSourceFileDecorators (/Users/martin/my-project/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:8152:46)
      at /Users/martin/my-project/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:7960:31
      at Array.map (<anonymous>)
      at AngularDependencies.getDependencies (/Users/martin/my-project/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:7949:21)
      at CliApplication.Application.getDependenciesData (/Users/martin/my-project/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:9498:40)
} reason: InvalidOperationError: Expected to find an initializer.
    at InvalidOperationError.BaseError [as constructor] (/Users/martin/my-project/node_modules/ts-simple-ast/dist/errors/BaseError.js:7:28)
    at new InvalidOperationError (/Users/martin/my-project/node_modules/ts-simple-ast/dist/errors/InvalidOperationError.js:8:28)
    at Object.throwIfNullOrUndefined (/Users/martin/my-project/node_modules/ts-simple-ast/dist/errors/helpers.js:96:15)
    at PropertySignature.InitializerGetExpressionableNode.class_1.getInitializerOrThrow (/Users/martin/my-project/node_modules/ts-simple-ast/dist/compiler/base/initializer/InitializerGetExpressionableNode.js:25:27)
    at RouterParserUtil.cleanFileDynamics (/Users/martin/my-project/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:5677:80)
    at AngularDependencies.getSourceFileDecorators (/Users/martin/my-project/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:8152:46)
    at /Users/martin/my-project/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:7960:31
    at Array.map (<anonymous>)
    at AngularDependencies.getDependencies (/Users/martin/my-project/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:7949:21)
    at CliApplication.Application.getDependenciesData (/Users/martin/my-project/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:9498:40)

```

**Comment by criskrzysiu** [comment]
same thing happens with guards: Weird thing, adding valueOf to enum fixes things.. werid
```
enum Rights {
  Cases_Read = 'Cases_Read'
}
'``

```{
        path: 'some_route',
        data: {
          permissions: {
            oneOf: [Rights.Cases_Read], // this does not work
            oneOf: [Rights.Cases_Read.valueOf()], //this fixes things
          } as Permissions,
        },
        loadChildren: () => import('./somemodule').then((m) => m.SomeModule),
      },```

**Comment by GVHengy** [comment]
Same issue with app.routing.ts
The difference is I use variables for "path" property in Routes object.
Possible duplicate to  #1045 #1029 #1025

**Comment by Sebastian-G** [comment]
It seems to relate to the `tsconfig.json` path definition. 
How did you import your Enum?  In my case I could solve the issue by importing the file, without using the shorted path.

`import {Role} from '@shared/models';` ➡️ `import {Role} from '../shared/models';`)
