### ISSUE TITLE
issue using compodoc in nx workspace

### ISSUE THREAD

**Issue by DuncanFaulkner** [compodoc/compodoc#1069]
recently upgraded a project to angular 12, the project is using nx workspaces when I try and call npm run compodoc I was getting an error can't find tsconfig.json, I fixed this as the nx workspace uses tsconfig.base.json this then generates the following error:
[16:22:51] Using tsconfig : /home/duncan.faulkner/development/ast-uk/msl/tsconfig.base.json
internal/modules/cjs/loader.js:1044
    throw err;
    ^

SyntaxError: /home/duncan.faulkner/development/ast-uk/msl/tsconfig.base.json: Unexpected token / in JSON at position 488
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1041:22)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at CliApplication.generate (/home/duncan.faulkner/development/ast-uk/msl/node_modules/compodoc/dist/index-cli.js:3574:29)
    at Object.<anonymous> (/home/duncan.faulkner/development/ast-uk/msl/node_modules/compodoc/bin/index-cli.js:6:5)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

script:   "compodoc": "./node_modules/.bin/compodoc -d ./documentation -r 8090 -p ./tsconfig.base.json -s --theme postmark --name 'Portal'"

version 1.1.11 of compodoc
vs code 1.57-insiders
typescript: 4.2.4

**Comment by DuncanFaulkner** [comment]
had comments in tsconfig file, removed these and back in business
