### ISSUE TITLE
[BUG] Cant update from 1.1.11 to 1.1.12

### ISSUE THREAD

**Issue by slubowsky** [compodoc/compodoc#1090]
npm i results in error
```
PS C:\dev\my-app> npm i
npm WARN deprecated ts-simple-ast@12.4.0: NOTICE: ts-simple-ast has been renamed to ts-morph and version reset to 1.0.0. Switch at your leisure...
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated opn@6.0.0: The package has been renamed to `open`
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

> sleep@6.3.0 install C:\dev\my-app\node_modules\sleep
> node-gyp rebuild


C:\dev\my-app\node_modules\sleep>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! find VS 
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS checking VS2019 (16.11.31410.223) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview"
gyp ERR! find VS - "Visual Studio C++ core features" missing
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:326:5)
gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
gyp ERR! System Windows_NT 10.0.19043
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\dev\my-app\node_modules\sleep
gyp ERR! node -v v14.17.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\live-server\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @angular/cdk@12.1.1 requires a peer of rxjs@^6.5.3 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/common@12.1.1 requires a peer of rxjs@^6.5.3 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/core@12.1.1 requires a peer of rxjs@^6.5.3 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/forms@12.1.1 requires a peer of rxjs@^6.5.3 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/router@12.1.1 requires a peer of rxjs@^6.5.3 but none is installed. You must install peer dependencies yourself.
npm WARN @azure/msal-angular@2.0.1 requires a peer of rxjs@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular2-signaturepad@3.0.4 requires a peer of @angular/common@^8.0.0 || ^9.0.0 || ^10.0.0 || ^11.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular2-signaturepad@3.0.4 requires a peer of @angular/core@^8.0.0 || ^9.0.0 || ^10.0.0 || ^11.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@5.0.2 requires a peer of @popperjs/core@^2.9.2 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sleep@6.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sleep@6.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2021-07-08T13_08_38_390Z-debug.log
```

Version info
```
Angular CLI: 12.1.1
Node: 14.17.3
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 12.1.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.1
@angular-devkit/build-angular   12.1.1
@angular-devkit/core            8.3.29
@angular-devkit/schematics      8.3.29
@schematics/angular             8.3.29
rxjs                            7.2.0
typescript                      4.3.5
```

**Comment by cjdreiss** [comment]
This broke our installs/builds as well, we had a caret for compodoc and its now bringing in sleep which we cannot build.

**Comment by vogloblinsky** [comment]
@cjdreiss on windows too ?

**Comment by KrakenTyio** [comment]
ubuntu 20.04 also happen

**Comment by vogloblinsky** [comment]
@KrakenTyio Can i have versions informations like @slubowsky ?

**Comment by vogloblinsky** [comment]
@KrakenTyio Reproduced in Ubuntu 20.10
Fixed by https://github.com/compodoc/compodoc/commit/a1d5a1a04274c44e78f8387fcff832b3e5582b18, i will release a quick 1.1.13 this afternoon.

**Comment by cjdreiss** [comment]
Thanks for the quick fix!
