### ISSUE TITLE
[BUG]  parsing service.ts error

### ISSUE THREAD

**Issue by su4g** [compodoc/compodoc#1110]
##### **Overview of the issue**

I have two service file can't analyse , Always throw 
`Error: marked(): input parameter is of type [object Array], string expected `

##### **Operating System, Node.js, npm, compodoc version(s)**

node 14.15.4
npm 6.14.10
angularCLI v 11.2.12

##### **Angular configuration, a `package.json` file in the root folder**

` "compodoc": "./node_modules/.bin/compodoc -p ./tsconfig.doc.json`

##### **Compodoc installed globally or locally ?**

locally

##### **If possible sourcecode of the file where it breaks**

this is error file demo
```
import { Injectable } from '@angular/core';
import { AppService } from '../../app.service';
import { AbstractControl, FormGroup } from '@angular/forms';
import { Router } from '@angular/router';
@Injectable()
export class FormService {
  // some variable
    constructor(
        private appService: AppService,
    ) { }

  // some function
}
```

##### **If possible your terminal logs before the error**

```
[11:37:52] parsing        : D:/workspace/angular-local/angular-v12/src/app/common/form-element/form.service.ts
Unhandled Rejection at: Promise {
  <rejected> Error: marked(): input parameter is of type [object Array], string expected
      at marked (D:\workspace\angular-local\angular-v12\node_modules\marked\src\marked.js:27:11)
      at D:\workspace\angular-local\angular-v12\node_modules\@compodoc\compodoc\dist\index-cli-32a621dc.js:600:23
      at arrayEach (D:\workspace\angular-local\angular-v12\node_modules\@compodoc\compodoc\node_modules\lodash\lodash.js:530:11)
      at Object.forEach (D:\workspace\angular-local\angular-v12\node_modules\@compodoc\compodoc\node_modules\lodash\lodash.js:9410:14)
      at markedtags (D:\workspace\angular-local\angular-v12\node_modules\@compodoc\compodoc\dist\index-cli-32a621dc.js:599:18)
      at ClassHelper.visitMethodDeclaration (D:\workspace\angular-local\angular-v12\node_modules\@compodoc\compodoc\dist\index-cli-32a621dc.js:7420:32) 
      at ClassHelper.visitMembers (D:\workspace\angular-local\angular-v12\node_modules\@compodoc\compodoc\dist\index-cli-32a621dc.js:6884:51)
      at ClassHelper.visitClassDeclaration (D:\workspace\angular-local\angular-v12\node_modules\@compodoc\compodoc\dist\index-cli-32a621dc.js:6689:24)  
      at D:\workspace\angular-local\angular-v12\node_modules\@compodoc\compodoc\dist\index-cli-32a621dc.js:7965:63
      at Array.reduce (<anonymous>)
} reason: Error: marked(): input parameter is of type [object Array], string expected
    at marked (D:\workspace\angular-local\angular-v12\node_modules\marked\src\marked.js:27:11)
    at D:\workspace\angular-local\angular-v12\node_modules\@compodoc\compodoc\dist\index-cli-32a621dc.js:600:23
    at arrayEach (D:\workspace\angular-local\angular-v12\node_modules\@compodoc\compodoc\node_modules\lodash\lodash.js:530:11)
    at Object.forEach (D:\workspace\angular-local\angular-v12\node_modules\@compodoc\compodoc\node_modules\lodash\lodash.js:9410:14)
    at markedtags (D:\workspace\angular-local\angular-v12\node_modules\@compodoc\compodoc\dist\index-cli-32a621dc.js:599:18)
    at ClassHelper.visitMethodDeclaration (D:\workspace\angular-local\angular-v12\node_modules\@compodoc\compodoc\dist\index-cli-32a621dc.js:7420:32)   
    at ClassHelper.visitMembers (D:\workspace\angular-local\angular-v12\node_modules\@compodoc\compodoc\dist\index-cli-32a621dc.js:6884:51)
    at ClassHelper.visitClassDeclaration (D:\workspace\angular-local\angular-v12\node_modules\@compodoc\compodoc\dist\index-cli-32a621dc.js:6689:24)    
    at D:\workspace\angular-local\angular-v12\node_modules\@compodoc\compodoc\dist\index-cli-32a621dc.js:7965:63
    at Array.reduce (<anonymous>)
[11:37:52] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! otrs-new@0.0.0 compodoc: `compodoc -p ./tsconfig.doc.json --language zh-CN`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the otrs-new@0.0.0 compodoc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\workspace\angular-local\nodejs\node_cache\_logs\2021-08-06T03_37_52_570Z-debug.log
```

##### **Reproduce the error**

in tsconfig.doc.json
```
{
    "include": [
        "src/**/*.ts"
    ],
    "exclude": [
        "src/test.ts",
        "src/**/*.spec.ts",
        "src/app/file-to-exclude.ts",
        "src/**/form.service.ts",
    ]
}
```
Everything worked fine when I exclude 'form.service.ts' , how can i fix this file and get doc

**Comment by su4g** [comment]
sorry, my mistake, i read doc of JSDOC , i have some tags which is not supported in Compodoc .
