### ISSUE TITLE
[BUG] Unable to generate documentation

### ISSUE THREAD

**Issue by MiniMarker** [compodoc/compodoc#1115]
### Unable to generate documentation.

All of a sudden i've getting errors when building the documentation

It fails during the "Get dependencies data" stage.

Current version: "@compodoc/compodoc": "^1.1.13",

```
Unhandled Rejection at: Promise {
  <rejected> Error: marked(): input parameter is of type [object Array], string expected
      at marked (C:\Users\<projectPath>\node_modules\marked\src\marked.js:27:11)
      at C:\Users\<projectPath>\node_modules\@compodoc\compodoc\dist\index-cli-32a621dc.js:600:23
      at arrayEach (C:\Users\<projectPath>\node_modules\lodash\lodash.js:530:11)
      at Object.forEach (C:\Users\<projectPath>\node_modules\lodash\lodash.js:9410:14)
      at markedtags (C:\Users\<projectPath>\node_modules\@compodoc\compodoc\dist\index-cli-32a621dc.js:599:18)
      at ClassHelper.visitProperty (C:\Users\<projectPath>\node_modules\@compodoc\compodoc\dist\index-cli-32a621dc.js:7302:36)
      at ClassHelper.visitMembers (C:\Users\<projectPath>\node_modules\@compodoc\compodoc\dist\index-cli-32a621dc.js:6889:58)
      at ClassHelper.visitClassDeclaration (C:\Users\<projectPath>\node_modules\@compodoc\compodoc\dist\index-cli-32a621dc.js:6689:24)
      at C:\Users\<projectPath>\node_modules\@compodoc\compodoc\dist\index-cli-32a621dc.js:7965:63
      at Array.reduce (<anonymous>)
```

**Comment by Claudiu2000** [comment]
Hi, 
Had the same problem but was fixed by adding some extra spaces for @link types
Before: 
`
    /**
     * Creates Magic Unicorns
     * @param unicorn - {@link UnicornInterface}
     */
`
After: 
`
    /**
     * Creates Magic Unicorns
     * @param unicorn- { @link UnicornInterface }
     */
`

**Comment by reworc** [comment]
this does not really fix the issue - Although the documentation is successfully generated afterwards, the links are not correctly resolved, but treated as normal text

**Comment by MiniMarker** [comment]
Hi, found the issue!
I had the `@author` and `@date` params in the ts doc, looks like these made the codegen crash

**Comment by kussmaul** [comment]
In my case, the `marked()` error occurs only when `@link` is used in a comment for a `get` - other `@link` uses seem fine.

    /**
     * Gets {@link User} in this component. // ERROR HERE
     * @returns User in this component.
     */
    get user() { return this._user; }
