### ISSUE TITLE
[BUG] Error: marked(): input parameter is of type [object Array], string expected

### ISSUE THREAD

**Issue by Tim-arts** [compodoc/compodoc#1129]
##### **Overview of the issue**

I'm using Storybook which bases its config on Compodoc. While building the project its crashes with this error: 
```
Unhandled Rejection at: Promise {
  <rejected> Error: marked(): input parameter is of type [object Array], string expected
      at marked (C:\git_td\storybook-chrono-saeiv\node_modules\marked\src\marked.js:27:11)
      at ClassHelper.addAccessor (C:\git_td\storybook-chrono-saeiv\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:6799:52)
      at ClassHelper.visitMembers (C:\git_td\storybook-chrono-saeiv\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:7223:38)
      at ClassHelper.visitClassDeclaration (C:\git_td\storybook-chrono-saeiv\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:7015:24)
      at C:\git_td\storybook-chrono-saeiv\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:10149:63
      at Array.reduce (<anonymous>)
      at AngularDependencies.getClassIO (C:\git_td\storybook-chrono-saeiv\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:10146:33)
      at AngularDependencies.processClass (C:\git_td\storybook-chrono-saeiv\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:9032:23)
      at parseNode (C:\git_td\storybook-chrono-saeiv\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:9295:31)
      at C:\git_td\storybook-chrono-saeiv\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:9664:13
```

I've located the file responsible from the bug meaning if I delete its content, Storybook builds sucessfully. This is the content that I have (it's quite long but idk what makes it bug)

```
import { EventEmitter, Output, Input } from '@angular/core';
import { AbstractControl } from '@angular/forms';
import { MatFormGroup } from './matFormGroup';

/**
 * Base class used to define basic common behavior for controls
 * @class
 */
export class Field {

/**
 * Base class used to define basic common behavior for controls
 * @constructor
 */
    protected constructor() {
        this._readonly = false;
    }

    protected _editing: boolean = true
    private _readonly: boolean = false
    private _value: any = null

    /**
     * FormGroup to which to bind the control
     * @field
     */
    @Input() public group: MatFormGroup;

    /**
     * Name of the control within the {@link group}
     * @field
     */
    @Input() prop: string = ''

    /**
     * Label to display for the control
     * @field
     */
    @Input() label: string = ''

    /**
     * Placeholder is the value to show as an example when no value is set
     * @field
     */
    @Input() placeholder: string = ''

    /**
     * Gets or sets the value for the control
     * @property
     */
    get value() {
        if(this.control)
            return this.control.value;
        else
            return this._value;
    }

    /**
     * Propagates updabe value event in the case the value is not bound to a {@link MatFormGroup}
     * @field
     */
    @Output() onUpdateValue: EventEmitter<{ name: string, index: number, value: any }> = new EventEmitter()

    set value(v: any) {
        if(this.control)
            this.control.setValue(v);
        else {
            this._value = v;
            this.onUpdateValue.next({ name: this.prop, index: this.rowIndex, value: v });
        }
    }

    /**
     * Gets or sets if the controle is enabled or not
     * @property
     */
    public get readonly() {
        return (this._readonly ||
                (this.group != null && this.group.readOnly) ||
                this.control?.disabled) ?? false;
    }

    @Input('readonly')
    public set readonly(v: boolean){
        if(this.control != null){
            this.control.disable();
        }
        else {
            this._readonly = v;
        }
    }

    /**
     * Returns true if validations fail
     * @readonly
     * @property
     */
    public get invalid(): boolean {
        if (this.group != null && this.group.get(this.prop) != null)
            return this.group.get(this.prop)?.invalid ?? false;
        else
            return false;
    }

    /**
     * Retrieves the error list from the validations
     * @readonly
     * @property
     */
    public get errors(): string {
        let err = this.control?.errors;
        if(!err)
            return '';
        return JSON.stringify(err);
    }

    /**
     * Defines if the control is in edit mode or not
     * @property
     */
    public get editing(): boolean {
        return this.group?.editing ?? this._editing;
    }

    /**
     * Propagates the edit mode event
     * @field
     */
    @Output() editingChange: EventEmitter<boolean> = new EventEmitter();

    @Input()
    public set editing(value: boolean) {

        if(!!this.control && this.control.disabled){
            console.debug('Cannot edit readonly field');
            return;
        }

        if (!!this.group) {
            this.group.editing = value;
        }
        else {
            this._editing = value;
        }
        this.editingChange.next(value);
    }

    /**
     * Retrieves the control associated with the current {@link prop} from within the {@link group}
     */
    get control(): AbstractControl {
        if(this.group && this.group.controls[this.prop])
        {
            return this.group.controls[this.prop];
        }
        else
        return <AbstractControl><any>null;
    }

    /**
     * Sets the current position within the datasource
     */
    @Input() rowIndex: number = 0

    updateValue() {
        if (!!this.onUpdateValue) {
            this.onUpdateValue.emit({ name: this.prop, index: this.rowIndex, value: this.value });
        }
    }
}
```

**Comment by vogloblinsky** [comment]
Fixed by https://github.com/compodoc/compodoc/commit/33aa835ccdadb032ba7ffef0f38fc6033392640b
