### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by SDAdham** [compodoc/compodoc#1138]
Hi, I am getting Maximum call stack size exceeded:
```
[17:03:47] parsing        : <proj-dir>/<to-angular-service>.service.ts
Unhandled Rejection at: Promise {
  <rejected> RangeError: Maximum call stack size exceeded
      at RegExp.exec (<anonymous>)
      at replaceLinkTag (<proj-dir>\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:522:33)
      at Object._resolveLinks [as resolveLinks] (<proj-dir>\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:538:16)
      at <proj-dir>\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:898:43
      at arrayEach (<proj-dir>\node_modules\lodash\lodash.js:530:11)
      at Object.forEach (<proj-dir>\node_modules\lodash\lodash.js:9410:14)
      at markedtags (<proj-dir>\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:896:18)
      at ClassHelper.visitMethodDeclaration (<proj-dir>\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:7766:32)
      at ClassHelper.visitMembers (<proj-dir>\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:7210:51)
      at ClassHelper.visitClassDeclaration (<proj-dir>\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:7015:24)
} reason: RangeError: Maximum call stack size exceeded
    at RegExp.exec (<anonymous>)
    at replaceLinkTag (<proj-dir>\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:522:33)
    at Object._resolveLinks [as resolveLinks] (<proj-dir>\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:538:16)
    at <proj-dir>\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:898:43
    at arrayEach (<proj-dir>\node_modules\lodash\lodash.js:530:11)
    at Object.forEach (<proj-dir>\node_modules\lodash\lodash.js:9410:14)
    at markedtags (<proj-dir>\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:896:18)
    at ClassHelper.visitMethodDeclaration (<proj-dir>\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:7766:32)
    at ClassHelper.visitMembers (<proj-dir>\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:7210:51)
    at ClassHelper.visitClassDeclaration (<proj-dir>\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:7015:24)
```
Not sure why, can you please help?

**Comment by sandrafreihofer** [comment]
Which version of compodoc did you use? I think this error should be fixed with this [PR](https://github.com/compodoc/compodoc/pull/1136) and will be available in the next release of compodoc.

**Comment by SDAdham** [comment]
Hi @sandrafreihofer , I'm on version `1.1.15`

**Comment by sandrafreihofer** [comment]
@SDAdham we had similar problems with that version and trying it directly with current state of `develop` branch solves the problem. I think the next release will fix your issues as well.

**Comment by SDAdham** [comment]
Thanks @sandrafreihofer , I already fixed it on my side. I created this https://github.com/compodoc/compodoc/issues/1140, can you please let me know if this is already there and I'm missing an option?
