### ISSUE TITLE
[BUG] Maximum call stack size exceeded

### ISSUE THREAD

**Issue by TheAngularGuy** [compodoc/compodoc#1141]
##### **Overview of the issue**

When generating the documentation i get this error:

```bach
RangeError: Maximum call stack size exceeded
```

##### **Operating System, Node.js, npm, compodoc version(s)**

os: windows 10 64bit
compodoc: 1.1.15
npm: 6.14.14
node: 14.17.5

##### **Angular configuration, a `package.json` file in the root folder**

```javascript
"dependencies": {
    "@angular/animations": "12.2.0",
    "@angular/cdk": "12.2.0",
    "@angular/common": "12.2.0",
    "@angular/compiler": "12.2.0",
    "@angular/core": "12.2.0",
    "@angular/forms": "12.2.0",
    "@angular/material": "12.2.0",
    "@angular/platform-browser": "12.2.0",
    "@angular/platform-browser-dynamic": "12.2.0",
    "@angular/router": "12.2.0",
    "@auth0/angular-jwt": "5.0.2",
    "@ngneat/until-destroy": "8.0.3",
    "@ngxs/store": "3.7.1",
    "asmcrypto.js": "2.3.2",
    "class-transformer": "0.3.1",
    "compress.js": "1.1.2",
    "crypto-browserify": "3.12.0",
    "d3": "6.7.0",
    "dayjs": "1.9.6",
    "file-saver": "2.0.2",
    "idb": "6.0.0",
    "lodash": "4.17.21",
    "material-design-icons": "3.0.1",
    "ol": "6.6.1",
    "reflect-metadata": "0.1.13",
    "rxjs": "6.6.7",
    "stream-browserify": "3.0.0",
    "tslib": "2.3.0",
    "zone.js": "0.11.4"
  },
  "devDependencies": {
    "@angular-builders/jest": "12.1.0",
    "@angular-devkit/build-angular": "12.2.0",
    "@angular-eslint/builder": "12.0.0",
    "@angular-eslint/eslint-plugin": "12.0.0",
    "@angular-eslint/eslint-plugin-template": "12.0.0",
    "@angular-eslint/schematics": "12.0.0",
    "@angular-eslint/template-parser": "12.0.0",
    "@angular/cli": "12.2.0",
    "@angular/compiler-cli": "12.2.0",
    "@angular/elements": "^12.2.12",
    "@angular/language-service": "12.2.0",
    "@babel/core": "^7.16.0",
    "@compodoc/compodoc": "^1.1.15",
    "@ngxs/devtools-plugin": "3.7.1",
    "@ngxs/logger-plugin": "3.7.1",
    "@ngxs/schematics": "0.0.1-alpha.5",
    "@storybook/addon-actions": "^6.3.12",
    "@storybook/addon-essentials": "^6.3.12",
    "@storybook/addon-links": "^6.3.12",
    "@storybook/angular": "^6.3.12",
    "@storybook/builder-webpack5": "^6.3.12",
    "@storybook/manager-webpack5": "^6.3.12",
    "@types/d3": "6.7.0",
    "@types/file-saver": "2.0.1",
    "@types/jest": "26.0.23",
    "@types/lodash": "4.14.168",
    "@types/node": "15.12.2",
    "@types/ol": "6.5.3",
    "@typescript-eslint/eslint-plugin": "4.25.0",
    "@typescript-eslint/parser": "4.25.0",
    "@webcomponents/custom-elements": "^1.5.0",
    "babel-loader": "^8.2.3",
    "copy-webpack-plugin": "5.0.4",
    "eslint": "7.26.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jest": "24.3.6",
    "eslint-plugin-jsdoc": "32.3.3",
    "eslint-plugin-prefer-arrow": "1.2.3",
    "icon-font-generator": "2.1.10",
    "jest": "27.0.6",
    "ntl": "5.1.0",
    "sonarqube-scanner": "2.5.0",
    "typescript": "4.3.2",
    "webpack-bundle-analyzer": "4.4.2"
  }
```

##### **Compodoc installed globally or locally ?**

Locally

##### **If possible your terminal logs before the error**

```
Unhandled Rejection at: Promise {
<rejected> RangeError: Maximum call stack size exceeded
at RegExp.exec (<anonymous>)
at replaceLinkTag (C:\XXXXXXX\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:522:33)
at Object._resolveLinks [as resolveLinks] (C:\XXXXXXX\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:538:16)
at C:\XXXXXXX\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:898:43
at arrayEach (C:\XXXXXXX\node_modules\lodash\lodash.js:530:11)
at Object.forEach (C:\XXXXXXX\node_modules\lodash\lodash.js:9410:14)
at markedtags (C:\XXXXXXX\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:896:18)
at ClassHelper.visitMethodDeclaration (C:\XXXXXXX\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:7766:32)
at ClassHelper.visitMembers (C:\XXXXXXX\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:7210:51)
at ClassHelper.visitClassDeclaration (C:\XXXXXXX\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:7015:24)
} reason: RangeError: Maximum call stack size exceeded
at RegExp.exec (<anonymous>)
at replaceLinkTag (C:\XXXXXXX\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:522:33)
at Object._resolveLinks [as resolveLinks] (C:\XXXXXXX\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:538:16)
at C:\XXXXXXX\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:898:43
at arrayEach (C:\XXXXXXX\node_modules\lodash\lodash.js:530:11)
at Object.forEach (C:\XXXXXXX\node_modules\lodash\lodash.js:9410:14)
at markedtags (C:\XXXXXXX\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:896:18)
at ClassHelper.visitMethodDeclaration (C:\XXXXXXX\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:7766:32)
at ClassHelper.visitMembers (C:\XXXXXXX\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:7210:51)
at ClassHelper.visitClassDeclaration (C:\XXXXXXX\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:7015:24)
[17:11:13] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
```

**Comment by dr-itz** [comment]
This should be fixed by #1136

**Comment by amariq** [comment]
@dr-itz Nope. Still same issue here. Even on 1.1.16.

In my case the rrror occurs with links that point to the same type or its property, like this:
```
export interface SomeInterface {
    prop1: number;
    /**
     * Some text {@link prop1}.
     */
    prop2: boolean;
}
```

**Comment by amariq** [comment]
Oh, seems like I had some `npm i` shenanigans again — checked it once more and everything is indeed working fine on **1.1.16**!

Sorry for the misinformation 😅

**Comment by vogloblinsky** [comment]
Cool !
