### ISSUE TITLE
Error when try to generate documentation on project upgraded to angular 13

### ISSUE THREAD

**Issue by Obliczeniowo** [compodoc/compodoc#1144]
Error in console:

```
Unhandled Rejection at: Promise {
  <rejected> Error: marked(): input parameter is of type [object Array], string expected
      at marked (\node_modules\marked\src\marked.js:27:11)
      at ClassHelper.addAccessor (\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:6773:52)
      at ClassHelper.visitMembers (\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:7223:38)
      at ClassHelper.visitClassDeclaration (\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:7015:24)
      at \node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:10149:63
      at Array.reduce (<anonymous>)
      at AngularDependencies.getClassIO (\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:10146:33)
      at AngularDependencies.processClass (\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:9032:23)
      at parseNode (\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:9295:31)
      at \node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:9664:13
} reason: Error: marked(): input parameter is of type [object Array], string expected
    at marked (\node_modules\marked\src\marked.js:27:11)
    at ClassHelper.addAccessor (\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:6773:52)
    at ClassHelper.visitMembers (\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:7223:38)
    at ClassHelper.visitClassDeclaration (\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:7015:24)
    at \node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:10149:63
    at Array.reduce (<anonymous>)
    at AngularDependencies.getClassIO (\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:10146:33)
    at AngularDependencies.processClass (\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:9032:23)
    at parseNode (\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:9295:31)
    at \node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:9664:13
[02:58:40] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
```

**Comment by Obliczeniowo** [comment]
Ok I move to previous version v 1.1.11 since there is some problem with parsing inside library

**Comment by amariq** [comment]
I also get this error since v1.1.14+, but I don't think it has any relation to Angular version — had it on both 11 and 12.

In my case, I get `marked(): input parameter is of type [object Array], string expected` with link tags that point to some type and its property, like here:
```
export class SomeComponent {
    /**
     * Some text here and {@link SomeInterface.someOption}
     */
    @HostBinding('class.some-class')
    get someGetter(): boolean {
        return this.options.someOption;
    }
}
```

**Comment by amariq** [comment]
Oops, I can confirm that **1.1.16** is fixed the issue for me. 

Sorry for the misinformation in the previous comment 😅 Looks like something went wrong with my `node_modules` installation during the update, now everything works fine.

**Comment by vogloblinsky** [comment]
@Obliczeniowo could you test with last version ?

**Comment by Obliczeniowo** [comment]
Yes I confirm that new wersion **1.1.16** works
