### ISSUE TITLE
[BUG] Unhandled Rejection at: Promise {

### ISSUE THREAD

**Issue by hmendezm** [compodoc/compodoc#1164]
Hi Guys, compodoc was working for a long time but Today compodoc decided to stop working. The only thing I change was to use lazy loading in Angular but I do not see how this can affect it.

compodoc: v1.1.14

Unhandled Rejection at: Promise {
  <rejected> SyntaxError: JSON5: invalid character '(' at 1:40
      at syntaxError (C:\Projects\....\node_modules\json5\lib\parse.js:1083:17)
      at invalidChar (C:\Projects\....\node_modules\json5\lib\parse.js:1028:12)
      at Object.value (C:\Projects\....\node_modules\json5\lib\parse.js:287:15)
      at lex (C:\Projects\.....\node_modules\json5\lib\parse.js:78:42)
      at Object.parse (C:\Projects\....\node_modules\json5\lib\parse.js:25:17)
      at loopInsideModule (C:\Projects\.....\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:5976:63)
      at loopRoutesParser (C:\Projects\.....\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:6009:29)
      at loopRoutesParser (C:\Projects\...\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:6014:21)
      at RouterParserUtil.constructRoutesTree (C:\Projects\...\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:6018:9)
      at AngularDependencies.getDependencies (C:\Projects\....\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:9026:50) {
    lineNumber: 1,
    columnNumber: 40
  }
} reason: SyntaxError: JSON5: invalid character '(' at 1:40
    at syntaxError (C:\Projects\....\node_modules\json5\lib\parse.js:1083:17)
    at invalidChar (C:\Projects\...\node_modules\json5\lib\parse.js:1028:12)
    at Object.value (C:\Projects\....\node_modules\json5\lib\parse.js:287:15)
    at lex (C:\Projects\...\node_modules\json5\lib\parse.js:78:42)
    at Object.parse (C:\Projects\....\node_modules\json5\lib\parse.js:25:17)
    at loopInsideModule (C:\Projects\.....\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:5976:63)
    at loopRoutesParser (C:\Projects\.....\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:6009:29)
    at loopRoutesParser (C:\Projects\.....\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:6014:21)
    at RouterParserUtil.constructRoutesTree (C:\Projects\......\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:6018:9)
    at AngularDependencies.getDependencies (C:\Projects\....\node_modules\@compodoc\compodoc\dist\index-cli-8ef9c2ed.js:9026:50) {
  lineNumber: 1,
  columnNumber: 40
}
[08:10:37] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/isoc/issues/new)

**Comment by vogloblinsky** [comment]
Can i have the sourcecode of your routing ?

**Comment by hmendezm** [comment]
Hi vogloblinsky,

I found the issue. The issue is when you use `` instead of '' inside import(....)

Best
hmendez

**Comment by vogloblinsky** [comment]
Ok thanks, reproduced
