### ISSUE TITLE
[BUG] routing module <rejected> InvalidOperationError: Could not find the node's symbol.

### ISSUE THREAD

**Issue by jiangshanwe** [compodoc/compodoc#1165]
# compodoc version

1.1.16

#tsconfig.doc.json

```json
{
  "include": ["src/**/*.ts"],
  "exclude": ["src/test.ts", "src/**/*.spec.ts", "src/app/file-to-exclude.ts"]
}
```

# console error
```
[10:57:24] parsing        : D:/webstorm_workspace/jyf-frontend/src/app/routes/routes-routing.module.ts
[10:57:24] Analysing routes definitions and clean them if necessary
Unhandled Rejection at: Promise {
  <rejected> InvalidOperationError: Could not find the node's symbol.
      at Object.throwIfNullOrUndefined (C:\Users\jiang\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\@ts-morph\common\dist\ts-morph-common.js:473:19)
      at PropertyAccessExpression.getSymbolOrThrow (C:\Users\jiang\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\ts-morph\dist\ts-morph.js:3054:30)
      at _loop_3 (C:\Users\jiang\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli-298ea115.js:6411:22)
      at RouterParserUtil.cleanFileSpreads (C:\Users\jiang\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli-298ea115.js:6427:17)
      at AngularDependencies.getSourceFileDecorators (C:\Users\jiang\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli-298ea115.js:9320:32)
      at C:\Users\jiang\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli-298ea115.js:9130:31
      at Array.map (<anonymous>)
      at AngularDependencies.getDependencies (C:\Users\jiang\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli-298ea115.js:9119:21)
      at CliApplication.Application.getDependenciesData (C:\Users\jiang\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli-298ea115.js:10845:40)
      at C:\Users\jiang\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli-298ea115.js:10656:23
} reason: InvalidOperationError: Could not find the node's symbol.
    at Object.throwIfNullOrUndefined (C:\Users\jiang\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\@ts-morph\common\dist\ts-morph-common.js:473:19)
    at PropertyAccessExpression.getSymbolOrThrow (C:\Users\jiang\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\ts-morph\dist\ts-morph.js:3054:30)
    at _loop_3 (C:\Users\jiang\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli-298ea115.js:6411:22)
    at RouterParserUtil.cleanFileSpreads (C:\Users\jiang\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli-298ea115.js:6427:17)
    at AngularDependencies.getSourceFileDecorators (C:\Users\jiang\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli-298ea115.js:9320:32)
    at C:\Users\jiang\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli-298ea115.js:9130:31
    at Array.map (<anonymous>)
    at AngularDependencies.getDependencies (C:\Users\jiang\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli-298ea115.js:9119:21)
    at CliApplication.Application.getDependenciesData (C:\Users\jiang\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli-298ea115.js:10845:40)
    at C:\Users\jiang\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli-298ea115.js:10656:23
[10:57:28] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jiuyi-frontend@0.0.0 compodoc: `npx compodoc -p tsconfig.doc.json --language zh-CN`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jiuyi-frontend@0.0.0 compodoc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jiang\AppData\Roaming\npm-cache\_logs\2021-12-17T02_57_28_643Z-debug.log
```

# debug.log
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'compodoc'
1 verbose cli ]
2 info using npm@6.14.11
3 info using node@v14.16.0
4 verbose run-script [ 'precompodoc', 'compodoc', 'postcompodoc' ]
5 info lifecycle jiuyi-frontend@0.0.0~precompodoc: jiuyi-frontend@0.0.0
6 info lifecycle jiuyi-frontend@0.0.0~compodoc: jiuyi-frontend@0.0.0
7 verbose lifecycle jiuyi-frontend@0.0.0~compodoc: unsafe-perm in lifecycle true
8 verbose lifecycle jiuyi-frontend@0.0.0~compodoc: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\webstorm_workspace\jyf-frontend\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Java\jdk1.8.0_191\bin;C:\Program Files\TortoiseSVN\bin;D:\apache_maven\apache-maven-3.6.0\bin;C:\Program Files\Git\cmd;C:\Program Files\PuTTY\;C:\Program Files\nodejs\;C:\Program Files (x86)\NetSarang\Xshell 7\;C:\Program Files\MySQL\MySQL Shell 8.0\bin\;C:\Users\jiang\AppData\Local\Microsoft\WindowsApps;C:\Users\jiang\AppData\Roaming\npm;C:\Program Files\Fiddler
9 verbose lifecycle jiuyi-frontend@0.0.0~compodoc: CWD: D:\webstorm_workspace\jyf-frontend
10 silly lifecycle jiuyi-frontend@0.0.0~compodoc: Args: [ '/d /s /c', 'npx compodoc -p tsconfig.doc.json --language zh-CN' ]
11 silly lifecycle jiuyi-frontend@0.0.0~compodoc: Returned: code: 1  signal: null
12 info lifecycle jiuyi-frontend@0.0.0~compodoc: Failed to exec compodoc script
13 verbose stack Error: jiuyi-frontend@0.0.0 compodoc: `npx compodoc -p tsconfig.doc.json --language zh-CN`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid jiuyi-frontend@0.0.0
15 verbose cwd D:\webstorm_workspace\jyf-frontend
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "compodoc"
18 verbose node v14.16.0
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 1
22 error jiuyi-frontend@0.0.0 compodoc: `npx compodoc -p tsconfig.doc.json --language zh-CN`
22 error Exit status 1
23 error Failed at the jiuyi-frontend@0.0.0 compodoc script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by jiangshanwe** [comment]
# routes-routing.module.ts
```typescript
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { environment } from '@env/environment';
import { jyfRoutes } from '@app/routes/jyf-routes/jyf-routes';
import { LayoutDefaultComponent } from '../../../projects/jyf/src/lib/app/layout/default/default.component';
import { LockGuard } from '../../../projects/jyf/src/lib/app/core/guard/lockGuard';
import { InitResolverService } from '../../../projects/jyf/src/lib/app/core/resolve/init-resolver.service';
import { MobileComponent } from '../../../projects/jyf/src/lib/app/layout/mobile/mobile.component';
import { LayoutPassportComponent } from '../../../projects/jyf/src/lib/app/layout/passport/passport.component';

const routes: Routes = [
  {
    path: '',
    component: LayoutDefaultComponent,
    canActivate: [LockGuard],
    resolve: {
      init: InitResolverService,
    },
    children: [
      { path: '', redirectTo: '/dashboard', pathMatch: 'full' },
      ...jyfRoutes.routesModule
    ],
  },
  // 移动端布局
  {
    path: 'mobile',
    component: MobileComponent,
    children: [
      ...jyfRoutes.workflowMobileModule,
    ],
  },
  // passport
  {
    path: 'passport',
    component: LayoutPassportComponent,
    children: [
      ...jyfRoutes.passportModule,
    ],
  },
  // 单页
  ...jyfRoutes.singlePagesModule,
  // 默认跳转
  { path: '**', redirectTo: '/dashboard' },
];

@NgModule({
  imports: [RouterModule.forRoot(routes, { useHash: environment.useHash })],
  exports: [RouterModule],
  providers: [LockGuard],
})
export class RouteRoutingModule {
}

```
