### ISSUE TITLE
Please look at this issue , i was unable to build compo doc

### ISSUE THREAD

**Issue by kamruzzaman** [compodoc/compodoc#1260]
Please look at this issue , i was unable to build compo doc
Error during generation of routes JSON file, maybe a trailing comma or an external variable inside one route.
Unhandled Rejection at: Promise {
  <rejected> SyntaxError: JSON5: invalid character '.' at 1:74
      at syntaxError (E:\MOFLFRONTEND\MoFL-UI\node_modules\json5\lib\parse.js:1083:17)
      at invalidChar (E:\MOFLFRONTEND\MoFL-UI\node_modules\json5\lib\parse.js:1028:12)
      at Object.afterPropertyValue (E:\MOFLFRONTEND\MoFL-UI\node_modules\json5\lib\parse.js:654:15)
      at Object.default (E:\MOFLFRONTEND\MoFL-UI\node_modules\json5\lib\parse.js:146:37)
      at lex (E:\MOFLFRONTEND\MoFL-UI\node_modules\json5\lib\parse.js:78:42)
      at Object.parse (E:\MOFLFRONTEND\MoFL-UI\node_modules\json5\lib\parse.js:25:17)
      at loopInsideModule (E:\MOFLFRONTEND\MoFL-UI\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:6269:63)
      at loopRoutesParser (E:\MOFLFRONTEND\MoFL-UI\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:6302:29)
      at loopRoutesParser (E:\MOFLFRONTEND\MoFL-UI\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:6307:21)
      at loopRoutesParser (E:\MOFLFRONTEND\MoFL-UI\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:6307:21) {       
    lineNumber: 1,
    columnNumber: 74
  }
} reason: SyntaxError: JSON5: invalid character '.' at 1:74
    at syntaxError (E:\MOFLFRONTEND\MoFL-UI\node_modules\json5\lib\parse.js:1083:17)
    at invalidChar (E:\MOFLFRONTEND\MoFL-UI\node_modules\json5\lib\parse.js:1028:12)
    at Object.afterPropertyValue (E:\MOFLFRONTEND\MoFL-UI\node_modules\json5\lib\parse.js:654:15)
    at Object.default (E:\MOFLFRONTEND\MoFL-UI\node_modules\json5\lib\parse.js:146:37)
    at lex (E:\MOFLFRONTEND\MoFL-UI\node_modules\json5\lib\parse.js:78:42)
    at Object.parse (E:\MOFLFRONTEND\MoFL-UI\node_modules\json5\lib\parse.js:25:17)
    at loopInsideModule (E:\MOFLFRONTEND\MoFL-UI\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:6269:63)
    at loopRoutesParser (E:\MOFLFRONTEND\MoFL-UI\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:6302:29)
    at loopRoutesParser (E:\MOFLFRONTEND\MoFL-UI\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:6307:21)
    at loopRoutesParser (E:\MOFLFRONTEND\MoFL-UI\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:6307:21) {
  lineNumber: 1,
  columnNumber: 74
}

**Comment by paolagodoy** [comment]
HI, I have the same issue. Angular 10

**Comment by paolagodoy** [comment]
The only way to make it work was adding --minimal but I need graphs, dependencies and searchs 
Unhandled Rejection at: Promise {
  <rejected> SyntaxError: JSON5: invalid character '(' at 1:1
      at syntaxError (//node_modules/json5/lib/parse.js:1083:17)
      at invalidChar (//node_modules/json5/lib/parse.js:1028:12)
      at Object.value (//node_modules/json5/lib/parse.js:287:15)
      at lex (//node_modules/json5/lib/parse.js:78:42)
      at Object.parse (//node_modules/json5/lib/parse.js:25:17)
      at loopModulesParser (//node_modules/@compodoc/compodoc/dist/index-cli-f7393cac.js:6225:51)
      at RouterParserUtil.constructRoutesTree (//node_modules/@compodoc/compodoc/dist/index-cli-f7393cac.js:6250:13)
      at AngularDependencies.getDependencies (//node_modules/@compodoc/compodoc/dist/index-cli-f7393cac.js:9494:50)
      at CliApplication.Application.getDependenciesData (//node_modules/@compodoc/compodoc/dist/index-cli-f7393cac.js:11176:40)
      at //node_modules/@compodoc/compodoc/dist/index-cli-f7393cac.js:10985:23 {
    lineNumber: 1,
    columnNumber: 1
  }
} reason: SyntaxError: JSON5: invalid character '(' at 1:1
    at syntaxError (//node_modules/json5/lib/parse.js:1083:17)
    at invalidChar (//node_modules/json5/lib/parse.js:1028:12)
    at Object.value (//node_modules/json5/lib/parse.js:287:15)
    at lex (//node_modules/json5/lib/parse.js:78:42)
    at Object.parse (//node_modules/json5/lib/parse.js:25:17)
    at loopModulesParser (//node_modules/@compodoc/compodoc/dist/index-cli-f7393cac.js:6225:51)
    at RouterParserUtil.constructRoutesTree (//node_modules/@compodoc/compodoc/dist/index-cli-f7393cac.js:6250:13)
    at AngularDependencies.getDependencies (//node_modules/@compodoc/compodoc/dist/index-cli-f7393cac.js:9494:50)
    at CliApplication.Application.getDependenciesData (//node_modules/@compodoc/compodoc/dist/index-cli-f7393cac.js:11176:40)
    at //node_modules/@compodoc/compodoc/dist/index-cli-f7393cac.js:10985:23 {
  lineNumber: 1,
  columnNumber: 1
}
[16:31:09] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
