### ISSUE TITLE
Unhandled Rejection at: Promise

### ISSUE THREAD

**Issue by iztokb** [compodoc/compodoc#1303]
Hey
I'm trying to generate docs with command npm run compodoc:build, but keep getting an error that points to filling the issue on github. I assume that its this repo specific issue as lib works as expected in other projects. 

Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)

**Error detail** 
Unhandled Rejection at: Promise {
  <rejected> SyntaxError: JSON5: invalid character ',' at 1:37
      at syntaxError (C:\repos\playground\myTestApp\node_modules\json5\lib\parse.js:1083:17)
      at invalidChar (C:\repos\playground\myTestApp\node_modules\json5\lib\parse.js:1028:12)
      at Object.afterPropertyName (C:\repos\playground\myTestApp\node_modules\json5\lib\parse.js:640:15)
      at Object.default (C:\repos\playground\myTestApp\node_modules\json5\lib\parse.js:146:37)
      at lex (C:\repos\playground\myTestApp\node_modules\json5\lib\parse.js:78:42)
      at Object.parse (C:\repos\playground\myTestApp\node_modules\json5\lib\parse.js:25:17)
      at loopInsideModule (C:\repos\playground\myTestApp\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:6269:63)
      at loopRoutesParser (C:\repos\playground\myTestApp\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:6302:29)
      at loopRoutesParser (C:\repos\playground\myTestApp\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:6307:21)
      at RouterParserUtil.constructRoutesTree (C:\repos\playground\myTestApp\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:6311:9) {
    lineNumber: 1,
    columnNumber: 37
  }
} reason: SyntaxError: JSON5: invalid character ',' at 1:37
    at syntaxError (C:\repos\playground\myTestApp\node_modules\json5\lib\parse.js:1083:17)
    at invalidChar (C:\repos\playground\myTestApp\node_modules\json5\lib\parse.js:1028:12)
    at Object.afterPropertyName (C:\repos\playground\myTestApp\node_modules\json5\lib\parse.js:640:15)
    at Object.default (C:\repos\playground\myTestApp\node_modules\json5\lib\parse.js:146:37)
    at lex (C:\repos\playground\myTestApp\node_modules\json5\lib\parse.js:78:42)
    at Object.parse (C:\repos\playground\myTestApp\node_modules\json5\lib\parse.js:25:17)
    at loopInsideModule (C:\repos\playground\myTestApp\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:6269:63)
    at loopRoutesParser (C:\repos\playground\myTestApp\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:6302:29)
    at loopRoutesParser (C:\repos\playground\myTestApp\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:6307:21)
    at RouterParserUtil.constructRoutesTree (C:\repos\playground\myTestApp\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:6311:9) {
  lineNumber: 1,
  columnNumber: 37
}

**Comment by iztokb** [comment]
I assume that this has the same cause as as issue #1302 . I'll close this issue and report if fix for that issue didn't resolve this.
