### ISSUE TITLE
[BUG] Incorrectly parsing filename, causing FileNotFoundError

### ISSUE THREAD

**Issue by AndruC** [compodoc/compodoc#1306]
I'm bringing compodoc into an existing Angular project. Running build hit a snag pretty early on.

I followed a few steps, adding the library to the project

npm install -g @compodoc/compodoc
ng add @compodoc/compodoc
npm run compodoc:build
...FileNotFoundError

Output (edited for brevity)

```log

> app@0.0.1 compodoc:build
> compodoc -p tsconfig.doc.json

1.1.19

TypeScript version used by Compodoc : 4.5.5

TypeScript version of current project : 4.6.4

Node.js version : v16.14.2

Operating system : macOS Monterey

[17:24:21] No configuration file found, switching to CLI flags.
[17:24:21] Using tsconfig file : /Users/andrew/projects/kohomobile/tsconfig.doc.json
...
[17:24:21] Including      : /Users/andrew/projects/mobile/src/apple-pay/apple-pay.module.ts
[17:24:21] Including      : /Users/andrew/projects/mobile/src/app/app.actions.ts
[17:24:21] Including      : /Users/andrew/projects/mobile/src/app/app.component.ts
[17:24:21] Including      : /Users/andrew/projects/mobile/src/app/app.module.ts
[17:24:21] Including      : /Users/andrew/projects/mobile/src/app/app.guard.ts
[17:24:21] Including      : /Users/andrew/projects/mobile/src/app/app.routes.ts
[17:24:21] Including      : /Users/andrew/projects/mobile/src/app/authenticated.routes.ts
[17:24:21] Including      : /Users/andrew/projects/mobile/src/app/translation-loader.ts
...
[17:27:09] Searching package.json file
[17:27:09] package.json file found
[17:27:09] Processing package.json dependencies
[17:27:09] Get dependencies data
...
[17:27:10] parsing        : /Users/andrew/projects/mobile/src/app/app.guard.ts
[17:27:10] found          : AppGuard
[17:27:10] parsing        : /Users/andrew/projects/mobile/src/app/app.routes.ts
[17:27:10] Analysing routes definitions and clean them if necessary
Unhandled Rejection at:
  <rejected> FileNotFoundError: File not found: /Users/andrew/projects/mobile/src/app/authenticated.ts
      at DirectoryCoordinator.addSourceFileAtPath (/Users/andrew/projects/mobile/node_modules/ts-morph/dist/ts-morph.js:18643:19)
      at Project.addSourceFileAtPath (/Users/andrew/projects/mobile/node_modules/ts-morph/dist/ts-morph.js:20088:51)
      at _loop_3 (/Users/andrew/projects/mobile/node_modules/@compodoc/compodoc/dist/index-cli-f7393cac.js:6567:33)
      at RouterParserUtil.cleanFileSpreads (/Users/andrew/projects/mobile/node_modules/@compodoc/compodoc/dist/index-cli-f7393cac.js:6597:17)
      at AngularDependencies.getSourceFileDecorators (/Users/andrew/projects/mobile/node_modules/@compodoc/compodoc/dist/index-cli-f7393cac.js:9605:32)
      at /Users/andrew/projects/mobile/node_modules/@compodoc/compodoc/dist/index-cli-f7393cac.js:9397:31
      at Array.map (<anonymous>)
      at AngularDependencies.getDependencies (/Users/andrew/projects/mobile/node_modules/@compodoc/compodoc/dist/index-cli-f7393cac.js:9386:21)
      at CliApplication.Application.getDependenciesData (/Users/andrew/projects/mobile/node_modules/@compodoc/compodoc/dist/index-cli-f7393cac.js:11176:40)
      at /Users/andrew/projects/mobile/node_modules/@compodoc/compodoc/dist/index-cli-f7393cac.js:10985:23 {
    path: '/Users/andrew/projects/mobile/src/app/authenticated.ts',
    code: 'ENOENT'
```

From what I can tell, it parsed the import tree correctly up to `app.routes.ts` (and hopefully you can already see where this is going), failing to find its dependency at `src/app/authenticated.ts`. This of course, wasn't found, and if we look at `app.routes.ts` you can see its (valid) Typescript import:

```typescript
// app.routes.ts

import { AuthenticatedRoutes } from "./authenticated.routes";
```

It looks like trailing parts of the name, after the first `.` are getting lost. I'm surprised why this happened with `authenticated.routes.ts` and not `app.routes.ts`.

**Comment by KevinFernandes** [comment]
Having a similar problem with `.` in the folder paths (not just in the filenames).  Seeing this when trying to use Storybook, but it does not get that far.

Note the ` path: 'C:/github/CR/Web/CMM.ts',` where the "CMM.ts" should have been "CMM.Web".

We have lots of files with `.` in their names and paths so without a fix it looks like we will not be able to use this tool or Storybook.

```
Unhandled Rejection at: Promise {
  <rejected> FileNotFoundError: File not found: C:/github/CR/Web/CMM.ts
      at DirectoryCoordinator.addSourceFileAtPath (C:\github\CR\Web\CMM.Web\node_modules\ts-morph\dist\ts-morph.js:18643:19)
      at Project.addSourceFileAtPath (C:\github\CR\Web\CMM.Web\node_modules\ts-morph\dist\ts-morph.js:20088:51)
      at _loop_3 (C:\github\CR\Web\CMM.Web\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:6567:33)
      at RouterParserUtil.cleanFileSpreads (C:\github\Capacity-Reporting\Web\CMM.Web\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:6597:17)
      at AngularDependencies.getSourceFileDecorators (C:\github\Capacity-Reporting\Web\CMM.Web\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:9605:32)    
      at C:\github\CR\Web\CMM.Web\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:9397:31
      at Array.map (<anonymous>)
      at AngularDependencies.getDependencies (C:\github\CR\Web\CMM.Web\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:9386:21)
      at CliApplication.Application.getDependenciesData (C:\github\CR\Web\CMM.Web\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:11176:40)      at C:\github\CR\Web\CMM.Web\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:10985:23 {
    path: 'C:/github/CR/Web/CMM.ts',
    code: 'ENOENT'
  }
} reason: FileNotFoundError: File not found: C:/github/CR/Web/CMM.ts
    at DirectoryCoordinator.addSourceFileAtPath (C:\github\CR\Web\CMM.Web\node_modules\ts-morph\dist\ts-morph.js:18643:19)
    at Project.addSourceFileAtPath (C:\github\CR\Web\CMM.Web\node_modules\ts-morph\dist\ts-morph.js:20088:51)
    at _loop_3 (C:\github\CR\Web\CMM.Web\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:6567:33)
    at RouterParserUtil.cleanFileSpreads (C:\github\CR\Web\CMM.Web\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:6597:17)
    at AngularDependencies.getSourceFileDecorators (C:\github\CR\Web\CMM.Web\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:9605:32)      
    at C:\github\CR\Web\CMM.Web\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:9397:31
    at Array.map (<anonymous>)
    at AngularDependencies.getDependencies (C:\github\CR\Web\CMM.Web\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:9386:21)
    at CliApplication.Application.getDependenciesData (C:\github\CR\Web\CMM.Web\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:11176:40)  
    at C:\github\CR\Web\CMM.Web\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:10985:23 {
  path: 'C:/github/CR/Web/CMM.ts',
  code: 'ENOENT'
}
```
