### ISSUE TITLE
SyntaxError: JSON5: invalid character '.' at 1:178       at syntaxError (/Users/mac/Desktop/projects/personal_projects/RMS_ANGULAR/rms_angular/node_modules/json5/lib/parse.js:1110:17)

### ISSUE THREAD

**Issue by kirklimbu** [compodoc/compodoc#1320]
Unhandled Rejection at: Promise {
  <rejected> SyntaxError: JSON5: invalid character '.' at 1:178
      at syntaxError (/Users/mac/Desktop/projects/personal_projects/RMS_ANGULAR/rms_angular/node_modules/json5/lib/parse.js:1110:17)
      at invalidChar (/Users/mac/Desktop/projects/personal_projects/RMS_ANGULAR/rms_angular/node_modules/json5/lib/parse.js:1055:12)
      at Object.afterPropertyValue (/Users/mac/Desktop/projects/personal_projects/RMS_ANGULAR/rms_angular/node_modules/json5/lib/parse.js:676:15)
      at Object.default (/Users/mac/Desktop/projects/personal_projects/RMS_ANGULAR/rms_angular/node_modules/json5/lib/parse.js:168:37)
      at lex (/Users/mac/Desktop/projects/personal_projects/RMS_ANGULAR/rms_angular/node_modules/json5/lib/parse.js:100:42)
      at Object.parse (/Users/mac/Desktop/projects/personal_projects/RMS_ANGULAR/rms_angular/node_modules/json5/lib/parse.js:25:17)
      at loopInsideModule (/Users/mac/Desktop/projects/personal_projects/RMS_ANGULAR/rms_angular/node_modules/@compodoc/compodoc/dist/index-cli-f7393cac.js:6269:63)
      at loopRoutesParser (/Users/mac/Desktop/projects/personal_projects/RMS_ANGULAR/rms_angular/node_modules/@compodoc/compodoc/dist/index-cli-f7393cac.js:6302:29)
      at loopRoutesParser (/Users/mac/Desktop/projects/personal_projects/RMS_ANGULAR/rms_angular/node_modules/@compodoc/compodoc/dist/index-cli-f7393cac.js:6307:21)
      at RouterParserUtil.constructRoutesTree (/Users/mac/Desktop/projects/personal_projects/RMS_ANGULAR/rms_angular/node_modules/@compodoc/compodoc/dist/index-cli-f7393cac.js:6311:9) {
    lineNumber: 1,
    columnNumber: 178
  }
} reason: SyntaxError: JSON5: invalid character '.' at 1:178
    at syntaxError (/Users/mac/Desktop/projects/personal_projects/RMS_ANGULAR/rms_angular/node_modules/json5/lib/parse.js:1110:17)
    at invalidChar (/Users/mac/Desktop/projects/personal_projects/RMS_ANGULAR/rms_angular/node_modules/json5/lib/parse.js:1055:12)
    at Object.afterPropertyValue (/Users/mac/Desktop/projects/personal_projects/RMS_ANGULAR/rms_angular/node_modules/json5/lib/parse.js:676:15)
    at Object.default (/Users/mac/Desktop/projects/personal_projects/RMS_ANGULAR/rms_angular/node_modules/json5/lib/parse.js:168:37)
    at lex (/Users/mac/Desktop/projects/personal_projects/RMS_ANGULAR/rms_angular/node_modules/json5/lib/parse.js:100:42)
    at Object.parse (/Users/mac/Desktop/projects/personal_projects/RMS_ANGULAR/rms_angular/node_modules/json5/lib/parse.js:25:17)
    at loopInsideModule (/Users/mac/Desktop/projects/personal_projects/RMS_ANGULAR/rms_angular/node_modules/@compodoc/compodoc/dist/index-cli-f7393cac.js:6269:63)
    at loopRoutesParser (/Users/mac/Desktop/projects/personal_projects/RMS_ANGULAR/rms_angular/node_modules/@compodoc/compodoc/dist/index-cli-f7393cac.js:6302:29)
    at loopRoutesParser (/Users/mac/Desktop/projects/personal_projects/RMS_ANGULAR/rms_angular/node_modules/@compodoc/compodoc/dist/index-cli-f7393cac.js:6307:21)
    at RouterParserUtil.constructRoutesTree (/Users/mac/Desktop/projects/personal_projects/RMS_ANGULAR/rms_angular/node_modules/@compodoc/compodoc/dist/index-cli-f7393cac.js:6311:9) {
  lineNumber: 1,
  columnNumber: 178
}

Angular CLI: 11.0.7
Node: 16.14.2
OS: darwin x64

Angular: 11.0.9

**Comment by kirklimbu** [comment]
npx compodoc -p tsconfig.json --disableDependencies --minimal

this command solved my issue. 
hope this helps 
thanks

**Comment by henning410** [comment]
@kirklimbu If your issue get solved, close your issue. This makes it easier for the developers and maintainers to have a better overview over the issues. Thx

**Comment by markwhitfeld** [comment]
This issue may contain your solution, or a way to figure out the issue: https://github.com/compodoc/compodoc/issues/1124
