### ISSUE TITLE
[BUG] Sorry, but there was a problem during parsing or generation of the documentation

### ISSUE THREAD

**Issue by agentilcore** [compodoc/compodoc#1324]
I'm trying generate the documentation but I have an error

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'compodoc'
1 verbose cli ]
2 info using npm@6.14.11
3 info using node@v12.20.2
4 verbose run-script [ 'precompodoc', 'compodoc', 'postcompodoc' ]
5 info lifecycle shell@0.0.0~precompodoc: shell@0.0.0
6 info lifecycle shell@0.0.0~compodoc: shell@0.0.0
7 verbose lifecycle shell@0.0.0~compodoc: unsafe-perm in lifecycle true
8 verbose lifecycle shell@0.0.0~compodoc: PATH: C:\Users\myUser\AppData\Roaming\nvm\v12.20.2\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;(...ruta...)\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files (x86)\Microsoft SQL Server\160\Tools\Binn\;C:\Program Files\Microsoft SQL Server\160\Tools\Binn\;C:\Program Files\Microsoft SQL Server\160\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\160\DTS\Binn\;C:\Program Files\Git\cmd;C:\Program Files\Azure Data Studio\bin;%NVM_HOME%;%NVM_SYMLINK%;C:\Users\myUser\AppData\Local\Microsoft\WindowsApps;C:\Users\myUser\.dotnet\tools;C:\Users\myUser\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Azure Data Studio\bin;C:\Users\myUser\AppData\Roaming\nvm;C:\Program Files\nodejs
9 verbose lifecycle shell@0.0.0~compodoc: CWD: (...ruta...)
10 silly lifecycle shell@0.0.0~compodoc: Args: [ '/d /s /c', 'npx compodoc -p tsconfig.doc.json' ]
11 silly lifecycle shell@0.0.0~compodoc: Returned: code: 1  signal: null
12 info lifecycle shell@0.0.0~compodoc: Failed to exec compodoc script
13 verbose stack Error: shell@0.0.0 compodoc: `npx compodoc -p tsconfig.doc.json`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\myUser\AppData\Roaming\nvm\v12.20.2\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\myUser\AppData\Roaming\nvm\v12.20.2\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1022:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid shell@0.0.0
15 verbose cwd (...ruta...)
16 verbose Windows_NT 10.0.19045
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "compodoc"
18 verbose node v12.20.2
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 1
22 error shell@0.0.0 compodoc: `npx compodoc -p tsconfig.doc.json`
22 error Exit status 1
23 error Failed at the shell@0.0.0 compodoc script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

[16:14:24] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! shell@0.0.0 compodoc: `npx compodoc -p tsconfig.doc.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the shell@0.0.0 compodoc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by vogloblinsky** [comment]
Is it possible to have information about the last file where Compodoc breaks ?
