### ISSUE TITLE
[BUG] Invalid character '+' at 1:6169

### ISSUE THREAD

**Issue by AdamOndrejkovic** [compodoc/compodoc#1346]
```
Unhandled Rejection at: Promise {
  <rejected> SyntaxError: JSON5: invalid character '+' at 1:6196
      at syntaxError (C:\Users\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1110:17)
      at invalidChar (C:\UsersAppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1055:12)
      at Object.afterPropertyValue (C:\UsersAppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:676:15)
      at Object.default (C:\Users\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:168:37)
      at lex (C:\Users\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:100:42)
      at Object.parse (C:\Users\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:25:17)
      at loopInsideModule (C:\Users\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:6269:63)
      at loopRoutesParser (C:\Users\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:6302:29)
      at loopRoutesParser (C:\Users\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:6307:21)
      at loopRoutesParser (C:\Users\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:6307:21) {
    lineNumber: 1,
    columnNumber: 6196
  }
} reason: SyntaxError: JSON5: invalid character '+' at 1:6196
    at syntaxError (C:\Users\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1110:17)
    at invalidChar (C:\Users\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1055:12)
    at Object.afterPropertyValue (C:\Users\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:676:15)
    at Object.default (C:\Users\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:168:37)
    at lex (C:\Users\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:100:42)
    at Object.parse (C:\Users\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:25:17)
    at loopInsideModule (C:\Users\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:6269:63)
    at loopRoutesParser (C:\Users\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:6302:29)
    at loopRoutesParser (C:\Users\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:6307:21)
    at loopRoutesParser (C:\Users\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:6307:21) {
  lineNumber: 1,
  columnNumber: 6196
}
```

**Comment by Carlos-Eduardo-Rodrigues** [comment]
Having an similar issue
```
Unhandled Rejection at: Promise {
  <rejected> SyntaxError: JSON5: invalid character '.' at 1:62
      at syntaxError (/home/carloseduardo/Workspace/hub-ep-app/node_modules/json5/lib/parse.js:1110:17)
      at invalidChar (/home/carloseduardo/Workspace/hub-ep-app/node_modules/json5/lib/parse.js:1055:12)
      at Object.afterPropertyValue (/home/carloseduardo/Workspace/hub-ep-app/node_modules/json5/lib/parse.js:676:15)
      at Object.default (/home/carloseduardo/Workspace/hub-ep-app/node_modules/json5/lib/parse.js:168:37)
      at lex (/home/carloseduardo/Workspace/hub-ep-app/node_modules/json5/lib/parse.js:100:42)
      at Object.parse (/home/carloseduardo/Workspace/hub-ep-app/node_modules/json5/lib/parse.js:25:17)
      at loopInsideModule (/home/carloseduardo/Workspace/hub-ep-app/node_modules/@compodoc/compodoc/dist/index.js:6345:63)
      at loopRoutesParser (/home/carloseduardo/Workspace/hub-ep-app/node_modules/@compodoc/compodoc/dist/index.js:6378:29)
      at loopRoutesParser (/home/carloseduardo/Workspace/hub-ep-app/node_modules/@compodoc/compodoc/dist/index.js:6389:21)
      at RouterParserUtil.constructRoutesTree (/home/carloseduardo/Workspace/hub-ep-app/node_modules/@compodoc/compodoc/dist/index.js:6393:9) {
    lineNumber: 1,
    columnNumber: 62
  }
} reason: SyntaxError: JSON5: invalid character '.' at 1:62
    at syntaxError (/home/carloseduardo/Workspace/hub-ep-app/node_modules/json5/lib/parse.js:1110:17)
    at invalidChar (/home/carloseduardo/Workspace/hub-ep-app/node_modules/json5/lib/parse.js:1055:12)
    at Object.afterPropertyValue (/home/carloseduardo/Workspace/hub-ep-app/node_modules/json5/lib/parse.js:676:15)
    at Object.default (/home/carloseduardo/Workspace/hub-ep-app/node_modules/json5/lib/parse.js:168:37)
    at lex (/home/carloseduardo/Workspace/hub-ep-app/node_modules/json5/lib/parse.js:100:42)
    at Object.parse (/home/carloseduardo/Workspace/hub-ep-app/node_modules/json5/lib/parse.js:25:17)
    at loopInsideModule (/home/carloseduardo/Workspace/hub-ep-app/node_modules/@compodoc/compodoc/dist/index.js:6345:63)
    at loopRoutesParser (/home/carloseduardo/Workspace/hub-ep-app/node_modules/@compodoc/compodoc/dist/index.js:6378:29)
    at loopRoutesParser (/home/carloseduardo/Workspace/hub-ep-app/node_modules/@compodoc/compodoc/dist/index.js:6389:21)
    at RouterParserUtil.constructRoutesTree (/home/carloseduardo/Workspace/hub-ep-app/node_modules/@compodoc/compodoc/dist/index.js:6393:9) {
  lineNumber: 1,
  columnNumber: 62
}
[19:06:51] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
/home/carloseduardo/Workspace/hub-ep-app/node_modules/@angular-devkit/core/src/logger/indent.js:35
            entry.message = indentMap[l] + entry.message.split(/\n/).join('\n' + indentMap[l]);
                                                         ^

TypeError: entry.message.split is not a function
    at /home/carloseduardo/Workspace/hub-ep-app/node_modules/@angular-devkit/core/src/logger/indent.js:35:58
    at /home/carloseduardo/Workspace/hub-ep-app/node_modules/rxjs/dist/cjs/internal/operators/map.js:10:37
    at OperatorSubscriber._this._next (/home/carloseduardo/Workspace/hub-ep-app/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
    at OperatorSubscriber.Subscriber.next (/home/carloseduardo/Workspace/hub-ep-app/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18)
    at /home/carloseduardo/Workspace/hub-ep-app/node_modules/rxjs/dist/cjs/internal/Subject.js:69:34
    at Object.errorContext (/home/carloseduardo/Workspace/hub-ep-app/node_modules/rxjs/dist/cjs/internal/util/errorContext.js:22:9)
    at Subject.next (/home/carloseduardo/Workspace/hub-ep-app/node_modules/rxjs/dist/cjs/internal/Subject.js:59:24)
    at IndentLogger.next (/home/carloseduardo/Workspace/hub-ep-app/node_modules/@angular-devkit/core/src/logger/logger.js:86:23)
    at Object.next (/home/carloseduardo/Workspace/hub-ep-app/node_modules/@angular-devkit/architect/src/schedule-by-name.js:50:20)
    at ConsumerObserver.next (/home/carloseduardo/Workspace/hub-ep-app/node_modules/rxjs/dist/cjs/internal/Subscriber.js:113:33)
```

**Comment by vogloblinsky** [comment]
What kind of routing files do you have ?
