### ISSUE TITLE
[BUG] Parsing error compodoc told me to report

### ISSUE THREAD

**Issue by windmillcode0** [compodoc/compodoc#1354]
# Compodoc parsing issue

## Expected Behavior
* when I run the app everything should work fine
*

## Current Behavior
```ts
Unhandled Rejection at: Promise {
  <rejected> SyntaxError: JSON5: invalid character '}' at 1:60
      at syntaxError (C:\Users\Restop-8734\My_Apps\WindmillcodeSite_v2\apps\zero\frontend\AngularApp\node_modules\json5\lib\parse.js:1110:17)
      at invalidChar (C:\Users\Restop-8734\My_Apps\WindmillcodeSite_v2\apps\zero\frontend\AngularApp\node_modules\json5\lib\parse.js:1055:12)
      at Object.afterPropertyName (C:\Users\Restop-8734\My_Apps\WindmillcodeSite_v2\apps\zero\frontend\AngularApp\node_modules\json5\lib\parse.js:662:15)
      at Object.default (C:\Users\Restop-8734\My_Apps\WindmillcodeSite_v2\apps\zero\frontend\AngularApp\node_modules\json5\lib\parse.js:168:37)
      at lex (C:\Users\Restop-8734\My_Apps\WindmillcodeSite_v2\apps\zero\frontend\AngularApp\node_modules\json5\lib\parse.js:100:42)
      at Object.parse (C:\Users\Restop-8734\My_Apps\WindmillcodeSite_v2\apps\zero\frontend\AngularApp\node_modules\json5\lib\parse.js:25:17)
      at loopInsideModule (C:\Users\Restop-8734\My_Apps\WindmillcodeSite_v2\apps\zero\frontend\AngularApp\node_modules\@compodoc\compodoc\dist\index.js:6345:63)
      at loopRoutesParser (C:\Users\Restop-8734\My_Apps\WindmillcodeSite_v2\apps\zero\frontend\AngularApp\node_modules\@compodoc\compodoc\dist\index.js:6378:29)
      at loopRoutesParser (C:\Users\Restop-8734\My_Apps\WindmillcodeSite_v2\apps\zero\frontend\AngularApp\node_modules\@compodoc\compodoc\dist\index.js:6389:21)
      at RouterParserUtil.constructRoutesTree (C:\Users\Restop-8734\My_Apps\WindmillcodeSite_v2\apps\zero\frontend\AngularApp\node_modules\@compodoc\compodoc\dist\index.js:6393:9) {
    lineNumber: 1,
    columnNumber: 60
  }
} reason: SyntaxError: JSON5: invalid character '}' at 1:60
    at syntaxError (C:\Users\Restop-8734\My_Apps\WindmillcodeSite_v2\apps\zero\frontend\AngularApp\node_modules\json5\lib\parse.js:1110:17)
    at invalidChar (C:\Users\Restop-8734\My_Apps\WindmillcodeSite_v2\apps\zero\frontend\AngularApp\node_modules\json5\lib\parse.js:1055:12)
    at Object.afterPropertyName (C:\Users\Restop-8734\My_Apps\WindmillcodeSite_v2\apps\zero\frontend\AngularApp\node_modules\json5\lib\parse.js:662:15)
    at Object.default (C:\Users\Restop-8734\My_Apps\WindmillcodeSite_v2\apps\zero\frontend\AngularApp\node_modules\json5\lib\parse.js:168:37)
    at lex (C:\Users\Restop-8734\My_Apps\WindmillcodeSite_v2\apps\zero\frontend\AngularApp\node_modules\json5\lib\parse.js:100:42)
    at Object.parse (C:\Users\Restop-8734\My_Apps\WindmillcodeSite_v2\apps\zero\frontend\AngularApp\node_modules\json5\lib\parse.js:25:17)
    at loopInsideModule (C:\Users\Restop-8734\My_Apps\WindmillcodeSite_v2\apps\zero\frontend\AngularApp\node_modules\@compodoc\compodoc\dist\index.js:6345:63)
    at loopRoutesParser (C:\Users\Restop-8734\My_Apps\WindmillcodeSite_v2\apps\zero\frontend\AngularApp\node_modules\@compodoc\compodoc\dist\index.js:6378:29)
    at loopRoutesParser (C:\Users\Restop-8734\My_Apps\WindmillcodeSite_v2\apps\zero\frontend\AngularApp\node_modules\@compodoc\compodoc\dist\index.js:6389:21)
    at RouterParserUtil.constructRoutesTree (C:\Users\Restop-8734\My_Apps\WindmillcodeSite_v2\apps\zero\frontend\AngularApp\node_modules\@compodoc\compodoc\dist\index.js:6393:9) {
  lineNumber: 1,
  columnNumber: 60
}
```

## Steps to Reproduce

1. yarn install compodoc
2. cd to angular app
3. compodoc -p tsconfig.doc.json -s
4. observe the error

## Environment
Angular CLI: 16.0.3
Node: 18.16.0
Package Manager: yarn 1.22.19
OS: win32 x64

Angular: 16.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.3
@angular-devkit/build-angular   16.0.3
@angular-devkit/core            16.0.3
@angular-devkit/schematics      16.0.3
@angular/cdk                    16.0.2
@angular/material               16.0.2
@schematics/angular             16.0.3
ng-packagr                      16.0.1
rxjs                            7.5.7
typescript                      5.0.4
@compodoc/compodoc              1.1.21,

**Comment by vogloblinsky** [comment]
@windmillcode0 What kind of routing files do you have ?

**Comment by windmillcode0** [comment]
at that point in time just routing-module.ts files
