### ISSUE TITLE
[BUG] [Routing] Enums in routing data fails parsing 

### ISSUE THREAD

**Issue by Haynesy** [compodoc/compodoc#1366]
##### **Overview of the issue**

```
// Imported from another file
export enum PermissionCode {
	Admin_Access = 'Admin_Access',
	Admin_AccessClient = 'Admin_AccessClient',
}

const routes: Routes = [
	{
		path: '',
		component: StandardLayoutComponent,
		children: [
			{
				path: '',
				component: MapPageComponent,
				canActivate: [AuthGuard],
				data: {
					documentTitle: 'Map',
					permissions: [PermissionCode.Map_View],
				},
			},
		],
	},
];
```

The permissions array in the route causes an error on parsing in JSON5:  SyntaxError: JSON5: invalid character '.' at 1:194

Changing code to:
```
// Imported from another file
export enum PermissionCode {
	Admin_Access = 'Admin_Access',
	Admin_AccessClient = 'Admin_AccessClient',
}

const permissionMapView = PermissionCode.Map_View;
const routes: Routes = [
	{
		path: '',
		component: StandardLayoutComponent,
		children: [
			{
				path: '',
				component: MapPageComponent,
				canActivate: [AuthGuard],
				data: {
					documentTitle: 'Map',
					permissions: [permissionMapView],
				},
			},
		],
	},
];

Fixes the issue
```

##### **Operating System, Node.js, npm, compodoc version(s)**
node: v18.16.1
npm: 9.5.1
OS: Windows 11
Compodoc: 1.1.19

##### **Angular configuration, a `package.json` file in the root folder**

{
  "name": "bug-report-app-name",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng lint && jest && ng build",
    "build-prod": "ng lint && jest && ng build --configuration production",
    "test": "jest",
    "test-watch": "jest --watch",
    "lint": "ng lint",
    "mock:server": "npm run concat:mocks && json-server --routes mocks/routes.json --watch mocks/data.json",
    "start:proxy": "ng serve --proxy-config proxy.conf.json",
    "start:proxy:mock:server": "concurrently --kill-others \"npm run mock:server\" \"npm run start:proxy\"",
    "concat:mocks": "node \"./mocks/concat-json.js\"",
    "docs:json": "compodoc -p ./tsconfig.json -e json -d .",
    "storybook": "npm run docs:json && start-storybook -p 6006",
    "build-storybook": "npm run docs:json && build-storybook"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^16.1.5",
    "@angular/cdk": "^16.1.5",
    "@angular/common": "^16.1.5",
    "@angular/compiler": "^16.1.5",
    "@angular/core": "^16.1.5",
    "@angular/forms": "^16.1.5",
    "@angular/platform-browser": "^16.1.5",
    "@angular/platform-browser-dynamic": "^16.1.5",
    "@angular/router": "^16.1.5",
    "@carbon/icons": "^11.22.1",
    "@carbon/type": "^10.17.0",
    "@mapbox/mapbox-gl-draw": "^1.4.2",
    "@microsoft/signalr": "^7.0.0",
    "@ngneat/until-destroy": "^9.2.2",
    "@ngrx/component": "^16.1.0",
    "@ngrx/effects": "^16.1.0",
    "@ngrx/router-store": "^16.1.0",
    "@ngrx/store": "^16.1.0",
    "@ngrx/store-devtools": "^16.1.0",
    "@storybook/addon-a11y": "^6.5.12",
    "@turf/turf": "^6.5.0",
    "@types/mapbox-gl": "^2.1.0",
    "@types/signalr": "^2.2.37",
    "@watergis/mapbox-gl-export": "^2.0.1",
    "addon-screen-reader": "^1.8.6",
    "ag-grid-angular": "^28.1.0",
    "ag-grid-community": "^28.1.0",
    "ag-grid-enterprise": "^28.1.0",
    "aws-amplify": "^5.3.4",
    "bootstrap": "^4.6.2",
    "c": "^1.1.1",
    "carbon-components": "^10.38.0",
    "copy-to-clipboard": "^3.3.1",
    "crypto-js": "^4.0.0",
    "d3": "^7.8.5",
    "date-fns": "^2.28.0",
    "google-libphonenumber": "^3.2.18",
    "help": "^3.0.2",
    "install": "^0.13.0",
    "intl-tel-input": "^17.0.3",
    "jquery": "^3.6.0",
    "lodash": "^4.17.21",
    "mapbox-gl": "^2.9.1",
    "mathjs": "^11.8.2",
    "moment": "^2.29.4",
    "ng-qrcode": "^16.0.0",
    "ngx-bootstrap": "^6.2.0",
    "ngx-intl-tel-input": "3.2.0",
    "ngx-papaparse": "^5.1.0",
    "npm": "^9.8.0",
    "prettier": "^2.1.2",
    "primeflex": "^2.0.0",
    "primeicons": "^4.1.0",
    "primeng": "^16.0.2",
    "rxjs": "^7.8.1",
    "sass": "^1.32.13",
    "signalr": "^2.4.3",
    "stacktrace-js": "^2.0.2",
    "storybook-addon-breakpoints": "^1.0.0",
    "storybook-addon-designs": "^6.3.1",
    "storybook-addon-measure-viewport": "^0.2.1",
    "storybook-addon-perfect-design": "^1.0.1",
    "storybook-addon-related-links": "0.0.4",
    "storybook-color-picker": "^3.0.2",
    "tslib": "^2.6.0",
    "underscore": "^1.13.1",
    "uuid": "^9.0.0",
    "wicket": "^1.3.8",
    "zone.js": "^0.13.1"
  },
  "devDependencies": {
    "@angular-builders/jest": "^16.0.0",
    "@angular-devkit/build-angular": "^16.1.4",
    "@angular-eslint/builder": "^16.1.0",
    "@angular-eslint/eslint-plugin": "^16.1.0",
    "@angular-eslint/eslint-plugin-template": "^16.1.0",
    "@angular-eslint/schematics": "^16.1.0",
    "@angular-eslint/template-parser": "^16.1.0",
    "@angular/cli": "^16.1.4",
    "@angular/compiler-cli": "^16.1.5",
    "@angular/elements": "^16.1.5",
    "@babel/core": "^7.22.9",
    "@compodoc/compodoc": "^1.1.19",
    "@ngrx/eslint-plugin": "^16.1.0",
    "@ngrx/schematics": "^13.2.0",
    "@storybook/addon-actions": "^7.0.27",
    "@storybook/addon-essentials": "^7.0.27",
    "@storybook/addon-interactions": "^7.0.27",
    "@storybook/addon-links": "^7.0.27",
    "@storybook/angular": "^7.0.27",
    "@storybook/builder-webpack5": "^7.0.27",
    "@storybook/manager-webpack5": "^6.5.16",
    "@storybook/testing-library": "^0.2.0",
    "@types/d3": "^7.0.0",
    "@types/jest": "^28.1.3",
    "@types/lodash": "^4.14.181",
    "@types/node": "^15.14.9",
    "@typescript-eslint/eslint-plugin": "^5.29.0",
    "@typescript-eslint/parser": "^5.29.0",
    "@webcomponents/custom-elements": "^1.5.0",
    "babel-loader": "^9.1.3",
    "codelyzer": "^6.0.2",
    "concurrently": "^5.3.0",
    "eslint": "^8.2.0",
    "eslint-plugin-import": "2.27.5",
    "eslint-plugin-jsdoc": "46.4.4",
    "eslint-plugin-prefer-arrow": "^1.2.3",
    "eslint-plugin-rxjs": "^5.0.3",
    "eslint-plugin-rxjs-angular": "^2.0.1",
    "eslint-plugin-storybook": "^0.5.13",
    "jest": "^29.6.1",
    "jest-environment-jsdom": "^29.6.1",
    "jest-preset-angular": "^13.1.1",
    "jest-when": "^3.5.1",
    "json-concat": "0.0.1",
    "json-server": "^0.17.3",
    "ts-jest": "^29.1.1",
    "ts-node": "~8.3.0",
    "typescript": "<5.2",
    "webpack": "^5.88.0"
  },
  "browser": {
    "crypto": false,
    "fs": false,
    "path": false
  },
  "resolutions": {
    "webpack": "5.70.0"
  },
  "peerDependencies": {
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "uuid": "^9.0.0"
  },
  "overrides": {
    "ngx-intl-tel-input@3.2.0": {
      "@angular/common": "16.1.5",
      "@angular/core": "16.1.5",
      "@angular/forms": "16.1.5"
    }
  }
}

##### **Compodoc installed globally or locally ?**

Installed locally to the solution

##### **If possible sourcecode of the file where it breaks**

See above example

##### **If possible your terminal logs before the error**

**NOTE: Includes a console log I added to parse.js line 168:37 of json5**

[12:53:21] found          : OutgoingsComponent
{
  line: 1,
  column: 194,
  parseState: 'afterArrayValue',
  stack: [
    [ [Object] ],
    {
      path: '',
      component: 'StandardLayoutComponent',
      children: [Array]
    },
    [ [Object] ],
    {
      path: '',
      component: 'MapPageComponent',
      canActivate: [Array],
      data: [Object]
    },
    { documentTitle: 'Map', permissions: [Array] },
    [ 'PermissionCode' ]
  ],
  pos: 194,
  token: { type: 'string', value: 'PermissionCode', line: 1, column: 193 },
  key: 'permissions',
  root: [
    {
      path: '',
      component: 'StandardLayoutComponent',
      children: [Array]
    }
  ]
}
Unhandled Rejection at: Promise {
  <rejected> SyntaxError: JSON5: invalid character '.' at 1:194
      at syntaxError (C:\Development\vmol\products\VMOnline.Cobra\node_modules\json5\lib\parse.js:1110:17)
      at invalidChar (C:\Development\vmol\products\VMOnline.Cobra\node_modules\json5\lib\parse.js:1055:12)
      at Object.afterArrayValue (C:\Development\vmol\products\VMOnline.Cobra\node_modules\json5\lib\parse.js:694:15)
      at Object.default (C:\Development\vmol\products\VMOnline.Cobra\node_modules\json5\lib\parse.js:168:37)
      at lex (C:\Development\vmol\products\VMOnline.Cobra\node_modules\json5\lib\parse.js:100:42)
      at Object.parse (C:\Development\vmol\products\VMOnline.Cobra\node_modules\json5\lib\parse.js:25:17)
      at loopInsideModule (C:\Development\vmol\products\VMOnline.Cobra\node_modules\@compodoc\compodoc\dist\index.js:6345:63)
      at loopRoutesParser (C:\Development\vmol\products\VMOnline.Cobra\node_modules\@compodoc\compodoc\dist\index.js:6378:29)
      at loopRoutesParser (C:\Development\vmol\products\VMOnline.Cobra\node_modules\@compodoc\compodoc\dist\index.js:6389:21)
      at RouterParserUtil.constructRoutesTree (C:\Development\vmol\products\VMOnline.Cobra\node_modules\@compodoc\compodoc\dist\index.js:6393:9) {
    lineNumber: 1,
    columnNumber: 194
  }
} reason: SyntaxError: JSON5: invalid character '.' at 1:194
    at syntaxError (C:\Development\vmol\products\VMOnline.Cobra\node_modules\json5\lib\parse.js:1110:17)
    at invalidChar (C:\Development\vmol\products\VMOnline.Cobra\node_modules\json5\lib\parse.js:1055:12)
    at Object.afterArrayValue (C:\Development\vmol\products\VMOnline.Cobra\node_modules\json5\lib\parse.js:694:15)
    at Object.default (C:\Development\vmol\products\VMOnline.Cobra\node_modules\json5\lib\parse.js:168:37)
    at lex (C:\Development\vmol\products\VMOnline.Cobra\node_modules\json5\lib\parse.js:100:42)
    at Object.parse (C:\Development\vmol\products\VMOnline.Cobra\node_modules\json5\lib\parse.js:25:17)
    at loopInsideModule (C:\Development\vmol\products\VMOnline.Cobra\node_modules\@compodoc\compodoc\dist\index.js:6345:63)
    at loopRoutesParser (C:\Development\vmol\products\VMOnline.Cobra\node_modules\@compodoc\compodoc\dist\index.js:6378:29)
    at loopRoutesParser (C:\Development\vmol\products\VMOnline.Cobra\node_modules\@compodoc\compodoc\dist\index.js:6389:21)
    at RouterParserUtil.constructRoutesTree (C:\Development\vmol\products\VMOnline.Cobra\node_modules\@compodoc\compodoc\dist\index.js:6393:9) {
  lineNumber: 1,
  columnNumber: 194
}
[12:53:21] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)

##### **Motivation for or Use Case**

We have multiple routes in our solution set up with permission codes added in this way. Its inconvenient to add a const for every permission or enum we want to add to data.

##### **Reproduce the error**

I think an array using an enum syntax in the data section of a route should cause the issue

##### **Related issues**

I couldn't see any that matched exactly

##### **Suggest a Fix**

Not sure if this needs to be re-created in json5 or if its able to be handled in this package

**Comment by Haynesy** [comment]
Actually just had another one. It looks like it doesn't like any enum in the data payload.

Can also trigger the issue with 

```
{
    path: 'land/site',
    component: ModelGroupPageComponent,
    data: {
	    documentTitle: 'Land Site Models',
	    modelCategory: ModelCategory.Land,
    },
    pathMatch: 'full',
    canActivate: [AuthGuard],
}
```
It will complain about modelCategory

**Comment by Haynesy** [comment]
Also have a similar failure with `loadChildren` in the below code

```
const routes: Routes = [
	{
		path: '',
		children: [
			{
				path: ':assessmentNumber',
				component: PropertyPageComponent,
				canActivateChild: [AuthGuard],
				data: { letComponentSetDocumentTitle: true },
				loadChildren: () =>
					import('./property-page-routing.module').then(async (module) => {
						await module.selectRoutesToLoad(IdsPropertyRoutesModule.siteSettingService);
						return module.IdsPropertyPageRoutesModule;
					}),
			},
			{
				path: '**',
				pathMatch: 'full',
				component: PropertyPageComponent,
			},
		],
	},
];
```

Is fixed by moving function out to a const:

```
const loadThemChildren = () =>
	import('./property-page-routing.module').then(async (module) => {
		await module.selectRoutesToLoad(IdsPropertyRoutesModule.siteSettingService);
		return module.IdsPropertyPageRoutesModule;
	});

const routes: Routes = [
	{
		path: '',
		children: [
			{
				path: ':assessmentNumber',
				component: PropertyPageComponent,
				canActivateChild: [AuthGuard],
				data: { letComponentSetDocumentTitle: true },
				loadChildren: loadThemChildren,
			},
			{
				path: '**',
				pathMatch: 'full',
				component: PropertyPageComponent,
			},
		],
	},
];
```

**Comment by racetiger** [comment]
exactly the same behavior here when using an enum in the data protecting a route :

```typescript
const routes: Routes = [
	{
		path: 'schedule',
		component: TaskSchedulerPageComponent,
		canActivate: [AuthGuardService],
		data: { protectedWith: FEATURES.TASK_SCHEDULER }
	}
];
```
will produce : 

```
Unhandled Rejection at: Promise {
  <rejected> SyntaxError: JSON5: invalid character '.' at 1:120
      at syntaxError (/home/jdoe/.nvm/versions/node/v20.11.0/lib/node_modules/@compodoc/compodoc/node_modules/json5/lib/parse.js:1110:17)
```
but works fine if the enum is replaced by a constant :

```typescript
const routes: Routes = [
	{
		path: 'schedule',
		component: TaskSchedulerPageComponent,
		canActivate: [AuthGuardService],
		data: { protectedWith: FEATURES_TASK_SCHEDULER }
	}
];
``` 
version tested : `@compodoc/compodoc@1.1.25`

**Comment by jcardali** [comment]
Sharing another repro:

```
const routes: Routes = [
  {
    path: '',
    component: PageStepperWrapperComponent,
    data: {
      showCloseButton: true,
    },
    children: [
      {
        path: 'fivek',
        component: FivekComponent,
        data: {
          positionTierGuard: {
            excludedTiers: [TierEnum.V3]
          }
        },
      },
    ],
  },
];
```

Passing a string to `excludedTiers` clears up the error.

**Comment by kussmaul** [comment]
There are multiple reports of similar problems, e.g., #1023 #1025 #1126 #1334 #1366 #1415

I think the issue is that compodoc parses routes as JSON5, but Angular routes are **not** JSON5,
and so can use full javascript/typescript syntax, including spread operators, enums, property references, etc.
A workaround is to move all of the non-JSON5 syntax to constants, and use those constants in the routes.
