### ISSUE TITLE
[BUG] Error during generation of documentation

### ISSUE THREAD

**Issue by gualtierim** [compodoc/compodoc#1417]
Compodoc version: 1.1.23
Error:
`````
Unhandled Rejection at: Promise {
  <rejected> SyntaxError: JSON5: invalid character '.' at 1:1347
      at syntaxError (/Library/WebServer/Documents/Tierra/gazelle/gazelle-ng-frontend/node_modules/json5/lib/parse.js:1110:17)
      at invalidChar (/Library/WebServer/Documents/Tierra/gazelle/gazelle-ng-frontend/node_modules/json5/lib/parse.js:1055:12)
      at Object.afterPropertyValue (/Library/WebServer/Documents/Tierra/gazelle/gazelle-ng-frontend/node_modules/json5/lib/parse.js:676:15)
      at Object.default (/Library/WebServer/Documents/Tierra/gazelle/gazelle-ng-frontend/node_modules/json5/lib/parse.js:168:37)
      at lex (/Library/WebServer/Documents/Tierra/gazelle/gazelle-ng-frontend/node_modules/json5/lib/parse.js:100:42)
      at Object.parse (/Library/WebServer/Documents/Tierra/gazelle/gazelle-ng-frontend/node_modules/json5/lib/parse.js:25:17)
      at loopInsideModule (/Library/WebServer/Documents/Tierra/gazelle/gazelle-ng-frontend/node_modules/@compodoc/compodoc/dist/index.js:6592:59)
      at loopRoutesParser (/Library/WebServer/Documents/Tierra/gazelle/gazelle-ng-frontend/node_modules/@compodoc/compodoc/dist/index.js:6613:29)
      at loopRoutesParser (/Library/WebServer/Documents/Tierra/gazelle/gazelle-ng-frontend/node_modules/@compodoc/compodoc/dist/index.js:6624:21)
      at RouterParserUtil.constructRoutesTree (/Library/WebServer/Documents/Tierra/gazelle/gazelle-ng-frontend/node_modules/@compodoc/compodoc/dist/index.js:6628:9) {
    lineNumber: 1,
    columnNumber: 1347
  }
} reason: SyntaxError: JSON5: invalid character '.' at 1:1347
    at syntaxError (/Library/WebServer/Documents/Tierra/gazelle/gazelle-ng-frontend/node_modules/json5/lib/parse.js:1110:17)
    at invalidChar (/Library/WebServer/Documents/Tierra/gazelle/gazelle-ng-frontend/node_modules/json5/lib/parse.js:1055:12)
    at Object.afterPropertyValue (/Library/WebServer/Documents/Tierra/gazelle/gazelle-ng-frontend/node_modules/json5/lib/parse.js:676:15)
    at Object.default (/Library/WebServer/Documents/Tierra/gazelle/gazelle-ng-frontend/node_modules/json5/lib/parse.js:168:37)
    at lex (/Library/WebServer/Documents/Tierra/gazelle/gazelle-ng-frontend/node_modules/json5/lib/parse.js:100:42)
    at Object.parse (/Library/WebServer/Documents/Tierra/gazelle/gazelle-ng-frontend/node_modules/json5/lib/parse.js:25:17)
    at loopInsideModule (/Library/WebServer/Documents/Tierra/gazelle/gazelle-ng-frontend/node_modules/@compodoc/compodoc/dist/index.js:6592:59)
    at loopRoutesParser (/Library/WebServer/Documents/Tierra/gazelle/gazelle-ng-frontend/node_modules/@compodoc/compodoc/dist/index.js:6613:29)
    at loopRoutesParser (/Library/WebServer/Documents/Tierra/gazelle/gazelle-ng-frontend/node_modules/@compodoc/compodoc/dist/index.js:6624:21)
    at RouterParserUtil.constructRoutesTree (/Library/WebServer/Documents/Tierra/gazelle/gazelle-ng-frontend/node_modules/@compodoc/compodoc/dist/index.js:6628:9) {
  lineNumber: 1,
  columnNumber: 1347
}
`````

**Comment by vogloblinsky** [comment]
@gualtierim What kind of routing files do you have ?
