### ISSUE TITLE
[BUG] Unhandled Rejection - SyntaxError: JSON5: invalid character '.' at 1:588

### ISSUE THREAD

**Issue by Brett-Henning** [compodoc/compodoc#1426]
Hi, 

I tried to compile compodoc and ran into this error. Hope this is helpful to you.

Unhandled Rejection at: Promise {
  <rejected> SyntaxError: JSON5: invalid character '.' at 1:588
      at syntaxError (C:\Users\brett\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1110:17)
      at invalidChar (C:\Users\brett\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1055:12)
      at Object.afterPropertyValue (C:\Users\brett\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:676:15)
      at Object.default (C:\Users\brett\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:168:37)
      at lex (C:\Users\brett\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:100:42)       
      at Object.parse (C:\Users\brett\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:25:17)
      at loopInsideModule (C:\Users\brett\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index.js:6580:63)
      at loopRoutesParser (C:\Users\brett\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index.js:6613:29)
      at loopRoutesParser (C:\Users\brett\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index.js:6624:21)
      at loopRoutesParser (C:\Users\brett\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index.js:6624:21) {
    lineNumber: 1,
    columnNumber: 588
  }
} reason: SyntaxError: JSON5: invalid character '.' at 1:588
    at syntaxError (C:\Users\brett\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1110:17)
    at invalidChar (C:\Users\brett\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1055:12)
    at Object.afterPropertyValue (C:\Users\brett\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:676:15)
    at Object.default (C:\Users\brett\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:168:37)
    at lex (C:\Users\brett\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:100:42)
    at Object.parse (C:\Users\brett\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:25:17) 
    at loopInsideModule (C:\Users\brett\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index.js:6580:63)
    at loopRoutesParser (C:\Users\brett\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index.js:6613:29)
    at loopRoutesParser (C:\Users\brett\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index.js:6624:21)
    at loopRoutesParser (C:\Users\brett\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index.js:6624:21) {
  lineNumber: 1,
  columnNumber: 588
}

**Comment by vogloblinsky** [comment]
@Brett-Henning What kind of routing files do you have ?

**Comment by markwhitfeld** [comment]
This issue may contain your solution, or a way to figure out the issue: https://github.com/compodoc/compodoc/issues/1124
