### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'getKindName')

### ISSUE THREAD

**Issue by shanearthurrose** [compodoc/compodoc#1461]
[11:06:21] Analysing routes definitions and clean them if necessary
Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read properties of undefined (reading 'getKindName')
      at _loop_3 (C:\Users\s.rose\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index.js:6903:110)
      at RouterParserUtil.cleanFileSpreads (C:\Users\s.rose\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index.js:6915:17)
      at AngularDependencies.getSourceFileDecorators (C:\Users\s.rose\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index.js:10088:32)
      at C:\Users\s.rose\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index.js:9880:31
      at Array.map (<anonymous>)
      at AngularDependencies.getDependencies (C:\Users\s.rose\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index.js:9869:21)
      at Application.getDependenciesData (C:\Users\s.rose\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index.js:11669:40)
      at C:\Users\s.rose\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index.js:11475:23
} reason: TypeError: Cannot read properties of undefined (reading 'getKindName')
    at _loop_3 (C:\Users\s.rose\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index.js:6903:110)
    at RouterParserUtil.cleanFileSpreads (C:\Users\s.rose\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index.js:6915:17)
    at AngularDependencies.getSourceFileDecorators (C:\Users\s.rose\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index.js:10088:32)
    at C:\Users\s.rose\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index.js:9880:31
    at Array.map (<anonymous>)
    at AngularDependencies.getDependencies (C:\Users\s.rose\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index.js:9869:21)
    at Application.getDependenciesData (C:\Users\s.rose\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index.js:11669:40)
    at C:\Users\s.rose\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index.js:11475:23
[11:06:21] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)

**Comment by vogloblinsky** [comment]
Can i have informations about the file where it breaks.

**Comment by freed00m** [comment]
@vogloblinsky I observe this happens to me, when I try to do spread operator inside the routing array,

by default demoRoues is empty when running compodoc
```
// No demo routes in production
export const demoRoutes = []
```

```
import { demoRoutes } from './app-routing.module.dummy'

export const APP_ROUTES: Routes = [
  /**
   * Demo routes are empty array in production mode,
   *  see angular.json for list of file replacement.
   */
  ...demoRoutes,
  {
    path: '',
    redirectTo: '/overview',
    pathMatch: 'full',
  },
```

Also even without the spread operator,

i see a problem that compodoc has problem building array

```
[12:30:27] Error during generation of routes JSON file, maybe a trailing comma or an external variable inside one route.
```

As a workaround, I do the spread operator outside the file in the routing.module.ts

```
const APP_ROUTES_EXTRA = [...pilotRoutes, ...demoRoutes, ...APP_ROUTES]

@NgModule({
  imports: [RouterModule.forRoot(APP_ROUTES_EXTRA)],
  exports: [RouterModule],
})
export class AppRoutingModule {}
```

**Comment by vogloblinsky** [comment]
Already fixed
