### ISSUE TITLE
[BUG] getting issue while running npm run compodoc in angular project with nodejs <=18

### ISSUE THREAD

**Issue by akashmakde** [compodoc/compodoc#1506]
getting issue while running npm run compodoc in angular project
 ReadableStream
  ^

ReferenceError: ReadableStream is not defined
    at Object.<anonymous> (D:\3.0ang\my-app\node_modules\undici\lib\web\fetch\response.js:527:3)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)       
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (D:\3.0ang\my-app\node_modules\undici\lib\web\fetch\index.js:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)

OS: windows 11, node 16.20.0 angular 15.2.0 compodoc 1.1.19

**Comment by vogloblinsky** [comment]
Do you have a more detailed log error please ?
Before the `ReadableStream is not defined`

**Comment by Dhug95** [comment]
I have the exact same problem on macos. There are no details before, I have the same error message:

/Users/francesco/Desktop/redhgpl4us/com.enelgreenpower.pl4us-web/src/main/webapp/angular-elements/node_modules/undici/lib/web/fetch/response.js:527
  ReadableStream
  ^

ReferenceError: ReadableStream is not defined
    at Object.<anonymous> (/Users/francesco/Desktop/redhgpl4us/com.enelgreenpower.pl4us-web/src/main/webapp/angular-elements/node_modules/undici/lib/web/fetch/response.js:527:3)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/Users/francesco/Desktop/redhgpl4us/com.enelgreenpower.pl4us-web/src/main/webapp/angular-elements/node_modules/undici/lib/web/fetch/index.js:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
francesco@Francescos-MacBook-Pro angular-elements %

This seems to be related to the dependency undici that doesn't support node 16 since ReadableStream is available from node 18

The command used is > compodoc -p ./tsconfig.json -e json -d .

and the tsconfig file is this

`{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "module": "es2020",
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "allowSyntheticDefaultImports": true
  }
}`

**Comment by vogloblinsky** [comment]
@Dhug95 Strange because i didn't see `undici` in the package-lock.json of compodoc.
What is the parent of this dependency in your package-lock.json ?
Can i have the lines in your terminal (if possible) before the error ?
Unit tests of compodoc run fine on Node.js 16
Thanks

**Comment by Dhug95** [comment]
@vogloblinsky when I give the command to install compodoc I get this:

**EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'cheerio@1.0.0',
npm WARN EBADENGINE   required: { node: '>=18.17' },
npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'pdfmake@0.2.13',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'undici@6.19.8',
npm WARN EBADENGINE   required: { node: '>=18.17' },
npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'whatwg-mimetype@4.0.0',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'whatwg-encoding@3.1.1',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
npm WARN EBADENGINE }**

Then in the package-lock there is 

**"@compodoc/compodoc": {
      "version": "1.1.19",
      "resolved": "https://registry.npmjs.org/@compodoc/compodoc/-/compodoc-1.1.19.tgz",
      "integrity": "sha512-09vdSIgoAXWD1MiLZNhiljLNQ1XzHw/w5shw5IPcUImr/I+1Y52srUL46mEXN8AXo0hbHb5LZcgs70mmrOvY7Q==",
      "requires": {
        "@angular-devkit/schematics": "^13.2.4",
        "@babel/core": "^7.17.5",
        "@babel/preset-env": "^7.16.11",
        "@compodoc/live-server": "^1.2.3",
        "@compodoc/ngd-transformer": "^2.1.0",
        "chalk": "4.1.2",
        "cheerio": "^1.0.0-rc.10",
        "chokidar": "^3.5.3",
        "colors": "1.4.0",
        "commander": "^9.0.0",
        "cosmiconfig": "^7.0.1",
        "decache": "^4.6.1",
        "fancy-log": "^2.0.0",
        "findit2": "^2.2.3",
        "fs-extra": "^10.0.1",
        "glob": "^7.2.0",
        "handlebars": "^4.7.7",
        "html-entities": "^2.3.2",
        "i18next": "^21.6.11",
        "inside": "^1.0.0",
        "json5": "^2.2.0",
        "lodash": "^4.17.21",
        "loglevel": "^1.8.0",
        "loglevel-plugin-prefix": "^0.8.4",
        "lunr": "^2.3.9",
        "marked": "^4.0.12",
        "minimist": "^1.2.5",
        "opencollective-postinstall": "^2.0.3",
        "os-name": "4.0.1",
        "pdfjs-dist": "^2.12.313",
        "pdfmake": "^0.2.4",
        "semver": "^7.3.5",
        "traverse": "^0.6.6",
        "ts-morph": "^13.0.3",
        "uuid": "^8.3.2"
      },**

and the problem seems to be **cheerio**, even if here appears the version 1.0.0-rc.10 then in the same file there is this

**"cheerio": {
      "version": "1.0.0",
      "resolved": "https://registry.npmjs.org/cheerio/-/cheerio-1.0.0.tgz",
      "integrity": "sha512-quS9HgjQpdaXOvsZz82Oz7uxtXiy6UIsIQcpBj7HRw2M63Skasm9qlDocAM7jNuaxdhpPU7c4kJN+gA5MCu4ww==",
      "requires": {
        "cheerio-select": "^2.1.0",
        "dom-serializer": "^2.0.0",
        "domhandler": "^5.0.3",
        "domutils": "^3.1.0",
        "encoding-sniffer": "^0.2.0",
        "htmlparser2": "^9.1.0",
        "parse5": "^7.1.2",
        "parse5-htmlparser2-tree-adapter": "^7.0.0",
        "parse5-parser-stream": "^7.1.2",
        "undici": "^6.19.5",
        "whatwg-mimetype": "^4.0.0"
      },**

Here there are the lines of terminal

francesco@Francescos-MacBook-Pro angular-elements % npm run docs:json

> angular-elements@0.0.0 docs:json
> compodoc -p ./tsconfig.json -e json -d .

/Users/francesco/Desktop/redhgpl4us/com.enelgreenpower.pl4us-web/src/main/webapp/angular-elements/node_modules/undici/lib/web/fetch/response.js:527
  ReadableStream
  ^

ReferenceError: ReadableStream is not defined
    at Object.<anonymous> (/Users/francesco/Desktop/redhgpl4us/com.enelgreenpower.pl4us-web/src/main/webapp/angular-elements/node_modules/undici/lib/web/fetch/response.js:527:3)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/Users/francesco/Desktop/redhgpl4us/com.enelgreenpower.pl4us-web/src/main/webapp/angular-elements/node_modules/undici/lib/web/fetch/index.js:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)

**Comment by Dhug95** [comment]
I tried to install **cheerio version 1.0.0-rc.10** as dependency in my project and now it works. Probably the version should be forced to be that in the required dependencies of compodoc without the **"^"** otherwise it's broken on node 16

**EDIT**: if trying to remove package-lock and node_modules and start installing again, same problem

**Comment by vogloblinsky** [comment]
@Dhug95, ok the bug with Cheerio is fixed (https://github.com/compodoc/compodoc/issues/1504)
I will release a new version this afternoon. Stay tuned and let's see if it is fixed.

**Comment by Dhug95** [comment]
@vogloblinsky Hi, any news about the release?

**Comment by vogloblinsky** [comment]
Node.js 16 is no longer supported.
