### ISSUE TITLE
[BUG] Cannot find module 'json5'

### ISSUE THREAD

**Issue by shandilya3** [compodoc/compodoc#219]
Error: Cannot find module 'json5'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by Altafard** [comment]
npm i json5?

**Comment by Altafard** [comment]
Try install json5 globally

**Comment by shandilya3** [comment]
RangeError: Invalid array length
[14:49:21] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://gith
ub.com/compodoc/compodoc/issues/new)

**Comment by shandilya3** [comment]
npm install json5 worked  for me Thanks  @Altafard
