### ISSUE TITLE
[BUG] Graph generation error for large project

### ISSUE THREAD

**Issue by rarichard** [compodoc/compodoc#226]
##### **Overview of the issue**

When running compodoc with graphs enabled for a large project, receiving this error: 
abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ") at Error
    at jsStackTrace (/usr/local/lib/node_modules/angular2-dependencies-graph/node_modules/viz.js/viz.js:5:20800)
    at stackTrace (/usr/local/lib/node_modules/angular2-dependencies-graph/node_modules/viz.js/viz.js:5:20983)
    at abort (/usr/local/lib/node_modules/angular2-dependencies-graph/node_modules/viz.js/viz.js:28:5424)
    at abortOnCannotGrowMemory (/usr/local/lib/node_modules/angular2-dependencies-graph/node_modules/viz.js/viz.js:5:21343)
    at enlargeMemory (/usr/local/lib/node_modules/angular2-dependencies-graph/node_modules/viz.js/viz.js:5:21788)
    at Function.dynamicAlloc [as alloc] (/usr/local/lib/node_modules/angular2-dependencies-graph/node_modules/viz.js/viz.js:5:6269)
    at _sbrk (/usr/local/lib/node_modules/angular2-dependencies-graph/node_modules/viz.js/viz.js:5:602676)
    at N4 (/usr/local/lib/node_modules/angular2-dependencies-graph/node_modules/viz.js/viz.js:21:7406)
    at cK (/usr/local/lib/node_modules/angular2-dependencies-graph/node_modules/viz.js/viz.js:13:185312)
    at bK (/usr/local/lib/node_modules/angular2-dependencies-graph/node_modules/viz.js/viz.js:13:185061)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

##### **Operating System, Node.js, npm, compodoc version(s)**

OS: Mac OS 10.12.5
Node: 7.10.0
compodoc: 1.0.0-beta 10 

##### **Angular configuration, a `package.json` file in the root folder**

Angular 4, tsconfig.json and package.json in root folder of project.

##### **Compodoc installed globally or locally ?**
Compodoc installed globally.

##### **Motivation for or Use Case**

Would like to be able to see graphs for large projects. 

##### **Reproduce the error**

Run compodoc for a large projects without --disableGraph. See error thrown.

**Comment by vogloblinsky** [comment]
How many modules/ components do you have ?

**Comment by rarichard** [comment]
125 components, 98 modules

**Comment by vogloblinsky** [comment]
Ok reproduced with Primeng project: https://github.com/primefaces/primeng

**Comment by vogloblinsky** [comment]
@rarichard 
visjs is used during graph generation, and handle very badly large modules array.
What i have implemented is just a limit, over 150 modules, main graph generation is disabled.
Coming soon in 1.0.0-beta.14
