### ISSUE TITLE
[BUG] Compodoc on Travis CI raise a module not found error

### ISSUE THREAD

**Issue by nsanitate** [compodoc/compodoc#232]
##### **Overview of the issue**

When Travis CI starts my `npm run docs`, a module not found error is raised:

```bash
> rimraf docs && compodoc -t -p tsconfig.json -d docs -n "J2SE to JavaScript" --theme readthedocs --disableGraph --disablePrivateOrInternalSupport
module.js:487
    throw err;
    ^
Error: Cannot find module 'send'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/travis/build/apuliasoft/j2se-js/node_modules/live-server/index.js:10:9)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! j2se-js@0.0.0-development docs: `rimraf docs && compodoc -t -p tsconfig.json -d docs -n "J2SE to JavaScript" --theme readthedocs --disableGraph --disablePrivateOrInternalSupport`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the j2se-js@0.0.0-development docs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2017-07-19T17_02_56_193Z-debug.log
The command "npm run docs" exited with 1.
```

##### **Operating System, Node.js, npm, compodoc version(s)**

```
Operating System Details
   Distributor ID:	Ubuntu
   Description:	Ubuntu 12.04.5 LTS
   Release:	12.04
   Codename:	precise
Linux Version
   3.13.0-29-generic
$ node --version
v8.1.4
$ npm --version
5.0.3
$ compodoc --version
1.0.0-beta.13
```

##### **Angular configuration, a `package.json` file in the root folder**

```json
{
  "name": "j2se-js",
  "version": "0.0.0-development",
  "description": "j2se-js : a JavaScript porting of j2se framework",
  "main": "src/index.ts",
  "directories": {
    "src": "src",
    "doc": "docs",
    "test": "test"
  },
  "scripts": {
    "commit": "git-cz",
    "test:watch": "mocha -r ts-node/register **/*.spec.ts --watch-extensions ts --watch",
    "test": "nyc -e .ts -x **/*.spec.ts mocha -r ts-node/register **/*.spec.ts",
    "coverage": "nyc report --reporter=text-lcov | coveralls",
    "docs": "rimraf docs && compodoc -t -p tsconfig.json -d docs -n \"J2SE to JavaScript\" --theme readthedocs --disableGraph --disablePrivateOrInternalSupport",
    "build": "rimraf dist && tsc --project tsconfig.prod.json",
    "build-dev": "rimraf dist && tsc --project tsconfig.dev.json",
    "lint": "tslint -p tsconfig.dev.json",
    "postinstall": "",
    "semantic-release": "semantic-release pre && npm publish && semantic-release post"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/apuliasoft/j2se-js.git"
  },
  "keywords": [
    "j2se",
    "java",
    "util"
  ],
  "author": "ApuliaSoft <info@apuliasoft.com>",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/apuliasoft/j2se-js/issues"
  },
  "homepage": "https://github.com/apuliasoft/j2se-js#readme",
  "devDependencies": {
    "@compodoc/compodoc": "1.0.0-beta.13",
    "@types/chai": "~4.0.0",
    "@types/mocha": "~2.2.0",
    "chai": "~4.1.0",
    "commitizen": "~2.9.0",
    "coveralls": "~2.13.0",
    "cz-conventional-changelog": "~2.0.0",
    "mocha": "~3.4.0",
    "mocha-lcov-reporter": "~1.3.0",
    "nyc": "~11.0.0",
    "rimraf": "~2.6.0",
    "semantic-release": "~6.3.0",
    "ts-loader": "~2.3.0",
    "ts-node": "~3.2.0",
    "tslint": "~5.5.0",
    "typescript": "~2.4.0"
  },
  "config": {
    "commitizen": {
      "path": "node_modules/cz-conventional-changelog"
    }
  }
}

```

##### **Compodoc installed globally or locally ?**

locally

##### **Motivation for or Use Case**

I want to build documentation automatically and deploy on GitHub Pages for each commit.

##### **Suggest a Fix**

I suggest to remove `live-server` dependency if `-s` option is not set.

**Comment by vogloblinsky** [comment]
Did you do a clean npm install before running compodoc in your CI ?

Can i have the travis logs ?

There is an issue on live-server repository : https://github.com/tapio/live-server/issues/202

**Comment by nsanitate** [comment]
I cleaned the cache and rebuilt, but the result did not change

Here my travis log:
[j2se-js.travis-ci.txt](https://github.com/compodoc/compodoc/files/1161519/j2se-js.travis-ci.txt)

**Comment by nsanitate** [comment]
In the log I read:

```
npm ERR! extraneous: cors@2.8.4 /home/travis/build/apuliasoft/j2se-js/node_modules/cors
npm ERR! extraneous: opn@5.1.0 /home/travis/build/apuliasoft/j2se-js/node_modules/opn
npm ERR! extraneous: proxy-middleware@0.15.0 /home/travis/build/apuliasoft/j2se-js/node_modules/proxy-middleware
npm ERR! extraneous: send@0.15.3 /home/travis/build/apuliasoft/j2se-js/node_modules/send
npm ERR! extraneous: underscore.string@2.2.1 /home/travis/build/apuliasoft/j2se-js/node_modules/underscore.string
npm ERR! missing: cors@latest, required by live-server@1.2.0
npm ERR! missing: opn@latest, required by live-server@1.2.0
npm ERR! missing: proxy-middleware@latest, required by live-server@1.2.0
npm ERR! missing: send@latest, required by live-server@1.2.0
npm ERR! invalid: colors@1.1.2 /home/travis/build/apuliasoft/j2se-js/node_modules/live-server/node_modules/colors
npm ERR! invalid: event-stream@3.3.4 /home/travis/build/apuliasoft/j2se-js/node_modules/live-server/node_modules/event-stream
npm ERR! invalid: object-assign@4.1.1 /home/travis/build/apuliasoft/j2se-js/node_modules/live-server/node_modules/object-assign
npm ERR! missing: underscore.string@~2.2.0rc, required by travis-ci@2.1.1
```

All this library are also annotated as UNMET DEPENDENCY.

I will try to downgrade my local NPM from 5.3.0 to 5.0.3 (travis version). So maybe I can reproduce this error.

**Comment by vogloblinsky** [comment]
@nsanitate could reproduce the bug.
I have downgraded the dependency of live-server.
Between now and next 1.0.0-beta.14 compodoc release, you could add a npm-shrinkwrap.json file to override live-server version. Just tested on your repo, works fine :

```
{
  "dependencies": {
    "live-server": {
      "version": "1.1.0"
    }
  }
}
```
