### ISSUE TITLE
[BUG] 'Expected \'}\' instead of \'.\' at line 1 column 1015 of the JSON5 data. Still to read: ".\\"CREATE\\",\\"resourceT"'

### ISSUE THREAD

**Issue by randyaa** [compodoc/compodoc#361]
##### **Overview of the issue**

Trying to run compodoc over my existing application produces the following error. the stacktrace doesn't yield a lot of info:
```
[15:50:15] parsing        : C:/extras/code/gitlab/project-name/src/app/common/feature/feature-input/feature-input.component.ts
[15:50:15] found          : FeatureInputComponent
Unhandled Rejection at: Promise {
  <rejected> { SyntaxError: Expected '}' instead of '.' at line 1 column 1015 of the JSON5 data. Still to read: ".\"CREATE\",\"resourceT"
    at error (C:\extras\code\gitlab\projectx\authoring-ui\node_modules\json5\lib\json5.js:56:25)
    at next (C:\extras\code\gitlab\projectx\authoring-ui\node_modules\json5\lib\json5.js:72:17)
    at object (C:\extras\code\gitlab\projectx\authoring-ui\node_modules\json5\lib\json5.js:464:25)
    at value (C:\extras\code\gitlab\projectx\authoring-ui\node_modules\json5\lib\json5.js:482:20)
    at array (C:\extras\code\gitlab\projectx\authoring-ui\node_modules\json5\lib\json5.js:417:36)
    at value (C:\extras\code\gitlab\projectx\authoring-ui\node_modules\json5\lib\json5.js:484:20)
    at object (C:\extras\code\gitlab\projectx\authoring-ui\node_modules\json5\lib\json5.js:459:35)
    at value (C:\extras\code\gitlab\projectx\authoring-ui\node_modules\json5\lib\json5.js:482:20)
    at array (C:\extras\code\gitlab\projectx\authoring-ui\node_modules\json5\lib\json5.js:417:36)
    at value (C:\extras\code\gitlab\projectx\authoring-ui\node_modules\json5\lib\json5.js:484:20)
  message: 'Expected \'}\' instead of \'.\' at line 1 column 1015 of the JSON5 data. Still to read: ".\\"CREATE\\",\\"resourceT"',
  at: 1014,
  lineNumber: 1,
  columnNumber: 1015 } } reason: { SyntaxError: Expected '}' instead of '.' at line 1 column 1015 of the JSON5 data. Still to read: ".\"CREATE\",\"resourceT"
    at error (C:\extras\code\gitlab\projectx\authoring-ui\node_modules\json5\lib\json5.js:56:25)
    at next (C:\extras\code\gitlab\projectx\authoring-ui\node_modules\json5\lib\json5.js:72:17)
    at object (C:\extras\code\gitlab\projectx\authoring-ui\node_modules\json5\lib\json5.js:464:25)
    at value (C:\extras\code\gitlab\projectx\authoring-ui\node_modules\json5\lib\json5.js:482:20)
    at array (C:\extras\code\gitlab\projectx\authoring-ui\node_modules\json5\lib\json5.js:417:36)
    at value (C:\extras\code\gitlab\projectx\authoring-ui\node_modules\json5\lib\json5.js:484:20)
    at object (C:\extras\code\gitlab\projectx\authoring-ui\node_modules\json5\lib\json5.js:459:35)
    at value (C:\extras\code\gitlab\projectx\authoring-ui\node_modules\json5\lib\json5.js:482:20)
    at array (C:\extras\code\gitlab\projectx\authoring-ui\node_modules\json5\lib\json5.js:417:36)
    at value (C:\extras\code\gitlab\projectx\authoring-ui\node_modules\json5\lib\json5.js:484:20)
  message: 'Expected \'}\' instead of \'.\' at line 1 column 1015 of the JSON5 data. Still to read: ".\\"CREATE\\",\\"resourceT"',
  at: 1014,
  lineNumber: 1,
  columnNumber: 1015 }
```
I've tried removing all the code in `feature-input.component.ts` and it yields the same error so I don't think that's where the problem is

##### **Operating System, Node.js, npm, compodoc version(s)**

Windows 7, node 6.11.1, npm 3.10.10, ng-cli 1.2.6, compodoc 1.0.3

##### **Angular configuration, a `package.json` file in the root folder**

not exactly sure what you're looking for here but these are the versions we're using
```
@angular/cli: 1.2.6
node: 6.11.1
os: win32 x64
@angular/animations: 4.4.3
@angular/cdk: 2.0.0-beta.11
@angular/common: 4.4.3
@angular/compiler: 4.4.3
@angular/core: 4.4.3
@angular/forms: 4.4.3
@angular/http: 4.4.3
@angular/material: 2.0.0-beta.11
@angular/platform-browser: 4.4.3
@angular/platform-browser-dynamic: 4.4.3
@angular/router: 4.4.3
@angular/cli: 1.2.6
@angular/compiler-cli: 4.4.3
```

##### **Compodoc installed globally or locally ?**

locally

##### **Motivation for or Use Case**

...

##### **Reproduce the error**

not able to figure this out yet...

**Comment by vogloblinsky** [comment]
@randyaa I just had the same issue when working for the issue https://github.com/compodoc/compodoc/issues/216
FeatureInputComponent is the last file parsed, and after routing mixing stuff happened, and there is a route where i think you have someting dynamic, an enum, etc.
Can you post an example of one of these custom routes ?
Thanks

**Comment by GermainMoreau** [comment]
Hi @vogloblinsky, getting more or less the same error here..!

When compodoc tries to parse app-routing.module:

> Routes parsing error, maybe a trailing comma or an external variable, trying to fix that later after sources scanning.

I think that this produce this error for me (just after parsing the latest file):

`Unhandled Rejection at: Promise {
  <rejected> { SyntaxError: Expected '}' instead of '.' at line 1 column 76 of the JSON5 data. Still to read: ".\"uploadPath\",\"compo"`...

You'll find my AppRoutingModule below:

```
import {NgModule} from '@angular/core';
import {RouterModule, Routes} from '@angular/router';
import {ApplicationComponent} from '../application/application.component';
import {ApplicationConst} from './routingConst';
import {AuthGuard} from './authGuard';
import {NewPasswordComponent} from '../application/new-password/new-password.component';

const appRoutes: Routes = [
  {path: '', component: ApplicationComponent},
  {path: ApplicationConst.uploadPath, component: ApplicationComponent, canActivate: [AuthGuard]},
  {path: ApplicationConst.resetPasswordPath, component: NewPasswordComponent},
  {path: '**', redirectTo: '', pathMatch: 'full'}
];

@NgModule({
  imports: [RouterModule.forRoot(appRoutes)],
  exports: [RouterModule]
})

export class AppRoutingModule {
}
```

I remain at your disposal for every questions! :)

**Comment by vogloblinsky** [comment]
Yes @GermainMoreau, thanks for your feedback.
`ApplicationConst.uploadPath` is a dynamic import string, i have to handle that for routes.
The stuff was done for components/directives metadatas, it will not take so much time.
I will work on that today and tomorrow.
Stay tuned.

**Comment by vogloblinsky** [comment]
Bug fixed for dynamic path and pathMatch for route definition.
Need to work on other parts of route description : angular.io/api/router/Routes#description
@randyaa Is there any routes in your app with dynamic path ?

**Comment by disophisis** [comment]
We've got something very similar and I just wanted to make sure it's a case that will be handled by any fixes here.

When declaring routes, we're using enum values for the `rights:` field:

```
const routes: Routes = [ 
	{
		path: '',
		component: UsersComponent,
		data: {
			pageTitle: 'PAGE.TITLE',
			pageIcon: 'person',
			rights: [GenericRight.Right],
		},
	},
];
```

The parser is failing on the GenericRight.Right enum value with this stack trace:

Unhandled Rejection at: Promise {
  <rejected> { SyntaxError: Expected ']' instead of '.' at line 1 column 136 of the JSON5 data. Still to read: ".\"Right\"]"
...
...
...
  message: 'Expected \']\' instead of \'.\' at line 1 column 136 of the JSON5 data. Still to read: ".\\"Right\\"]"',
  at: 135,

We've temporarily gotten around this by declaring these rights ahead of time and just using that variable  when setting the `rights:` field.

**Comment by vogloblinsky** [comment]
Yes @disophisis it is in my todolist.
It is the `GenericRight.Right` which breaks the stuff.
I had to scan data informations for each routes, and found if there is a dynamic variable like this, and replace it during TypeScript AST parsing.
Keep in touch with this issue.
