### ISSUE TITLE
[BUG]: Dynamic route | Unhandled Rejection Parsing Route

### ISSUE THREAD

**Issue by khoying** [compodoc/compodoc#374]
##### **Overview of the issue**

I am new to compodoc.  I was hoping to use it to document our Angular application.  However, it is failing to build the documentation.  It appears that it is unable to parse the routing configuration.  I suspect that this is due to that routing name not being hard coded but references from a properties class.

##### **Operating System, Node.js, npm, compodoc version(s)**

compodoc version 1.0.4

##### **Angular configuration, a `package.json` file in the root folder**

Not sure what you are asking.  You want a copy of package.json???

##### **Compodoc installed globally or locally ?**

Installed locally.  Referenced in the package.json

##### **Motivation for or Use Case**

Because it does not work.

##### **Reproduce the error**

Run the script:  ./node_modules/.bin/compodoc -p ./tsconfig.json
And get the error:
Unhandled Rejection at: Promise {
  <rejected> { SyntaxError: Expected '}' instead of '.' at line 1 column 23 of the JSON5 data. Still to read: ".\"ROUTES\".\"admin\".\"h"
    at error (C:\Users\khoying\Documents\Projects\SupplyChain\Hydra\workspace\hydra\hydra-web\build\static\node_modules\json5\lib\json5.js:56:25)
    at next (C:\Users\khoying\Documents\Projects\SupplyChain\Hydra\workspace\hydra\hydra-web\build\static\node_modules\json5\lib\json5.js:72:17)
    at object (C:\Users\khoying\Documents\Projects\SupplyChain\Hydra\workspace\hydra\hydra-web\build\static\node_modules\json5\lib\json5.js:464:25)
    at value (C:\Users\khoying\Documents\Projects\SupplyChain\Hydra\workspace\hydra\hydra-web\build\static\node_modules\json5\lib\json5.js:482:20)
    at array (C:\Users\khoying\Documents\Projects\SupplyChain\Hydra\workspace\hydra\hydra-web\build\static\node_modules\json5\lib\json5.js:417:36)
    at value (C:\Users\khoying\Documents\Projects\SupplyChain\Hydra\workspace\hydra\hydra-web\build\static\node_modules\json5\lib\json5.js:484:20)
    at Object.parse (C:\Users\khoying\Documents\Projects\SupplyChain\Hydra\workspace\hydra\hydra-web\build\static\node_modules\json5\lib\json5.js:508:18)
    at loopModulesParser (C:\Users\khoying\Documents\Projects\SupplyChain\Hydra\workspace\hydra\hydra-web\build\static\node_modules\@compodoc\compodoc\dist\index-cli.js:654:48)
    at loopModulesParser (C:\Users\khoying\Documents\Projects\SupplyChain\Hydra\workspace\hydra\hydra-web\build\static\node_modules\@compodoc\compodoc\dist\index-cli.js:660:25)
    at RouterParserUtil.constructRoutesTree (C:\Users\khoying\Documents\Projects\SupplyChain\Hydra\workspace\hydra\hydra-web\build\static\node_modules\@compodoc\compodoc\dist\index-cli.js:692:13)
  message: 'Expected \'}\' instead of \'.\' at line 1 column 23 of the JSON5 data. Still to read: ".\\"ROUTES\\".\\"admin\\".\\"h"',
  at: 22,
  lineNumber: 1,
  columnNumber: 23 } } reason: { SyntaxError: Expected '}' instead of '.' at line 1 column 23 of the JSON5 data. Still to read: ".\"ROUTES\".\"admin\".\"h"
    at error (C:\Users\khoying\Documents\Projects\SupplyChain\Hydra\workspace\hydra\hydra-web\build\static\node_modules\json5\lib\json5.js:56:25)
    at next (C:\Users\khoying\Documents\Projects\SupplyChain\Hydra\workspace\hydra\hydra-web\build\static\node_modules\json5\lib\json5.js:72:17)
    at object (C:\Users\khoying\Documents\Projects\SupplyChain\Hydra\workspace\hydra\hydra-web\build\static\node_modules\json5\lib\json5.js:464:25)
    at value (C:\Users\khoying\Documents\Projects\SupplyChain\Hydra\workspace\hydra\hydra-web\build\static\node_modules\json5\lib\json5.js:482:20)
    at array (C:\Users\khoying\Documents\Projects\SupplyChain\Hydra\workspace\hydra\hydra-web\build\static\node_modules\json5\lib\json5.js:417:36)
    at value (C:\Users\khoying\Documents\Projects\SupplyChain\Hydra\workspace\hydra\hydra-web\build\static\node_modules\json5\lib\json5.js:484:20)
    at Object.parse (C:\Users\khoying\Documents\Projects\SupplyChain\Hydra\workspace\hydra\hydra-web\build\static\node_modules\json5\lib\json5.js:508:18)
    at loopModulesParser (C:\Users\khoying\Documents\Projects\SupplyChain\Hydra\workspace\hydra\hydra-web\build\static\node_modules\@compodoc\compodoc\dist\index-cli.js:654:48)
    at loopModulesParser (C:\Users\khoying\Documents\Projects\SupplyChain\Hydra\workspace\hydra\hydra-web\build\static\node_modules\@compodoc\compodoc\dist\index-cli.js:660:25)
    at RouterParserUtil.constructRoutesTree (C:\Users\khoying\Documents\Projects\SupplyChain\Hydra\workspace\hydra\hydra-web\build\static\node_modules\@compodoc\compodoc\dist\index-cli.js:692:13)
  message: 'Expected \'}\' instead of \'.\' at line 1 column 23 of the JSON5 data. Still to read: ".\\"ROUTES\\".\\"admin\\".\\"h"',
  at: 22,
  lineNumber: 1,
  columnNumber: 23 }
[08:01:55] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)

The routing is defined as:
const adminRoutes: Routes = [
  	{	path: Properties.ROUTES.admin.home.route,
  		component: AdminComponent,
  		data: { breadcrumb: Properties.ROUTES.admin.home.breadcrumb }
  	}
];

##### **Related issues**

Not that I am aware

##### **Suggest a Fix**

Ability to support routes defined as above using variables. And/Or provide that ability to disable the routing documentation so that the rest of the documentation can be generated at least.

**Comment by vogloblinsky** [comment]
Can i have an example of the failing route ?
Working on it here : https://github.com/compodoc/compodoc/issues/216

**Comment by khoying** [comment]
Here is an example:

```
const adminRoutes: Routes = [
  	{	path: Properties.ROUTES.admin.home.route,
  		component: AdminComponent,
  		data: { breadcrumb: Properties.ROUTES.admin.home.breadcrumb }
  	}
];
```

**Comment by vogloblinsky** [comment]
Bug fixed for dynamic path and pathMatch for route definition.
Need to work on other parts of route description : angular.io/api/router/Routes#description
