### ISSUE TITLE
[BUG] Error 'TypeError: Cannot read property 'kind' of undefined' when building documentation

### ISSUE THREAD

**Issue by okon3** [compodoc/compodoc#396]
##### **Overview of the issue**

Generating the documentation fails with:
```
Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'kind' of undefined
    at Object.isStringLiteral (E:\projects\Project\node_modules\@compodoc\compodoc\node_modules\typescript\lib\typescript.js:11237:21)
    at SymbolHelper.parseSymbols (E:\projects\Project\node_modules\@compodoc\compodoc\dist\index-cli.js:3121:16)
    at E:\projects\Project\node_modules\@compodoc\compodoc\dist\index-cli.js:3145:53
    at Array.map (<anonymous>)
    at SymbolHelper.getSymbolDeps (E:\projects\Project\node_modules\@compodoc\compodoc\dist\index-cli.js:3145:21)
    at ModuleHelper.getModuleProviders (E:\projects\Project\node_modules\@compodoc\compodoc\dist\index-cli.js:3371:14)
    at ModuleDepFactory.create (E:\projects\Project\node_modules\@compodoc\compodoc\dist\index-cli.js:3285:42)
    at visitNode (E:\projects\Project\node_modules\@compodoc\compodoc\dist\index-cli.js:4525:34)
    at Array.forEach (<anonymous>)
    at parseNode (E:\projects\Project\node_modules\@compodoc\compodoc\dist\index-cli.js:4631:26) } reason: TypeError: Cannot read property 'kind' of undefined
    at Object.isStringLiteral (E:\projects\Project\node_modules\@compodoc\compodoc\node_modules\typescript\lib\typescript.js:11237:21)
    at SymbolHelper.parseSymbols (E:\projects\Project\node_modules\@compodoc\compodoc\dist\index-cli.js:3121:16)
    at E:\projects\Project\node_modules\@compodoc\compodoc\dist\index-cli.js:3145:53
    at Array.map (<anonymous>)
    at SymbolHelper.getSymbolDeps (E:\projects\Project\node_modules\@compodoc\compodoc\dist\index-cli.js:3145:21)
    at ModuleHelper.getModuleProviders (E:\projects\Project\node_modules\@compodoc\compodoc\dist\index-cli.js:3371:14)
    at ModuleDepFactory.create (E:\projects\Project\node_modules\@compodoc\compodoc\dist\index-cli.js:3285:42)
    at visitNode (E:\projects\Project\node_modules\@compodoc\compodoc\dist\index-cli.js:4525:34)
    at Array.forEach (<anonymous>)
    at parseNode (E:\projects\Project\node_modules\@compodoc\compodoc\dist\index-cli.js:4631:26)
[11:21:02] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! project@1.1.0 compodoc: `compodoc -p src/tsconfig.app.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the project@1.1.0 compodoc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\luca\AppData\Roaming\npm-cache\_logs\2017-12-02T10_21_02_197Z-debug.log
```

This is the content of the log from npm:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'compodoc' ]
2 info using npm@5.5.1
3 info using node@v8.9.0
4 verbose run-script [ 'precompodoc', 'compodoc', 'postcompodoc' ]
5 info lifecycle project@1.1.0~precompodoc: project@1.1.0
6 info lifecycle project@1.1.0~compodoc: project@1.1.0
7 verbose lifecycle project@1.1.0~compodoc: unsafe-perm in lifecycle true
8 verbose lifecycle project@1.1.0~compodoc: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;E:\projects\Project\node_modules\.bin;c:\programdata\oracle\java\javapath;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\ProgramData\chocolatey\bin;C:\Program Files\Java\jdk1.8.0_131\bin;C:\Android\android-sdk\tools;C:\Android\android-sdk\platform-tools;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin;C:\Users\luca\AppData\Local\.meteor\;C:\Users\luca\AppData\Local\atom\bin;c:\Git\bin\;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\luca\AppData\Roaming\npm;C:\Users\luca\AppData\Local\Yarn\bin
9 verbose lifecycle project@1.1.0~compodoc: CWD: E:\projects\Project
10 silly lifecycle project@1.1.0~compodoc: Args: [ '/d /s /c', 'compodoc -p src/tsconfig.app.json' ]
11 silly lifecycle project@1.1.0~compodoc: Returned: code: 1  signal: null
12 info lifecycle project@1.1.0~compodoc: Failed to exec compodoc script
13 verbose stack Error: project@1.1.0 compodoc: `compodoc -p src/tsconfig.app.json`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid project@1.1.0
15 verbose cwd E:\projects\Project
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "compodoc"
18 verbose node v8.9.0
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error project@1.1.0 compodoc: `compodoc -p src/tsconfig.app.json`
22 error Exit status 1
23 error Failed at the project@1.1.0 compodoc script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

And this is the full compodoc log from the terminal:
https://pastebin.com/TZqzRZ7C

##### **Operating System, Node.js, npm, compodoc version(s)**

```
Angular CLI: 1.5.4
Node: 8.9.0
OS: win32 x64
Angular: 5.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.4
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.4
@schematics/angular: 0.1.2
typescript: 2.4.2
webpack-bundle-analyzer: 2.9.1
webpack: 3.8.1
```

##### **Angular configuration, a `package.json` file in the root folder**

```
{
	"name": "project",
	"version": "1.1.0",
	"license": "MIT",
	"scripts": {
		"ng": "ng",
		"start": "yarn && ng serve --aot",
		"test": "yarn && ng test",
		"lint": "yarn && ng lint",
		"e2e": "yarn && ng e2e",
		"compodoc": "./node_modules/.bin/compodoc -p src/tsconfig.app.json",
	},
	"private": true,
	"dependencies": {
		"@angular/animations": "^5.0.0",
		"@angular/common": "^5.0.0",
		"@angular/compiler": "^5.0.0",
		"@angular/core": "^5.0.0",
		"@angular/forms": "^5.0.0",
		"@angular/http": "^5.0.0",
		"@angular/platform-browser": "^5.0.0",
		"@angular/platform-browser-dynamic": "^5.0.0",
		"@angular/router": "^5.0.0",
		"@ngrx/effects": "^4.1.0",
		"@ngrx/store": "^4.1.0",
		"animate.css": "3.5.2",
		"bootstrap": "^3.3.7",
		"classlist.js": "^1.1.20150312",
		"clusterize.js": "^0.18.0",
		"core-js": "^2.4.1",
		"dragula": "^3.7.2",
		"file-saver": "^1.3.3",
		"font-awesome": "^4.7.0",
		"icheck": "^1.0.2",
		"jquery": "^3.1.1",
		"jquery-match-height": "^0.7.2",
		"jquery-slimscroll": "^1.3.8",
		"jqueryui": "^1.11.1",
		"jspdf": "^1.3.5",
		"jspdf-autotable": "^2.3.2",
		"mdn-polyfills": "^2.1.1",
		"metismenu": "^2.6.2",
		"nestable": "^0.2.0",
		"ng2-dragula": "^1.5.0",
		"rxjs": "^5.5.2",
		"toastr": "^2.1.2",
		"xlsx": "^0.11.8",
		"zone.js": "^0.8.18"
	},
	"devDependencies": {
		"@angular/cli": "1.5.4",
		"@angular/compiler-cli": "^5.0.0",
		"@angular/language-service": "^5.0.0",
		"@compodoc/compodoc": "1.0.5",
		"@ngrx/store-devtools": "^4.0.0",
		"@types/file-saver": "~0.0.1",
		"@types/jasmine": "~2.5.53",
		"@types/jasminewd2": "~2.0.2",
		"@types/jspdf": "~1.1.31",
		"@types/node": "~6.0.60",
		"codelyzer": "~4.0.1",
		"jasmine-core": "~2.6.2",
		"jasmine-spec-reporter": "~4.1.0",
		"karma": "~1.7.0",
		"karma-chrome-launcher": "~2.1.1",
		"karma-cli": "~1.0.1",
		"karma-coverage-istanbul-reporter": "^1.2.1",
		"karma-jasmine": "~1.1.0",
		"karma-jasmine-html-reporter": "^0.2.2",
		"protractor": "~5.1.2",
		"ts-node": "~3.2.0",
		"tslint": "~5.7.0",
		"typescript": "~2.4.2",
		"webpack-bundle-analyzer": "^2.9.0"
	}
}

```

##### **Compodoc installed globally or locally ?**

locally, to run it i use `npm run compodoc`

##### **Motivation for or Use Case**

I can't build the documentation at all

##### **Reproduce the error**

It's hard for me to find the minimal required files to reproduce the error since it's the first time i'm trying compodoc and i don't have a "previous working configuration". Also I can't share all the code since the application is for a client

##### **Related issues**

Didn't find anything relevant

**Comment by vogloblinsky** [comment]
Try with 1.0.4
I will look that asap

**Comment by vogloblinsky** [comment]
Can i have the content of `E:/projects/Project/src/app/shared/shared.module.ts` ?

**Comment by okon3** [comment]
I have the error both on 1.0.4 and 1.0.5

here's the shared.module.ts

```
import { SearchLiv0Pipe } from './commons/pipes/searchLiv0.pipe';
import { SearchPipe } from './commons/pipes/search.pipe';


import { AuthenticationService } from './commons/services/authentication.service';

import { RoutingEffects } from './state/effects/routing-effects';
import { CommonCascadeActionsEffect } from './state/effects/common-cascade-actions-effects';
import { CommonRestService } from './commons/services/common-rest.service';
import { CommonRestEffects } from './state/effects/common-rest-effects';
import { RoutingTableService } from './commons/services/routing-table.service';
import { EffectsModule } from '@ngrx/effects';
import { SettingsEffects } from './state/effects/settings-effects';
import { ProxyEventDispatcherService } from './commons/services/ProxyEventDispatcherService';
import { InitializeDirective } from './commons/directives/initialize.directive';
import { DragulaModule } from 'ng2-dragula/components/dragular.module';
import { TemplateService } from './commons/services/template.service';
import { StoreDevtoolsModule } from '@ngrx/store-devtools';
import { StoreModule } from '@ngrx/store';
import { FormsModule } from '@angular/forms';
import { RouterModule, Router } from '@angular/router';
import { HttpModule, Http, XHRBackend, RequestOptions } from '@angular/http';
import { httpFactory } from './commons/interceptors/InterceptedHttp';
import { NgModule, ModuleWithProviders, Injector } from '@angular/core';
import { CommonModule } from '@angular/common';
import { BasicTemplateComponent } from './layouts/basic-template/basic-template.component';
import { EmptyTemplateComponent } from './layouts/empty-template/empty-template.component';
import { SidebarListComponent } from './commons/components/sidebar-template/sidebar-list/sidebar-list.component';
import { SidebarTemplateComponent } from './commons/components/sidebar-template/sidebar-template.component';
import { FooterTemplateComponent } from './commons/components/footer-template/footer-template.component';
import { TopnavbarTemplateComponent } from './commons/components/topnavbar-template/topnavbar-template.component';
import {VirtualScrollModule} from 'od-virtualscroll';

import { reducers } from './state/all-reducers';

import * as Stats from './../stats/commons/services/routing-table.service';
import * as Dynam from './../dynam/services/routing-table.service';
import { SettingsComponent } from './commons/components/settings/settings.component';
import { CardComponent } from './commons/components/card/card.component';

export const modules = [
	CommonModule,
	DragulaModule,
	FormsModule,
	HttpModule,
	RouterModule,
	VirtualScrollModule,
	StoreModule,
	StoreDevtoolsModule
];

export const declarations = [
	BasicTemplateComponent,
	EmptyTemplateComponent,
	SidebarTemplateComponent,
	SidebarListComponent,
	FooterTemplateComponent,
	TopnavbarTemplateComponent,
	InitializeDirective,
	SettingsComponent,
	CardComponent,
	SearchPipe,
	SearchLiv0Pipe
];

export const providers = [
	{
		provide: Http,
		useFactory: httpFactory,
		deps: [XHRBackend, RequestOptions, RoutingTableService, Injector]
	},
	TemplateService,
	ProxyEventDispatcherService,
	RoutingTableService,
	CommonRestService,
	AuthenticationService
];

@NgModule({
	imports: [
		...modules,
		StoreModule.forFeature('sharedModule', reducers),
		EffectsModule.forFeature([
			SettingsEffects,
			CommonRestEffects,
			CommonCascadeActionsEffect,
			RoutingEffects,

			Stats.RoutingTableService,
			Dynam.RoutingTableService
		]),
	],
	exports: [
		...modules,
		...declarations
	],
	declarations,
	providers
})

export class SharedModule {
	static forRoot(): ModuleWithProviders {
		return {
			ngModule: SharedModule,
			providers
		};
	}
}
```

I forgot to mention we have these warnings while compiling the app (which runs fine):
```
WARNING in Circular dependency detected:
src\app\shared\state\all-reducers.ts -> src\app\shared\state\reducers\template-reducers.ts -> src\app\shared\state\all-reducers.ts

WARNING in Circular dependency detected:
src\app\shared\state\reducers\template-reducers.ts -> src\app\shared\state\all-reducers.ts -> src\app\shared\state\reducers\template-reducers.ts

WARNING in Circular dependency detected:
src\app\stats\views\tab\tab-filter-cascade\tab-filter-cascade.component.ngfactory.js -> src\app\stats\views\tab\tab-filter-master\tab-filter-master.component.ngfactory.js -> src\app\stats\views\tab\tab-filter-cascade\tab-filter-cascade.component.ngfactory.js

WARNING in Circular dependency detected:
src\app\stats\views\tab\tab-filter-exclusive\tab-filter-exclusive.component.ngfactory.js -> src\app\stats\views\tab\tab-filter-master\tab-filter-master.component.ngfactory.js -> src\app\stats\views\tab\tab-filter-exclusive\tab-filter-exclusive.component.ngfactory.js

WARNING in Circular dependency detected:
src\app\stats\views\tab\tab-filter-master\tab-filter-master.component.ngfactory.js -> src\app\stats\views\tab\tab-filter-exclusive\tab-filter-exclusive.component.ngfactory.js -> src\app\stats\views\tab\tab-filter-master\tab-filter-master.component.ngfactory.js

```

**Comment by vogloblinsky** [comment]
Thanks, reproduced

**Comment by jberall** [comment]
I had a similar error and it was because I had a get username() { return 'val';} in my service.
I changed to getUsername().

I found the error by going to the file where it crashed and eliminating each method until I found the issue and workaround so compodoc could work.

**Comment by vogloblinsky** [comment]
Related to https://github.com/compodoc/compodoc/issues/407

**Comment by guilhermejcgois** [comment]
I'm still having this same issue with 1.1.3 with this:
```
export const selector = 'app-selector';
@Component({
  selector
})
export class Component { }
```
Documentation generation only proceeds if I change to
```
export const selector = 'app-selector';

@Component({
  selector: selector
})
export class Component { }
```
Inclusive, I have checked the source inside node_modules and the code of #295a029 is present, I suppose that should work, but it don't
