### ISSUE TITLE
handlebars is not in the dependency list

### ISSUE THREAD

**Issue by shlomiassaf** [compodoc/compodoc#4]
After npm install I get this:
```
Error: Cannot find module 'handlebars'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/compodoc/dist/index.js:8:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

had to `npm install -g handlebars` to get it working...

**Comment by vogloblinsky** [comment]
Fixed in [v0.0.6](https://github.com/compodoc/compodoc/releases/tag/v0.0.6)
