### ISSUE TITLE
[BUG] Got error when parsing spread operator in routes

### ISSUE THREAD

**Issue by seokju-na** [compodoc/compodoc#404]
##### **Overview of the issue**

```
Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'forEach' of undefined
    at /Users/townus/.nvm/versions/node/v8.9.1/lib/node_modules/@compodoc/compodoc/dist/index-cli.js:993:32
    at Array.forEach (<anonymous>)
    at RouterParserUtil.cleanRoutesDefinitionWithImport (/Users/townus/.nvm/versions/node/v8.9.1/lib/node_modules/@compodoc/compodoc/dist/index-cli.js:992:30)
    at Dependencies.visitEnumDeclarationForRoutes (/Users/townus/.nvm/versions/node/v8.9.1/lib/node_modules/@compodoc/compodoc/dist/index-cli.js:5153:67)
    at /Users/townus/.nvm/versions/node/v8.9.1/lib/node_modules/@compodoc/compodoc/dist/index-cli.js:5179:51
    at Array.reduce (<anonymous>)
    at Dependencies.getRouteIO (/Users/townus/.nvm/versions/node/v8.9.1/lib/node_modules/@compodoc/compodoc/dist/index-cli.js:5177:41)
    at parseNode (/Users/townus/.nvm/versions/node/v8.9.1/lib/node_modules/@compodoc/compodoc/dist/index-cli.js:4729:36)
    at /Users/townus/.nvm/versions/node/v8.9.1/lib/node_modules/@compodoc/compodoc/dist/index-cli.js:4856:13
    at visitNodes (/Users/townus/.nvm/versions/node/v8.9.1/lib/node_modules/@compodoc/compodoc/node_modules/typescript/lib/typescript.js:12643:30) } reason: TypeError: Cannot read property 'forEach' of undefined
    at /Users/townus/.nvm/versions/node/v8.9.1/lib/node_modules/@compodoc/compodoc/dist/index-cli.js:993:32
    at Array.forEach (<anonymous>)
    at RouterParserUtil.cleanRoutesDefinitionWithImport (/Users/townus/.nvm/versions/node/v8.9.1/lib/node_modules/@compodoc/compodoc/dist/index-cli.js:992:30)
    at Dependencies.visitEnumDeclarationForRoutes (/Users/townus/.nvm/versions/node/v8.9.1/lib/node_modules/@compodoc/compodoc/dist/index-cli.js:5153:67)
    at /Users/townus/.nvm/versions/node/v8.9.1/lib/node_modules/@compodoc/compodoc/dist/index-cli.js:5179:51
    at Array.reduce (<anonymous>)
    at Dependencies.getRouteIO (/Users/townus/.nvm/versions/node/v8.9.1/lib/node_modules/@compodoc/compodoc/dist/index-cli.js:5177:41)
    at parseNode (/Users/townus/.nvm/versions/node/v8.9.1/lib/node_modules/@compodoc/compodoc/dist/index-cli.js:4729:36)
    at /Users/townus/.nvm/versions/node/v8.9.1/lib/node_modules/@compodoc/compodoc/dist/index-cli.js:4856:13
    at visitNodes (/Users/townus/.nvm/versions/node/v8.9.1/lib/node_modules/@compodoc/compodoc/node_modules/typescript/lib/typescript.js:12643:30)
```

##### **Operating System, Node.js, npm, compodoc version(s)**

node.js v8.9.1
npm v5.5.1
compodoc v1.0.5

##### **Compodoc installed globally or locally ?**

globally

##### **Motivation for or Use Case**

On `app-routing.module.ts` file:

```typescript
...

export const APP_ROUTES: Routes = [
    {
        path: '',
        component: IntroPageComponent,
        resolve: {
            authorized: AccountAuthCheckResolver,
            oauth: AccountOauthResolver
        }
    },
    {
        path: '404',
        component: NotfoundPageComponent
    },
    {
        path: 'account',
        loadChildren: 'app/account/account-routing.module#AccountRoutingModule'
    },
    {
        path: 'commerce',
        loadChildren: 'app/commerce/commerce-routing.module#CommerceRoutingModule'
    },
    ...COMMERCE_DESIGN_POPUP_ROUTES // Got error in here
];
```
 I think I have an error when parsing array spread operator.

**Comment by vogloblinsky** [comment]
I need to handle this scenario during routes parsing.
Keep in touch

**Comment by priteshkapuriya** [comment]
@seokju-na 
I had the same issue while parsing spread operator 

//before with error.
export const pagesRoutes: Routes = [...defaultRoute, ...monitorRoutes, ...selectedRoutes, ...configureRoutes, ...systemRoutes];

//converted above as below as workaround for now and error was gone.
export const pagesRoutes: Routes = [];
pagesRoutes.concat(defaultRoute,monitorRoutes, selectedRoutes, configureRoutes, systemRoutes);

Could be useful to you as workaround until the issue is resolved.

**Comment by seokju-na** [comment]
@priteshkapuriya 
Thanks for useful information!
I should use like that until the issue is resolved.

p.s. And I realized I mistook spread operator name lol.

**Comment by trungk18** [comment]
Interestingly, I have the same problem with the app routing module but mine doesn't use spread operator.

**Comment by priteshkapuriya** [comment]
@trungk18 
Provide more details like code chunk where it fails like if not spread operator then what it is not able to parse?

**Comment by trungk18** [comment]
@priteshkapuriya Sure below is the error from the console.

```
[15:48:45] Searching package.json file
[15:48:45] package.json file found
[15:48:45] Searching README.md, CHANGELOG.md, CONTRIBUTING.md, LICENSE.md, TODO.md files
[15:48:45] Error during D:\Source Code\zyllem-core\Client\README read
[15:48:45] Continuing without README.md file
[15:48:45] Error during D:\Source Code\zyllem-core\Client\CHANGELOG read
[15:48:45] Continuing without CHANGELOG.md file
[15:48:45] Error during D:\Source Code\zyllem-core\Client\CONTRIBUTING read
[15:48:45] Continuing without CONTRIBUTING.md file
[15:48:45] Error during D:\Source Code\zyllem-core\Client\LICENSE read
[15:48:45] Continuing without LICENSE.md file
[15:48:45] Error during D:\Source Code\zyllem-core\Client\TODO read
[15:48:45] Continuing without TODO.md file
[15:48:45] Get dependencies data
[15:48:45] parsing        : D:/Source Code/zyllem-core/Client/modules/dispatcher/app-routing.module.ts
Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'forEach' of undefined
    at C:\Users\trung.vo\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:993:31
    at Array.forEach (native)
    at RouterParserUtil.cleanRoutesDefinitionWithImport (C:\Users\trung.vo\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:992:30)
    at Dependencies.visitEnumDeclarationForRoutes (C:\Users\trung.vo\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:5153:67)
    at C:\Users\trung.vo\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:5179:51
    at Array.reduce (native)
    at Dependencies.getRouteIO (C:\Users\trung.vo\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:5177:41)
    at parseNode (C:\Users\trung.vo\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:4729:36)
    at C:\Users\trung.vo\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:4856:13
    at visitNodes (C:\Users\trung.vo\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\typescript\lib\typescript.js:12643:30) } reason: TypeError: Cannot read property 'forEach' of undefined
    at C:\Users\trung.vo\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:993:31
    at Array.forEach (native)
    at RouterParserUtil.cleanRoutesDefinitionWithImport (C:\Users\trung.vo\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:992:30)
    at Dependencies.visitEnumDeclarationForRoutes (C:\Users\trung.vo\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:5153:67)
    at C:\Users\trung.vo\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:5179:51
    at Array.reduce (native)
    at Dependencies.getRouteIO (C:\Users\trung.vo\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:5177:41)
    at parseNode (C:\Users\trung.vo\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:4729:36)
    at C:\Users\trung.vo\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:4856:13
    at visitNodes (C:\Users\trung.vo\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\typescript\lib\typescript.js:12643:30
```

And this is my `app-routing.module.ts`

```typescript
import { NgModule } from '@angular/core'
import { RouterModule, Routes } from '@angular/router'
import * as component from './'
import * as APP_SETTING from './shared/app.setting'
import * as resolve from './shared/resolve'

const routes: Routes = [
    generateRouteWithChildren(
        APP_SETTING.STATE.QUEUE,
        APP_SETTING.STATE.QUEUE_BUNDLE,
        APP_SETTING.STATE.QUEUE_POINTS,
        APP_SETTING.STATE.QUEUE_TASKS,
        APP_SETTING.STATE.QUEUE_TASK),    
    generateRoute(APP_SETTING.STATE.QUEUE, component.QueueRedirectComponent),
    generateRouteWithChildren(
        APP_SETTING.STATE.DRIVER,
        APP_SETTING.STATE.DRIVER_BUNDLES,
        APP_SETTING.STATE.DRIVER_POINTS,
        APP_SETTING.STATE.DRIVER_TASKS,
        APP_SETTING.STATE.DRIVER_TASK),
    generateRoute(APP_SETTING.STATE.DRIVER, component.DriverRedirectComponent),
    {
        path: '',
        pathMatch: 'full',
        redirectTo: APP_SETTING.STATE.DRIVER
    }
];

@NgModule({
    imports: [RouterModule.forRoot(routes, {
        useHash: true
        //,enableTracing: true // <-- debugging purposes only        
    })],
    exports: [RouterModule]
})

export class AppRoutingModule { }

function generateRouteWithChildren(routePath: string, bundleState, pointsState, tasksState, taskState) {    
    return {
        path: `${routePath}/:${APP_SETTING.API_PARAMS.TYPE}`,
        component: component.BundleListComponent,
        resolve: {
            response: resolve.BundleListResolve
        },
        data: {
            state: bundleState
        },
        children: [
            {
                path: `:${APP_SETTING.API_PARAMS.BUNDLE_ID}`, component: component.PointListComponent,
                resolve: {
                    response: resolve.PointListResolve
                },
                data: {
                    state: pointsState
                },
                children: [
                    {
                        path: `:${APP_SETTING.API_PARAMS.POINT_ID}`, component: component.TaskListComponent,
                        resolve: {
                            response: resolve.TaskListResolve
                        },
                        data: {
                            state: tasksState
                        },
                        children: [
                            {
                                path: `:${APP_SETTING.API_PARAMS.TASK_ID}`, component: component.TaskDetailComponent,
                                resolve: {
                                    response: resolve.TaskDetailResolve
                                },
                                data: {
                                    state: taskState
                                }
                            },
                            { path: '', component: component.EmptyComponent }
                        ]
                    },
                    { path: '', component: component.EmptyComponent }
                ]
            },
            { path: '', component: component.EmptyComponent }
        ]

    }
}

function generateRoute(routePath, routeComponent) {
    return {
        path: routePath,
        component: routeComponent,
        resolve: {
            state: resolve.StateResolve
        },
        data: {
            state: routePath
        }
    }
}
```
