### ISSUE TITLE
[BUG] Can't import objects in angular routes and generate the docs

### ISSUE THREAD

**Issue by GuilleEneas** [compodoc/compodoc#405]
##### **Overview of the issue**
[BUG] running `npm run docs:compodoc:serve:watch` (`compodoc -p tsconfig.json -s -w`) I get the next output. The file which fails is my app.routes.ts.
```ts
import { Routes } from '@angular/router';

import { HomeRoutes } from '@Client/apps/home/home.routes';
import { DocumentRoutes } from '@Client/apps/organization/documents/documents.routes';
import { VideoRoutes } from '@Client/apps/entertainment/videos/video.routes';
import { AboutComponent } from '@Client/about';
import { KirbyInteractionComponent } from './apps/organization/hardware/kirby-interaction/kirby-interaction.component';

export const ROUTES: Routes = [
  HomeRoutes,
  ...DocumentRoutes,
  VideoRoutes,
  { path: 'about', component: AboutComponent},
  { path: 'hardware', component: KirbyInteractionComponent },
  { path: '**', redirectTo: '/home' }
];

```
but if I comment  the 3 first lines of the routes array it works. I tried and the docs are generated if I make this changes

```ts
...
export const ROUTES: Routes = [
  // HomeRoutes,
  // ...DocumentRoutes,
  // VideoRoutes,
  { path: 'about', component: AboutComponent},
  { path: 'hardware', component: KirbyInteractionComponent },
  { path: '**', redirectTo: '/home' }
];
...
```
```
Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'forEach' of undefined
    at /Users/guille/nepos/x2/angulario/node_modules/@compodoc/compodoc/dist/index-cli.js:993:31
    at Array.forEach (native)
    at RouterParserUtil.cleanRoutesDefinitionWithImport (/Users/guille/nepos/x2/angulario/node_modules/@compodoc/compodoc/dist/index-cli.js:992:30)
    at Dependencies.visitEnumDeclarationForRoutes (/Users/guille/nepos/x2/angulario/node_modules/@compodoc/compodoc/dist/index-cli.js:5153:67)
    at /Users/guille/nepos/x2/angulario/node_modules/@compodoc/compodoc/dist/index-cli.js:5179:51
    at Array.reduce (native)
    at Dependencies.getRouteIO (/Users/guille/nepos/x2/angulario/node_modules/@compodoc/compodoc/dist/index-cli.js:5177:41)
    at parseNode (/Users/guille/nepos/x2/angulario/node_modules/@compodoc/compodoc/dist/index-cli.js:4729:36)
    at /Users/guille/nepos/x2/angulario/node_modules/@compodoc/compodoc/dist/index-cli.js:4856:13
    at visitNodes (/Users/guille/nepos/x2/angulario/node_modules/@compodoc/compodoc/node_modules/typescript/lib/typescript.js:12643:30) } reason: TypeError: Cannot read property 'forEach' of undefined
    at /Users/guille/nepos/x2/angulario/node_modules/@compodoc/compodoc/dist/index-cli.js:993:31
    at Array.forEach (native)
    at RouterParserUtil.cleanRoutesDefinitionWithImport (/Users/guille/nepos/x2/angulario/node_modules/@compodoc/compodoc/dist/index-cli.js:992:30)
    at Dependencies.visitEnumDeclarationForRoutes (/Users/guille/nepos/x2/angulario/node_modules/@compodoc/compodoc/dist/index-cli.js:5153:67)
    at /Users/guille/nepos/x2/angulario/node_modules/@compodoc/compodoc/dist/index-cli.js:5179:51
    at Array.reduce (native)
    at Dependencies.getRouteIO (/Users/guille/nepos/x2/angulario/node_modules/@compodoc/compodoc/dist/index-cli.js:5177:41)
    at parseNode (/Users/guille/nepos/x2/angulario/node_modules/@compodoc/compodoc/dist/index-cli.js:4729:36)
    at /Users/guille/nepos/x2/angulario/node_modules/@compodoc/compodoc/dist/index-cli.js:4856:13
    at visitNodes (/Users/guille/nepos/x2/angulario/node_modules/@compodoc/compodoc/node_modules/typescript/lib/typescript.js:12643:30)
```

##### **Operating System, Node.js, npm, compodoc version(s)**

- OS: OS X Yosemite 10.10.5
- node: v7.10.0
- npm:  v3.10.10
- compoodoc: v1.0.5 (locally)
running ` compodoc -p tsconfig.json -s -w` I get this output

##### **Angular configuration, a `package.json` file in the root folder**
```json
{
  "name": "Enkel",
  "version": "18.0.0",
  "description": "",
  "private": true,
  "homepage": "https://nepos.io",
  "license": "MIT",
  "scripts": {
    "ava": "./node_modules/ava/cli.js",
    "ava:watch": "./node_modules/ava/cli.js -w",
    "build:aot:prod": "npm run clean:dist && npm run clean:aot && cross-env BUILD_AOT=1 npm run webpack -- --config config/webpack.prod.js  --progress --profile --bail && cd dist && npm install",
    "build:aot": "npm run build:aot:prod",
    "build:dev": "npm run clean:dist && npm run webpack -- --config config/webpack.dev.js --progress --profile",
    "build:docker": "npm run build:prod && docker build -t angular2-webpack-start:latest .",
    "build:prod:poly": "npm run build:aot:prod && cd dist && npm install && cd ..",
    "build:prod": "npm run clean:dist && npm run webpack -- --config config/webpack.prod.js  --progress --profile --bail",
    "build": "npm run build:dev",
    "ci:aot": "npm run lint && npm run test && npm run build:aot && npm run e2e",
    "ci:jit": "npm run lint && npm run test && npm run build:prod && npm run e2e",
    "ci:nobuild": "npm run lint && npm test && npm run e2e",
    "ci:testall": "npm run lint && npm run test && npm run build:prod && npm run e2e && npm run build:aot && npm run e2e",
    "ci:travis": "npm run lint && npm run test && npm run build:aot && npm run e2e:travis",
    "ci": "npm run ci:testall",
    "clean:dll": "npm run rimraf -- dll",
    "clean:aot": "npm run rimraf -- compiled",
    "clean:dist": "npm run rimraf -- dist",
    "clean:install": "npm set progress=false && npm install",
    "clean": "npm cache clean --force && npm run rimraf -- node_modules doc coverage dist compiled dll",
    "docker": "docker",
    "docs": "npm run typedoc -- --options typedoc.json --exclude '**/*.spec.ts' ./src/",
    "docs:compodoc": "compodoc -p tsconfig.json",
    "docs:compodoc:serve": "compodoc -p tsconfig.json -s",
    "docs:compodoc:serve:watch": "compodoc -p tsconfig.json -s -w",
    "e2e:live": "npm-run-all -p -r server:prod:ci protractor:live",
    "e2e:travis": "npm-run-all -p -r server:prod:ci protractor:delay",
    "e2e": "npm-run-all -p -r server:prod:ci protractor",
    "karma": "./node_modules/karma/bin/karma start ./karma.conf.js --single-run",
    "lint": "npm run tslint \"src/**/*.ts\"",
    "node": "node",
    "postinstall": "npm run webdriver:update",
    "postversion": "git push && git push --tags",
    "preclean:install": "npm run clean",
    "preversion": "npm test",
    "protractor": "protractor",
    "protractor:delay": "sleep 3 && npm run protractor",
    "protractor:live": "protractor --elementExplorer",
    "rimraf": "rimraf",
    "server:dev:hmr": "npm run server:dev -- --hotOnly",
    "server:dev": "npm run webpack-dev-server -- --config config/webpack.dev.js --open --progress --profile --watch --content-base src/",
    "server:prod": "http-server dist/client -p 3000 -c-1 --cors",
    "server": "npm run server:dev",
    "start:hmr": "npm run server:dev:hmr",
    "start": "npm run server:dev",
    "test": "npm run karma && npm run ava",
    "tslint": "tslint",
    "typedoc": "typedoc",
    "version": "npm run build",
    "watch:dev:hmr": "npm run watch:dev -- --hot",
    "watch:dev": "npm run build:dev -- --watch",
    "watch:prod": "npm run build:prod -- --watch",
    "watch:test": "npm run test -- --auto-watch --no-single-run",
    "watch": "npm run watch:dev",
    "webdriver-manager": "webdriver-manager",
    "webdriver:start": "npm run webdriver-manager start",
    "webdriver:update": "webdriver-manager update",
    "webpack-dev-server": "node --max_old_space_size=4096 node_modules/webpack-dev-server/bin/webpack-dev-server.js",
    "webpack": "node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js"
  },
  "dependencies": {
    "@angular/animations": "~4.4.4",
    "@angular/common": "~4.4.4",
    "@angular/compiler": "~4.4.4",
    "@angular/core": "~4.4.4",
    "@angular/forms": "~4.4.4",
    "@angular/http": "~4.4.4",
    "@angular/platform-browser": "~4.4.4",
    "@angular/platform-browser-dynamic": "~4.4.4",
    "@angular/platform-server": "~4.4.4",
    "@angular/router": "~4.4.4",
    "@angularclass/hmr": "~2.1.3",
    "@angularclass/hmr-loader": "^3.0.4",
    "anchorme": "^1.1.2",
    "async": "^2.5.0",
    "cookie-parser": "^1.4.3",
    "core-js": "^2.4.1",
    "deep-freeze": "0.0.1",
    "howler": "^2.0.5",
    "http-server": "^0.10.0",
    "ie-shim": "^0.1.0",
    "kirby": "git+ssh://git@github.com/nepos/kirby.git#v0.6.1",
    "lodash": "^4.17.4",
    "logger": "git+https://github.com/nepos/logger.git",
    "moment": "^2.19.1",
    "passport": "^0.4.0",
    "passport-local": "^1.0.0",
    "redux": "^3.7.2",
    "redux-persist": "^4.10.2",
    "redux-thunk": "^2.2.0",
    "redux-watch": "^1.1.1",
    "reflect-metadata": "^0.1.10",
    "rxjs": "5.4.3",
    "ws": "^3.2.0",
    "zone.js": "~0.8.18"
  },
  "devDependencies": {
    "@angular/cli": "^1.4.9",
    "@angular/compiler-cli": "~4.4.4",
    "@compodoc/compodoc": "1.0.5",
    "@types/hammerjs": "^2.0.34",
    "@types/jasmine": "2.5.45",
    "@types/lodash": "^4.14.80",
    "@types/node": "^7.0.39",
    "@types/source-map": "^0.5.0",
    "@types/uglify-js": "^2.6.28",
    "@types/webpack": "^2.2.16",
    "add-asset-html-webpack-plugin": "^1.0.2",
    "angular2-template-loader": "^0.6.2",
    "assets-webpack-plugin": "^3.5.1",
    "ava": "^0.23.0",
    "awesome-typescript-loader": "~3.3.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-register": "^6.26.0",
    "codelyzer": "~3.1.0",
    "copy-webpack-plugin": "^4.2.0",
    "cross-env": "^5.0.0",
    "css-loader": "^0.28.0",
    "debug": "^3.1.0",
    "exports-loader": "^0.6.4",
    "expose-loader": "^0.7.3",
    "extract-text-webpack-plugin": "~3.0.0",
    "fetch-mock": "^5.13.1",
    "file-loader": "^0.11.1",
    "find-root": "^1.0.0",
    "generate-json-webpack-plugin": "^0.2.2",
    "gh-pages": "^1.0.0",
    "html-webpack-plugin": "^2.28.0",
    "imports-loader": "^0.7.1",
    "inline-manifest-webpack-plugin": "^3.0.1",
    "istanbul-instrumenter-loader": "2.0.0",
    "jasmine-core": "^2.5.2",
    "karma": "^1.6.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-coverage": "^1.1.1",
    "karma-jasmine": "^1.1.0",
    "karma-mocha-reporter": "^2.2.3",
    "karma-remap-coverage": "^0.1.4",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^2.0.4",
    "ng-router-loader": "^2.1.0",
    "ngc-webpack": "^3.2.0",
    "node-sass": "^4.5.3",
    "npm-run-all": "^4.0.2",
    "optimize-js-plugin": "0.0.4",
    "parse5": "^3.0.2",
    "preload-webpack-plugin": "^1.2.2",
    "protractor": "^5.1.1",
    "raw-loader": "^0.5.1",
    "redux-devtools-extension": "^2.13.2",
    "rimraf": "~2.6.1",
    "sass-loader": "^6.0.6",
    "script-ext-html-webpack-plugin": "^1.8.5",
    "sinon": "^4.0.2",
    "source-map-loader": "^0.2.1",
    "string-replace-loader": "~1.3.0",
    "style-loader": "^0.18.1",
    "to-string-loader": "^1.1.5",
    "ts-node": "^3.3.0",
    "tslib": "^1.7.1",
    "tslint": "^5.8.0",
    "tslint-loader": "^3.5.3",
    "typedoc": "^0.7.1",
    "typescript": "^2.5.3",
    "uglifyjs-webpack-plugin": "^1.0.1",
    "url-loader": "^0.5.8",
    "webpack": "^3.5.5",
    "webpack-dev-middleware": "^1.10.1",
    "webpack-dev-server": "^2.9.4",
    "webpack-dll-bundles-plugin": "^1.0.0-beta.5",
    "webpack-hot-middleware": "^2.20.0",
    "webpack-merge": "~4.1.0"
  },
  "engines": {
    "node": ">= 4.2.1",
    "npm": ">= 3"
  },
  "ava": {
    "files": [
      "src/client/**/*.test.js",
      "src/server/**/*.test.js"
    ],
    "source": [
      "src/client/**/*.test.js",
      "src/server/**/*.test.js",
      "!node_modules/**"
    ],
    "require": [
      "babel-register",
      "babel-polyfill",
      "./src/client/test/test-globals.js"
    ],
    "babel": "inherit"
  }
}

```

##### **Motivation for or Use Case**

With the previous version this didn't happen

I will revert my project to previous version till this is solved.

Thank you very much. This is an awesome doc tool! 😄

**Comment by vogloblinsky** [comment]
Duplicate https://github.com/compodoc/compodoc/issues/404
Yes, spread operators and direct object import are not supported right now.
I will work on that during the next 2 weeks.
