### ISSUE TITLE
  <rejected> TypeError: Cannot read property 'text' of undefined     at Dependencies.getSymboleName 

### ISSUE THREAD

**Issue by aliaburas80** [compodoc/compodoc#427]
Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'text' of undefined
    at Dependencies.getSymboleName 
    at visitNode (\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:4520:42)
    at Array.forEach (native)
    at parseNode \AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:4631:26)
    at\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:4856:13
    at visitNodes (\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\typescript\lib\typescript.js:12643:30)
    at Object.forEachChild (AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\typescript\lib\typescript.js:12821:24)
    at Dependencies.getSourceFileDecorators (AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:4510:12)
    at \AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:4393:27
    at Array.map (native) } reason: TypeError: Cannot read property 'text' of undefined
    at Dependencies.getSymboleName (\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:4968:25)
    at visitNode (\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:4520:42)
    at Array.forEach (native)
    at parseNode (\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:4631:26)
    at AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:4856:13
    at visitNodes (\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\typescript\lib\typescript.js:12643:30)
    at Object.forEachChild (\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\typescript\lib\typescript.js:12821:24)
    at Dependencies.getSourceFileDecorators (\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:4510:12)
    at \AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:4393:27
    at Array.map (native)

**Comment by aliaburas80** [comment]
Problem solved its was my bad

**Comment by jhonatanTeixeira** [comment]
what bad? i have the same problem and don't know how to solve

**Comment by vogloblinsky** [comment]
@jhonatanTeixeira 
Version 1.0.8 contains --disableRoutesGraph if you want to bypass this error (created during routes graph)
