### ISSUE TITLE
[BUG] Parsing fails

### ISSUE THREAD

**Issue by aleksandar78** [compodoc/compodoc#429]
#### Document generation fails with following error: 
...
_[13:12:35] Process page   : functions
[13:12:35] Process page   : variables_
_Unhandled Rejection at: Promise {
  <rejected> RangeError: Maximum call stack size exceeded
    at lunr.TokenStore.add (/home/developer/Projects/Production/eris-platform/node_modules/lunr/lunr.js:1884:28)
    at lunr.TokenStore.add (/home/developer/Projects/Production/eris-platform/node_modules/lunr/lunr.js:1891:17)
    at lunr.TokenStore.add (/home/developer/Projects/Production/eris-platform/node_modules/lunr/lunr.js:1891:17)
    at lunr.TokenStore.add (/home/developer/Projects/Production/eris-platform/node_modules/lunr/lunr.js:1891:17)
    at lunr.TokenStore.add (/home/developer/Projects/Production/eris-platform/node_modules/lunr/lunr.js:1891:17)
    at lunr.TokenStore.add (/home/developer/Projects/Production/eris-platform/node_modules/lunr/lunr.js:1891:17)
    at lunr.TokenStore.add (/home/developer/Projects/Production/eris-platform/node_modules/lunr/lunr.js:1891:17)
    at lunr.TokenStore.add (/home/developer/Projects/Production/eris-platform/node_modules/lunr/lunr.js:1891:17)
    at lunr.TokenStore.add (/home/developer/Projects/Production/eris-platform/node_modules/lunr/lunr.js:1891:17)
    at lunr.TokenStore.add (/home/developer/Projects/Production/eris-platform/node_modules/lunr/lunr.js:1891:17) } reason: RangeError: Maximum call stack size exceeded
    at lunr.TokenStore.add (/home/developer/Projects/Production/eris-platform/node_modules/lunr/lunr.js:1884:28)
    at lunr.TokenStore.add (/home/developer/Projects/Production/eris-platform/node_modules/lunr/lunr.js:1891:17)
    at lunr.TokenStore.add (/home/developer/Projects/Production/eris-platform/node_modules/lunr/lunr.js:1891:17)
    at lunr.TokenStore.add (/home/developer/Projects/Production/eris-platform/node_modules/lunr/lunr.js:1891:17)
    at lunr.TokenStore.add (/home/developer/Projects/Production/eris-platform/node_modules/lunr/lunr.js:1891:17)
    at lunr.TokenStore.add (/home/developer/Projects/Production/eris-platform/node_modules/lunr/lunr.js:1891:17)
    at lunr.TokenStore.add (/home/developer/Projects/Production/eris-platform/node_modules/lunr/lunr.js:1891:17)
    at lunr.TokenStore.add (/home/developer/Projects/Production/eris-platform/node_modules/lunr/lunr.js:1891:17)
    at lunr.TokenStore.add (/home/developer/Projects/Production/eris-platform/node_modules/lunr/lunr.js:1891:17)
    at lunr.TokenStore.add (/home/developer/Projects/Production/eris-platform/node_modules/lunr/lunr.js:1891:17)
[12:22:06] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command._

##### **Operating System, Node.js, npm, compodoc version(s)**
OS: Linux 4.14
Node v9.2.1
Npm v5.6.0
compodoc 1.0.5

##### **Angular configuration, a `package.json` file in the root folder**
Angular project contains multiple application and one lib folder with shared libraries. 
Command used by CI server to generate separate documention for shared libraries:
`compodoc lib -p scripts/tsconfig.docs.json -d lib-docs --disableCoverage --disablePrivateOrInternalSupport`
 

**Project dependencies**
{
  "dependencies": {
    "angular/animations": "^5.2.0",
    "angular/common": "^5.2.0",
    "angular/compiler": "^5.2.0",
    "angular/core": "^5.2.0",
    "angular/forms": "^5.2.0",
    "angular/http": "^5.2.0",
    "angular/platform-browser": "^5.2.0",
    "angular/platform-browser-dynamic": "^5.2.0",
    "angular/router": "^5.2.0",
    "exprivia/e4cure-ng-translate": "^0.2.0",
    "exprivia/ecore-platform": "^3.0.0-alpha.115",
    "ng-bootstrap/ng-bootstrap": "^1.0.0-beta.9",
    "ngrx/effects": "^4.1.1",
    "ngrx/router-store": "^4.1.1",
    "ngrx/store": "^4.1.1",
    "ngrx/store-devtools": "^4.1.1",
    "angular-in-memory-web-api": "^0.5.2",
    "bootstrap": "4.0.0-beta.2",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.3",
    "font-awesome": "^4.7.0",
    "global": "^4.3.2",
    "intl": "^1.2.5",
    "jasmine-marbles": "^0.2.0",
    "ng2-pdf-viewer": "^3.0.8",
    "ng2-toastr": "^4.1.2",
    "ngx-chips": "^1.6.2",
    "rxjs": "^5.5.6",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.20"
  },
  "devDependencies": {
    "angular/cli": "1.6.3",
    "angular/compiler-cli": "^5.2.0",
    "angular/language-service": "^5.2.0",
    "compodoc/compodoc": "^1.0.5",
    "types/jasmine": "~2.8.3",
    "types/jasminewd2": "~2.0.3",
    "types/karma": "^1.7.3",
    "types/node": "~9.3.0",
    "types/webpack": "^3.8.2",
    "types/webpack-env": "^1.13.3",
    "angular2-template-loader": "^0.6.2",
    "awesome-typescript-loader": "^3.4.1",
    "codecov": "^3.0.0",
    "codelyzer": "~4.0.2",
    "concurrently": "^3.5.1",
    "css-loader": "^0.28.8",
    "gh-pages": "^1.1.0",
    "gulp": "^3.9.1",
    "gulp-inline-ng2-template": "^4.1.0",
    "istanbul-instrumenter-loader": "^3.0.0",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "json-loader": "^0.5.7",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.3.3",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-mocha-reporter": "^2.2.5",
    "karma-phantomjs-launcher": "^1.0.4",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^2.0.9",
    "node-sass": "^4.7.2",
    "protractor": "~5.2.2",
    "raw-loader": "^0.5.1",
    "rimraf": "^2.6.2",
    "sass-loader": "^6.0.6",
    "source-map-explorer": "^1.5.0",
    "to-string-loader": "^1.1.5",
    "ts-node": "~4.1.0",
    "tslint": "^5.9.1",
    "typescript": "~2.6.2",
    "webpack": "^3.10.0",
    "webpack-angular-externals": "^1.0.2",
    "webpack-rxjs-externals": "^1.1.0"
  }
}

##### **Compodoc installed globally or locally ?**
Locally.

##### **Motivation for or Use Case**

Unable to generate documentation and complite build automation process.

**Comment by vogloblinsky** [comment]
Fixed with https://github.com/compodoc/compodoc/commit/f495cd8ab1d2b2a9063db833d2fddf318c0a8d67
Will come very soon with 1.0.6
