### ISSUE TITLE
[BUG]: Error if HTTP_INTERCEPTORS registered via providers

### ISSUE THREAD

**Issue by tklingert** [compodoc/compodoc#456]
##### **Overview of the issue**
Compodoc fails within an error if a HTTP_INTERCEPTORS class is registered to angular module providers.

##### **Operating System, Node.js, npm, compodoc version(s)**
Compodoc: 1.0.5
Node.js version : v8.9.1
Operating system : Windows 10 (x64)
npm: 5.5.1

##### **Angular configuration, a `package.json` file in the root folder**
```
+-- @angular/animations@5.1.0
+-- @angular/cli@1.5.4
+-- @angular/common@5.1.0
+-- @angular/compiler@5.1.0
+-- @angular/compiler-cli@5.1.0
+-- @angular/core@5.1.0
+-- @angular/forms@5.1.0
+-- @angular/http@5.1.0
+-- @angular/language-service@5.1.0
+-- @angular/platform-browser@5.1.0
+-- @angular/platform-browser-dynamic@5.1.0
+-- @angular/router@5.1.0
+-- @compodoc/compodoc@1.0.5
```

##### **Compodoc installed globally or locally ?**
locally

##### **Reproduce the error**
1. Add an http interceptor to any angular module:

```
 import { HTTP_INTERCEPTORS } from '@angular/common/http';
 ...
 
 @NgModule({
 ...
 
 providers: [
    {
      provide: HTTP_INTERCEPTORS,
      useFactory: (languageService: GlobalLanguageService) => new HttpConfigurationInterceptor(languageService),
      deps: [GlobalLanguageService]
    },
...
})
```

2. run compodoc
  ->  Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'split' of undefined
    at SymbolHelper.parseDeepIndentifier (D:\dev\src\GET\cdm_frontend_WebUI\node_modules\@compodoc\compodoc\dist\index-cli.js:2986:29)
    at D:\dev\src\GET\cdm_frontend_WebUI\node_modules\@compodoc\compodoc\dist\index-cli.js:3372:70
    at Array.map (<anonymous>)
    at ModuleHelper.getModuleProviders (D:\dev\src\GET\cdm_frontend_WebUI\node_modules\@compodoc\compodoc\dist\index-cli.js:3372:14)
    at ModuleDepFactory.create (D:\dev\src\GET\cdm_frontend_WebUI\node_modules\@compodoc\compodoc\dist\index-cli.js:3285:42)
    at visitNode (D:\dev\src\GET\cdm_frontend_WebUI\node_modules\@compodoc\compodoc\dist\index-cli.js:4525:34)
    at Array.forEach (<anonymous>)
    at parseNode (D:\dev\src\GET\cdm_frontend_WebUI\node_modules\@compodoc\compodoc\dist\index-cli.js:4631:26)
    at D:\dev\src\GET\cdm_frontend_WebUI\node_modules\@compodoc\compodoc\dist\index-cli.js:4856:13
    at visitNodes (D:\dev\src\GET\cdm_frontend_WebUI\node_modules\@compodoc\compodoc\node_modules\typescript\lib\typescript.js:12643:30) } reason: TypeError: Cannot read property 'split' of undefined
    at SymbolHelper.parseDeepIndentifier (D:\dev\src\GET\cdm_frontend_WebUI\node_modules\@compodoc\compodoc\dist\index-cli.js:2986:29)
    at D:\dev\src\GET\cdm_frontend_WebUI\node_modules\@compodoc\compodoc\dist\index-cli.js:3372:70
    at Array.map (<anonymous>)
    at ModuleHelper.getModuleProviders (D:\dev\src\GET\cdm_frontend_WebUI\node_modules\@compodoc\compodoc\dist\index-cli.js:3372:14)
    at ModuleDepFactory.create (D:\dev\src\GET\cdm_frontend_WebUI\node_modules\@compodoc\compodoc\dist\index-cli.js:3285:42)
    at visitNode (D:\dev\src\GET\cdm_frontend_WebUI\node_modules\@compodoc\compodoc\dist\index-cli.js:4525:34)
    at Array.forEach (<anonymous>)
    at parseNode (D:\dev\src\GET\cdm_frontend_WebUI\node_modules\@compodoc\compodoc\dist\index-cli.js:4631:26)
    at D:\dev\src\GET\cdm_frontend_WebUI\node_modules\@compodoc\compodoc\dist\index-cli.js:4856:13
    at visitNodes (D:\dev\src\GET\cdm_frontend_WebUI\node_modules\@compodoc\compodoc\node_modules\typescript\lib\typescript.js:12643:30)
  Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)

**Comment by kharlamm** [comment]
+1
