### ISSUE TITLE
[BUG] Error. There was a problem during parsing or generation of the documentation. Unhandled Rejection at: Promise 

### ISSUE THREAD

**Issue by Yerkon** [compodoc/compodoc#470]
##### **Overview of the issue**
`npm run compodoc`
```
[16:22:23] parsing        : C:/Users/Erkebulan/Source/Repos/TMK.WEB/src/app/departments/department-1/department-1-routing.module.ts
[16:22:23] Analysing routes definitions and clean them if necessary
Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'text' of undefined
    at NodeObject.getText (C:\Users\Erkebulan\Source\Repos\TMK.WEB\node_modules\typescript\lib\typescript.js:94867:31)
    at ClassHelper.stringifyDefaultValue (C:\Users\Erkebulan\Source\Repos\TMK.WEB\node_modules\@compodoc\compodoc\dist\index-cli.js:3885:18)
    at Dependencies.visitVariableDeclaration (C:\Users\Erkebulan\Source\Repos\TMK.WEB\node_modules\@compodoc\compodoc\dist\index-cli.js:5499:42)
    at parseNode (C:\Users\Erkebulan\Source\Repos\TMK.WEB\node_modules\@compodoc\compodoc\dist\index-cli.js:5207:43)
    at C:\Users\Erkebulan\Source\Repos\TMK.WEB\node_modules\@compodoc\compodoc\dist\index-cli.js:5281:13
    at visitEachNode (C:\Users\Erkebulan\Source\Repos\TMK.WEB\node_modules\@compodoc\compodoc\node_modules\typescript\lib\typescript.js:15956:30)
    at Object.forEachChild (C:\Users\Erkebulan\Source\Repos\TMK.WEB\node_modules\@compodoc\compodoc\node_modules\typescript\lib\typescript.js:16136:24)
    at Dependencies.getSourceFileDecorators (C:\Users\Erkebulan\Source\Repos\TMK.WEB\node_modules\@compodoc\compodoc\dist\index-cli.js:4932:12)
    at C:\Users\Erkebulan\Source\Repos\TMK.WEB\node_modules\@compodoc\compodoc\dist\index-cli.js:4783:27
    at Array.map (<anonymous>) } reason: TypeError: Cannot read property 'text' of undefined
    at NodeObject.getText (C:\Users\Erkebulan\Source\Repos\TMK.WEB\node_modules\typescript\lib\typescript.js:94867:31)
    at ClassHelper.stringifyDefaultValue (C:\Users\Erkebulan\Source\Repos\TMK.WEB\node_modules\@compodoc\compodoc\dist\index-cli.js:3885:18)
    at Dependencies.visitVariableDeclaration (C:\Users\Erkebulan\Source\Repos\TMK.WEB\node_modules\@compodoc\compodoc\dist\index-cli.js:5499:42)
    at parseNode (C:\Users\Erkebulan\Source\Repos\TMK.WEB\node_modules\@compodoc\compodoc\dist\index-cli.js:5207:43)
    at C:\Users\Erkebulan\Source\Repos\TMK.WEB\node_modules\@compodoc\compodoc\dist\index-cli.js:5281:13
    at visitEachNode (C:\Users\Erkebulan\Source\Repos\TMK.WEB\node_modules\@compodoc\compodoc\node_modules\typescript\lib\typescript.js:15956:30)
    at Object.forEachChild (C:\Users\Erkebulan\Source\Repos\TMK.WEB\node_modules\@compodoc\compodoc\node_modules\typescript\lib\typescript.js:16136:24)
    at Dependencies.getSourceFileDecorators (C:\Users\Erkebulan\Source\Repos\TMK.WEB\node_modules\@compodoc\compodoc\dist\index-cli.js:4932:12)
    at C:\Users\Erkebulan\Source\Repos\TMK.WEB\node_modules\@compodoc\compodoc\dist\index-cli.js:4783:27
    at Array.map (<anonymous>)
```

## department-1-routing.module:
```
...
const routes: Routes = [
    {
        path: '',
        component: Department1PageComponent,
        data: {
            shouldReuseTag: 'department-1'
        }
    },
    {
        path: ':type',
        component: Department1PageComponent,
        data: {
            shouldReuseTag: 'department-1'
        }
    },
    ...departmentRoutes,
    facilityRoute
];

@NgModule({
    imports: [RouterModule.forChild(routes)],
    exports: [RouterModule],
    providers: []
})
export class Department1RoutingModule { }
```

##### **Operating System, Node.js, npm, compodoc version(s)**
Angular CLI: 1.7.0-rc.0
Node: 8.9.4
OS: win32 x64
Angular: 5.2.4
Compodoc: 1.0.7

##### **Compodoc installed globally or locally ?**
Both

**Comment by vogloblinsky** [comment]
@Yerkon 
Where is defined `facilityRoute` in your example ?
Inside the file or with an import ?

**Comment by Yerkon** [comment]
> Where is defined facilityRoute in your example ?
> Inside the file or with an import ?

Inside the file

**Comment by vogloblinsky** [comment]
I have implemented an option to disable routes graph if you want to have your documentation. Coming in 1.0.8 today.

**Comment by vogloblinsky** [comment]
This commit https://github.com/compodoc/compodoc/commit/2533deef63d1c2c05f4a1497a3d2fa9d3a14eade may be fix this issue, have a test with next release 1.1.0.
