### ISSUE TITLE
[BUG] Routing with lazy-loaded modules from external npm module

### ISSUE THREAD

**Issue by felpel** [compodoc/compodoc#488]
##### **Overview of the issue**

When we access the `Routing` section of our Angular app, the routing is not correctly shown. **Does it support lazy-loaded modules** in routing?

##### **Operating System, Node.js, npm, compodoc version(s)**

| OS | Node.JS | NPM | compodoc |
| ---| --------| ------| --------- |
| Windows 10 | 9.5.0 | 5.6.0 | **1.0.7** |

##### **Angular configuration, a `package.json` file in the root folder**

<details>
<summary>packages.json</summary>

```json
{
  "name": "autovu-portal-clientapp",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "pretest": "node ./src/testManager.js",
    "test": "ng test --sr -cc",
    "lint": "ng lint",
    "doc:build": "compodoc -p ./src/tsconfig.app.json -n \"PTMS Portal\"",
    "doc:serve": "compodoc -s",
    "doc": "compodoc -p ./src/tsconfig.app.json -s -n \"PTMS Portal\""
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.1.1",
    "@angular/common": "^5.1.1",
    "@angular/compiler": "^5.1.1",
    "@angular/core": "^5.1.1",
    "@angular/forms": "^5.1.1",
    "@angular/http": "^5.1.1",
    "@angular/platform-browser": "^5.1.1",
    "@angular/platform-browser-dynamic": "^5.1.1",
    "@angular/router": "^5.1.1",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "jquery": "^3.2.1",
    "less": "^2.7.2",
    "lodash": "^4.17.4",
    "ng2-tooltip": "0.0.7",
    "ngx-clipboard": "9.1.1",
    "ngx-infinite-scroll": "^0.6.1",
    "oidc-client": "^1.3.0",
    "rxjs": "^5.5.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.4.1",
    "@angular/compiler-cli": "^5.1.1",
    "@types/jasmine": "^2.8.3",
    "@types/lodash": "^4.14.98",
    "@types/node": "~6.0.60",
    "babel-polyfill": "^6.9.1",
    "chai": "^4.1.1",
    "codelyzer": "^4.0.2",
    "compodoc": "0.0.41",
    "glob": "^7.1.2",
    "jasmine-core": "^2.5.2",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^1.7.1",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.3.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-phantomjs-launcher": "^1.0.4",
    "karma-trx-reporter": "^0.2.9",
    "ts-node": "^2.0.0",
    "tslint": "^5.8.0",
    "typescript": "~2.4.2"
  }
}
```
</details>

<details><summary>.angular-cli.json</summary>

```json
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "autovu-portal-clientapp"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "wwwroot",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "../node_modules/bootstrap/dist/css/bootstrap.css",
        "webgrid/css/sc-icons.min.css",
        "webgrid/css/themes/theme-autovu-dark.min.css",
        "assets/styles.less"
      ],
      "scripts": [
		    "../node_modules/jquery/dist/jquery.min.js",
        "../node_modules/bootstrap/dist/js/bootstrap.js"
	  ],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json"
    },
    {
      "project": "src/tsconfig.spec.json"
    },
    {
      "project": "e2e/tsconfig.e2e.json"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "component": {}
  }
}
```
</details>

##### **Compodoc installed globally or locally ?**

**Locally** as a dev dependency in packages.json

##### **Motivation for or Use Case**

I think the analysis should automatically detect when the route children are lazy loaded.

##### **Reproduce the error**

Provide a route that loads the children from another module. In my application, I have:
```ts
const routes: Routes = [
  { path: '', canActivateChild: [AuthGuard], loadChildren: './portal/portal.module#PortalModule' },
  // other routes ommitted
];
```
The `PortalModule` imports `PortalRoutingModule` which has another set of routes:
```ts
const routes: Routes = [
  { 
    path: '', component: PortalComponent, children: [
      { path: 'principals', canActivateChild: [AdminGuard], loadChildren: '../principals/principals.module#PrincipalsModule' },
      { path: 'dashboard', loadChildren: '../dashboard/dashboard.module#DashboardModule' },
      { path: '', pathMatch: 'full', redirectTo: 'dashboard' }
    ]
  }
];
```
As you can see, the initial routes also load other children modules. Right now, I see this in my generated documentation:
![image](https://user-images.githubusercontent.com/5000004/36552843-dfbd9814-17c8-11e8-9204-df6549f6cc4a.png)

##### **Related issues**

N/A

##### **Suggest a Fix**

Check the **Reproduce error** section 😄

**Comment by vogloblinsky** [comment]
Installe compodoc inside this scope @compodoc/compodoc and not directly compodoc

**Comment by felpel** [comment]
@vogloblinsky that was my mistake... I've updated to 1.0.7, but I no longer have any routes in my generated documentation. 😞 
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/5000004/36623895-51e887dc-18d7-11e8-8b93-0d061c3cdd87.png)
</details>

**Comment by istiti** [comment]
Same here

**Comment by hellraisercenobit** [comment]
Same here too

**Comment by martijnmelchers** [comment]
Is there any update when this will be fixed? Would be awesome! Thanks 💃

**Comment by vogloblinsky** [comment]
@martijnmelchers Is it possible to have a minimal project where it fails ? (easy to debug for me)
The demo project works fine : 
- https://compodoc.github.io/compodoc-demo-todomvc-angular/routes.html
- https://github.com/compodoc/compodoc-demo-todomvc-angular

**Comment by vogloblinsky** [comment]
@hellraisercenobit Ok i reopen and rename the issue.

**Comment by felpel** [comment]
I'm still getting an error and I don't get it if I use the `disableRoutesGraph` switch... :suspect: 

<details>
<summary>npm log</summary>

> autovu-portal-clientapp@0.0.0 doc C:\Dev\AutoVu.Saas.Ptms.Portal\src\AutoVu.Saas.Ptms.Portal.ClientApp
> compodoc -p ./tsconfig.json -s
...
[21:29:46] parsing        : C:/Dev/AutoVu.Saas.Ptms.Portal/src/AutoVu.Saas.Ptms.Portal.ClientApp/src/app/portal/portal-routing.module.ts
[21:29:46] Analysing routes definitions and clean them if necessary
Unhandled Rejection at: Promise {
  <rejected> Error: Could not find the node's symbol.
    at InvalidOperationError.BaseError [as constructor] (C:\Dev\AutoVu.Saas.Ptms.Portal\src\AutoVu.Saas.Ptms.Portal.ClientApp\node_modules\ts-simple-ast\dist\errors\BaseError.js:16:28)
    at new InvalidOperationError (C:\Dev\AutoVu.Saas.Ptms.Portal\src\AutoVu.Saas.Ptms.Portal.ClientApp\node_modules\ts-simple-ast\dist\errors\InvalidOperationError.js:17:28)
    at Object.throwIfNullOrUndefined (C:\Dev\AutoVu.Saas.Ptms.Portal\src\AutoVu.Saas.Ptms.Portal.ClientApp\node_modules\ts-simple-ast\dist\errors\helpers.js:96:15)
    at Identifier.Node.getSymbolOrThrow (C:\Dev\AutoVu.Saas.Ptms.Portal\src\AutoVu.Saas.Ptms.Portal.ClientApp\node_modules\ts-simple-ast\dist\compiler\common\Node.js:167:23)
    at RouterParserUtil.cleanFileDynamics (C:\Dev\AutoVu.Saas.Ptms.Portal\src\AutoVu.Saas.Ptms.Portal.ClientApp\node_modules\@compodoc\compodoc\dist\index-cli.js:1290:18)
    at Dependencies.getSourceFileDecorators (C:\Dev\AutoVu.Saas.Ptms.Portal\src\AutoVu.Saas.Ptms.Portal.ClientApp\node_modules\@compodoc\compodoc\dist\index-cli.js:5589:45)
    at C:\Dev\AutoVu.Saas.Ptms.Portal\src\AutoVu.Saas.Ptms.Portal.ClientApp\node_modules\@compodoc\compodoc\dist\index-cli.js:5416:27
    at Array.map (<anonymous>)
    at Dependencies.getDependencies (C:\Dev\AutoVu.Saas.Ptms.Portal\src\AutoVu.Saas.Ptms.Portal.ClientApp\node_modules\@compodoc\compodoc\dist\index-cli.js:5410:21)
    at CliApplication.Application.getDependenciesData (C:\Dev\AutoVu.Saas.Ptms.Portal\src\AutoVu.Saas.Ptms.Portal.ClientApp\node_modules\@compodoc\compodoc\dist\index-cli.js:7079:40) } reason: Error: Could not find the node's symbol.
    at InvalidOperationError.BaseError [as constructor] (C:\Dev\AutoVu.Saas.Ptms.Portal\src\AutoVu.Saas.Ptms.Portal.ClientApp\node_modules\ts-simple-ast\dist\errors\BaseError.js:16:28)
    at new InvalidOperationError (C:\Dev\AutoVu.Saas.Ptms.Portal\src\AutoVu.Saas.Ptms.Portal.ClientApp\node_modules\ts-simple-ast\dist\errors\InvalidOperationError.js:17:28)
    at Object.throwIfNullOrUndefined (C:\Dev\AutoVu.Saas.Ptms.Portal\src\AutoVu.Saas.Ptms.Portal.ClientApp\node_modules\ts-simple-ast\dist\errors\helpers.js:96:15)
    at Identifier.Node.getSymbolOrThrow (C:\Dev\AutoVu.Saas.Ptms.Portal\src\AutoVu.Saas.Ptms.Portal.ClientApp\node_modules\ts-simple-ast\dist\compiler\common\Node.js:167:23)
    at RouterParserUtil.cleanFileDynamics (C:\Dev\AutoVu.Saas.Ptms.Portal\src\AutoVu.Saas.Ptms.Portal.ClientApp\node_modules\@compodoc\compodoc\dist\index-cli.js:1290:18)
    at Dependencies.getSourceFileDecorators (C:\Dev\AutoVu.Saas.Ptms.Portal\src\AutoVu.Saas.Ptms.Portal.ClientApp\node_modules\@compodoc\compodoc\dist\index-cli.js:5589:45)
    at C:\Dev\AutoVu.Saas.Ptms.Portal\src\AutoVu.Saas.Ptms.Portal.ClientApp\node_modules\@compodoc\compodoc\dist\index-cli.js:5416:27
    at Array.map (<anonymous>)
    at Dependencies.getDependencies (C:\Dev\AutoVu.Saas.Ptms.Portal\src\AutoVu.Saas.Ptms.Portal.ClientApp\node_modules\@compodoc\compodoc\dist\index-cli.js:5410:21)
    at CliApplication.Application.getDependenciesData (C:\Dev\AutoVu.Saas.Ptms.Portal\src\AutoVu.Saas.Ptms.Portal.ClientApp\node_modules\@compodoc\compodoc\dist\index-cli.js:7079:40)
[21:29:49] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
</details>

**Comment by vogloblinsky** [comment]
@felpel Is it possible to have the code of `portal-routing.module.ts`, here or by email (github profile) ?

**Comment by JBusch** [comment]
In my case, the routes menu entry also did not get generated. i changed 
`export const appRoutes = [...]` to `export const appRoutes: Routes = [...]` and the routes entry gets generated. maybe that helps :)

**Comment by Jonatthu** [comment]
This is still happening on version 1.1.7 @vogloblinsky

**Comment by aruballo** [comment]
Any updates on this? 

At the moment my Routes graph is loaded correctly (had to make a seperate module that contained the APP_ROUTES definition and imported/exported the routermodule), but the lazy loaded modules listed in the graph do not show up in the modules section of the documentation, so I do not have any definitions for them.

**Comment by bboynton97** [comment]
I'm having the same issue where lazy loaded routes are not being detected by compodoc
