### ISSUE TITLE
BUG Unable to generate documentation from 'compodoc -p src/tsconfig.app.json'

### ISSUE THREAD

**Issue by nortain** [compodoc/compodoc#511]
Unable to generate documentation when attempting to run compodoc.  Setup npm script: 
"compodoc": "./node_modules/.bin/compodoc -p src/tsconfig.app.json",
executed by npm run compodoc:

Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pe-mat@0.0.1 compodoc: `compodoc -p src/tsconfig.app.json`
npm ERR! Exit status 1

##### **Operating System, Node.js, npm, compodoc version(s)**
OS: macOS 10.12.6
node: v8.9.4
npm: 5.6.0
compodoc: 1.0.9

##### **Angular configuration, a `package.json` file in the root folder**
Standard Angular-cli configuration with package.json in the root directory
Angular: 5.12
Angular/cli: 1.62
Debug log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'compodoc' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'precompodoc', 'compodoc', 'postcompodoc' ]
5 info lifecycle pe-mat@0.0.1~precompodoc: pe-mat@0.0.1
6 info lifecycle pe-mat@0.0.1~compodoc: pe-mat@0.0.1
7 verbose lifecycle pe-mat@0.0.1~compodoc: unsafe-perm in lifecycle true
8 verbose lifecycle pe-mat@0.0.1~compodoc: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/mikemc/IDEA/pe-mat/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle pe-mat@0.0.1~compodoc: CWD: /Users/mikemc/IDEA/pe-mat
10 silly lifecycle pe-mat@0.0.1~compodoc: Args: [ '-c', 'compodoc -p src/tsconfig.app.json' ]
11 silly lifecycle pe-mat@0.0.1~compodoc: Returned: code: 1  signal: null
12 info lifecycle pe-mat@0.0.1~compodoc: Failed to exec compodoc script
13 verbose stack Error: pe-mat@0.0.1 compodoc: `compodoc -p src/tsconfig.app.json`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid pe-mat@0.0.1
15 verbose cwd /Users/mikemc/IDEA/pe-mat
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "compodoc"
18 verbose node v8.9.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error pe-mat@0.0.1 compodoc: `compodoc -p src/tsconfig.app.json`
22 error Exit status 1
23 error Failed at the pe-mat@0.0.1 compodoc script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

##### **Compodoc installed globally or locally ?**

compodoc is installed locally

##### **Motivation for or Use Case**

Unable to generate documentation

**Comment by nortain** [comment]
I figured out what was causing the problem.  Inside of my routes I was referencing a constant like:
const LOGIN = "/LOGIN";
This same const was being used elsewhere in the code by the Router using a the navigateByUrl(LOGIN);
To make that same const work with Routes I was doing something like:
{path: LOGIN.slice(1), component: LoginComponent}
While this worked fine for the application as a whole when trying to generate documentation it would blow up.
I made a secondary const beneath my first that sliced the first constant ahead of time and just called it ROUTES_LOGIN. 
like:
export const ROUTES_LOGIN = LOGIN.slice(1);

using  {path: ROUTES_LOGIN, component: LoginComponent} works just fine now.
