### ISSUE TITLE
[BUG] Promise rejection on Process page dependencies

### ISSUE THREAD

**Issue by NicolasDeclercq** [compodoc/compodoc#516]
##### **Overview of the issue**

Promise rejection while generating documentation

##### **Operating System, Node.js, npm, compodoc version(s)**
windows 7
angular 4.4.5

node 8.1.3
npm 5.0.3

##### **Angular configuration, a `package.json` file in the root folder**
```{
  "scripts": {
    "ng": "ng",
    "start": "npm i && npm run test-silent && ng serve --env dev",
    "start:local": "npm i && npm run test-silent && ng serve --env dev-local-api",
    "build": "ng build --prod --env prod --build-optimize",
    "test": "ng test -cc",
    "test-silent": "ng test -sr -cc -w=false --browsers PhantomJS",
    "test:accessibility": "pa11y-ci",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "xi18n": "ng xi18n --output-path ./src/i18n/",
    "build-i18n:en": "ng build --output-path=dist/en --aot --prod --bh /en/ --i18n-file=src/i18n/messages.en.xlf --i18n-format=xlf --locale=en --build-optimize",
    "build-i18n:fr": "ng build --output-path=dist/fr --aot --prod --bh /fr/ --i18n-file=src/i18n/messages.fr.xlf --i18n-format=xlf --locale=fr --build-optimize",
    "build-i18n": "npm run build-i18n:en && npm run build-i18n:fr",
    "doc": "compodoc -p ./tsconfig.json -s"
  },
  "dependencies": {
    "@angular-redux/form": "^6.6.0",
    "@angular-redux/router": "^6.3.1",
    "@angular-redux/store": "^6.5.7",
    "@angular/animations": "^4.4.5",
    "@angular/common": "^4.4.5",
    "@angular/compiler": "^4.4.5",
    "@angular/core": "^4.4.5",
    "@angular/forms": "^4.4.5",
    "@angular/http": "^4.4.5",
    "@angular/platform-browser": "^4.4.5",
    "@angular/platform-browser-dynamic": "^4.4.5",
    "@angular/router": "^4.4.5",
    "@ngrx/core": "^1.2.0",
    "@ngrx/store": "^2.2.3",
    "@ngrx/store-devtools": "^3.2.4",
    "@types/redux-promise-middleware": "0.0.6",
    "angular4-notifications": "0.0.2",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.1",
    "gsap": "^1.20.4",
    "ng2-translate": "^5.0.0",
    "ngx-cookie-service": "^1.0.9",
    "ngx-feature-toggle": "^4.0.0",
    "ngx-pipes": "^1.6.5",
    "p-map": "^1.2.0",
    "pa11y-ci": "^1.3.1",
    "promise-polyfill": "^6.0.2",
    "ramda": "^0.24.1",
    "ramda-adjunct": "^1.18.0",
    "redux": "^3.7.2",
    "redux-devtools": "^3.4.0",
    "redux-logger": "^3.0.6",
    "redux-observable": "^0.17.0",
    "redux-promise": "^0.5.3",
    "redux-promise-middleware": "^4.4.1",
    "rxjs": "^5.5.2",
    "web-animations-js": "^2.3.1",
    "webpack": "^3.7.1",
    "whatwg-fetch": "^2.0.3",
    "zone.js": "^0.8.18"
  },
  "devDependencies": {
    "@angular/cli": "^1.3.2",
    "@angular/compiler-cli": "^4.4.5",
    "@angular/language-service": "^4.4.5",
    "@compodoc/compodoc": "^1.0.9",
    "@ngtools/json-schema": "^1.1.0",
    "@types/jasmine": "^2.6.0",
    "@types/jasminewd2": "^2.0.3",
    "@types/node": "^6.0.89",
    "ajv": "^5.2.3",
    "codelyzer": "~3.0.1",
    "common-tags": "^1.4.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "^1.7.1",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-firefox-launcher": "^1.0.1",
    "karma-ie-launcher": "^1.0.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-phantomjs-launcher": "^1.0.4",
    "less": "^2.7.2",
    "node-sass": "^4.5.3",
    "protractor": "~5.1.2",
    "react": "^15.6.2",
    "react-redux": "^5.0.6",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
}
```

##### **Compodoc installed globally or locally ?**
install locally

##### **Motivation for or Use Case**

Unable to generate documentation

##### **Suggest a Fix**

[15:38:58] Process pages
[15:38:58] Process page   : dependencies
Unhandled Rejection at: Promise {
  <rejected> Error: Parse error on line 33:
...      {{> menu data menu='normal' }}
-----------------------^
Expecting 'CLOSE', got 'ID'
    at Parser.parseError (D:\platon-front\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:107:11)
    at Parser.parse (D:\platon-front\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:159:22)
    at HandlebarsEnvironment.parse (D:\platon-front\node_modules\handlebars\dist\cjs\handlebars\compiler\base.js:12:17)
    at compileInput (D:\platon-front\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:454:19)
    at D:\platon-front\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:463:18
    at HtmlEngine.render (D:\platon-front\node_modules\@compodoc\compodoc\dist\index-cli.js:2585:16)
    at CliApplication.Application.processPage (D:\platon-front\node_modules\@compodoc\compodoc\dist\index-cli.js:7801:40)
    at D:\platon-front\node_modules\@compodoc\compodoc\dist\index-cli.js:7829:62
    at Array.map (native)
    at CliApplication.Application.processPages (D:\platon-front\node_modules\@compodoc\compodoc\dist\index-cli.js:7829:27) } reason: Error: Parse error on line 33:
...      {{> menu data menu='normal' }}
-----------------------^
Expecting 'CLOSE', got 'ID'
    at Parser.parseError (D:\platon-front\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:107:11)
    at Parser.parse (D:\platon-front\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:159:22)
    at HandlebarsEnvironment.parse (D:\platon-front\node_modules\handlebars\dist\cjs\handlebars\compiler\base.js:12:17)
    at compileInput (D:\platon-front\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:454:19)
    at D:\platon-front\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:463:18
    at HtmlEngine.render (D:\platon-front\node_modules\@compodoc\compodoc\dist\index-cli.js:2585:16)
    at CliApplication.Application.processPage (D:\platon-front\node_modules\@compodoc\compodoc\dist\index-cli.js:7801:40)
    at D:\platon-front\node_modules\@compodoc\compodoc\dist\index-cli.js:7829:62
    at Array.map (native)
    at CliApplication.Application.processPages (D:\platon-front\node_modules\@compodoc\compodoc\dist\index-cli.js:7829:27)

**Comment by vogloblinsky** [comment]
@NicolasDeclercq Can you retest with last version, since 1.1.3 menu is a pure web component and the code where you have this error doesn't exist anymore.

**Comment by vogloblinsky** [comment]
Closing this issue due to no activity since my last comment. Feel free to re-open.
