### ISSUE TITLE
Error: Cannot find module 'uuid/v4'

### ISSUE THREAD

**Issue by FabienDehopre** [compodoc/compodoc#523]
##### **Overview of the issue**

After installing the version 1.1.0, i received the following error:
```
Error: Cannot find module 'uuid/v4'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\dvlp\libs\opw-kernel\node_modules\@compodoc\compodoc\dist\index-cli.js:1398:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```
I installed the `uuid` package manually and then compodoc starts working correctly.
I suppose you are missing a dependency somewhere.

##### **Operating System, Node.js, npm, compodoc version(s)**

OS: Windows 7
NodeJS: 8.11.1
NPM: 5.6.0
Compodoc: 1.1.0

##### **Angular configuration, a `package.json` file in the root folder**

```json
{
  "name": "@opw/kernel",
  "version": "2.3.1",
  "description": "OPW Kernel library containing pipes, services, components, etc...",
  "main": "./bundles/kernel.umd.js",
  "module": "./esm5/kernel.js",
  "es2015": "./esm2015/kernel.js",
  "scripts": {
    "build": "node build.js",
    "lint": "tslint -c tslint.json -t stylish -p tsconfig.json",
    "lint:fix": "tslint -c tslint.json -t stylish -p tsconfig.json --fix",
    "test": "jest --coverage --config ./.jestrc.json",
    "test:watch": "jest --watch",
    "pack-lib": "npm pack ./dist",
    "publish-lib": "npm publish ./dist",
    "publish-lib:next": "npm publish --tag next ./dist",
    "compodoc": "compodoc -p tsconfig.json -d ./documentation -n \"Documentation Kernel Frontend\" --theme material --disablePrivate --disableInternal --disableLifeCycleHooks",
    "format": "prettier --write \"**/*.ts\" \"**/*.js\" \"**/*.md\" \"**/*.json\"",
    "format:check": "prettier --list-different \"**/*.ts\" \"**/*.js\" \"**/*.md\" \"**/*.json\"",
    "changelog": "standard-changelog -i CHANGELOG.md -s"
  },
  "typings": "./kernel.d.ts",
  "keywords": [
    "angular",
    "kernel",
    "opw",
    "spw"
  ],
  "license": "MIT",
  "dependencies": {
    "tslib": "^1.9.0"
  },
  "peerDependencies": {
    "@angular/core": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "angular-l10n": "^4.1.0",
    "angular-oauth2-oidc": "^3.1.0",
    "lodash": "^4.17.5",
    "moment": "^2.20.1",
    "primeng": "^5.2.0",
    "rxjs": "^5.5.0",
    "text-encoding": "^0.6.4",
    "zone.js": "^0.8.20"
  },
  "devDependencies": {
    "@angular/animations": "^5.2.9",
    "@angular/common": "^5.2.9",
    "@angular/compiler": "^5.2.9",
    "@angular/compiler-cli": "^5.2.9",
    "@angular/core": "^5.2.9",
    "@angular/forms": "^5.2.9",
    "@angular/platform-browser": "^5.2.9",
    "@angular/platform-browser-dynamic": "^5.2.9",
    "@angular/router": "^5.2.9",
    "@commitlint/cli": "^6.1.3",
    "@commitlint/config-conventional": "^6.1.3",
    "@commitlint/prompt-cli": "^6.1.3",
    "@compodoc/compodoc": "^1.1.0",
    "@types/jest": "^22.2.2",
    "@types/lodash": "4.14.74",
    "@types/moment-timezone": "^0.5.4",
    "@types/node": "8.0.1",
    "@types/text-encoding": "0.0.32",
    "angular-l10n": "^4.1.5",
    "angular-oauth2-oidc": "^3.1.4",
    "chalk": "2.3.0",
    "codelyzer": "^4.2.1",
    "core-js": "2.5.1",
    "husky": "^0.15.0-rc.13",
    "jest": "^22.4.3",
    "jest-preset-angular": "^5.2.1",
    "lint-staged": "^4.3.0",
    "lodash": "^4.17.5",
    "moment": "^2.21.0",
    "moment-timezone": "^0.5.13",
    "prettier": "^1.11.1",
    "primeng": "^5.2.4",
    "reflect-metadata": "0.1.10",
    "rollup": "0.50.0",
    "rollup-plugin-license": "0.5.0",
    "rollup-plugin-node-resolve": "3.0.0",
    "rollup-plugin-sourcemaps": "0.4.2",
    "rxjs": "^5.5.8",
    "shelljs": "0.7.8",
    "source-map-loader": "0.2.3",
    "standard-changelog": "^1.0.18",
    "text-encoding": "^0.6.4",
    "ts-loader": "3.1.1",
    "tslint": "^5.9.1",
    "tslint-angular": "^1.1.1",
    "tslint-config-prettier": "^1.10.0",
    "typescript": "~2.6.2",
    "uglify-js": "3.1.6",
    "webpack": "3.8.1",
    "zone.js": "^0.8.20"
  }
}
```

##### **Compodoc installed globally or locally ?**

Locally

**Comment by vogloblinsky** [comment]
Thanks, bad installation during development in devDependencies.
1.1.1 online to fix it.
