### ISSUE TITLE
[BUG] Error: "name" not defined in [object Object]

### ISSUE THREAD

**Issue by ojuniorbezerra** [compodoc/compodoc#547]
Has anyone ever had this error?
Unhandled Rejection at: Promise {
  <rejected> { Error: "name" not defined in [object Object]
    at strict (/home/juniorbezerra/workspace-git-remote/licitar-frontend/node_modules/@compodoc/compodoc/node_modules/handlebars/dist/cjs/handlebars/runtime.js:96:15)
    at eval (eval at createFunctionContext (/home/juniorbezerra/workspace-git-remote/licitar-frontend/node_modules/@compodoc/compodoc/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:6:62)
    at prog (/home/juniorbezerra/workspace-git-remote/licitar-frontend/node_modules/@compodoc/compodoc/node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
    at execIteration (/home/juniorbezerra/workspace-git-remote/licitar-frontend/node_modules/@compodoc/compodoc/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:51:19)
    at Object.<anonymous> (/home/juniorbezerra/workspace-git-remote/licitar-frontend/node_modules/@compodoc/compodoc/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:61:13)
    at eval (eval at createFunctionContext (/home/juniorbezerra/workspace-git-remote/licitar-frontend/node_modules/@compodoc/compodoc/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:10:31)
    at Object.prog [as fn] (/home/juniorbezerra/workspace-git-remote/licitar-frontend/node_modules/@compodoc/compodoc/node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
    at JsdocParamsHelper.helperFunc (/home/juniorbezerra/workspace-git-remote/licitar-frontend/node_modules/@compodoc/compodoc/dist/index-cli.js:2255:28)
    at Object.<anonymous> (/home/juniorbezerra/workspace-git-remote/licitar-frontend/node_modules/@compodoc/compodoc/dist/index-cli.js:2752:38)
    at eval (eval at createFunctionContext (/home/juniorbezerra/workspace-git-remote/licitar-frontend/node_modules/@compodoc/compodoc/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:6:78)
  description: undefined,
  fileName: undefined,
  lineNumber: undefined,
  message: '"name" not defined in [object Object]',
  name: 'Error',
  number: undefined } } reason: { Error: "name" not defined in [object Object]
    at strict (/home/juniorbezerra/workspace-git-remote/licitar-frontend/node_modules/@compodoc/compodoc/node_modules/handlebars/dist/cjs/handlebars/runtime.js:96:15)
    at eval (eval at createFunctionContext (/home/juniorbezerra/workspace-git-remote/licitar-frontend/node_modules/@compodoc/compodoc/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:6:62)
    at prog (/home/juniorbezerra/workspace-git-remote/licitar-frontend/node_modules/@compodoc/compodoc/node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
    at execIteration (/home/juniorbezerra/workspace-git-remote/licitar-frontend/node_modules/@compodoc/compodoc/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:51:19)
    at Object.<anonymous> (/home/juniorbezerra/workspace-git-remote/licitar-frontend/node_modules/@compodoc/compodoc/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:61:13)
    at eval (eval at createFunctionContext (/home/juniorbezerra/workspace-git-remote/licitar-frontend/node_modules/@compodoc/compodoc/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:10:31)
    at Object.prog [as fn] (/home/juniorbezerra/workspace-git-remote/licitar-frontend/node_modules/@compodoc/compodoc/node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
    at JsdocParamsHelper.helperFunc (/home/juniorbezerra/workspace-git-remote/licitar-frontend/node_modules/@compodoc/compodoc/dist/index-cli.js:2255:28)
    at Object.<anonymous> (/home/juniorbezerra/workspace-git-remote/licitar-frontend/node_modules/@compodoc/compodoc/dist/index-cli.js:2752:38)
    at eval (eval at createFunctionContext (/home/juniorbezerra/workspace-git-remote/licitar-frontend/node_modules/@compodoc/compodoc/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:6:78)
  description: undefined,
  fileName: undefined,
  lineNumber: undefined,
  message: '"name" not defined in [object Object]',
  name: 'Error',
  number: undefined }

**Comment by vogloblinsky** [comment]
Fixed here : https://github.com/compodoc/compodoc/commit/888547a4a1d0c75dc43258f55ddabf27dd0cf12f
Will come in 1.1.3
