### ISSUE TITLE
[BUG] ENOENT: Error: File Not found

### ISSUE THREAD

**Issue by briosheje** [compodoc/compodoc#566]
##### **Overview of the issue**
While running the default `compodoc -p tsconfig.json -s`, the procedure gets stuck with an ENOENT error:
```
[11:40:37] Empty metadatas, trying to found it with imports.
Unhandled Rejection at: Promise {
  <rejected> { Error: File not found: C:/Users/<user>/svn/ng2framework/hx-base/src/app/Framework/SubModules/Svc.ts
    at FileNotFoundError.BaseError [as constructor] (C:\Users\<user>\svn\ng2framework\hx-base\node_modules\ts-simple-ast\dist\errors\BaseError.js:16:28)
    at new FileNotFoundError (C:\Users\<user>\svn\ng2framework\hx-base\node_modules\ts-simple-ast\dist\errors\FileNotFoundError.js:17:28)
    at Project.addExistingSourceFile (C:\Users\<user>\svn\ng2framework\hx-base\node_modules\ts-simple-ast\dist\Project.js:264:19)
    at ImportsUtil.findValueInImportOrLocalVariables (C:\Users\<user>\svn\ng2framework\hx-base\node_modules\@compodoc\compodoc\dist\index-cli.js:639:23)
    at Dependencies.findProperties (C:\Users\<user>\svn\ng2framework\hx-base\node_modules\@compodoc\compodoc\dist\index-cli.js:6092:41)
    at visitNode (C:\Users\<user>\svn\ng2framework\hx-base\node_modules\@compodoc\compodoc\dist\index-cli.js:5605:43)
    at Array.forEach (<anonymous>)
    at parseNode (C:\Users\<user>\svn\ng2framework\hx-base\node_modules\@compodoc\compodoc\dist\index-cli.js:5726:64)
    at C:\Users\<user>\svn\ng2framework\hx-base\node_modules\@compodoc\compodoc\dist\index-cli.js:5978:13
    at visitNodes (C:\Users\<user>\svn\ng2framework\hx-base\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:13999:30)
  filePath: 'C:/Users/<user>/svn/ng2framework/hx-base/src/app/Framework/SubModules/Svc.ts',
  code: 'ENOENT' } } reason: { Error: File not found: C:/Users/<user>/svn/ng2framework/hx-base/src/app/Framework/SubModules/Svc.ts
    at FileNotFoundError.BaseError [as constructor] (C:\Users\<user>\svn\ng2framework\hx-base\node_modules\ts-simple-ast\dist\errors\BaseError.js:16:28)
    at new FileNotFoundError (C:\Users\<user>\svn\ng2framework\hx-base\node_modules\ts-simple-ast\dist\errors\FileNotFoundError.js:17:28)
    at Project.addExistingSourceFile (C:\Users\<user>\svn\ng2framework\hx-base\node_modules\ts-simple-ast\dist\Project.js:264:19)
    at ImportsUtil.findValueInImportOrLocalVariables (C:\Users\<user>\svn\ng2framework\hx-base\node_modules\@compodoc\compodoc\dist\index-cli.js:639:23)
    at Dependencies.findProperties (C:\Users\<user>\svn\ng2framework\hx-base\node_modules\@compodoc\compodoc\dist\index-cli.js:6092:41)
    at visitNode (C:\Users\<user>\svn\ng2framework\hx-base\node_modules\@compodoc\compodoc\dist\index-cli.js:5605:43)
    at Array.forEach (<anonymous>)
    at parseNode (C:\Users\<user>\svn\ng2framework\hx-base\node_modules\@compodoc\compodoc\dist\index-cli.js:5726:64)
    at C:\Users\<user>\svn\ng2framework\hx-base\node_modules\@compodoc\compodoc\dist\index-cli.js:5978:13
    at visitNodes (C:\Users\<user>\svn\ng2framework\hx-base\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:13999:30)
  filePath: 'C:/Users/<user>/svn/ng2framework/hx-base/src/app/Framework/SubModules/Svc.ts',
  code: 'ENOENT' }

```
##### **Operating System, Node.js, npm, compodoc version(s)**
Operating System: Windows 10
Node.js version: v.8.9.2
NPM version: v.5.5.1
Compodoc version: ^1.1.2

##### **Angular configuration, a `package.json` file in the root folder**
I'm using the Angular Starter project: https://github.com/gdi2290/angular-starter
And I've added some stuff to it, though the package.json is the exact same, aside some additional packages which doesn't really impact at all.

##### **Compodoc installed globally or locally ?**
Compodoc is installed **locally**.

##### **Motivation for or Use Case**
I guess because of that:
`[11:40:37] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)`

##### **Reproduce the error**
It's not that easy to reproduce the issue, since the project is quite big already.
However, the folder where the error is thrown (the analyzed folder), has an index.ts file which holds these informations:

```
export { AuthUser } from './classes/user/authuser.class';
export { AuthAziende } from './classes/IAuth';
export * from './classes/ICore';
export * from './classes/IDocument';
export * from './classes/IEntityFramework';
export * from './classes/ISettings';
export * from './classes/IStore';

export { ILoginResponse } from './interfaces/ILoginResponse';
export { IGenericList } from './interfaces/IGenericList';
export { IGenericEntity } from './interfaces/IGenericEntity';
export { IDefaultRequest } from './interfaces/IDefaultRequest';
export { IWSResponse } from './interfaces/IApp';

export { RestService } from './services/rest/rest.service';
export { SVCService } from './services/shared/standard.svc.service';
export { HxSVCModule } from './Framework.svc.module';

```
I would guess the issue is somehow there, since there is no Svc.ts file, just Svc folder.

##### **Related issues**
None.

##### **Suggest a Fix**
See above

**Comment by briosheje** [comment]
Okay, I guess I've found why this is creating issues: it looks like that any `index.ts` file is not interpreted correctly.

Somehow, an import like:
`import { IWSResponse } from '../../../SubModules/Svc';`

Whereas in `../../../SubModules/Svc/index.ts` the class is exported in this way:
`export { IWSResponse } from './interfaces/IApp';`

Will somehow fail, because the compodoc compiler seems to be looking for `Svc.ts` instead of `Svc/index.ts`.

Sounds intriguing, though, not sure whether it was mentioned somewhere in the documentations, but I don't see why this would fail in an ideal scenario.

**Comment by vogloblinsky** [comment]
Ok i have reproduced the issue.

**Comment by vogloblinsky** [comment]
One workaround is to go deeper when you import something from a barrel file, pointing to index.ts

`import { FooterComponentSchema } from './metadatas';`
`import { FooterComponentSchema } from './metadatas/index';`

**Comment by briosheje** [comment]
@vogloblinsky Oh, thanks! I didn't really thing about that indeed!

To be entirely honest, I didn't event notice it at first because I'm using an auto importer on visual studio code, so it just automatically omits `index`.

Thanks for the support! Perhaps it's worth mentioning that if some modules lazy load occurs, this may be something to take care about for documentation purposes, at least until 1.1.4 is out :)

**Comment by vogloblinsky** [comment]
> Perhaps it's worth mentioning that if some modules lazy load occurs, this may be something to take care about for documentation purposes, at least until 1.1.4 is out :)

Can you explain a little more about `if some modules lazy load occurs`? thanks

**Comment by briosheje** [comment]
@vogloblinsky Basically, the issue came out because, in my case, I have a module which is lazy loaded in my application through the `index.ts` file inside the module's folder.

As far as I can see, it is also a quite common practice to put, in the same index file, all the exports related to that module.

Example: assuming you have a structure like:

`MyLazyModule/`
`MyLazyModule/Interfaces/`

you may have an `index.ts` file in your `MyLazyModule` folder which exports **the module AND all the interfaces**, so that these can be easily loaded if the module is exported somewhere else (outside of the application as a standalone module).

In the end, you will have an `index.ts` like:

`
export { myLazyLoadedModule } from 'myLazyLoadedModule.module';
export { InterfaceA } from './interfaces/a';
export { InterfaceB } from './interfaces/b';
`

and, maybe, you will have a file which is doing something like:

`
import { interfaceA } from './MyLazyModule';
`

which will lead to the issue. However, this is probably because the module is lazy loaded (hence the index.ts file, which is needed for the lazy load to work).

What I meant is that without that index.ts file specifically, the issue wouldn't even exist, so this can be somehow related to the lazy loading topic, in the angular context.
