### ISSUE TITLE
[BUG] Routing parse issue

### ISSUE THREAD

**Issue by gwest7** [compodoc/compodoc#570]
##### **Overview of the issue**

Installed compodoc locally on an old CLI generated Angular project.

After adding the compodoc script in package.json:

`npm run compodoc`

```
...
[06:56:54] Get dependencies data
[06:56:55] parsing        : /Users/gary/myapp/src/main.ts
[06:56:55] parsing        : /Users/gary/myapp/src/polyfills.ts
[06:56:55] parsing        : /Users/gary/myapp/src/app/app-routing.module.ts
[06:56:55] Analysing routes definitions and clean them if necessary
Unhandled Rejection at: Promise {
  <rejected> Error: Expected to find an initializer.
    at InvalidOperationError.BaseError [as constructor] (/Users/gary/myapp/node_modules/ts-simple-ast/dist/errors/BaseError.js:7:28)
    at new InvalidOperationError (/Users/gary/myapp/node_modules/ts-simple-ast/dist/errors/InvalidOperationError.js:8:28)
    at Object.throwIfNullOrUndefined (/Users/gary/myapp/node_modules/ts-simple-ast/dist/errors/helpers.js:96:15)
    at EnumMember.InitializerGetExpressionableNode.class_1.getInitializerOrThrow (/Users/gary/myapp/node_modules/ts-simple-ast/dist/compiler/base/initializer/InitializerGetExpressionableNode.js:25:27)
    at RouterParserUtil.cleanFileDynamics (/Users/gary/myapp/node_modules/@compodoc/compodoc/dist/index-cli.js:1383:80)
    at Dependencies.getSourceFileDecorators (/Users/gary/myapp/node_modules/@compodoc/compodoc/dist/index-cli.js:5812:45)
    at /Users/gary/myapp/node_modules/@compodoc/compodoc/dist/index-cli.js:5638:27
    at Array.map (<anonymous>)
    at Dependencies.getDependencies (/Users/gary/myapp/node_modules/@compodoc/compodoc/dist/index-cli.js:5632:21)
    at CliApplication.Application.getDependenciesData (/Users/gary/myapp/node_modules/@compodoc/compodoc/dist/index-cli.js:7309:40) } reason: Error: Expected to find an initializer.
    at InvalidOperationError.BaseError [as constructor] (/Users/gary/myapp/node_modules/ts-simple-ast/dist/errors/BaseError.js:7:28)
    at new InvalidOperationError (/Users/gary/myapp/node_modules/ts-simple-ast/dist/errors/InvalidOperationError.js:8:28)
    at Object.throwIfNullOrUndefined (/Users/gary/myapp/node_modules/ts-simple-ast/dist/errors/helpers.js:96:15)
    at EnumMember.InitializerGetExpressionableNode.class_1.getInitializerOrThrow (/Users/gary/myapp/node_modules/ts-simple-ast/dist/compiler/base/initializer/InitializerGetExpressionableNode.js:25:27)
    at RouterParserUtil.cleanFileDynamics (/Users/gary/myapp/node_modules/@compodoc/compodoc/dist/index-cli.js:1383:80)
    at Dependencies.getSourceFileDecorators (/Users/gary/myapp/node_modules/@compodoc/compodoc/dist/index-cli.js:5812:45)
    at /Users/gary/myapp/node_modules/@compodoc/compodoc/dist/index-cli.js:5638:27
    at Array.map (<anonymous>)
    at Dependencies.getDependencies (/Users/gary/myapp/node_modules/@compodoc/compodoc/dist/index-cli.js:5632:21)
    at CliApplication.Application.getDependenciesData (/Users/gary/myapp/node_modules/@compodoc/compodoc/dist/index-cli.js:7309:40)
```

##### **Operating System, Node.js, npm, compodoc version(s)**

OSX 10.13.3, Node.js 10.0.0, npm 6.0.1, compodoc@1.1.3, AngularCLI 1.6, Angular Core 5.1.1

##### **Angular configuration, a `package.json` file in the root folder**

Stock standard Angular CLI 1.6 generated project

```
"dependencies": {
    "@angular/animations": "^5.1.1",
    "@angular/common": "^5.1.1",
    "@angular/compiler": "^5.1.1",
    "@angular/core": "^5.1.1",
    "@angular/forms": "^5.1.1",
    "@angular/http": "^5.1.1",
    "@angular/platform-browser": "^5.1.1",
    "@angular/platform-browser-dynamic": "^5.1.1",
    "@angular/router": "^5.1.1",
    "@angular/service-worker": "^5.1.1",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-beta.7",
    "bootstrap": "^4.0.0-beta.2",
    "core-js": "^2.5.3",
    "font-awesome": "^4.7.0",
    "moment-timezone": "^0.5.14",
    "ng2-img-cropper": "^0.9.0",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.6.0",
    "@angular/compiler-cli": "^5.1.1",
    "@angular/language-service": "^5.1.1",
    "@compodoc/compodoc": "^1.1.3",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/moment-timezone": "^0.5.4",
    "@types/node": "^6.0.94",
    "codelyzer": "^4.0.2",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2"
  }
```

##### **Compodoc installed globally or locally ?**

Locally.

##### **Motivation for or Use Case**

I wanted to see what compodoc did with a previous project of mine, but I can't get past this line:

`Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)`

I searched for the bug prior to making this submission, but found nothing.

##### **Reproduce the error**

Simply run `compodoc`.

**Comment by vogloblinsky** [comment]
Can i have the source code of `/Users/gary/myapp/src/app/app-routing.module.ts` for debugging ?

**Comment by gwest7** [comment]
```
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

import { Access } from './models/access';
import { ADMIN } from './models/roles';
import { Role } from './models/role';

import { AuthGuard } from './services/auth.guard';

import { HomeComponent } from './components/home/home.component';
import { BookingsComponent } from './components/bookings/bookings.component';
import { ListComponent as BookingsListComponent, Data as BookingData } from './components/bookings/list/list.component';
import { UsersComponent } from './components/users/users.component';
import { UserDetailComponent } from './components/user-detail/user-detail.component';
import { ReferrersComponent } from './components/referrers/referrers.component';
import { ListComponent as ReferrerListComponent, Data as ReferrerData } from './components/referrers/list/list.component';
import { StoresComponent } from './components/stores/stores.component';
import { CommissionsComponent } from './components/commissions/commissions.component';
import { ListComponent as CommissionListComponent, Data as ComData } from './components/commissions/list/list.component';
import { RewardsComponent } from './components/rewards/rewards.component';
import { StoreDetailComponent } from './components/store-detail/store-detail.component';
import { ProfileComponent } from './components/profile/profile.component';
import { BookingDetailComponent } from './components/booking-detail/booking-detail.component';
import { BookingEditComponent } from './components/booking-edit/booking-edit.component';
import { UserEditComponent } from './components/user-edit/user-edit.component';
import { ReferrerVetComponent } from './components/referrer-vet/referrer-vet.component';
import { BookingResolveComponent } from './components/booking-resolve/booking-resolve.component';
import { StoreEditComponent } from './components/store-edit/store-edit.component';
import { CommissionDetailComponent } from './components/commission-detail/commission-detail.component';
import { ReferrerImportComponent } from './components/referrer-import/referrer-import.component';
import { ReferrerExportComponent } from './components/referrer-export/referrer-export.component';
import { MessagesComponent } from './components/messages/messages.component';

//##############################
//  ROUTES
//##############################

const routes: Routes = [
  {path:'', component:HomeComponent},

  // BOOKING
  {path:'bookings', component:BookingsComponent, canActivate:[AuthGuard], data: {permission: Access.Bookings_R}, children: [
    {path:'', pathMatch: 'full', redirectTo: 'open'},
    {path:'open', component:BookingsListComponent, data:{"filter":BookingData.Bookings}},
    {path:'walkins', component:BookingsListComponent, data:{"filter":BookingData.WalkIns}},
    {path:'orders', component:BookingsListComponent, data:{"filter":BookingData.Orders}},
    {path:'resolved', component:BookingsListComponent, data:{"filter":BookingData.Resolved}},
  ]},
  {path:`booking/:id`, component:BookingDetailComponent, canActivate:[AuthGuard], data: {permission: Access.Bookings_R}},
  {path:`booking-add`, component:BookingEditComponent, canActivate:[AuthGuard], data: {permission: Access.Bookings_C}},
  {path:`booking/:id/edit`, component:BookingEditComponent, canActivate:[AuthGuard], data: {permission: Access.Bookings_U}},
  {path:`booking/:id/res`, component:BookingResolveComponent, canActivate:[AuthGuard]},

  // USER
  {path:'users', component:UsersComponent, canActivate:[AuthGuard], data: {permissions: [Access.Users_R, Access.Users_Referrer_R, Access.Users_Admin_R]}},
  {path:`user/:id`, component:UserDetailComponent, canActivate:[AuthGuard], data: {permissions: [Access.Users_R, Access.Users_Referrer_R, Access.Users_Admin_R]}},
  {path:`user-add`, component:UserEditComponent, canActivate:[AuthGuard], data: {permissions: [Access.Users_R, Access.Users_Referrer_R, Access.Users_Admin_R]}},
  {path:`user/:id/edit`, component:UserEditComponent, canActivate:[AuthGuard], data: {permissions: [Access.Users_R, Access.Users_Referrer_R, Access.Users_Admin_R]}},

  // REFERRER
  {path:'refs', component:ReferrersComponent, canActivate:[AuthGuard], data: {permission: Access.Users_Referrer_R}, children: [
    {path:'', pathMatch: 'full', redirectTo: 'reqs'},
    {path:'reqs', component:ReferrerListComponent, data:{"filter":ReferrerData.Requests}},
    {path:'updates', component:ReferrerListComponent, data:{"filter":ReferrerData.Updates}},
    {path:'list', component:ReferrerListComponent, data:{"filter":ReferrerData.Individual}},
    {path:'comps', component:ReferrerListComponent, data:{"filter":ReferrerData.Company}},
  ]},
  {path:`ref/:id/vet`, component:ReferrerVetComponent, canActivate:[AuthGuard], data: {permission: Access.Users_R}},
  {path:`ref-import`, component:ReferrerImportComponent, canActivate:[AuthGuard], data: {permission: Access.Users_C}},
  {path:`ref-export`, component:ReferrerExportComponent, canActivate:[AuthGuard], data: {permission: Access.Users_R}},

  // STORE
  {path:'stores', component:StoresComponent, canActivate:[AuthGuard], data: {permission: Access.Stores_R}},
  {path:`store/:id`, component:StoreDetailComponent, canActivate:[AuthGuard], data: {permission: Access.Stores_R}},
  {path:`store-add`, component:StoreEditComponent, canActivate:[AuthGuard], data: {permission: Access.Stores_C}},
  {path:`store/:id/edit`, component:StoreEditComponent, canActivate:[AuthGuard], data: {permission: Access.Stores_U}},

  // COMMISSIONS
  {path:'comms', component:CommissionsComponent, canActivate:[AuthGuard], data: {permission: Access.Commissions_R}, children: [
    {path:'', pathMatch: 'full', redirectTo:'new'},
    {path:'eft', component:CommissionListComponent, data:{"filter":ComData.NewEFT, permission: Access.Commissions_NewCash_R}, canActivate:[AuthGuard]},
    {path:'new', component:CommissionListComponent, data:{"filter":ComData.NewCash, permission: Access.Commissions_NewEFT_R}, canActivate:[AuthGuard]},
    {path:'collectable', component:CommissionListComponent, data:{"filter":ComData.Collectable, permission: Access.Commissions_Collectable_R}, canActivate:[AuthGuard]},
    {path:'collected', component:CommissionListComponent, data:{"filter":ComData.Collected, permission: Access.Commissions_Collected_R}, canActivate:[AuthGuard]},
    {path:'payable', component:CommissionListComponent, data:{"filter":ComData.Payable, permission: Access.Commissions_Payable_R}, canActivate:[AuthGuard]},
    {path:'past', component:CommissionListComponent, data:{"filter":ComData.Paid, permission: Access.Commissions_Paid_R}, canActivate:[AuthGuard]},
  ]},
  {path:`comm/:id`, component:CommissionDetailComponent, canActivate:[AuthGuard], data: {permission: Access.Commissions_R}},

  {path:'rewards', component:RewardsComponent, canActivate:[AuthGuard], data: {permission: Access.Rewards_R}},
  {path:'msgs', component:MessagesComponent, canActivate:[AuthGuard], data: {permission: Access.Messages_R}},
  {path:'profile', component:ProfileComponent, canActivate:[AuthGuard]},
  {path:'**', redirectTo:''},
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
```

**Comment by mscud** [comment]
i am having the same issue, #669 #632 #608 and #603 seem to be related, would be great to have a fix
