### ISSUE TITLE
SyntaxError: JSON5: invalid character '.' at 1:144

### ISSUE THREAD

**Issue by nickjpanella** [compodoc/compodoc#573]
##### **Overview of the issue**

running `npm run compodoc` goes through almost everything successfully and then at the end throws the following error: 

```
Unhandled Rejection at: Promise {
  <rejected> { SyntaxError: JSON5: invalid character '.' at 1:144
    at syntaxError (G:\WINDOWS\DESKTOP\GitHub\project\client\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1:12963)
    at invalidChar (G:\WINDOWS\DESKTOP\GitHub\project\client\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1:12177)
    at Object.afterPropertyValue (G:\WINDOWS\DESKTOP\GitHub\project\client\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1:8133)
    at Object._default [as default] (G:\WINDOWS\DESKTOP\GitHub\project\client\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1:2255)
    at lex (G:\WINDOWS\DESKTOP\GitHub\project\client\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1:1680)
    at Object.parse (G:\WINDOWS\DESKTOP\GitHub\project\client\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1:992)
    at loopInsideModule (G:\WINDOWS\DESKTOP\GitHub\project\client\node_modules\@compodoc\compodoc\dist\index-cli.js:1075:52)
    at loopRoutesParser (G:\WINDOWS\DESKTOP\GitHub\project\client\node_modules\@compodoc\compodoc\dist\index-cli.js:1108:29)
    at loopRoutesParser (G:\WINDOWS\DESKTOP\GitHub\project\client\node_modules\@compodoc\compodoc\dist\index-cli.js:1113:21)
    at RouterParserUtil.constructRoutesTree (G:\WINDOWS\DESKTOP\GitHub\project\client\node_modules\@compodoc\compodoc\dist\index-cli.js:1117:9) lineNumber: 1, columnNumber: 144 } } reason: { SyntaxError: JSON5: invalid character '.' at 1:144
    at syntaxError (G:\WINDOWS\DESKTOP\GitHub\project\client\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1:12963)
    at invalidChar (G:\WINDOWS\DESKTOP\GitHub\project\client\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1:12177)
    at Object.afterPropertyValue (G:\WINDOWS\DESKTOP\GitHub\project\client\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1:8133)
    at Object._default [as default] (G:\WINDOWS\DESKTOP\GitHub\project\client\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1:2255)
    at lex (G:\WINDOWS\DESKTOP\GitHub\project\client\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1:1680)
    at Object.parse (G:\WINDOWS\DESKTOP\GitHub\project\client\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1:992)
    at loopInsideModule (G:\WINDOWS\DESKTOP\GitHub\project\client\node_modules\@compodoc\compodoc\dist\index-cli.js:1075:52)
    at loopRoutesParser (G:\WINDOWS\DESKTOP\GitHub\project\client\node_modules\@compodoc\compodoc\dist\index-cli.js:1108:29)
    at loopRoutesParser (G:\WINDOWS\DESKTOP\GitHub\project\client\node_modules\@compodoc\compodoc\dist\index-cli.js:1113:21)
    at RouterParserUtil.constructRoutesTree (G:\WINDOWS\DESKTOP\GitHub\project\client\node_modules\@compodoc\compodoc\dist\index-cli.js:1117:9) lineNumber: 1, columnNumber: 144 }
[22:17:18] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
error An unexpected error occurred: "Command failed.
Exit code: 1
```

##### **Operating System, Node.js, npm, compodoc version(s)**

Windows 10, Node 8.9.0, npm 5.8.0, compodoc 1.1.3

##### **Angular configuration, a `package.json` file in the root folder**

```
"scripts": {
    "compodoc": "./node_modules/.bin/compodoc -p src/tsconfig.app.json",
```

##### **Compodoc installed globally or locally ?**

both

##### **Motivation for or Use Case**

Error thrown, but no specific location printed.

**Comment by DrMabuse23** [comment]
same here

**Comment by vogloblinsky** [comment]
@DrMabuse23 which version of Node.js, npm, compodoc ?

**Comment by DrMabuse23** [comment]
`````
npm --v                                                                                                                          
6.4.1

 ./node_modules/.bin/compodoc --version                                                                                         
1.1.5

 node --version                                                                                                                   
v8.11.3
`````

**Comment by DrMabuse23** [comment]
@vogloblinsky

**Comment by DrMabuse23** [comment]
ok i found my error 
````
const routes: Routes = [
  {
    path: '',
    component: LandingpageComponent,
  },
  {
    path: `journey`,
    loadChildren: 'src/app/journey/journey.module#JourneyModule'
  }
];
````
the backticks kills on path: `journey`, kills the generation
with nomarl '' still running again but with ${} it works!!
