### ISSUE TITLE
[BUG] Error: Could not find the node's symbol.

### ISSUE THREAD

**Issue by javico2609** [compodoc/compodoc#586]
##### **Operating System, Node.js, npm, compodoc version(s)**

Win 10
NPM 6.0.1
Compodoc 1.1.3
Node v8.11.1
Angular 6.0.4

##### **Angular configuration, a `package.json` file in the root folder**
{
  "name": "frontend",
  "version": "0.1.0",
  "license": "MIT",
  "main": "main.ts",
  "scripts": {
    "ng": "ng",
    "compodoc": "./node_modules/.bin/compodoc -p src/tsconfig.app.json --theme vagrant"
  },
  "private": true,
  "dependencies": {
    "@angular/core": "6.0.4",
  },
  "devDependencies": {
    "@angular/cli": "6.0.8",
    "@compodoc/compodoc": "^1.1.2",
    "typescript": "~2.7.2"
  }
}

##### **Compodoc installed globally or locally ?**

locally

##### **Motivation for or Use Case**

Unhandled Rejection at: Promise {
  <rejected> Error: Could not find the node's symbol.
    at InvalidOperationError.BaseError [as constructor] (...\node_modules\ts-simple-ast\dist\errors\BaseError.js:7:28)
    at new InvalidOperationError ( ....\node_modules\ts-simple-ast\dist\errors\InvalidOperationError.js:8:28)

##### **Reproduce the error**

angular 6 app with lazy loading routes

**Comment by vogloblinsky** [comment]
Is it possible to have your terminal logs ? or the lines before this error ?
Thanks

**Comment by jerkovicl** [comment]
In my case lines that are problem are :
```
const routes: Routes = [
  // Module is lazy loaded, see app-routing.module.ts
  { path: '', component: CountriesComponent, data: { title: extract('Countries') } },
  {
    path: 'add',
    component: CountriesManagerComponent,
    data: { title: extract('New Country'), expectedRole: [Permissions.CountriesEdit] },
    canActivate: [RoleGuard],
  },
];
```

**Comment by jberall** [comment]
I had a similar issue.
I used a reference of an enum and it would not compile.
As such I believe the issue is in the expectedRole: [Permissions.CountriesEdit].
Try changing that.

**Comment by bartios** [comment]
this seems to be related to #525

**Comment by ravinsinghd** [comment]
I had a similar issue. Compodoc 1.1.8

`Unhandled Rejection at: Promise {
  <rejected> Error: Could not find the node's symbol.
      at InvalidOperationError.BaseError [as constructor] (C:\Users\Ravin\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\ts-simple-ast\dist\errors\BaseError.js:7:28)
      at new InvalidOperationError (C:\Users\Ravin\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\ts-simple-ast\dist\errors\InvalidOperationError.js:8:28)
      at Object.throwIfNullOrUndefined (C:\Users\Ravin\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\ts-simple-ast\dist\errors\helpers.js:96:15)
      at Identifier.Node.getSymbolOrThrow (C:\Users\Ravin\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\ts-simple-ast\dist\compiler\common\Node.js:131:23)
      at RouterParserUtil.cleanFileDynamics (C:\Users\Ravin\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:4574:18)
      at AngularDependencies.getSourceFileDecorators (C:\Users\Ravin\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:7004:46)
      at C:\Users\Ravin\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:6816:31
      at Array.map (<anonymous>)
      at AngularDependencies.getDependencies (C:\Users\Ravin\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:6805:21)
      at CliApplication.Application.getDependenciesData (C:\Users\Ravin\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:8348:40) } reason: Error: Could not find the node's symbol.
    at InvalidOperationError.BaseError [as constructor] (C:\Users\Ravin\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\ts-simple-ast\dist\errors\BaseError.js:7:28)
    at new InvalidOperationError (C:\Users\Ravin\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\ts-simple-ast\dist\errors\InvalidOperationError.js:8:28)
    at Object.throwIfNullOrUndefined (C:\Users\Ravin\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\ts-simple-ast\dist\errors\helpers.js:96:15)
    at Identifier.Node.getSymbolOrThrow (C:\Users\Ravin\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\ts-simple-ast\dist\compiler\common\Node.js:131:23)
    at RouterParserUtil.cleanFileDynamics (C:\Users\Ravin\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:4574:18)
    at AngularDependencies.getSourceFileDecorators (C:\Users\Ravin\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:7004:46)
    at C:\Users\Ravin\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:6816:31
    at Array.map (<anonymous>)
    at AngularDependencies.getDependencies (C:\Users\Ravin\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:6805:21)
    at CliApplication.Application.getDependenciesData (C:\Users\Ravin\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:8348:40)`

**Comment by attilacsanyi** [comment]
Its an old issue, seems none of the dynamic route path can work from external variables. Last working version was 1.0.9 since then I use the disable route graph flag to skip generating that.

**Comment by dotmobo** [comment]
same issue for me with lazy loading modules routes, thx for the tips @attilacsanyi !

**Comment by attilacsanyi** [comment]
@dotmobo @vogloblinsky maybe [this is the only solution](https://github.com/compodoc/compodoc/issues/525#issuecomment-488822477) for the problem.

Thanks for @brentmiller
