### ISSUE TITLE
[BUG] Problem command compodoc -p src/tsconfig.app.json

### ISSUE THREAD

**Issue by osanchez88** [compodoc/compodoc#593]
Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'expression' of undefined
    at loop (C:\Users\osanchez\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:6234:22)
    at Dependencies.findExpressionByNameInExpressions (C:\Users\osanchez\AppData\Roaming\npm\node_modules\@compodoc\comp
odoc\dist\index-cli.js:6246:9)
    at parseNode (C:\Users\osanchez\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:6097:56)
    at C:\Users\osanchez\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:6204:13
    at visitNodes (C:\Users\osanchez\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\ts-simple-ast\node
_modules\typescript\lib\typescript.js:14006:30)
    at Object.forEachChild (C:\Users\osanchez\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\ts-simple
-ast\node_modules\typescript\lib\typescript.js:14220:24)
    at Dependencies.getSourceFileDecorators (C:\Users\osanchez\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\
index-cli.js:5815:16)
    at C:\Users\osanchez\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:5638:27
    at Array.map (<anonymous>)
    at Dependencies.getDependencies (C:\Users\osanchez\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cl
i.js:5632:21) } reason: TypeError: Cannot read property 'expression' of undefined
    at loop (C:\Users\osanchez\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:6234:22)
    at Dependencies.findExpressionByNameInExpressions (C:\Users\osanchez\AppData\Roaming\npm\node_modules\@compodoc\comp
odoc\dist\index-cli.js:6246:9)
    at parseNode (C:\Users\osanchez\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:6097:56)
    at C:\Users\osanchez\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:6204:13
    at visitNodes (C:\Users\osanchez\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\ts-simple-ast\node
_modules\typescript\lib\typescript.js:14006:30)
    at Object.forEachChild (C:\Users\osanchez\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\ts-simple
-ast\node_modules\typescript\lib\typescript.js:14220:24)
    at Dependencies.getSourceFileDecorators (C:\Users\osanchez\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\
index-cli.js:5815:16)
    at C:\Users\osanchez\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:5638:27
    at Array.map (<anonymous>)
    at Dependencies.getDependencies (C:\Users\osanchez\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cl
i.js:5632:21)
[08:25:31] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on git
hub. (https://github.com/compodoc/compodoc/issues/new)

**Comment by vogloblinsky** [comment]
Could you provide the source code of the file where it breaks ?

**Comment by Shamshiel** [comment]
I have the same or a similir problem with compodoc. At least the error is the same.
The error is in my _main.ts_ script. I commented out some code to find the problematic part and it seems to be the following:
`var script = document.createElement('script');`

Without this line everything works fine and compodoc doesn't fail creating the documentation.

**Comment by mrdowden** [comment]
I am running into this same issue. The line I must remove to get it to work is in main.ts:

`platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.log(err));`

Since this is a pretty standard Angular 5 app I'm not sure why this would cause a problem. Also note that I must *remove* the above code (commenting it out doesn't work). The `platformBrowserDynamic()` by itself doesn't cause the error.

I'm running using a local installation of compodoc via the following command:

`./node_modules/.bin/compodoc -p src/tsconfig.app.json`

Note that this appear quite similar to #560 except that there's no requirement that the bootstrap statement appear inside of a block (it fails either way).

The full stack trace is below:
```
Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'expression' of undefined
    at loop (/home/mdowden/workspace/flexepark-web-app/node_modules/@compodoc/compodoc/dist/index-cli.js:6234:21)
    at Dependencies.findExpressionByNameInExpressions (/home/mdowden/workspace/flexepark-web-app/node_modules/@compodoc/compodoc/dist/index-cli.js:6246:9)
    at parseNode (/home/mdowden/workspace/flexepark-web-app/node_modules/@compodoc/compodoc/dist/index-cli.js:6097:56)
    at /home/mdowden/workspace/flexepark-web-app/node_modules/@compodoc/compodoc/dist/index-cli.js:6204:13
    at visitNodes (/home/mdowden/workspace/flexepark-web-app/node_modules/ts-simple-ast/node_modules/typescript/lib/typescript.js:14006:30)
    at Object.forEachChild (/home/mdowden/workspace/flexepark-web-app/node_modules/ts-simple-ast/node_modules/typescript/lib/typescript.js:14220:24)
    at Dependencies.getSourceFileDecorators (/home/mdowden/workspace/flexepark-web-app/node_modules/@compodoc/compodoc/dist/index-cli.js:5815:16)
    at /home/mdowden/workspace/flexepark-web-app/node_modules/@compodoc/compodoc/dist/index-cli.js:5638:27
    at Array.map (native)
    at Dependencies.getDependencies (/home/mdowden/workspace/flexepark-web-app/node_modules/@compodoc/compodoc/dist/index-cli.js:5632:21) } reason: TypeError: Cannot read property 'expression' of undefined
    at loop (/home/mdowden/workspace/flexepark-web-app/node_modules/@compodoc/compodoc/dist/index-cli.js:6234:21)
    at Dependencies.findExpressionByNameInExpressions (/home/mdowden/workspace/flexepark-web-app/node_modules/@compodoc/compodoc/dist/index-cli.js:6246:9)
    at parseNode (/home/mdowden/workspace/flexepark-web-app/node_modules/@compodoc/compodoc/dist/index-cli.js:6097:56)
    at /home/mdowden/workspace/flexepark-web-app/node_modules/@compodoc/compodoc/dist/index-cli.js:6204:13
    at visitNodes (/home/mdowden/workspace/flexepark-web-app/node_modules/ts-simple-ast/node_modules/typescript/lib/typescript.js:14006:30)
    at Object.forEachChild (/home/mdowden/workspace/flexepark-web-app/node_modules/ts-simple-ast/node_modules/typescript/lib/typescript.js:14220:24)
    at Dependencies.getSourceFileDecorators (/home/mdowden/workspace/flexepark-web-app/node_modules/@compodoc/compodoc/dist/index-cli.js:5815:16)
    at /home/mdowden/workspace/flexepark-web-app/node_modules/@compodoc/compodoc/dist/index-cli.js:5638:27
    at Array.map (native)
    at Dependencies.getDependencies (/home/mdowden/workspace/flexepark-web-app/node_modules/@compodoc/compodoc/dist/index-cli.js:5632:21)
```

**Comment by mrdowden** [comment]
So I just realized have another Angular 5 app with very much the same essential setup (but much less code) that has no problem running compodoc in the exact same way, even with this line in the file. So I did more digging.

It turns out there is a `try { ... } catch(e) {}` block in the **main.ts** file (above the `bootstrapModule` that is causing the problem.
