### ISSUE TITLE
[BUG] Error when loading gulp plugin @compodoc/gulp-compodoc v0.0.9

### ISSUE THREAD

**Issue by MggLp** [compodoc/compodoc#598]
##### **Overview of the issue**

Error when loading gulp tasks in VS2017 Task Runner Explorer and produces the following stacktrace:
```
Failed to run "C:\Desenv\SGC\Sgc.Web\Sgc.Web\Gulpfile.js"...
cmd.exe /c gulp --tasks-simple
C:\Desenv\SGC\Sgc.Web\Sgc.Web\node_modules\@compodoc\gulp-compodoc\node_modules\fs-extra\lib\fs\index.js:92
exports.write = function (fd, buffer, ...args) {
                                      ^^^
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Desenv\SGC\Sgc.Web\Sgc.Web\node_modules\@compodoc\gulp-compodoc\node_modules\fs-extra\lib\index.js:6:3)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Desenv\SGC\Sgc.Web\Sgc.Web\node_modules\@compodoc\gulp-compodoc\node_modules\@compodoc\compodoc\dist\index.js:12:10)
    at Module._compile (module.js:397:26)
```

##### **Operating System, Node.js, npm, compodoc version(s)**

OS: Windows 10 Enterprise v1803 build 17134.1
Node.js: v8.11.1
npm: v5.6.0
compodoc: v0.0.41
@compodoc/gulp-compodoc: v0.0.9
Visual Studio: MS Visual Studio Enterprise 2017 v15.7.4
.NET Framework: v4.7.03056

##### **Angular configuration, a `package.json` file in the root folder**

package.json is in the root folder with following content:
```
{
  "version": "1.0.0",
  "name": "xxx.abc.xyz",
  "description": "some desc",
  "private": true,
  "scripts": {
    "compodoc": "./node_modules/.bin/compodoc Angular -p tsconfig.json"
  },
  "dependencies": {
    "@angular/common": "6.0.2",
    "@angular/compiler": "6.0.2",
    "@angular/core": "6.0.2",
    "@angular/forms": "6.0.2",
    "@angular/http": "6.0.2",
    "@angular/platform-browser": "6.0.2",
    "@angular/platform-browser-dynamic": "6.0.2",
    "@angular/router": "6.0.2",
    "@angular/upgrade": "6.0.2",
    "angular-in-memory-web-api": "0.6.0",
    "core-js": "2.5.6",
    "reflect-metadata": "0.1.12",
    "rxjs": "6.1.0",
    "systemjs": "0.21.3",
    "zone.js": "0.8.26",
    "bowser": "1.9.3",
    "js-cookie": "2.2.0",
    "toastr": "2.1.4",
    "underscore": "1.9.0",
    "backbone": "1.3.3",
    "jquery-hoverintent": "1.9.0",
    "jquery-visibility": "1.0.11",
    "signalr": "2.2.3",
    "jquery-migrate": "1.4.1",
    "jquery.documentsize": "1.2.4",
    "bootstrap": "4.1.1",
    "intl": "1.2.5",
    "classlist-polyfill": "1.2.0",
    "stacktrace-js": "2.0.0",
    "codemirror": "5.37.0",
    "jquery-contextmenu": "2.6.4"
  },
  "devDependencies": {
    "@compodoc/gulp-compodoc": "1.1.3",
    "@types/backbone": "1.3.42",
    "@types/bowser": "1.0.31",
    "@types/codemirror": "0.0.56",
    "@types/core-js": "0.9.46",
    "@types/jquery": "2.0.48",
    "@types/jquery.contextmenu": "1.7.33",
    "@types/jqueryui": "1.12.2",
    "@types/js-cookie": "2.1.0",
    "@types/microsoft-ajax": "0.0.33",
    "@types/node": "10.1.4",
    "@types/sharepoint": "2016.1.0",
    "@types/signalr": "2.2.35",
    "@types/toastr": "2.1.35",
    "@types/underscore": "1.8.8",
    "bower": "1.8.4",
    "compodoc": "0.0.41",
    "del": "3.0.0",
    "fancy-log": "1.3.2",
    "files-exist": "1.1.0",
    "gulp": "3.9.1",
    "gulp-buster": "1.1.0",
    "gulp-clean-css": "3.9.4",
    "gulp-concat": "2.6.1",
    "gulp-debug": "4.0.0",
    "gulp-inline-ng2-template": "4.1.0",
    "gulp-less": "4.0.0",
    "gulp-print": "5.0.0",
    "gulp-sequence": "1.0.0",
    "gulp-strip-css-comments": "2.0.0",
    "gulp-tap": "1.0.1",
    "gulp-typedoc": "2.2.0",
    "gulp-uglify": "3.0.0",
    "html-minifier": "3.5.16",
    "jquery-tageditor": "1.0.1",
    "json2": "0.4.0",
    "parse-filepath": "1.0.2",
    "require-dir": "1.0.0",
    "systemjs-builder": "0.16.13",
    "systemjs-plugin-text": "0.0.11",
    "typedoc": "0.11.1"
  }
}

```
##### **Compodoc installed globally or locally ?**

Installed locally

##### **If possible sourcecode of the file where it breaks**

It breaks in file 
C:\Desenv\SGC\Sgc.Web\Sgc.Web\node_modules\@compodoc\gulp-compodoc\node_modules\fs-extra\lib\fs\index.js
and the source code is:
```

'use strict'
// This is adapted from https://github.com/normalize/mz
// Copyright (c) 2014-2016 Jonathan Ong me@jongleberry.com and Contributors
const u = require('universalify').fromCallback
const fs = require('graceful-fs')

const api = [
  'access',
  'appendFile',
  'chmod',
  'chown',
  'close',
  'copyFile',
  'fchmod',
  'fchown',
  'fdatasync',
  'fstat',
  'fsync',
  'ftruncate',
  'futimes',
  'lchown',
  'link',
  'lstat',
  'mkdir',
  'mkdtemp',
  'open',
  'readFile',
  'readdir',
  'readlink',
  'realpath',
  'rename',
  'rmdir',
  'stat',
  'symlink',
  'truncate',
  'unlink',
  'utimes',
  'writeFile'
].filter(key => {
  // Some commands are not available on some systems. Ex:
  // fs.copyFile was added in Node.js v8.5.0
  // fs.mkdtemp was added in Node.js v5.10.0
  // fs.lchown is not available on at least some Linux
  return typeof fs[key] === 'function'
})

// Export all keys:
Object.keys(fs).forEach(key => {
  if (key === 'promises') {
    // fs.promises is a getter property that triggers ExperimentalWarning
    // Don't re-export it here, the getter is defined in "lib/index.js"
    return
  }
  exports[key] = fs[key]
})

// Universalify async methods:
api.forEach(method => {
  exports[method] = u(fs[method])
})

// We differ from mz/fs in that we still ship the old, broken, fs.exists()
// since we are a drop-in replacement for the native module
exports.exists = function (filename, callback) {
  if (typeof callback === 'function') {
    return fs.exists(filename, callback)
  }
  return new Promise(resolve => {
    return fs.exists(filename, resolve)
  })
}

// fs.read() & fs.write need special treatment due to multiple callback args

exports.read = function (fd, buffer, offset, length, position, callback) {
  if (typeof callback === 'function') {
    return fs.read(fd, buffer, offset, length, position, callback)
  }
  return new Promise((resolve, reject) => {
    fs.read(fd, buffer, offset, length, position, (err, bytesRead, buffer) => {
      if (err) return reject(err)
      resolve({ bytesRead, buffer })
    })
  })
}

// Function signature can be
// fs.write(fd, buffer[, offset[, length[, position]]], callback)
// OR
// fs.write(fd, string[, position[, encoding]], callback)
// We need to handle both cases, so we use ...args
exports.write = function (fd, buffer, ...args) {
  if (typeof args[args.length - 1] === 'function') {
    return fs.write(fd, buffer, ...args)
  }

  return new Promise((resolve, reject) => {
    fs.write(fd, buffer, ...args, (err, bytesWritten, buffer) => {
      if (err) return reject(err)
      resolve({ bytesWritten, buffer })
    })
  })
}
```

##### **Motivation for or Use Case**

I can't even load the gulp tasks in VS2017 Task Runner Explorer therefore I cannot make a compodoc gulp task to run automatically at build time.

##### **Reproduce the error**

1) Create a gulpfile.js file in the root folder of .NET web application 
2) write in that file the code line:
`module.compodoc = require("@compodoc/gulp-compodoc");`

3) Then go to Task Runner Explorer and press the refresh button: error is logged into Output tab and the Task Runner Explorer no longer displays any gulp task and instead shows "Failed to load. See output window (Ctrl + Alt + O) for more information".

**Comment by vogloblinsky** [comment]
Could you move this issue in this repository please : https://github.com/compodoc/gulp-compodoc
