### ISSUE TITLE
[BUG] : Unhandled Rejection at: Promise

### ISSUE THREAD

**Issue by andyOlarte514** [compodoc/compodoc#602]

**Comment by vogloblinsky** [comment]
Could you please explain your issue ? The template is empty.

**Comment by andyOlarte514** [comment]
Unhandled Rejection at: Promise {
  <rejected> RangeError: Invalid array length
    at CodeBlockWriter._writeIndentation (/Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/code-block-writer/dist/code-block-writer.js:380:23)
    at CodeBlockWriter.writeIndividual (/Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/code-block-writer/dist/code-block-writer.js:317:26)
    at /Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/code-block-writer/dist/code-block-writer.js:311:29
    at Array.forEach (<anonymous>)
    at CodeBlockWriter._writeIndentingNewLines (/Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/code-block-writer/dist/code-block-writer.js:306:15)
    at CodeBlockWriter.write (/Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/code-block-writer/dist/code-block-writer.js:216:14)
    at StringStructurePrinter.printText (/Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/ts-simple-ast/dist/structurePrinters/common/StringStructurePrinter.js:12:20)
    at CommaNewLineSeparatedStructuresPrinter.printText (/Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/ts-simple-ast/dist/structurePrinters/formatting/CommaNewLineSeparatedStructuresPrinter.js:18:35)
    at ArrayLiteralExpression.insertElements (/Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/ts-simple-ast/dist/compiler/expression/array/ArrayLiteralExpression.js:56:26)
    at _loop_3 (/Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/@compodoc/compodoc/dist/index-cli.js:1334:32) } reason: RangeError: Invalid array length
    at CodeBlockWriter._writeIndentation (/Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/code-block-writer/dist/code-block-writer.js:380:23)
    at CodeBlockWriter.writeIndividual (/Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/code-block-writer/dist/code-block-writer.js:317:26)
    at /Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/code-block-writer/dist/code-block-writer.js:311:29
    at Array.forEach (<anonymous>)
    at CodeBlockWriter._writeIndentingNewLines (/Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/code-block-writer/dist/code-block-writer.js:306:15)
    at CodeBlockWriter.write (/Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/code-block-writer/dist/code-block-writer.js:216:14)
    at StringStructurePrinter.printText (/Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/ts-simple-ast/dist/structurePrinters/common/StringStructurePrinter.js:12:20)
    at CommaNewLineSeparatedStructuresPrinter.printText (/Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/ts-simple-ast/dist/structurePrinters/formatting/CommaNewLineSeparatedStructuresPrinter.js:18:35)
    at ArrayLiteralExpression.insertElements (/Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/ts-simple-ast/dist/compiler/expression/array/ArrayLiteralExpression.js:56:26)
    at _loop_3 (/Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/@compodoc/compodoc/dist/index-cli.js:1334:32)
[16:47:27] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! seller-center@1.0.0 compodoc: `compodoc -p src/tsconfig.app.json -d ./deploy/documentation/dist/  --includes ./docs`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the seller-center@1.0.0 compodoc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/andy.olarte/.npm/_logs/2018-07-09T21_47_27_766Z-debug.log

**Comment by vogloblinsky** [comment]
Can i have the source code of the file where it breaks ?

**Comment by andyOlarte514** [comment]
this source code



import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
// Local
import { RoutesConst } from '../../../../shared/util/routes.constants';
import { BillingComponent } from './billing-page/billing.component';


const routes: Routes = [
  {
    path: `${RoutesConst.sellerCenterUrls.billing}`,
    component: BillingComponent,
    data: { title: 'Facturación' }
  },
  {
    path: `${RoutesConst.sellerCenterUrlsInt.billingPayments}`,
    component: BillingComponent,
    data: { title: 'Facturación' }
  }
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
  providers: []
})
export class BillingRoutingModule {
}

**Comment by andyOlarte514** [comment]
17:21:27] parsing        : /Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/src/app/secure/seller-center/components/billing/billing.routing.ts
[17:21:27] Analysing routes definitions and clean them if necessary
Unhandled Rejection at: Promise {
  <rejected> Error: Could not find the node's symbol.
    at InvalidOperationError.BaseError [as constructor] (/Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/ts-simple-ast/dist/errors/BaseError.js:7:28)
    at new InvalidOperationError (/Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/ts-simple-ast/dist/errors/InvalidOperationError.js:8:28)
    at Object.throwIfNullOrUndefined (/Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/ts-simple-ast/dist/errors/helpers.js:96:15)
    at Identifier.Node.getSymbolOrThrow (/Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/ts-simple-ast/dist/compiler/common/Node.js:131:23)
    at RouterParserUtil.cleanFileDynamics (/Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/@compodoc/compodoc/dist/index-cli.js:1374:18)
    at Dependencies.getSourceFileDecorators (/Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/@compodoc/compodoc/dist/index-cli.js:5812:45)
    at /Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/@compodoc/compodoc/dist/index-cli.js:5638:27
    at Array.map (<anonymous>)
    at Dependencies.getDependencies (/Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/@compodoc/compodoc/dist/index-cli.js:5632:21)
    at CliApplication.Application.getDependenciesData (/Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/@compodoc/compodoc/dist/index-cli.js:7309:40) } reason: Error: Could not find the node's symbol.
    at InvalidOperationError.BaseError [as constructor] (/Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/ts-simple-ast/dist/errors/BaseError.js:7:28)
    at new InvalidOperationError (/Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/ts-simple-ast/dist/errors/InvalidOperationError.js:8:28)
    at Object.throwIfNullOrUndefined (/Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/ts-simple-ast/dist/errors/helpers.js:96:15)
    at Identifier.Node.getSymbolOrThrow (/Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/ts-simple-ast/dist/compiler/common/Node.js:131:23)
    at RouterParserUtil.cleanFileDynamics (/Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/@compodoc/compodoc/dist/index-cli.js:1374:18)
    at Dependencies.getSourceFileDecorators (/Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/@compodoc/compodoc/dist/index-cli.js:5812:45)
    at /Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/@compodoc/compodoc/dist/index-cli.js:5638:27
    at Array.map (<anonymous>)
    at Dependencies.getDependencies (/Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/@compodoc/compodoc/dist/index-cli.js:5632:21)
    at CliApplication.Application.getDependenciesData (/Users/andy.olarte/Documents/Exito/ComercioDirecto.SellerCenter.OrdersFront/node_modules/@compodoc/compodoc/dist/index-cli.js:7309:40)
[17:21:30] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! seller-center@1.0.0 compodoc: `compodoc -p src/tsconfig.app.json -n "Seller Center documentation"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the seller-center@1.0.0 compodoc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/andy.olarte/.npm/_logs/2018-07-26T22_21_30_468Z-debug.log
