### ISSUE TITLE
[BUG] Routes : Cannot read property 'depth' of undefined

### ISSUE THREAD

**Issue by anthonybriand** [compodoc/compodoc#616]
##### **Overview of the issue**

Error when generating application routing documentation

Stack :
```bash
[12:50:19] Process page   : routes
Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'depth' of undefined
    at Object.eval [as main] (eval at createFunctionContext (/usr/local/share/.config/yarn/global/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:6:93)
    at main (/usr/local/share/.config/yarn/global/node_modules/handlebars/dist/cjs/handlebars/runtime.js:175:32)
    at Object.ret (/usr/local/share/.config/yarn/global/node_modules/handlebars/dist/cjs/handlebars/runtime.js:178:12)
    at Object.ret [as routes] (/usr/local/share/.config/yarn/global/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:526:21)
    at Object.invokePartialWrapper [as invokePartial] (/usr/local/share/.config/yarn/global/node_modules/handlebars/dist/cjs/handlebars/runtime.js:72:46)
    at eval (eval at createFunctionContext (/usr/local/share/.config/yarn/global/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:31)
    at Object.prog [as fn] (/usr/local/share/.config/yarn/global/node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
    at CompareHelper.helperFunc (/usr/local/share/.config/yarn/global/node_modules/@compodoc/compodoc/dist/index-cli.js:155:24)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/@compodoc/compodoc/dist/index-cli.js:2857:38)
    at Object.eval [as main] (eval at createFunctionContext (/usr/local/share/.config/yarn/global/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:48:65) } reason: TypeError: Cannot read property 'depth' of undefined
    at Object.eval [as main] (eval at createFunctionContext (/usr/local/share/.config/yarn/global/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:6:93)
    at main (/usr/local/share/.config/yarn/global/node_modules/handlebars/dist/cjs/handlebars/runtime.js:175:32)
    at Object.ret (/usr/local/share/.config/yarn/global/node_modules/handlebars/dist/cjs/handlebars/runtime.js:178:12)
    at Object.ret [as routes] (/usr/local/share/.config/yarn/global/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:526:21)
    at Object.invokePartialWrapper [as invokePartial] (/usr/local/share/.config/yarn/global/node_modules/handlebars/dist/cjs/handlebars/runtime.js:72:46)
    at eval (eval at createFunctionContext (/usr/local/share/.config/yarn/global/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:31)
    at Object.prog [as fn] (/usr/local/share/.config/yarn/global/node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
    at CompareHelper.helperFunc (/usr/local/share/.config/yarn/global/node_modules/@compodoc/compodoc/dist/index-cli.js:155:24)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/@compodoc/compodoc/dist/index-cli.js:2857:38)
    at Object.eval [as main] (eval at createFunctionContext (/usr/local/share/.config/yarn/global/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:48:65)
[10:32:44] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
```

##### **Operating System, Node.js, npm, compodoc version(s)**

- **OS**
- - Ubuntu Docker Image
- **Node.JS**
- - 9.7.1
- **NPM**
- - 5.6.0
- **Yarn**
- - 1.9.4
- **Compodoc**
- - 1.1.3

##### **Angular configuration, a `package.json` file in the root folder**

I can not reveal the package.json (work related). I am using a CLI-generated workspace, with library support

##### **Compodoc installed globally or locally ?**

Globally with yarn

##### **If possible sourcecode of the file where it breaks**

At the route page processing

```
import {NgModule} from '@angular/core';
import {RouterModule, Routes} from '@angular/router';
import {HomeComponent} from './component/home/home.component';
import {LandingComponent, LoginComponent, BComponent} from '@naval-group/cpm-suite';

const routes: Routes = [
  {
    path: '',
    component: LandingComponent,
    children: [
      {
        path: '',
        pathMatch: 'full',
        component: LoginComponent
      },
      {
        path: 'b',
        pathMatch: 'full',
        component: BComponent
      }
    ]
  },
  {
    path: 'home',
    component: HomeComponent,
    children: [
      {
        path: '',
        pathMatch: 'full',
        redirectTo: 'a-list'
      },
      {
        path: 'b/:id',
        loadChildren: './module/b/b.module#BModule'
      },
      {
        path: 'a-list',
        loadChildren: './module/a/a.module#AModule'
      },
      {
        path: 'c',
        loadChildren: './module/c/c.module#CModule'
      },
      {
        path: 'd',
        loadChildren: './module/d-wrapper/d-wrapper.module#DWrapperModule'
      }
    ]
  }
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
```

##### **If possible your terminal logs before the error**

I can only give you these parts
```
Typescript version : 2.8.3

Node.js version : v9.11.2

Operating system : Linux 4.9
...
[13:03:36] -------------------
[13:03:36] Project statistics 
[13:03:36] - files      : 1124
[13:03:36] - module     : 19
[13:03:36] - component  : 93
[13:03:36] - directive  : 3
[13:03:36] - injectable : 20
[13:03:36] - injector   : 1
[13:03:36] - pipe       : 1
[13:03:36] - class      : 33
[13:03:36] - interface  : 36
[13:03:36] - route      : 16
[13:03:36] -------------------
...
[13:03:41] Process page   : dependencies
[13:03:41] Process page   : enumerations
[13:03:41] Process page   : functions
[13:03:41] Process page   : index
[13:03:41] Process page   : modules
[13:03:41] Process page   : overview
[13:03:41] Process page   : routes
```

##### **Motivation for or Use Case**

Can't generate a documentation

##### **Reproduce the error**

It fails even with an empty or full routing module

##### **Related issues**

I searched but I can't find anything that approaches

**Comment by mscud** [comment]
same issue here :(
only solution is to use version 1.0.1 so far

**Comment by roopeshreddy** [comment]
Same issue. After downgrading to 1.0.1 worked for me!

**Comment by gund** [comment]
Same here, the last version that still generates docs is v1.1.3 for me.

**Comment by EdgarOkode** [comment]
Same here. The issue just appears if compodoc is executed with `--disableCoverage` parameter.
