### ISSUE TITLE
[BUG]TypeError: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by lichangfeng** [compodoc/compodoc#637]
##### **Overview of the issue**

When I run: compodoc ./src -d ./compodoc -p tsconfig.json --theme stripe,  I get an error.

##### **Operating System, Node.js, npm, compodoc version(s)**
win10 x64
node v10.8.0
npm 6.2.0
compodoc 1.1.5

##### **Angular configuration, a `package.json` file in the root folder**

`{
  "name": "ngx-digi-course-front",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --proxy-config api.config.test.json --host 10.0.3.12 -o --port=4212",
    "start-lxf": "ng serve --proxy-config api.config.test.json --host 10.0.3.9 -o --port=4213",
    "start-lcf": "ng serve --proxy-config api.config.test.json --host 10.0.3.11 -o --port=4213",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "compodoc:build": "compodoc ./src -d ./compodoc -p tsconfig.json --theme stripe",
    "deploy": "ng build && deploy.bat",
    "link-tsing-ppt": "npm link tsing-ppt"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.1.0",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/elements": "^6.0.6",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/router": "^6.1.0",
    "core-js": "^2.5.4",
    "rxjs": "^6.0.0",
    "rxjs-compat": "^6.2.2",
    "zone.js": "~0.8.26",
    "bootstrap": "^3.3.7",
    "font-awesome": "^4.7.0",
    "jquery": "^3.2.1",
    "ng-zorro-antd": "^1.3.0",
    "ngx-ueditor": "^2.1.0",
    "ngx-umeditor": "^2.0.0",
    "ngx-webuploader": "^1.0.2",
    "ngx-treeview": "^6.0.0",
    "ts-md5": "1.2.2",
    "tsing-ppt": "latest",
    "document-register-element": "^1.7.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.7.0",
    "@angular/cli": "~6.1.3",
    "@angular/compiler-cli": "^6.1.0",
    "@angular/language-service": "^6.1.0",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "@types/jquery": "^3.2.18",
    "@compodoc/compodoc": "^1.1.5",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2"
  }
}
`

##### **Compodoc installed globally or locally ?**

locally 

##### **If possible sourcecode of the file where it breaks**

1. By tracing your code, I find the error occured in FrameworkDependencies, line 38
this.program = ts.createProgram(
            this.files,
            transpileOptions,
            compilerHost(transpileOptions)
        );
There is no error before this method, and the error occured after this method.

2.when I remove a file in assets dir, it works.

##### **If possible your terminal logs before the error**
[15:32:56] package.json file found
[15:32:56] Processing package.json dependencies
[15:32:56] Searching README.md, CHANGELOG.md, CONTRIBUTING.md, LICENSE.md, TODO.md files
[15:32:56] README.md file found
[15:32:56] Error during D:\ztyspacegitee\client\ts_course_client\ngx-digi-course-front1\CHANGELOG read
[15:32:56] Continuing without CHANGELOG.md file
[15:32:56] Error during D:\ztyspacegitee\client\ts_course_client\ngx-digi-course-front1\CONTRIBUTING read
[15:32:56] Continuing without CONTRIBUTING.md file
[15:32:56] Error during D:\ztyspacegitee\client\ts_course_client\ngx-digi-course-front1\LICENSE read
[15:32:56] Continuing without LICENSE.md file
[15:32:56] Error during D:\ztyspacegitee\client\ts_course_client\ngx-digi-course-front1\TODO read
[15:32:56] Continuing without TODO.md file
[15:32:56] Get dependencies data
Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'kind' of undefined
    at isObjectOrObjectArrayTypeReference (D:\ztyspacegitee\client\ts_course_client\ngx-digi-course-front1\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:20709:34)
    at parseNestedTypeLiteral (D:\ztyspacegitee\client\ts_course_client\ngx-digi-course-front1\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:20748:43)
    at parseParameterOrPropertyTag (D:\ztyspacegitee\client\ts_course_client\ngx-digi-course-front1\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:20733:85)
    at parseTag (D:\ztyspacegitee\client\ts_course_client\ngx-digi-course-front1\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:20572:40)
    at D:\ztyspacegitee\client\ts_course_client\ngx-digi-course-front1\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:20447:44
    at Object.scanRange (D:\ztyspacegitee\client\ts_course_client\ngx-digi-course-front1\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:8611:26)
    at parseJSDocCommentWorker (D:\ztyspacegitee\client\ts_course_client\ngx-digi-course-front1\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:20419:25)
    at Object.parseJSDocComment (D:\ztyspacegitee\client\ts_course_client\ngx-digi-course-front1\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:20373:31)
    at addJSDocComment (D:\ztyspacegitee\client\ts_course_client\ngx-digi-course-front1\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:15579:68)
    at createNodeWithJSDoc (D:\ztyspacegitee\client\ts_course_client\ngx-digi-course-front1\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:15906:17) } reason: TypeError: Cannot read property 'kind' of undefined
    at isObjectOrObjectArrayTypeReference (D:\ztyspacegitee\client\ts_course_client\ngx-digi-course-front1\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:20709:34)
    at parseNestedTypeLiteral (D:\ztyspacegitee\client\ts_course_client\ngx-digi-course-front1\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:20748:43)
    at parseParameterOrPropertyTag (D:\ztyspacegitee\client\ts_course_client\ngx-digi-course-front1\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:20733:85)
    at parseTag (D:\ztyspacegitee\client\ts_course_client\ngx-digi-course-front1\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:20572:40)
    at D:\ztyspacegitee\client\ts_course_client\ngx-digi-course-front1\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:20447:44
    at Object.scanRange (D:\ztyspacegitee\client\ts_course_client\ngx-digi-course-front1\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:8611:26)
    at parseJSDocCommentWorker (D:\ztyspacegitee\client\ts_course_client\ngx-digi-course-front1\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:20419:25)
    at Object.parseJSDocComment (D:\ztyspacegitee\client\ts_course_client\ngx-digi-course-front1\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:20373:31)
    at addJSDocComment (D:\ztyspacegitee\client\ts_course_client\ngx-digi-course-front1\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:15579:68)
    at createNodeWithJSDoc (D:\ztyspacegitee\client\ts_course_client\ngx-digi-course-front1\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:15906:17)

##### **Motivation for or Use Case**

cannot generate a doc.

**Comment by jmlopez-rod** [comment]
I also got a similar error. Maybe different typescript versions? Here is my stack trace:

```
Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'kind' of undefined
    at Object.isArrayLiteralExpression (./node_modules/ts-simple-ast/node_modules/typescript/lib/typescript.js:13389:21)
    at SymbolHelper.parseSymbols (./node_modules/@compodoc/compodoc/dist/index-cli.js:5245:20)
    at ./node_modules/@compodoc/compodoc/dist/index-cli.js:5283:62
    at Array.map (<anonymous>)
    at SymbolHelper.getSymbolDeps (./node_modules/@compodoc/compodoc/dist/index-cli.js:5283:30)
    at ComponentHelper.getComponentTemplate (./node_modules/@compodoc/compodoc/dist/index-cli.js:5444:35)
    at ComponentDepFactory.create (./node_modules/@compodoc/compodoc/dist/index-cli.js:5884:35)
    at visitDecorator (./node_modules/@compodoc/compodoc/dist/index-cli.js:6344:116)
    at Array.forEach (<anonymous>)
    at parseNode (./node_modules/@compodoc/compodoc/dist/index-cli.js:6456:64) } reason: TypeError: Cannot read property 'kind' of undefined
    at Object.isArrayLiteralExpression (./node_modules/ts-simple-ast/node_modules/typescript/lib/typescript.js:13389:21)
    at SymbolHelper.parseSymbols (./node_modules/@compodoc/compodoc/dist/index-cli.js:5245:20)
    at ./node_modules/@compodoc/compodoc/dist/index-cli.js:5283:62
    at Array.map (<anonymous>)
    at SymbolHelper.getSymbolDeps (./node_modules/@compodoc/compodoc/dist/index-cli.js:5283:30)
    at ComponentHelper.getComponentTemplate (./node_modules/@compodoc/compodoc/dist/index-cli.js:5444:35)
    at ComponentDepFactory.create (./node_modules/@compodoc/compodoc/dist/index-cli.js:5884:35)
    at visitDecorator (./node_modules/@compodoc/compodoc/dist/index-cli.js:6344:116)
    at Array.forEach (<anonymous>)
    at parseNode (./node_modules/@compodoc/compodoc/dist/index-cli.js:6456:64)
[22:50:29] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
```

Versions:

```
$ compodoc -V
1.1.5
$ tsc -v
Version 2.9.2
```

**Comment by lichangfeng** [comment]
@jmlopez-rod I think the ts.createProgram would skip the assets files，maybe

**Comment by jmlopez-rod** [comment]
So I started commenting out some code on the last file it mentioned it was parsing:

```
23:19:20] parsing        : ./src/main/iconPicker/IconPicker.component.ts
[23:19:20] found          : IIcon
[23:19:20] found          : IResponse
Unhandled Rejection at: Promise {

```

And turns out that the culprit is this:

```
@Component({
  selector: 'icon-picker',
  template,
})
```

`template` is imported from

```
import * as template from './IconPicker.tpl.html';
```

and I have a declaration file that states that the contents of such html files are strings

```
declare module '*.tpl.html' {
  const content: string;
  export = content;
}
```

The weird thing is that if I simply define

```
const template = `hello`;
```

Then things work.  So this tells me that my declaration file is not being loaded? Otherwise if I declare

```
@Component({
  selector: 'icon-picker',
  template: template,
})
```

Then I get no error.

**Comment by vogloblinsky** [comment]
@jmlopez-rod Thanks for the code example, it will help fixing this sytax use case

**Comment by vogloblinsky** [comment]
Closed by https://github.com/compodoc/compodoc/commit/b31604c70e7d6d93d9c555eaab9368e94def055c
