### ISSUE TITLE
Unhandled Rejection at: Promise {   <rejected> { SyntaxError: JSON5: invalid character '}'

### ISSUE THREAD

**Issue by phutaneVinayak** [compodoc/compodoc#657]
##### **Overview of the issue**
Unhandled Rejection at: Promise {
  <rejected> { SyntaxError: JSON5: invalid character '}' at 1:146

 i check my all component there syntax are all correct. i check twice and also angular cli tools doesn't reporting anything but compodoc is reporting this error

after build my application this issue getting started before it working smoothly 

##### **Operating System, Node.js, npm, compodoc version(s)**
compodoc -v: 1.1.5
typescript  -v: 2.9.1
node.js -v: 8.11.3
OS: windows 8.1

##### **Angular configuration, a `package.json` file in the root folder**
"scripts": {

    "compodoc": "./node_modules/.bin/compodoc -p src/tsconfig.app.json -w -s --theme Postmark"
  },
"dependencies": {
    "@agm/core": "^1.0.0-beta.3",
    "@angular/animations": "^6.1.6",
    "@angular/cdk": "^6.4.7",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/material": "^6.4.7",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/router": "^6.0.3",
    "@types/lodash": "^4.14.116",
    "core-js": "^2.5.4",
    "hammerjs": "^2.0.8",
    "lodash": "^4.17.10",
    "ngx-infinite-scroll": "^6.0.1",
    "rxjs": "^6.0.0",
    "rxjs-compat": "^6.3.2",
    "tassign": "^1.0.0",
    "zone.js": "^0.8.26" 
}
"devDependencies": {
    "@angular/compiler-cli": "^6.0.3",
    "@angular-devkit/build-angular": "~0.6.8",
    "typescript": "~2.7.2",
    "@angular/cli": "~6.0.8",
    "@angular/language-service": "^6.0.3",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1"
  }

##### **Compodoc installed globally or locally ?**
global

##### **If possible sourcecode of the file where it breaks**

yes
##### **If possible your terminal logs before the error**

Compodoc - 1.1.5

Typescript version : 2.9.1

Node.js version : v8.11.3

Operating system : Windows 8.1

[14:51:19] No configuration file found, switching to CLI flags.
[14:51:19] Using tsconfig file : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\tsconfig.app.json
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\browserslist
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\favicon.ico
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\index.html
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\karma.conf.js
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\main.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\polyfills.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\styles.css
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\test.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\theme.scss
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\tsconfig.app.json
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\tsconfig.spec.json
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\tslint.json
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\app-routing.module.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\app.component.css
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\app.component.html
[14:51:19] Ignoring       : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\app.component.spec.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\app.component.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\app.module.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\assets\.gitkeep
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\environments\environment.prod.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\assets\no-image.png
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\environments\environment.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\ng-components.module.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\common\common-routing-module-section.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\common\common.module.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\common\data-service.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\common\global-http-interceptor.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\login\login-routing.module.ts
[14:51:19] Ignoring       : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\login\login.module.spec.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\login\login.module.ts
[14:51:19] Ignoring       : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\common-service-module\service-module.module.spec.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\common-service-module\service-module.module.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\trip-routing.module.ts
[14:51:19] Ignoring       : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\trip.module.spec.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\trip.module.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\common\common-errors\app-error.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\common\common-errors\bad-input-request.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\common\common-errors\global-error-handler.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\common\common-errors\not-found-error.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\common\error-component\error-component.component.css
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\common\error-component\error-component.component.html
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\common\error-component\error-component.component.ts
[14:51:19] Ignoring       : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\common\error-component\error-component.component.spec.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\common\resolvers\get.resolver.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\models\accommodation.model.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\models\address.model.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\models\attachment.meta.model.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\models\attraction.model.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\models\author.model.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\models\blogs.model.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\models\category.model.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\models\distance.data.model.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\models\featured.image.model.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\models\fuel.station.model.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\models\image.meta.model.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\models\links.model.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\models\location.model.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\models\post.tag.model.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\models\sizes.model.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\models\trip.advisor.model.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\models\trip.advisor.review.model.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\models\trip.collection.model.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\models\trip.detail.model.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\models\trip.leg.model.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\models\trip.list.model.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\models\trip.model.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\models\trip.owner.model.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\models\way.point.model.ts
[14:51:19] Ignoring       : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\services\trip-list.service.spec.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\services\trip-list.service.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\components\trip\trip.component.css
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\components\trip\trip.component.html
[14:51:19] Ignoring       : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\components\trip\trip.component.spec.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\components\trip\trip.component.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\components\trip-details\trip-details.component.css
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\components\trip-details\trip-details.component.html
[14:51:19] Ignoring       : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\components\trip-details\trip-details.component.spec.ts
[14:51:19] Including      : E:\EasyRoads\EasyRoads Web App\easyroads-copy\src\app\trip\components\trip-details\trip-details.component.ts
[14:51:19] Searching package.json file
[14:51:19] package.json file found
[14:51:19] Processing package.json dependencies
[14:51:19] Searching README.md, CHANGELOG.md, CONTRIBUTING.md, LICENSE.md, TODO.md files
[14:51:20] README.md file found
[14:51:20] Error during E:\EasyRoads\EasyRoads Web App\easyroads-copy\CHANGELOG read
[14:51:20] Continuing without CHANGELOG.md file
[14:51:20] Error during E:\EasyRoads\EasyRoads Web App\easyroads-copy\CONTRIBUTING read
[14:51:20] Continuing without CONTRIBUTING.md file
[14:51:20] Error during E:\EasyRoads\EasyRoads Web App\easyroads-copy\LICENSE read
[14:51:20] Continuing without LICENSE.md file
[14:51:20] Error during E:\EasyRoads\EasyRoads Web App\easyroads-copy\TODO read
[14:51:20] Continuing without TODO.md file
[14:51:20] Get dependencies data
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/main.ts
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/polyfills.ts
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/test.ts
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/app-routing.module.ts
[14:51:20] Analysing routes definitions and clean them if necessary
[14:51:20] found          : AppRoutingModule
[14:51:20]                : - imports:
[14:51:20]                :     - RouterModule
[14:51:20]                : - exports:
[14:51:20]                :     - RouterModule
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/app.component.ts
[14:51:20] ignore         : AppComponent
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/app.module.ts
[14:51:20] found          : AppModule
[14:51:20]                : - imports:
[14:51:20]                :     - BrowserModule
[14:51:20]                :     - HttpClientModule
[14:51:20]                :     - CommonServiceModule
[14:51:20]                :     - AppRoutingModule
[14:51:20]                :     - BrowserAnimationsModule
[14:51:20]                :     - NgComponentGroupModule
[14:51:20]                : - declarations:
[14:51:20]                :     - AppComponent
[14:51:20]                : - providers:
[14:51:20]                :     - {
    provide: ErrorHandler, useClass: GlobalErrorHandler
}
[14:51:20]                :     - GlobalHttpInterceptor
[14:51:20]                : - bootstrap:
[14:51:20]                :     - AppComponent
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/environments/environment.prod.ts
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/environments/environment.ts
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/ng-components.module.ts
[14:51:20] found          : NgComponentGroupModule
[14:51:20]                : - exports:
[14:51:20]                :     - MatButtonModule
[14:51:20]                :     - MatCardModule
[14:51:20]                :     - MatGridListModule
[14:51:20]                :     - MatListModule
[14:51:20]                :     - MatTabsModule
[14:51:20]                :     - MatProgressSpinnerModule
[14:51:20]                :     - MatExpansionModule
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/common/common-routing-module-section.ts
[14:51:20] Analysing routes definitions and clean them if necessary
[14:51:20] found          : CommonRoutingModuleSection
[14:51:20]                : - imports:
[14:51:20]                :     - RouterModule
[14:51:20]                : - exports:
[14:51:20]                :     - RouterModule
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/common/common.module.ts
[14:51:20] found          : CommonModuleSection
[14:51:20]                : - imports:
[14:51:20]                :     - CommonModule
[14:51:20]                :     - CommonRoutingModuleSection
[14:51:20]                : - declarations:
[14:51:20]                :     - ErrorComponent
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/common/data-service.ts
[14:51:20] found          : DataService
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/common/global-http-interceptor.ts
[14:51:20] found          : GlobalHttpInterceptor
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/login/login-routing.module.ts
[14:51:20] Analysing routes definitions and clean them if necessary
[14:51:20] found          : LoginRoutingModule
[14:51:20]                : - imports:
[14:51:20]                :     - RouterModule
[14:51:20]                : - exports:
[14:51:20]                :     - RouterModule
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/login/login.module.ts
[14:51:20] found          : LoginModule
[14:51:20]                : - imports:
[14:51:20]                :     - CommonModule
[14:51:20]                :     - LoginRoutingModule
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/common-service-module/service-module.module.ts
[14:51:20] found          : CommonServiceModule
[14:51:20]                : - imports:
[14:51:20]                :     - CommonModule
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/trip/trip-routing.module.ts
[14:51:20] Analysing routes definitions and clean them if necessary
[14:51:20] Routes parsing error, maybe a trailing comma or an external variable, trying to fix that later after sources scanning.
[14:51:20] found          : TripRoutingModule
[14:51:20]                : - imports:
[14:51:20]                :     - RouterModule
[14:51:20]                : - exports:
[14:51:20]                :     - RouterModule
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/trip/trip.module.ts
[14:51:20] found          : TripModule
[14:51:20]                : - imports:
[14:51:20]                :     - CommonModule
[14:51:20]                :     - TripRoutingModule
[14:51:20]                :     - NgComponentGroupModule
[14:51:20]                :     - InfiniteScrollModule
[14:51:20]                :     - AgmCoreModule
[14:51:20]                : - declarations:
[14:51:20]                :     - TripDetailsComponent
[14:51:20]                :     - TripComponent
[14:51:20]                : - providers:
[14:51:20]                :     - TripListService
[14:51:20]                :     - GetResolver
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/common/common-errors/app-error.ts
[14:51:20] found          : AppError
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/common/common-errors/bad-input-request.ts
[14:51:20] found          : BadInputRequest
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/common/common-errors/global-error-handler.ts
[14:51:20] found          : GlobalErrorHandler
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/common/common-errors/not-found-error.ts
[14:51:20] found          : NotFoundError
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/common/error-component/error-component.component.ts
[14:51:20] found          : ErrorComponent
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/common/resolvers/get.resolver.ts
[14:51:20] found          : GetResolver
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/trip/models/accommodation.model.ts
[14:51:20] found          : AccommodationModel
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/trip/models/address.model.ts
[14:51:20] found          : AddressModel
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/trip/models/attachment.meta.model.ts
[14:51:20] found          : AttachmentMetaModel
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/trip/models/attraction.model.ts
[14:51:20] found          : AttractionModel
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/trip/models/author.model.ts
[14:51:20] found          : AuthorModel
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/trip/models/blogs.model.ts
[14:51:20] found          : BlogDataModel
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/trip/models/category.model.ts
[14:51:20] found          : CategoryModel
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/trip/models/distance.data.model.ts
[14:51:20] found          : DistanceDataModel
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/trip/models/featured.image.model.ts
[14:51:20] found          : FeaturedImageModel
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/trip/models/fuel.station.model.ts
[14:51:20] found          : FuelStationModel
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/trip/models/image.meta.model.ts
[14:51:20] found          : ImageMetaModel
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/trip/models/links.model.ts
[14:51:20] found          : LinksModel
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/trip/models/location.model.ts
[14:51:20] found          : LocationModel
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/trip/models/post.tag.model.ts
[14:51:20] found          : PostTagModel
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/trip/models/sizes.model.ts
[14:51:20] found          : SizesModel
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/trip/models/trip.advisor.model.ts
[14:51:20] found          : TripAdvisorModel
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/trip/models/trip.advisor.review.model.ts
[14:51:20] found          : TripAdvisorReviewModel
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/trip/models/trip.collection.model.ts
[14:51:20] found          : TripCollectionModel
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/trip/models/trip.detail.model.ts
[14:51:20] found          : TripDetailModel
[14:51:20] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/trip/models/trip.leg.model.ts
[14:51:20] found          : TripLegModel
[14:51:21] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/trip/models/trip.list.model.ts
[14:51:21] found          : TripList
[14:51:21] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/trip/models/trip.model.ts
[14:51:21] found          : Trip
[14:51:21] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/trip/models/trip.owner.model.ts
[14:51:21] found          : TripOwnerDetailModel
[14:51:21] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/trip/models/way.point.model.ts
[14:51:21] found          : WayPointModel
[14:51:21] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/trip/services/trip-list.service.ts
[14:51:21] found          : TripListService
[14:51:21] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/trip/components/trip/trip.component.ts
[14:51:21] found          : TripComponent
[14:51:21] parsing        : E:/EasyRoads/EasyRoads Web App/easyroads-copy/src/app/trip/components/trip-details/trip-details.component.ts
[14:51:21] found          : TripDetailsComponent
Unhandled Rejection at: Promise {
  <rejected> { SyntaxError: JSON5: invalid character '}' at 1:146
    at syntaxError (C:\Users\Vinayak\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1083:17)
    at invalidChar (C:\Users\Vinayak\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1028:12)
    at Object.afterPropertyName (C:\Users\Vinayak\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:640:15)
    at Object.default (C:\Users\Vinayak\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:146:37)
    at lex (C:\Users\Vinayak\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:78:42)
    at Object.parse (C:\Users\Vinayak\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:25:17)
    at loopInsideModule (C:\Users\Vinayak\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:1073:52)
    at loopRoutesParser (C:\Users\Vinayak\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:1106:29)
    at loopRoutesParser (C:\Users\Vinayak\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:1111:21)
    at RouterParserUtil.constructRoutesTree (C:\Users\Vinayak\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:1115:9) lineNumber: 1, columnNumber: 146 } } reason: { SyntaxError: JSON5: invalid character '}' at 1:146
    at syntaxError (C:\Users\Vinayak\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1083:17)
    at invalidChar (C:\Users\Vinayak\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1028:12)
    at Object.afterPropertyName (C:\Users\Vinayak\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:640:15)
    at Object.default (C:\Users\Vinayak\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:146:37)
    at lex (C:\Users\Vinayak\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:78:42)
    at Object.parse (C:\Users\Vinayak\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:25:17)
    at loopInsideModule (C:\Users\Vinayak\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:1073:52)
    at loopRoutesParser (C:\Users\Vinayak\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:1106:29)
    at loopRoutesParser (C:\Users\Vinayak\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:1111:21)
    at RouterParserUtil.constructRoutesTree (C:\Users\Vinayak\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:1115:9) lineNumber: 1, columnNumber: 146 }
[14:51:21] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)

##### **Motivation for or Use Case**

i try all other steps after i am pushing this as new issue. i don't know why it happen i am trying to find out why but it is not logging out anything . i check my all component there syntax are all correct. i check twice and also angular cli tools doesn't reporting anything but compodoc is reporting this error
##### **Related issues**

no

**Comment by phutaneVinayak** [comment]
i update my compodoc and set it from global to local . and i remove -w from my npm run script .it's start working so i am closing this issue. i don't know how it solve it just work for me now.  
i am investigating further more let see what outcome is coming . 

compodoc team it awesome tools. great job guys
