### ISSUE TITLE
[BUG] Could not generate doc with typed Object as 'data' in Angular Routes

### ISSUE THREAD

**Issue by lutzvahl** [compodoc/compodoc#661]
##### **Angular configuration, a `package.json` file in the root folder**

"dependencies": {
    "@angular/common": "^6.1.6",
    "@angular/compiler": "^6.1.6",
    "@angular/core": "^6.1.6",
    "@angular/forms": "^6.1.6",
    "@angular/http": "^6.1.6",
    "@angular/platform-browser": "^6.1.6",
    "@angular/platform-browser-dynamic": "^6.1.6",
    "@angular/router": "^6.1.6",
    "@ng-bootstrap/ng-bootstrap": "^3.2.0",
    "core-js": "^2.5.7",
    "fingerprintjs2": "^1.8.1",
    "font-awesome": "^4.7.0",
    "linqts": "^1.12.0",
    "moment": "^2.22.2",
    "ng2-charts": "^1.6.0",
    "ngx-bootstrap": "^3.0.1",
    "object-assign": "^4.1.1",
    "rxjs": "^6.3.1",
    "stacktrace-js": "^2.0.0",
    "typescript": "^2.9.2",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "^2.3.0",
    "@angular-devkit/architect": "^0.7.5",
    "@angular-devkit/build-angular": "^0.7.5",
    "@angular-devkit/core": "^0.7.5",
    "@angular/cli": "^6.1.5",
    "@angular/compiler-cli": "^6.1.6",
    "@compodoc/compodoc": "^1.1.5",
    "@types/angular": "^1.5.16",
    "@types/angular-resource": "^1.5.6",
    "@types/angular-route": "^1.3.2",
    "@types/angular-sanitize": "^1.3.3",
    "@types/hammerjs": "^2.0.35",
    "@types/uglify-js": "^2.6.28",
    "codelyzer": "^4.4.4",
    "intl": "^1.2.5",
    "less": "^2.7.2",
    "ts-node": "^3.0.2",
    "tslib": "^1.9.3",
    "tslint": "^5.11.0",
    "typedoc": "^0.12.0",
    "webpack-bundle-analyzer": "^2.13.1",
    "webpack-sources": "^1.2.0"
  },
  "engines": {
    "node": ">= 8",
    "npm": ">= 5"
  }

##### **Compodoc installed globally or locally ?**

locally

##### **If possible sourcecode of the file where it breaks**

const routes: Routes = [
  {
    path: "", component: MyComp, children: [
      { path: 'details/:id', redirectTo: '/details/:id/DETAILS', pathMatch: 'full' },
      {
        path: "details/:id/:detailsSection", loadChildren: "../lazy/xx-yy-details.module#DetailsModule"
        , data: new LazyRoutingOptions({ preload: true, delay: 2500 })
      }
    ]
  }
];

With the following code the generation is working:

const routes: Routes = [
  {
    path: "", component: MyComp, children: [
      { path: 'details/:id', redirectTo: '/details/:id/DETAILS', pathMatch: 'full' },
      {
        path: "details/:id/:detailsSection", loadChildren: "../lazy/xx-yy-details.module#DetailsModule"
        , data: { preload: true, delay: 2500 }
      }
    ]
  }
];

##### **If possible your terminal logs before the error**

> Unhandled Rejection at: Promise {
  <rejected> { SyntaxError: JSON5: invalid character '(' at 1:285
    at syntaxError (C:\XXX\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1083:17)
    at invalidChar (C:\XXX\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1028:12)
    at Object.afterPropertyValue (C:\XXX\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:654:15)
    at Object.default (C:\XXX\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:146:37)
    at lex (C:\XXX\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:78:42)
    at Object.parse (C:\XXX\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:25:17)
    at loopInsideModule (C:\XXX\node_modules\@compodoc\compodoc\dist\index-cli.js:1073:52)
    at loopRoutesParser (C:\XXX\node_modules\@compodoc\compodoc\dist\index-cli.js:1106:29)
    at loopRoutesParser (C:\XXX\node_modules\@compodoc\compodoc\dist\index-cli.js:1111:21)
    at RouterParserUtil.constructRoutesTree (C:\XXX\node_modules\@compodoc\compodoc\dist\index-cli.js:1115:9) lineNumber: 1, columnNumber: 285 } } reason: { SyntaxError: JSON5: invalid character '(' at 1:285
    at syntaxError (C:\XXX\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1083:17)
    at invalidChar (C:\XXX\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1028:12)
    at Object.afterPropertyValue (C:\XXX\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:654:15)
    at Object.default (C:\XXX\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:146:37)
    at lex (C:\XXX\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:78:42)
    at Object.parse (C:\XXX\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:25:17)
    at loopInsideModule (C:\XXX\node_modules\@compodoc\compodoc\dist\index-cli.js:1073:52)
    at loopRoutesParser (C:\XXX\node_modules\@compodoc\compodoc\dist\index-cli.js:1106:29)
    at loopRoutesParser (C:\XXX\node_modules\@compodoc\compodoc\dist\index-cli.js:1111:21)
    at RouterParserUtil.constructRoutesTree (C:\XXX\node_modules\@compodoc\compodoc\dist\index-cli.js:1115:9) lineNumber: 1, columnNumber: 285 }
[13:30:46] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
npm ERR! code ELIFECYCLE
npm ERR! errno 1

##### **Motivation for or Use Case**

Type security of lazy loading options

##### **Related issues**

#404 and Routing Issues https://github.com/compodoc/compodoc/projects/3

**Comment by bartios** [comment]
looks like #525 to me

**Comment by thatsmeta** [comment]
Please fix this...
