### ISSUE TITLE
[BUG] SyntaxError: JSON5: invalid character '.' at 1:41

### ISSUE THREAD

**Issue by austinthedeveloper** [compodoc/compodoc#663]
##### **Overview of the issue**
When running this on my project, the error `SyntaxError: JSON5: invalid character '.' at 1:41` keeps showing up at the end and throws an error. Looking at the logs, it seems that it has a problem with my routes shown below.

There are a few things about my code that I've checked:

- This app lazy-loads modules in the routes. app.routing shows how login is used
- fromComponents is an index.ts collection of components. I already removed it while testing and the same error happened
- I thought trailing commas were the issue. I removed them and it did not fix it.
- No lint errors using `ng lint`

```
// Only warnings/errors when building are about routes
parsing        : /PATH/src/app/modules/search/search-routing.module.ts
[09:17:10] Analysing routes definitions and clean them if necessary
[09:17:12] Routes parsing error, maybe a trailing comma or an external variable, trying to fix that later after sources scanning.
```

```
// LOGIN ROUTE
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import * as fromContainers from './containers';

const routes: Routes = [
    {
        path: '',
        component: fromContainers.LoginComponent,
    },
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})
export class DashboardRoutingModule { }
```
```
// APP ROUTE
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { CustomPreload } from './app-preload.strategy';

const routes: Routes = [
    { path: '', pathMatch: 'full', redirectTo: 'dashboard' },    
     {
        path: 'login',
        loadChildren: './modules/login/login.module#LoginModule',
    },
];

@NgModule({
    providers: [CustomPreload],
    imports: [
        RouterModule.forRoot(routes, { preloadingStrategy: CustomPreload }),
    ],
    exports: [RouterModule],
})
export class AppRoutingModule {}
```
```
// tsconfig.app.json
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "module": "es2015",
    "types": []
  },
  "exclude": [
    "src/test.ts",
    "**/*.spec.ts"
  ]
}
```

##### **Operating System, Node.js, npm, compodoc version(s)**
- Compodoc: ^1.1.5
- MacOs
- Node: 10.11.0
- Npm: 6.4.1
- Angular: 6+

##### **Angular configuration, a `package.json` file in the root folder**
```
// package.json 
scripts: {
  "compodoc": "compodoc -p src/tsconfig.app.json"
},
"dependencies": {
        "@angular/animations": "^6.1.8",
        "@angular/cdk": "^6.4.6",
        "@angular/common": "^6.1.8",
        "@angular/compiler": "^6.1.8",
        "@angular/core": "^6.1.8",
        "@angular/forms": "^6.1.8",
        "@angular/http": "^6.1.8",
        "@angular/material": "^6.4.6",
        "@angular/platform-browser": "^6.1.8",
        "@angular/platform-browser-dynamic": "^6.1.8",
        "@angular/router": "^6.1.8",
        ...PACKAGES
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "~0.6.8",
        "@angular/cli": "^6.2.3",
        "@angular/compiler-cli": "^6.1.8",
        "@angular/language-service": "^6.1.8",
        "@compodoc/compodoc": "^1.1.5",
        "codelyzer": "~4.2.1",
        "jasmine-core": "~2.99.1",
        "jasmine-spec-reporter": "~4.2.1",
        "karma": "~1.7.1",
        "karma-chrome-launcher": "~2.2.0",
        "karma-coverage-istanbul-reporter": "^2.0.2",
        "karma-jasmine": "~1.1.1",
        "karma-jasmine-html-reporter": "^0.2.2",
        "protractor": "~5.3.0",
        "ts-node": "~5.0.1",
        "tslib": "^1.9.3",
        "tslint": "~5.9.1",
        "typedoc": "^0.12.0",
        "typescript": "~2.9.2"
    }
```

##### **Compodoc installed globally or locally ?**
Both. Currently using locally. Global also throws the same error

##### **If possible your terminal logs before the error**
```
// Error message when running the compodoc command
// PATH is just a find/replace I did
Unhandled Rejection at: Promise {
  <rejected> { SyntaxError: JSON5: invalid character '.' at 1:41
    at syntaxError (/PATH/@compodoc/compodoc/node_modules/json5/lib/parse.js:1083:17)
    at invalidChar (/PATH/@compodoc/compodoc/node_modules/json5/lib/parse.js:1028:12)
    at Object.afterPropertyValue (/PATH/@compodoc/compodoc/node_modules/json5/lib/parse.js:654:15)
    at Object.default (/PATH/@compodoc/compodoc/node_modules/json5/lib/parse.js:146:37)
    at lex (/PATH/@compodoc/compodoc/node_modules/json5/lib/parse.js:78:42)
    at Object.parse (/PATH/@compodoc/compodoc/node_modules/json5/lib/parse.js:25:17)
    at loopInsideModule (/PATH/@compodoc/compodoc/dist/index-cli.js:1073:52)
    at loopRoutesParser (/PATH/@compodoc/compodoc/dist/index-cli.js:1106:29)
    at loopRoutesParser (/PATH/@compodoc/compodoc/dist/index-cli.js:1111:21)
    at RouterParserUtil.constructRoutesTree (/PATH/@compodoc/compodoc/dist/index-cli.js:1115:9) lineNumber: 1, columnNumber: 41 } } reason: { SyntaxError: JSON5: invalid character '.' at 1:41
    at syntaxError (/PATH/@compodoc/compodoc/node_modules/json5/lib/parse.js:1083:17)
    at invalidChar (/PATH/@compodoc/compodoc/node_modules/json5/lib/parse.js:1028:12)
    at Object.afterPropertyValue (/PATH/@compodoc/compodoc/node_modules/json5/lib/parse.js:654:15)
    at Object.default (/PATH/@compodoc/compodoc/node_modules/json5/lib/parse.js:146:37)
    at lex (/PATH/@compodoc/compodoc/node_modules/json5/lib/parse.js:78:42)
    at Object.parse (/PATH/@compodoc/compodoc/node_modules/json5/lib/parse.js:25:17)
    at loopInsideModule (/PATH/@compodoc/compodoc/dist/index-cli.js:1073:52)
    at loopRoutesParser (/PATH/@compodoc/compodoc/dist/index-cli.js:1106:29)
    at loopRoutesParser (/PATH/@compodoc/compodoc/dist/index-cli.js:1111:21)
    at RouterParserUtil.constructRoutesTree (/PATH/@compodoc/compodoc/dist/index-cli.js:1115:9) lineNumber: 1, columnNumber: 41 }
```

##### **Reproduce the error**
`npm run compodoc`

**Comment by austinthedeveloper** [comment]
I tried two things that worked but didn't help me identify what in my code is breaking the build:

- A fresh CLI 6 build creates docs no problem
- If I replace my routes on the broken app with a blank array (const routes: Routes = [];), the docs build

Is there something obvious with how the Routing is being written?
