### ISSUE TITLE
[BUG] Unhandled Rejection at: Promise {   <rejected> { SyntaxError: JSON5: invalid character '\"' at 1:276}

### ISSUE THREAD

**Issue by Razvan189** [compodoc/compodoc#676]
Unhandled Rejection at: Promise {
  <rejected> { SyntaxError: JSON5: invalid character '\"' at 1:276
    at syntaxError (C:\Users\rfrumusanu\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1083:17)
    at invalidChar (C:\Users\rfrumusanu\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1028:12)
    at Object.afterPropertyValue (C:\Users\rfrumusanu\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:654:15)
    at Object.default (C:\Users\rfrumusanu\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:146:37)
    at lex (C:\Users\rfrumusanu\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:78:42)
    at Object.parse (C:\Users\rfrumusanu\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:25:17)
    at loopInsideModule (C:\Users\rfrumusanu\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:1073:52)
    at loopRoutesParser (C:\Users\rfrumusanu\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:1106:29)
    at loopRoutesParser (C:\Users\rfrumusanu\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:1111:21)
    at loopRoutesParser (C:\Users\rfrumusanu\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:1111:21) lineNumber: 1, columnNumber: 276 } } re
ason: { SyntaxError: JSON5: invalid character '\"' at 1:276
    at syntaxError (C:\Users\rfrumusanu\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1083:17)
    at invalidChar (C:\Users\rfrumusanu\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1028:12)
    at Object.afterPropertyValue (C:\Users\rfrumusanu\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:654:15)
    at Object.default (C:\Users\rfrumusanu\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:146:37)
    at lex (C:\Users\rfrumusanu\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:78:42)
    at Object.parse (C:\Users\rfrumusanu\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:25:17)
    at loopInsideModule (C:\Users\rfrumusanu\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:1073:52)
    at loopRoutesParser (C:\Users\rfrumusanu\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:1106:29)
    at loopRoutesParser (C:\Users\rfrumusanu\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:1111:21)
    at loopRoutesParser (C:\Users\rfrumusanu\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:1111:21) lineNumber: 1, columnNumber: 276 }

**Comment by Razvan189** [comment]
Fixed by adding the `--disableRoutesGraph` comand

**Comment by Serginho** [comment]
Same issue: 

```
Unhandled Rejection at: Promise {
  <rejected> { SyntaxError: JSON5: invalid character '+' at 1:862
    at syntaxError (/Users/astrum/tulotero/tulotero-web/node_modules/json5/lib/parse.js:1083:17)
    at invalidChar (/Users/astrum/tulotero/tulotero-web/node_modules/json5/lib/parse.js:1028:12)
    at Object.afterPropertyValue (/Users/astrum/tulotero/tulotero-web/node_modules/json5/lib/parse.js:654:15)
    at Object.default (/Users/astrum/tulotero/tulotero-web/node_modules/json5/lib/parse.js:146:37)
    at lex (/Users/astrum/tulotero/tulotero-web/node_modules/json5/lib/parse.js:78:42)
    at Object.parse (/Users/astrum/tulotero/tulotero-web/node_modules/json5/lib/parse.js:25:17)
    at loopInsideModule (/Users/astrum/tulotero/tulotero-web/node_modules/@compodoc/compodoc/dist/index-cli.js:4121:52)
    at loopRoutesParser (/Users/astrum/tulotero/tulotero-web/node_modules/@compodoc/compodoc/dist/index-cli.js:4154:29)
    at loopRoutesParser (/Users/astrum/tulotero/tulotero-web/node_modules/@compodoc/compodoc/dist/index-cli.js:4159:21)
    at RouterParserUtil.constructRoutesTree (/Users/astrum/tulotero/tulotero-web/node_modules/@compodoc/compodoc/dist/index-cli.js:4163:9) lineNumber: 1, columnNumber: 862 } } reason: { SyntaxError: JSON5: invalid character '+' at 1:862
    at syntaxError (/Users/astrum/tulotero/tulotero-web/node_modules/json5/lib/parse.js:1083:17)
    at invalidChar (/Users/astrum/tulotero/tulotero-web/node_modules/json5/lib/parse.js:1028:12)
    at Object.afterPropertyValue (/Users/astrum/tulotero/tulotero-web/node_modules/json5/lib/parse.js:654:15)
    at Object.default (/Users/astrum/tulotero/tulotero-web/node_modules/json5/lib/parse.js:146:37)
    at lex (/Users/astrum/tulotero/tulotero-web/node_modules/json5/lib/parse.js:78:42)
    at Object.parse (/Users/astrum/tulotero/tulotero-web/node_modules/json5/lib/parse.js:25:17)
    at loopInsideModule (/Users/astrum/tulotero/tulotero-web/node_modules/@compodoc/compodoc/dist/index-cli.js:4121:52)
    at loopRoutesParser (/Users/astrum/tulotero/tulotero-web/node_modules/@compodoc/compodoc/dist/index-cli.js:4154:29)
    at loopRoutesParser (/Users/astrum/tulotero/tulotero-web/node_modules/@compodoc/compodoc/dist/index-cli.js:4159:21)
    at RouterParserUtil.constructRoutesTree (/Users/astrum/tulotero/tulotero-web/node_modules/@compodoc/compodoc/dist/index-cli.js:4163:9) lineNumber: 1, columnNumber: 862 }
```
