### ISSUE TITLE
[BUG] @param generates ng build `warning TS0: the type annotation on @param is redundant with its TypeScript type, remove the {...} part`

### ISSUE THREAD

**Issue by hughanderson4** [compodoc/compodoc#707]
##### **Overview of the issue**

When I use `@param` as shown in the Compodoc documentation [here](https://compodoc.app/guides/jsdoc-tags.html) I get the following warning when running `ng build`
In my case this warning causes an error and the build is unable to continue.

`TS0: the type annotation on @param is redundant with its TypeScript type, remove the {...} part`

##### **Operating System, Node.js, npm, compodoc version(s)**

OS: Windows 10
```terminal
D:\>node -v
v10.14.1

D:\>npm --version
6.4.1
```

##### **Angular configuration, a `package.json` file in the root folder**

package.json:

```
{
  "name": "framework",
  "version": "0.0.1",
  "private": true,
  "author": "Hugh Anderson",
  "license": "private",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build-ts": "npm run clean & ng build",
    "build-scss-bundle": "scss-bundle -e \"./framework/styles/_framework.scss\" -d \"./dist/framework/styles/_framework.scss\" && scss-bundle -e \"./framework/styles/variables.scss\" -d \"./dist/framework/styles/variables.scss\"",
    "build-assets": "cpx \"./framework/assets/**/*\" \"./dist/framework/assets\"",
    "build-all": "npm run build-ts & npm run build-assets & npm run build-scss-bundle ",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "clean": "rimraf \"./dist/*\"",
    "watch": "npm run clean && concurrently \"ng build --watch=true\" \"npm:watch-scss-*\" \"npm:watch-assets\"",
    "watch-scss-framework": "scss-bundle -e \"./framework/styles/_framework.scss\" -d \"./dist/framework/styles/_framework.scss\" -w \"./framework/styles\"",
    "watch-scss-variables": "scss-bundle -e \"./framework/styles/variables.scss\" -d \"./dist/framework/styles/variables.scss\" -w \"./framework/styles\"",
    "watch-assets": "cpx \"./framework/assets/**/*\" \"./dist/framework/assets\" --watch --verbose"
  },
  "dependencies": {
    "@angular/animations": "^7.0.4",
    "@angular/cdk": "~7.0.3",
    "@angular/common": "~7.0.0",
    "@angular/compiler": "~7.0.0",
    "@angular/core": "~7.0.0",
    "@angular/flex-layout": "^7.0.0-beta.19",
    "@angular/forms": "~7.0.0",
    "@angular/http": "~7.0.0",
    "@angular/material": "^7.0.3",
    "@angular/platform-browser": "~7.0.0",
    "@angular/platform-browser-dynamic": "~7.0.0",
    "@angular/router": "~7.0.0",
    "angular-gauge": "^3.1.1",
    "core-js": "^2.5.4",
    "hammerjs": "^2.0.8",
    "ngx-toastr": "^9.1.1",
    "rxjs": "~6.3.3",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.10.0",
    "@angular-devkit/build-ng-packagr": "~0.10.0",
    "@angular/cli": "~7.0.2",
    "@angular/compiler-cli": "~7.0.0",
    "@angular/language-service": "~7.0.0",
    "@babel/core": "^7.1.6",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "babel-loader": "^8.0.4",
    "codelyzer": "~4.5.0",
    "concurrently": "^4.0.1",
    "cpx": "^1.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng-packagr": "^4.2.0",
    "protractor": "~5.4.0",
    "rimraf": "^2.6.2",
    "scss-bundle": "^2.5.0-beta",
    "ts-node": "~7.0.0",
    "tsickle": ">=0.29.0",
    "tslib": "^1.9.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.1"
  }
}
```

##### **Compodoc installed globally or locally ?**

locally

##### **If possible sourcecode of the file where it breaks**

```
  /**
   * Creates an instance of VinDecodeResultComponent
   * 
   * @param {VinDecodeService} vinDecodeService Service that provides data subscription for current Vin Decode result
   */
  constructor(vinDecodeService: VinDecodeService) {
    // implementation removed
  }
```

##### **If possible your terminal logs before the error**

```
> Executing task: npm run build-ts <


> framework@0.0.1 build-ts d:\Dynatron\code\framework
> npm run clean & ng build


> framework@0.0.1 clean d:\Dynatron\code\framework
> rimraf "./dist/*"

Building Angular Package
Building entry point '@dynatron/framework'
Compiling TypeScript sources through ngc

BUILD ERROR
framework/src/lib/components/vin-decode/vin-decode-result/vin-decode-result.component.ts(32,3): warning TS0: the type annotation on @param is redundant with its TypeScript type, remove the {...} part

Error: framework/src/lib/components/vin-decode/vin-decode-result/vin-decode-result.component.ts(32,3): warning TS0: the type annotation on @param is redundant with its TypeScript type, remove the {...} part

    at Object.<anonymous> (d:\Dynatron\code\framework\node_modules\ng-packagr\lib\ngc\compile-source-files.js:40:68)
    at Generator.next (<anonymous>)
    at d:\Dynatron\code\framework\node_modules\ng-packagr\lib\ngc\compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (d:\Dynatron\code\framework\node_modules\ng-packagr\lib\ngc\compile-source-files.js:3:12)
    at Object.compileSourceFiles (d:\Dynatron\code\framework\node_modules\ng-packagr\lib\ngc\compile-source-files.js:17:12)
    at Object.<anonymous> (d:\Dynatron\code\framework\node_modules\ng-packagr\lib\ng-v5\entry-point\ts\compile-ngc.transform.js:31:32)
    at Generator.next (<anonymous>)
    at d:\Dynatron\code\framework\node_modules\ng-packagr\lib\ng-v5\entry-point\ts\compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)

framework/src/lib/components/vin-decode/vin-decode-result/vin-decode-result.component.ts(32,3): warning TS0: the type annotation on @param is redundant with its TypeScript type, remove the {...} part

Error: framework/src/lib/components/vin-decode/vin-decode-result/vin-decode-result.component.ts(32,3): warning TS0: the type annotation on @param is redundant with its TypeScript type, remove the {...} part

    at Object.<anonymous> (d:\Dynatron\code\framework\node_modules\ng-packagr\lib\ngc\compile-source-files.js:40:68)
    at Generator.next (<anonymous>)
    at d:\Dynatron\code\framework\node_modules\ng-packagr\lib\ngc\compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (d:\Dynatron\code\framework\node_modules\ng-packagr\lib\ngc\compile-source-files.js:3:12)
    at Object.compileSourceFiles (d:\Dynatron\code\framework\node_modules\ng-packagr\lib\ngc\compile-source-files.js:17:12)
    at Object.<anonymous> (d:\Dynatron\code\framework\node_modules\ng-packagr\lib\ng-v5\entry-point\ts\compile-ngc.transform.js:31:32)
    at Generator.next (<anonymous>)
    at d:\Dynatron\code\framework\node_modules\ng-packagr\lib\ng-v5\entry-point\ts\compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)
```

##### **Motivation for or Use Case**

Documentation says to use this particular format of comment, so I expect that it should not throw a Typescript build warning.

##### **Reproduce the error**

1. insert comment for `@param` as directed by the Compodoc documentation
2. run `ng build`
3. observe warning/error

##### **Related issues**

no

**Comment by peterramaldes** [comment]
Same issue here

**Comment by vogloblinsky** [comment]
Cannot reproduce with angular CLI 8.1.0
