### ISSUE TITLE
[BUG] Routing dynamic variable from TypeScript custom path

### ISSUE THREAD

**Issue by vogloblinsky** [compodoc/compodoc#718]
For compodoc-demo-todomvc-angular 

```
import { APP_ENUMS } from '@app/app-routes.enum';

const HOME_ROUTES: Routes = [
    {
        path: APP_ENUMS.home,
        component: HomeComponent
    }
];
```

```
Unhandled Rejection at: Promise {
  <rejected> Error: Could not find the node's symbol.
    at InvalidOperationError.BaseError [as constructor] (/home/vogloblinsky-local/Documents/www/TMP/compodoc/compodoc/node_modules/ts-simple-ast/dist/errors/BaseError.js:7:28)
    at new InvalidOperationError (/home/vogloblinsky-local/Documents/www/TMP/compodoc/compodoc/node_modules/ts-simple-ast/dist/errors/InvalidOperationError.js:8:28)
    at Object.throwIfNullOrUndefined (/home/vogloblinsky-local/Documents/www/TMP/compodoc/compodoc/node_modules/ts-simple-ast/dist/errors/helpers.js:96:15)
    at Identifier.Node.getSymbolOrThrow (/home/vogloblinsky-local/Documents/www/TMP/compodoc/compodoc/node_modules/ts-simple-ast/dist/compiler/common/Node.js:131:23)
    at RouterParserUtil.cleanFileDynamics (/home/vogloblinsky-local/Documents/www/TMP/compodoc/compodoc/dist/index-cli.js:4423:18)
    at AngularDependencies.getSourceFileDecorators (/home/vogloblinsky-local/Documents/www/TMP/compodoc/compodoc/dist/index-cli.js:6972:46)
    at /home/vogloblinsky-local/Documents/www/TMP/compodoc/compodoc/dist/index-cli.js:6782:31
    at Array.map (<anonymous>)
    at AngularDependencies.getDependencies (/home/vogloblinsky-local/Documents/www/TMP/compodoc/compodoc/dist/index-cli.js:6771:21)
    at CliApplication.Application.getDependenciesData (/home/vogloblinsky-local/Documents/www/TMP/compodoc/compodoc/dist/index-cli.js:8327:40) } reason: Error: Could not find the node's symbol.
    at InvalidOperationError.BaseError [as constructor] (/home/vogloblinsky-local/Documents/www/TMP/compodoc/compodoc/node_modules/ts-simple-ast/dist/errors/BaseError.js:7:28)
    at new InvalidOperationError (/home/vogloblinsky-local/Documents/www/TMP/compodoc/compodoc/node_modules/ts-simple-ast/dist/errors/InvalidOperationError.js:8:28)
    at Object.throwIfNullOrUndefined (/home/vogloblinsky-local/Documents/www/TMP/compodoc/compodoc/node_modules/ts-simple-ast/dist/errors/helpers.js:96:15)
    at Identifier.Node.getSymbolOrThrow (/home/vogloblinsky-local/Documents/www/TMP/compodoc/compodoc/node_modules/ts-simple-ast/dist/compiler/common/Node.js:131:23)
    at RouterParserUtil.cleanFileDynamics (/home/vogloblinsky-local/Documents/www/TMP/compodoc/compodoc/dist/index-cli.js:4423:18)
    at AngularDependencies.getSourceFileDecorators (/home/vogloblinsky-local/Documents/www/TMP/compodoc/compodoc/dist/index-cli.js:6972:46)
    at /home/vogloblinsky-local/Documents/www/TMP/compodoc/compodoc/dist/index-cli.js:6782:31
    at Array.map (<anonymous>)
    at AngularDependencies.getDependencies (/home/vogloblinsky-local/Documents/www/TMP/compodoc/compodoc/dist/index-cli.js:6771:21)
    at CliApplication.Application.getDependenciesData (/home/vogloblinsky-local/Documents/www/TMP/compodoc/compodoc/dist/index-cli.js:8327:40)
```

`import { APP_ENUMS } from '@app/app-routes.enum';` works

**Comment by merobal** [comment]
Maybe it's the same as https://github.com/compodoc/compodoc/issues/680, after I changed the type `Routes` to `Route[]` on my project it works well.

**Comment by Spongeroberto** [comment]
Changing the type to `Route[]` prevents the errors but does exclude your routes from the generated documentation. So more of a stopgap than an actual workaround
