### ISSUE TITLE
compodoc execute failed

### ISSUE THREAD

**Issue by zcg8633** [compodoc/compodoc#768]
https://travis-ci.org/rdkmaster/jigsaw/builds/517593048#L2589

/home/travis/.nvm/versions/node/v6.17.1/lib/node_modules/@compodoc/compodoc/node_modules/opn/index.js:11
const wslToWindowsPath = async path => {
                               ^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/travis/.nvm/versions/node/v6.17.1/lib/node_modules/@compodoc/compodoc/node_modules/live-server/index.js:11:9)

**Comment by vogloblinsky** [comment]
Compodoc doesn’t support Node.js 6
