### ISSUE TITLE
[BUG] can't start compodoc

### ISSUE THREAD

**Issue by zieglar** [compodoc/compodoc#770]
##### **Overview of the issue**
`compodoc -p tsconfig.json` can't start 

##### **Operating System, Node.js, npm, compodoc version(s)**

compodoc v1.1.9

[System Information]
OS Version     : macOS Mojave
NodeJS Version : v8.15.1
NPM Version    : 6.9.0
[Nest Information]
platform-express version : 6.1.0
@nestjsx/crud version    : 3.2.0
passport version         : 6.0.0
swagger version          : 3.0.2
typeorm version          : 6.0.0
common version           : 6.1.0
core version             : 6.1.0
jwt version              : 6.0.0

##### **Angular configuration, a `package.json` file in the root folder**
```
{
"dependencies": {
    "@nestjs/common": "^6.1.0",
    "@nestjs/core": "^6.1.0",
    "@nestjs/jwt": "^6.0.0",
    "@nestjs/passport": "^6.0.0",
    "@nestjs/platform-express": "^6.1.0",
    "@nestjs/swagger": "^3.0.2",
    "@nestjs/typeorm": "^6.0.0",
    "@nestjsx/crud": "^3.2.0",
    "@types/lodash": "^4.14.123",
    "bcrypt": "^3.0.5",
    "bcryptjs": "^2.4.3",
    "cache-manager": "^2.9.0",
    "cache-manager-ioredis": "^1.0.1",
    "class-transformer": "^0.2.0",
    "class-validator": "^0.9.1",
    "class-validator-jsonschema": "^1.2.0",
    "compression": "^1.7.4",
    "dayjs": "^1.8.12",
    "express-request-id": "^1.4.1",
    "helmet": "^3.16.0",
    "nestjs-config": "^1.3.21",
    "nestjs-redis": "^1.1.2",
    "nestjs-typeorm-paginate": "^0.1.1",
    "passport": "^0.4.0",
    "passport-http-bearer": "^1.0.1",
    "passport-jwt": "^4.0.0",
    "passport-oauth2-client-password": "^0.1.2",
    "pg": "^7.9.0",
    "redis": "^2.8.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^2.6.3",
    "rxjs": "^6.4.0",
    "serialize-error": "^4.1.0",
    "shortid": "^2.2.14",
    "swagger-ui-express": "^4.0.2",
    "typeorm": "^0.2.16",
    "utility": "^1.16.1"
  },
  "devDependencies": {
    "@compodoc/compodoc": "^1.1.9",
    "@nestjs/testing": "^6.1.0",
    "@types/bcrypt": "^3.0.0",
    "@types/bcryptjs": "^2.4.2",
    "@types/express": "^4.16.1",
    "@types/jest": "^24.0.11",
    "@types/node": "^11.13.2",
    "@types/node_redis": "^0.8.29",
    "@types/supertest": "^2.0.7",
    "@typescript-eslint/eslint-plugin": "^1.6.0",
    "@typescript-eslint/parser": "^1.6.0",
    "eslint": "^5.16.0",
    "eslint-config-prettier": "^4.1.0",
    "eslint-plugin-prettier": "^3.0.1",
    "jest": "^24.7.1",
    "nodemon": "^1.18.11",
    "prettier": "^1.16.4",
    "supertest": "^4.0.2",
    "ts-jest": "^24.0.2",
    "ts-node": "^8.0.3",
    "tsconfig-paths": "^3.8.0",
    "typescript": "^3.4.3"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".spec.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  },
  "standard": {
    "parser": "@typescript-eslint/parser",
    "plugins": [
      "typescript"
    ]
  }
}
```
##### **Compodoc installed globally or locally ?**

globally installed

##### **If possible sourcecode of the file where it breaks**
[02:12:29] found          : ChatRecordsModule
[02:12:29]                : - imports:
[02:12:29]                : 	- TypeOrmModule
[02:12:29]                : - providers:
[02:12:29]                : 	- ChatRecordsService
[02:12:29] parsing        : /Users/zieglar/Code/dyf-api/src/chatrecords/chatrecords.service.ts
[02:12:29] found          : ChatRecordsService
[02:12:29] parsing        : /Users/zieglar/Code/dyf-api/src/chatrooms/chatroom.entity.ts
[02:12:29] found          : ChatRoomEntity
[02:12:29] parsing        : /Users/zieglar/Code/dyf-api/src/chatrooms/chatrooms.controller.ts
[02:12:29] Empty metadatas, trying to found it with imports.

##### **Reproduce the error**

Unhandled Rejection at: Promise {
  <rejected> Error: Not implemented feature for syntax kind 'ObjectBindingPattern'.
    at NotImplementedError.BaseError [as constructor] (/Users/zieglar/.nvm/versions/node/v8.15.1/lib/node_modules/@compodoc/compodoc/node_modules/ts-simple-ast/dist/errors/BaseError.js:7:28)
    at new NotImplementedError (/Users/zieglar/.nvm/versions/node/v8.15.1/lib/node_modules/@compodoc/compodoc/node_modules/ts-simple-ast/dist/errors/NotImplementedError.js:8:28)
    at Object.getNotImplementedForSyntaxKindError (/Users/zieglar/.nvm/versions/node/v8.15.1/lib/node_modules/@compodoc/compodoc/node_modules/ts-simple-ast/dist/errors/helpers.js:76:12)
    at VariableDeclaration.BindingNamedNodeInternal.class_1.getNameNode (/Users/zieglar/.nvm/versions/node/v8.15.1/lib/node_modules/@compodoc/compodoc/node_modules/ts-simple-ast/dist/compiler/base/name/BindingNamedNode.js:24:34)
    at VariableDeclaration.BindingNamedNodeInternal.class_1.getName (/Users/zieglar/.nvm/versions/node/v8.15.1/lib/node_modules/@compodoc/compodoc/node_modules/ts-simple-ast/dist/compiler/base/name/BindingNamedNode.js:28:25)
    at findFunc (/Users/zieglar/.nvm/versions/node/v8.15.1/lib/node_modules/@compodoc/compodoc/node_modules/ts-simple-ast/dist/utils/compiler/getNodeByNameOrFindFunction.js:7:71)
    at Function.ArrayUtils.find (/Users/zieglar/.nvm/versions/node/v8.15.1/lib/node_modules/@compodoc/compodoc/node_modules/ts-simple-ast/dist/utils/ArrayUtils.js:38:21)
    at Object.getNodeByNameOrFindFunction (/Users/zieglar/.nvm/versions/node/v8.15.1/lib/node_modules/@compodoc/compodoc/node_modules/ts-simple-ast/dist/utils/compiler/getNodeByNameOrFindFunction.js:10:36)
    at SourceFile.StatementedNode.class_1.getVariableDeclaration (/Users/zieglar/.nvm/versions/node/v8.15.1/lib/node_modules/@compodoc/compodoc/node_modules/ts-simple-ast/dist/compiler/statement/StatementedNode.js:312:28)
    at ImportsUtil.findValueInImportOrLocalVariables (/Users/zieglar/.nvm/versions/node/v8.15.1/lib/node_modules/@compodoc/compodoc/dist/index-cli.js:4175:64) } reason: Error: Not implemented feature for syntax kind 'ObjectBindingPattern'.
    at NotImplementedError.BaseError [as constructor] (/Users/zieglar/.nvm/versions/node/v8.15.1/lib/node_modules/@compodoc/compodoc/node_modules/ts-simple-ast/dist/errors/BaseError.js:7:28)
    at new NotImplementedError (/Users/zieglar/.nvm/versions/node/v8.15.1/lib/node_modules/@compodoc/compodoc/node_modules/ts-simple-ast/dist/errors/NotImplementedError.js:8:28)
    at Object.getNotImplementedForSyntaxKindError (/Users/zieglar/.nvm/versions/node/v8.15.1/lib/node_modules/@compodoc/compodoc/node_modules/ts-simple-ast/dist/errors/helpers.js:76:12)
    at VariableDeclaration.BindingNamedNodeInternal.class_1.getNameNode (/Users/zieglar/.nvm/versions/node/v8.15.1/lib/node_modules/@compodoc/compodoc/node_modules/ts-simple-ast/dist/compiler/base/name/BindingNamedNode.js:24:34)
    at VariableDeclaration.BindingNamedNodeInternal.class_1.getName (/Users/zieglar/.nvm/versions/node/v8.15.1/lib/node_modules/@compodoc/compodoc/node_modules/ts-simple-ast/dist/compiler/base/name/BindingNamedNode.js:28:25)
    at findFunc (/Users/zieglar/.nvm/versions/node/v8.15.1/lib/node_modules/@compodoc/compodoc/node_modules/ts-simple-ast/dist/utils/compiler/getNodeByNameOrFindFunction.js:7:71)
    at Function.ArrayUtils.find (/Users/zieglar/.nvm/versions/node/v8.15.1/lib/node_modules/@compodoc/compodoc/node_modules/ts-simple-ast/dist/utils/ArrayUtils.js:38:21)
    at Object.getNodeByNameOrFindFunction (/Users/zieglar/.nvm/versions/node/v8.15.1/lib/node_modules/@compodoc/compodoc/node_modules/ts-simple-ast/dist/utils/compiler/getNodeByNameOrFindFunction.js:10:36)
    at SourceFile.StatementedNode.class_1.getVariableDeclaration (/Users/zieglar/.nvm/versions/node/v8.15.1/lib/node_modules/@compodoc/compodoc/node_modules/ts-simple-ast/dist/compiler/statement/StatementedNode.js:312:28)
    at ImportsUtil.findValueInImportOrLocalVariables (/Users/zieglar/.nvm/versions/node/v8.15.1/lib/node_modules/@compodoc/compodoc/dist/index-cli.js:4175:64)

**Comment by vogloblinsky** [comment]
Can i have `chatrooms.controller.ts` source code ?

**Comment by zieglar** [comment]
i found solution, some controller have relative reference entity, make all reference to absolute path resolve this.
