### ISSUE TITLE
[BUG] (node:5261) UnhandledPromiseRejectionWarning: RangeError: Invalid array length

### ISSUE THREAD

**Issue by huskerona** [compodoc/compodoc#771]
##### **Overview of the issue**

**compodoc** fails when processing exported reducers. Commenting them out will make **compodoc** run without a glitch.

##### **Operating System, Node.js, npm, compodoc version(s)**
macOS Mojave (10.14.4), node v10.0.0, npm v5.6.0, compodoc v1.1.9

##### **Compodoc installed globally or locally ?**
Both

##### **If possible sourcecode of the file where it breaks**

```
import {
    ActionReducerMap,
    MetaReducer
} from '@ngrx/store';
import { routerReducer } from '@ngrx/router-store';
import { storeFreeze } from 'ngrx-store-freeze';
import { environment } from '@saris/environments';
import { AppState } from './app-state';
import { variantReducer } from '../core/variant/variant.reducers';
import { questSetReducer } from '../core/questionnaire-set/questionnaire-set.reducers';
import { questionnaireReducer } from '../core/questionnaire/questionnaire.reducers';
import {sarisModuleReducer} from "../core/saris-module/saris-module.reducers";
import {questionReducer} from "../core/question/question.reducers";
import {lifecycleReducer} from "../lifecycle/lifecycle.reducers";

// Commenting the code below fixes the issue.
export const reducers: ActionReducerMap<AppState> = {
    router: routerReducer,
    variants: variantReducer,
    questSets: questSetReducer,
    questionnaires: questionnaireReducer,
    sarisModules: sarisModuleReducer,
    questions: questionReducer,
    lifecycles: lifecycleReducer
};


export const metaReducers: MetaReducer<AppState>[] =
    !environment.production ? [ storeFreeze ] : [];

```
##### **If possible your terminal logs before the error**
```
(node:6001) UnhandledPromiseRejectionWarning: RangeError: Invalid array length
    at pad (/Users/huske/.npm/_npx/6001/lib/node_modules/compodoc/dist/index-cli.js:74:24)
    at Logger.format (/Users/huske/.npm/_npx/6001/lib/node_modules/compodoc/dist/index-cli.js:78:19)
    at Logger.error (/Users/huske/.npm/_npx/6001/lib/node_modules/compodoc/dist/index-cli.js:56:33)
    at /Users/huske/.npm/_npx/6001/lib/node_modules/compodoc/dist/index-cli.js:1561:32
    at Array.map (<anonymous>)
    at Dependencies.getDependencies (/Users/huske/.npm/_npx/6001/lib/node_modules/compodoc/dist/index-cli.js:1552:21)
    at CliApplication.Application.getDependenciesData (/Users/huske/.npm/_npx/6001/lib/node_modules/compodoc/dist/index-cli.js:2914:40)
    at /Users/huske/.npm/_npx/6001/lib/node_modules/compodoc/dist/index-cli.js:2897:19
(node:6001) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6001) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Thanks!

**Comment by githendrik** [comment]
I have the same error output when trying to parse my routing-module.ts. Any feedback on this issue?

**Comment by blackholegalaxy** [comment]
Same thing here on a big app. Our `app.module.ts` fails.
