### ISSUE TITLE
Fails to generate documentation, not find node's symbol

### ISSUE THREAD

**Issue by PedroS5499** [compodoc/compodoc#791]
##### **Overview of the issue**

When run command `compodoc -p src/tsconfig.app.json -s` fails to generate documentation

##### **Operating System, Node.js, npm, compodoc version(s)**

Windows 7
node -v10.15.3
vpm -v6.4.1
compodoc -v1.1.9
angular -v7.2.9

##### **Compodoc installed globally or locally ?**

globally

##### **If possible sourcecode of the file where it breaks**

```import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

import { AuthGuard, AuthService, JwtInterceptor } from 'src/app/shared/auth';
import { Role } from 'src/app/shared/enums';
import { TasksAtComponent } from './tasks-at';
import { TaskAtComponent } from './task-at';


const routes: Routes = [
	{
		path: 'tasks/at',
		component: TasksAtComponent,
		canActivate: [AuthGuard],
		data: {
			roles: [Role.Admin, Role.At],
			title: 'Tasks List'
		}
	},

	{
		path: 'tasks/at/:id',
		component: TaskAtComponent,
		canActivate: [AuthGuard],
		data: {
			roles: [Role.Admin, Role.At],
			title: 'Task #:id'
		}
	},
]

@NgModule({
    imports: [RouterModule.forChild(routes)],
    exports: [RouterModule]
  })
  export class AtRoutingModule { }
```

##### **If possible your terminal logs before the error**

```
14:07:33] parsing        : C:/git-projects/web-workspace-angular/src/app/pages/at/at.module.ts
[14:07:33] found          : AtModule
[14:07:33]                : - imports:
[14:07:33]                :     - CommonModule
[14:07:33]                :     - SharedModule
[14:07:33]                :     - TasksAtModule
[14:07:34]                :     - TaskAtModule
[14:07:34]                :     - AtRoutingModule
[14:07:34] parsing        : C:/git-projects/web-workspace-angular/src/app/pages/at/at.routing.module.ts
[14:07:34] Analysing routes definitions and clean them if necessary
Unhandled Rejection at: Promise {
  <rejected> Error: Could not find the node's symbol.
      at InvalidOperationError.BaseError [as constructor] (C:\Users\a0776436\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\ts-simple-ast\dist\errors\BaseError.js:7:28)
      at new InvalidOperationError (C:\Users\a0776436\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\ts-simple-ast\dist\errors\InvalidOperationError.js:8:28)
      at Object.throwIfNullOrUndefined (C:\Users\a0776436\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\ts-simple-ast\dist\errors\helpers.js:96:15)
      at Identifier.Node.getSymbolOrThrow (C:\Users\a0776436\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\ts-simple-ast\dist\compiler\common\Node.js:131:23)
      at RouterParserUtil.cleanFileDynamics (C:\Users\a0776436\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:4923:18)
      at AngularDependencies.getSourceFileDecorators (C:\Users\a0776436\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:7410:46)
      at C:\Users\a0776436\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:7218:31
      at Array.map (<anonymous>)
      at AngularDependencies.getDependencies (C:\Users\a0776436\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:7207:21)
      at CliApplication.Application.getDependenciesData (C:\Users\a0776436\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:8757:40) }
reason: Error: Could not find the node's symbol.
    at InvalidOperationError.BaseError [as constructor] (C:\Users\a0776436\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\ts-simple-ast\dist\errors\BaseError.js:7:28)
    at new InvalidOperationError (C:\Users\a0776436\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\ts-simple-ast\dist\errors\InvalidOperationError.js:8:28)
    at Object.throwIfNullOrUndefined (C:\Users\a0776436\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\ts-simple-ast\dist\errors\helpers.js:96:15)
    at Identifier.Node.getSymbolOrThrow (C:\Users\a0776436\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\ts-simple-ast\dist\compiler\common\Node.js:131:23)
    at RouterParserUtil.cleanFileDynamics (C:\Users\a0776436\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:4923:18)
    at AngularDependencies.getSourceFileDecorators (C:\Users\a0776436\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:7410:46)
    at C:\Users\a0776436\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:7218:31
    at Array.map (<anonymous>)
    at AngularDependencies.getDependencies (C:\Users\a0776436\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:7207:21)
    at CliApplication.Application.getDependenciesData (C:\Users\a0776436\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\index-cli.js:8757:40)
[14:07:43] Sorry, but there was a problem during parsing or generation of the
documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
```

##### **Related issues**

[525] (https://github.com/compodoc/compodoc/issues/525)
[586] (https://github.com/compodoc/compodoc/issues/586)

##### **Suggest a Fix**

I tried put `valueOf()` in each enum and works

**Comment by peppeschiavo** [comment]
I have got this issue with version 1.1.10. I am using enumeration to define the routings. I have fixed by referencing enum values by their .valueOf() method, as suggested by brentmiller, in the last comment on this track https://github.com/compodoc/compodoc/issues/525, but it is little annoying we have to do that.

**Comment by PedroS5499** [comment]
.valueOf() worked
