### ISSUE TITLE
[BUG] Error, cannot build documentation

### ISSUE THREAD

**Issue by Tuqzar** [compodoc/compodoc#801]
**### Maybe this is due to the fact that I recently updated angular core to the 8th version**

[10:00:44] Searching package.json file
[10:00:44] package.json file found
[10:00:44] Processing package.json dependencies
[10:00:44] Searching README.md, CHANGELOG.md, CONTRIBUTING.md, LICENSE.md, TODO.md files
[10:00:44] README.md file found
[10:00:44] Error during xxxxxxxxxxxxxxxxxxxxx\ClientApp\CHANGELOG read
[10:00:44] Continuing without CHANGELOG.md file
[10:00:44] Error during xxxxxxxxxxxxxxxxxxxxx\ClientApp\CONTRIBUTING read
[10:00:44] Continuing without CONTRIBUTING.md file
[10:00:44] Error during xxxxxxxxxxxxxxxxxxxxx\ClientApp\LICENSE read
[10:00:44] Continuing without LICENSE.md file
[10:00:44] TODO.md file found
[10:00:44] Get dependencies data
[10:00:45] parsing        : xxxxxxxxxxxxxxxxxxxxx/ClientApp/src/main.ts
[10:00:45] parsing        : xxxxxxxxxxxxxxxxxxxxxClientApp/src/polyfills.ts
[10:00:45] parsing        : xxxxxxxxxxxxxxxxxxxxx/ClientApp/src/app/app-routing.module.ts
[10:00:45] Analysing routes definitions and clean them if necessary
Unhandled Rejection at: Promise {
  <rejected> Error: Expected to find an initializer.
      at InvalidOperationError.BaseError [as constructor] (C:\WORK\xxxxxxxx\ClientApp\node_modules\ts-simple-ast\dist\errors\BaseError.js:7:28)
      at new InvalidOperationError (C:\WORK\xxxxxxxx\ClientApp\node_modules\ts-simple-ast\dist\errors\InvalidOperationError.js:8:28)
      at Object.throwIfNullOrUndefined (C:\WORK\xxxxxxxx\ClientApp\node_modules\ts-simple-ast\dist\errors\helpers.js:96:15)
      at EnumMember.InitializerGetExpressionableNode.class_1.getInitializerOrThrow (C:\WORKxxxxxxxxClientApp\node_modules\ts-simple-ast\dist\compiler\
base\initializer\InitializerGetExpressionableNode.js:25:27)
      at RouterParserUtil.cleanFileDynamics (C:\WORK\xxxxxxxx\ClientApp\node_modules\@compodoc\compodoc\dist\index-cli.js:4932:80)
      at AngularDependencies.getSourceFileDecorators (C:\WORK\xxxxxxxxClientApp\node_modules\@compodoc\compodoc\dist\index-cli.js:7410:46)
      at C:\WORK\xxxxxxxxClientApp\node_modules\@compodoc\compodoc\dist\index-cli.js:7218:31
      at Array.map (<anonymous>)
      at AngularDependencies.getDependencies (C:\WORK\xxxxxxxxClientApp\node_modules\@compodoc\compodoc\dist\index-cli.js:7207:21)
      at CliApplication.Application.getDependenciesData (C:\WORK\xxxxxxxxClientApp\node_modules\@compodoc\compodoc\dist\index-cli.js:8757:40) } reason:
 Error: Expected to find an initializer.
    at InvalidOperationError.BaseError [as constructor] (C:\WORK\xxxxxxxxClientApp\node_modules\ts-simple-ast\dist\errors\BaseError.js:7:28)
    at new InvalidOperationError (C:\WORK\xxxxxxxxClientApp\node_modules\ts-simple-ast\dist\errors\InvalidOperationError.js:8:28)
    at Object.throwIfNullOrUndefined (C:\WORK\xxxxxxxx\ClientApp\node_modules\ts-simple-ast\dist\errors\helpers.js:96:15)
    at EnumMember.InitializerGetExpressionableNode.class_1.getInitializerOrThrow (C:\WORK\xxxxxxxxClientApp\node_modules\ts-simple-ast\dist\compiler\ba
se\initializer\InitializerGetExpressionableNode.js:25:27)
    at RouterParserUtil.cleanFileDynamics (C:\WORK\xxxxxxxxClientApp\node_modules\@compodoc\compodoc\dist\index-cli.js:4932:80)
    at AngularDependencies.getSourceFileDecorators (C:\WORK\xxxxxxxxClientApp\node_modules\@compodoc\compodoc\dist\index-cli.js:7410:46)
    at C:\WORK\xxxxxxxxClientApp\node_modules\@compodoc\compodoc\dist\index-cli.js:7218:31
    at Array.map (<anonymous>)
    at AngularDependencies.getDependencies (C:\WORK\xxxxxxxxClientApp\node_modules\@compodoc\compodoc\dist\index-cli.js:7207:21)
    at CliApplication.Application.getDependenciesData (C:\WORK\xxxxxxxxClientApp\node_modules\@compodoc\compodoc\dist\index-cli.js:8757:40)
[10:00:59] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/i
ssues/new)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! client-app@0.0.0 compodoc: `npx compodoc -p src/tsconfig.app.json -s`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the client-app@0.0.0 compodoc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxxxxxxx\AppData\Roaming\npm-cache\_logs\2019-07-03T07_00_59_863Z-debug.log

**Comment by vogloblinsky** [comment]
Just tested with demo project https://github.com/compodoc/compodoc-demo-todomvc-angular
Compodoc currently doesn't support new routing syntax with native import, but documentation generation doesn't break.
Could you share `app-routing.module.ts` source code ?

**Comment by daboudii** [comment]
Hello, same issue here but I have not update anything.
If it can help here is the debug.log


`0 info it worked if it ends with ok`
`1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'compodoc' ]`
`2 info using npm@6.7.0`
`3 info using node@v11.14.0`
`4 verbose run-script [ 'precompodoc', 'compodoc', 'postcompodoc' ]`
`5 info lifecycle govgis_frontend@4.0.0~precompodoc: govgis_frontend@4.0.0`
`6 info lifecycle govgis_frontend@4.0.0~compodoc: govgis_frontend@4.0.0`
`7 verbose lifecycle govgis_frontend@4.0.0~compodoc: unsafe-perm in lifecycle true`
`8 verbose lifecycle govgis_frontend@4.0.0~compodoc: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/user/govgis_frontend/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
`9 verbose lifecycle govgis_frontend@4.0.0~compodoc: CWD: /home/user/govgis_frontend`
`10 silly lifecycle govgis_frontend@4.0.0~compodoc: Args: [ '-c', 'compodoc -p tsconfig.json' ]`
`11 silly lifecycle govgis_frontend@4.0.0~compodoc: Returned: code: 1  signal: null`
`12 info lifecycle govgis_frontend@4.0.0~compodoc: Failed to exec compodoc script`
`13 verbose stack Error: govgis_frontend@4.0.0 compodoc: `compodoc -p tsconfig.json``
`13 verbose stack Exit status 1`
`13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)`
`13 verbose stack     at EventEmitter.emit (events.js:193:13)`
`13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)`
`13 verbose stack     at ChildProcess.emit (events.js:193:13)`
`13 verbose stack     at maybeClose (internal/child_process.js:999:16)`
`13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)`
`14 verbose pkgid govgis_frontend@4.0.0`
`15 verbose cwd /home/user/govgis_frontend`
`16 verbose Linux 4.18.0-24-generic`
`17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "compodoc"`
`18 verbose node v11.14.0`
`19 verbose npm  v6.7.0`
`20 error code ELIFECYCLE`
`21 error errno 1`
`22 error govgis_frontend@4.0.0 compodoc: `compodoc -p tsconfig.json``
`22 error Exit status 1`
`23 error Failed at the govgis_frontend@4.0.0 compodoc script.`
`23 error This is probably not a problem with npm. There is likely additional logging output above.`
`24 verbose exit [ 1, true ]`
