### ISSUE TITLE
[BUG] Error generate documentation router path lazy

### ISSUE THREAD

**Issue by JeanCarlosMacaneiro** [compodoc/compodoc#805]
Problem Generate documentation with router lazy, may class main context with contain load children  in declaration router, these are the files of my project:

`Packege.json
{
  "name": "angular-material-designer",
  "version": "0.0.0",
  "scripts": {
    "compodoc": "npx compodoc -p ./src/tsconfig.app.json -w -s",
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build", 
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^7.2.15",
    "@angular/cdk": "^7.3.7",
    "@angular/common": "^7.2.15",
    "@angular/compiler": "^7.2.15",
    "@angular/core": "^7.2.15",
    "@angular/forms": "^7.2.15",
    "@angular/http": "^7.2.15",
    "@angular/material": "^7.3.7",
    "@angular/material-moment-adapter": "^7.3.7",
    "@angular/platform-browser": "^7.2.15",
    "@angular/platform-browser-dynamic": "^7.2.15",
    "@angular/router": "^7.2.15",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "@types/exceljs": "^0.5.3",
    "chart.js": "^2.8.0",
    "core-js": "^2.6.8",
    "exceljs": "^1.13.0",
    "file-saver": "^2.0.2",
    "fsevents": "^1.2.9",
    "hammerjs": "^2.0.8",
    "html2canvas": "^1.0.0-rc.1",
    "jspdf": "^1.5.3",
    "jspdf-autotable": "^3.1.1",
    "material-design-icons": "^3.0.1",
    "ngx-cookie-service": "^2.2.0",
    "ngx-device-detector": "^1.3.9",
    "rxjs": "^6.5.2",
    "uuid": "^3.3.2",
    "zone.js": "^0.8.29"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.13.9",
    "@angular/cli": "^7.3.9",
    "@angular/compiler-cli": "^7.2.15",
    "@angular/language-service": "^7.2.15",
    "@compodoc/compodoc": "^1.1.9",
    "@types/jasmine": "^2.8.16",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.5",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "^5.4.2",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.1",
    "webpack-dev-server": "^3.7.2"
  }
}`

this is the file 
`/**
 * Sistema de navegación del modulo 
 * principal del proyecto
 */
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { ConstantsApp } from 'src/app/constants/constants-app';
import { AuthGuard } from 'src/app/auth-guard';
import { UserManagerCrudComponent } from '../../components/views/user-manager/user-manager-crud/user-manager-crud.component';
import { UserManagerFormComponent } from '../../components/views/user-manager/user-manager-form/user-manager-form/user-manager-form.component';
import { RolesManagerCrudComponent } from '../../components/views/roles-manager/roles-manager-crud/roles-manager-crud.component';
import { RolesManagerFormComponent } from '../../components/views/roles-manager/roles-manager-form/form/roles-manager-form.component';
import { UserSettingComponent } from '../../components/views/user-setting/user-setting/user-setting.component';
import { BrowserFileFormComponent } from '../../components/views/browser-files/form/browser-file-form/browser-file-form.component';
import { ValidationManagerCrudComponent } from '../../components/views/validation-manager/validation-manager-crud/validation-manager-crud.component';
import { ValidationManagerFormComponent } from '../../components/views/validation-manager/validation-manager-form/form/validation-manager-form/validation-manager-form.component';
import { ResourcesCrudComponent } from '../../components/views/resources-manager/resources-crud/resources-crud.component';
import { ResourcesFormComponent } from '../../components/views/resources-manager/resources-form/form/resources-form.component';
import { CollecManagementResponseCrudComponent } from '../../components/views/collec-management-response/collec-management-response-crud/collec-management-response-crud.component';
import { CollecManagementResponseFormComponent } from '../../components/views/collec-management-response/collec-management-response-form/form/collec-management-response-form.component';
import { CedantCompanyCrudComponent } from '../../components/views/cedant-company-manager/cedant-company-crud/cedant-company-crud.component';
import { CedantCompanyFormComponent } from '../../components/views/cedant-company-manager/cedant-company-form/form/cedant-company-form.component';
import { CollectActionsCrudComponent } from '../../components/views/collect-actions/collect-actions-crud/collect-actions-crud.component';
import { CollectActionsFormComponent } from '../../components/views/collect-actions/collect-actions-form/form/collect-actions-form.component';
import { CollectCourtCrudComponent } from '../../components/views/collect-court/collect-court-crud/collect-court-crud.component';
import { CollectCourtFormComponent } from '../../components/views/collect-court/collect-court-form/form/collect-court-form.component';
import { CollectPhaseCrudComponent } from '../../components/views/collect-phase-manager/collect-phase-crud/collect-phase-crud.component';
import { CollectPhaseFormComponent } from '../../components/views/collect-phase-manager/collect-phase-form/form/collect-phase-form.component';
import { CollectCompaniesCrudComponent } from '../../components/views/collect-companies/collect-companies-crud/collect-companies-crud.component';
import { CollectCompaniesFormComponent } from '../../components/views/collect-companies/collect-companies-form/form/collect-companies-form.component';
import { CollectPaymentTypeCrudComponent } from '../../components/views/collect-payment-type/collect-payment-type-crud/collect-payment-type-crud.component';
import { CollectPaymentTypeFormComponent } from '../../components/views/collect-payment-type/collect-payment-type-form/form/collect-payment-type-form.component';
import { CurrencyManagerCrudComponent } from '../../components/views/currency-manager/currency-manager-crud/currency-manager-crud.component';
import { CurrencyManagerFormComponent } from '../../components/views/currency-manager/currency-manager-form/form/currency-manager-form/currency-manager-form.component';
import { GeoUnitCrudComponent } from '../../components/views/geo-unit-manager/geo-unit-crud/geo-unit-crud.component';
import { GeoUniManagerFormComponent } from '../../components/views/geo-unit-manager/geo-unit-manager-form/form/geo-uni-manager-form/geo-uni-manager-form.component';
import { AttributeManagerCrudComponent } from '../../components/views/attribute-manager/attribute-manager-crud/attribute-manager-crud.component';
import { AttributeManagerFormComponent } from '../../components/views/attribute-manager/attribute-manager-form/form/attribute-manager-form/attribute-manager-form.component';
import { ParameterSystemCrudComponent } from '../../components/views/parameter-system/parameter-system-crud/parameter-system-crud.component';
import { ParameterSystemFormComponent } from '../../components/views/parameter-system/parameter-system-form/form/parameter-system-form.component';
import { RuleTypeManagerCrudComponent } from '../../components/views/rule-type-manager/rule-type-manager-crud/rule-type-manager-crud.component';
import { RuleTypeFormComponent } from '../../components/views/rule-type-manager/rule-type-form/form/rule-type-form/rule-type-form.component';
import { DebtorManagementCrudComponent } from '../../components/views/debtor-management/debtor-management-crud/debtor-management-crud.component';
import { DebtorManagementFormComponent } from '../../components/views/debtor-management/debtor-management-form/form/debtor-management-form/debtor-management-form.component';
import { CollectStrategiesCrudComponent } from '../../components/views/collect-strategies/collect-strategies-crud/collect-strategies-crud.component';
import { CollectStrategiesFormComponent } from '../../components/views/collect-strategies/collect-court-form/form/collect-strategies-form.component';
import { CollectCampaingCrudComponent } from '../../components/views/collect-campaing/collect-campaing-crud/collect-campaing-crud.component';
import { CollectCampaingFormComponent } from '../../components/views/collect-campaing/collect-campaing-form/form/collect-campaing-form.component';
import { CollectExceptionCrudComponent } from '../../components/views/collect-exception/collect-exception-rule-crud/collect-exception-crud.component';
import { CollectExceptionFormComponent } from '../../components/views/collect-exception/collect-exeption-form/form/collect-exception-form.component';
import { SideNavBarComponent } from 'src/app/components/views/main-context/side-nav-bar/side-nav-bar.component';
import { CollectAssigningsReportCrudComponent } from 'src/app/components/views/collect-assignings-report/collect-assignings-report-crud/collect-assignings-report-crud.component';
import { collectStrategiesCompaniesResumeReportCrudComponent } from 'src/app/components/views/collect-strategies-companies-resume-report/collect-strategies-companies-resume-report-crud/collect-strategies-companies-resume-report-crud.component';
import { collectAssigningSimulationCrudComponent } from 'src/app/components/views/collect-assigning-simulation/collect-assigning-simulation-crud/collect-assigning-simulation-crud.component';
import { CollectPreassignCrudComponent } from 'src/app/components/views/collect-preassign/collect-preassign-crud/collect-preassign-crud.component';
import { CollectPreassignFormComponent } from 'src/app/components/views/collect-preassign/collect-preassign-form/form/collect-preassign-form.component';
import { CollectJudicialStatusCrudComponent } from 'src/app/components/views/collect-judicial-status/collect-judicial-status-crud/collect-judicial-status-crud.component';
import { CollectJudicialStatusFormComponent } from 'src/app/components/views/collect-judicial-status/collect-judicial-status-form/form/collect-judicial-status-form.component';

/**
 * Todas rutas del main contex
 */
export const routesChildrenMainContext:Routes = [
  /**
  * USER MANAGEMENTS
  */
 { path: ConstantsApp.ROUTINGS_PATH.USER_MANAGER, component:UserManagerCrudComponent, outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 { path: ConstantsApp.ROUTINGS_PATH.USER_MANAGER_FORM, component:UserManagerFormComponent, outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 
 /**
  * ROLES MANAGEMENTS
  */
 { path: ConstantsApp.ROUTINGS_PATH.ROLES_MANAGER, component:RolesManagerCrudComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 { path: ConstantsApp.ROUTINGS_PATH.ROLES_MANAGER_FORMS, component:RolesManagerFormComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 
 /**
  * USER SETTINGS
  */
 { path: ConstantsApp.ROUTINGS_PATH.USER_SETTING, component:UserSettingComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },

 /**
  * FILE EXPLORE 
  */
 { path: ConstantsApp.ROUTINGS_PATH.BROWSER_FILES_BANNER, component:BrowserFileFormComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 { path: ConstantsApp.ROUTINGS_PATH.BROWSER_FILES_EXT_COB_OUT, component:BrowserFileFormComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 { path: ConstantsApp.ROUTINGS_PATH.BROWSER_FILES_EXT_COB_IN, component:BrowserFileFormComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },

 /**
  * VALIDATION MANAGEMENTS
  */
 { path: ConstantsApp.ROUTINGS_PATH.VALIDATION_MANAGER, component:ValidationManagerCrudComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 { path: ConstantsApp.ROUTINGS_PATH.VALIDATION_MANAGER_FORMS, component:ValidationManagerFormComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },

 /**
  * RESOURCES MANAGER
  */
 { path: ConstantsApp.ROUTINGS_PATH.RESOURCES_MANAGER, component:ResourcesCrudComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 { path: ConstantsApp.ROUTINGS_PATH.RESOURCES_FORM, component:ResourcesFormComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },

 /**
  * Collect Response manager
  */
 { path: ConstantsApp.ROUTINGS_PATH.COLLECT_MANAGER_RESPONSE, component:CollecManagementResponseCrudComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 { path: ConstantsApp.ROUTINGS_PATH.COLLECT_MANAGER_RESPONSE_FORM, component:CollecManagementResponseFormComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },

 /**
  * CEDANT COMPANY MANAGER
  */
 { path: ConstantsApp.ROUTINGS_PATH.CENDANT_COMPANY_MANAGER, component:CedantCompanyCrudComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 { path: ConstantsApp.ROUTINGS_PATH.CENDANT_COMPANY_FORM, component:CedantCompanyFormComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },

 /**
  * COLLECT ACTIONS
  */
 { path: ConstantsApp.ROUTINGS_PATH.COLLECT_ACTIONS, component:CollectActionsCrudComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 { path: ConstantsApp.ROUTINGS_PATH.COLLECT_ACTIONS_FORM, component:CollectActionsFormComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },

 /**
  * COLLECT COURT
  */
 { path: ConstantsApp.ROUTINGS_PATH.COLLECT_COURT, component:CollectCourtCrudComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 { path: ConstantsApp.ROUTINGS_PATH.COLLECT_COURT_FORM, component:CollectCourtFormComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 /**
  * COLLECT PHASE MANAGER
  */
 { path: ConstantsApp.ROUTINGS_PATH.COLLECT_PHASE_MANAGER, component:CollectPhaseCrudComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 { path: ConstantsApp.ROUTINGS_PATH.COLLECT_COLLECT_FORM, component:CollectPhaseFormComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 
 /**
  * COLLECT COMPANIES
  */
 { path: ConstantsApp.ROUTINGS_PATH.COLLECT_COMPANIES, component:CollectCompaniesCrudComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 { path: ConstantsApp.ROUTINGS_PATH.COLLECT_COMPANIES_FORM, component:CollectCompaniesFormComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },

 /**
  * COLLECT PAYMENT TYPE
  */
 { path: ConstantsApp.ROUTINGS_PATH.COLLECT_PAYMENT_TYPE, component:CollectPaymentTypeCrudComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 { path: ConstantsApp.ROUTINGS_PATH.COLLECT_PAYMENT_TYPE_FORM, component:CollectPaymentTypeFormComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },

 /**
  * CURRENCY
  */
 { path: ConstantsApp.ROUTINGS_PATH.CURRENCY_MANAGER, component:CurrencyManagerCrudComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 { path: ConstantsApp.ROUTINGS_PATH.CURRENCY_MANAGER_FORM, component:CurrencyManagerFormComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },

 /**
  * GEO UNIT
  */
 { path: ConstantsApp.ROUTINGS_PATH.GEO_UNIT_MANAGER, component:GeoUnitCrudComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 { path: ConstantsApp.ROUTINGS_PATH.GEO_UNIT_FORM, component:GeoUniManagerFormComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },

 /**
   * ATTRIBUTE
   */
 { path: ConstantsApp.ROUTINGS_PATH.ATTRIBUTE_MANAGER, component:AttributeManagerCrudComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 { path: ConstantsApp.ROUTINGS_PATH.ATTRIBUTE_FORM, component:AttributeManagerFormComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 
 /**
  * PARAMETER_SYSTEM
  */
 { path: ConstantsApp.ROUTINGS_PATH.PARAMETER_SYSTEM, component:ParameterSystemCrudComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 { path: ConstantsApp.ROUTINGS_PATH.PARAMETER_SYSTEM_FORM, component:ParameterSystemFormComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },

 /**
  * RULE_TYPE
  */
 { path: ConstantsApp.ROUTINGS_PATH.RULE_TYPE_MANAGER, component:RuleTypeManagerCrudComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 { path: ConstantsApp.ROUTINGS_PATH.RULE_TYPE_FORM, component:RuleTypeFormComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 
 /**
  * DEPTOR_MANAGENENTS
  */
 { path: ConstantsApp.ROUTINGS_PATH.DEPTOR_MANAGER, component:DebtorManagementCrudComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 { path: ConstantsApp.ROUTINGS_PATH.DEPTOR_MANAGER_FORM, component:DebtorManagementFormComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 
 /**
  * DEPTOR_MANAGENENTS
  */
 { path: ConstantsApp.ROUTINGS_PATH.COLLECT_STRATEGIES, component:CollectStrategiesCrudComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 { path: ConstantsApp.ROUTINGS_PATH.COLLECT_STRATEGIES_FORM, component:CollectStrategiesFormComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },

 /**
  * Collect Campaing
  */
 { path: ConstantsApp.ROUTINGS_PATH.COLLECT_CAMPAING, component:CollectCampaingCrudComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 { path: ConstantsApp.ROUTINGS_PATH.COLLECT_CAMPAING_FORM, component:CollectCampaingFormComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 
 /**
  * Collect Exception
  */
 { path: ConstantsApp.ROUTINGS_PATH.COLLECT_EXCEPTION, component:CollectExceptionCrudComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 { path: ConstantsApp.ROUTINGS_PATH.COLLECT_EXCEPTION_FORM, component:CollectExceptionFormComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },

 /**
  * Collect AsigningsReport
  */
 { path: ConstantsApp.ROUTINGS_PATH.COLLECT_ASIGNGS_REPORT, component:CollectAssigningsReportCrudComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 

 /**
  * Collect Preassign
  */
 { path: ConstantsApp.ROUTINGS_PATH.COLLECT_PREASSIGN, component:CollectPreassignCrudComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 { path: ConstantsApp.ROUTINGS_PATH.COLLECT_PREASSIGN_FORM, component:CollectPreassignFormComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },

 
 /**
  * Collect Companies and strategies resume 
  */
 { path: ConstantsApp.ROUTINGS_PATH.COLLECT_RESUME_STRATEGIES_COMPANIES_REPORT, component:collectStrategiesCompaniesResumeReportCrudComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 
 /**
  * Collect Companies and strategies resume 
  */
 { path: ConstantsApp.ROUTINGS_PATH.COLLECT_SIMULATION_ASSINGING, component:collectAssigningSimulationCrudComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 
 /**
  * Collect Companies and strategies resume 
  */
 { path: ConstantsApp.ROUTINGS_PATH.COLLECT_JUDICIAL_STATUS, component:CollectJudicialStatusCrudComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },
 { path: ConstantsApp.ROUTINGS_PATH.COLLECT_JUDICAL_STATUS_FORM, component:CollectJudicialStatusFormComponent,  outlet: ConstantsApp.ROUTINGS_PATH.MAIN_ROUTER_OUTLET, canActivate: [AuthGuard]  },

];

export const routesMainContext: Routes = [

  /** Default view Main context*/
  { path: ConstantsApp.ROUTINGS_PATH.MAIN_CONTEXT_DASHBOARD, component:SideNavBarComponent, children:routesChildrenMainContext, canActivate: [AuthGuard], } 

];

@NgModule({
  imports: [
    RouterModule.forChild(routesMainContext)
  ],
  exports: [RouterModule]
})
export class MainContextModuleRoutingModule { }
`

definition constant class
`
export const ConstantsApp = {
     /**
     * Routing app definitions
     */
    ROUTINGS_PATH:{
        DASHBOARD:"dashboard",
          ...
    }
}`

Logg error 
`
[16:34:18] parsing        : /Users/jmacaneiro/Documents/Projects/microservice-angular-project-base/front-end/src/app/modules/main-context-module/main-context-routing.module.ts
[16:34:18] Analysing routes definitions and clean them if necessary
Unhandled Rejection at: Promise {
  <rejected> Error: Could not find the node's symbol.
      at InvalidOperationError.BaseError [as constructor] (/Users/jmacaneiro/Documents/Projects/microservice-angular-project-base/front-end/node_modules/ts-simple-ast/dist/errors/BaseError.js:7:28)
      at new InvalidOperationError (/Users/jmacaneiro/Documents/Projects/microservice-angular-project-base/front-end/node_modules/ts-simple-ast/dist/errors/InvalidOperationError.js:8:28)
      at Object.throwIfNullOrUndefined (/Users/jmacaneiro/Documents/Projects/microservice-angular-project-base/front-end/node_modules/ts-simple-ast/dist/errors/helpers.js:96:15)
      at Identifier.Node.getSymbolOrThrow (/Users/jmacaneiro/Documents/Projects/microservice-angular-project-base/front-end/node_modules/ts-simple-ast/dist/compiler/common/Node.js:131:23)
      at RouterParserUtil.cleanFileDynamics (/Users/jmacaneiro/Documents/Projects/microservice-angular-project-base/front-end/node_modules/@compodoc/compodoc/dist/index-cli.js:4923:18)
      at AngularDependencies.getSourceFileDecorators (/Users/jmacaneiro/Documents/Projects/microservice-angular-project-base/front-end/node_modules/@compodoc/compodoc/dist/index-cli.js:7410:46)
      at /Users/jmacaneiro/Documents/Projects/microservice-angular-project-base/front-end/node_modules/@compodoc/compodoc/dist/index-cli.js:7218:31
      at Array.map (<anonymous>)
      at AngularDependencies.getDependencies (/Users/jmacaneiro/Documents/Projects/microservice-angular-project-base/front-end/node_modules/@compodoc/compodoc/dist/index-cli.js:7207:21)
      at CliApplication.Application.getDependenciesData (/Users/jmacaneiro/Documents/Projects/microservice-angular-project-base/front-end/node_modules/@compodoc/compodoc/dist/index-cli.js:8757:40) } reason: Error: Could not find the node's symbol.
    at InvalidOperationError.BaseError [as constructor] (/Users/jmacaneiro/Documents/Projects/microservice-angular-project-base/front-end/node_modules/ts-simple-ast/dist/errors/BaseError.js:7:28)
    at new InvalidOperationError (/Users/jmacaneiro/Documents/Projects/microservice-angular-project-base/front-end/node_modules/ts-simple-ast/dist/errors/InvalidOperationError.js:8:28)
    at Object.throwIfNullOrUndefined (/Users/jmacaneiro/Documents/Projects/microservice-angular-project-base/front-end/node_modules/ts-simple-ast/dist/errors/helpers.js:96:15)
    at Identifier.Node.getSymbolOrThrow (/Users/jmacaneiro/Documents/Projects/microservice-angular-project-base/front-end/node_modules/ts-simple-ast/dist/compiler/common/Node.js:131:23)
    at RouterParserUtil.cleanFileDynamics (/Users/jmacaneiro/Documents/Projects/microservice-angular-project-base/front-end/node_modules/@compodoc/compodoc/dist/index-cli.js:4923:18)
    at AngularDependencies.getSourceFileDecorators (/Users/jmacaneiro/Documents/Projects/microservice-angular-project-base/front-end/node_modules/@compodoc/compodoc/dist/index-cli.js:7410:46)
    at /Users/jmacaneiro/Documents/Projects/microservice-angular-project-base/front-end/node_modules/@compodoc/compodoc/dist/index-cli.js:7218:31
    at Array.map (<anonymous>)
    at AngularDependencies.getDependencies (/Users/jmacaneiro/Documents/Projects/microservice-angular-project-base/front-end/node_modules/@compodoc/compodoc/dist/index-cli.js:7207:21)
    at CliApplication.Application.getDependenciesData (/Users/jmacaneiro/Documents/Projects/microservice-angular-project-base/front-end/node_modules/@compodoc/compodoc/dist/index-cli.js:8757:40)
[16:34:24] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-material-designer@0.0.0 compodoc: `npx compodoc -p ./src/tsconfig.app.json -w -s`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-material-designer@0.0.0 compodoc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jmacaneiro/.npm/_logs/2019-07-08T20_34_24_096Z-debug.log
`
Pls help me.

**Comment by JeanCarlosMacaneiro** [comment]
im resolved de issue remove from import module lazy ROUTER class,
