### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cjrutherford** [compodoc/compodoc#821]
##### **Overview of the issue**

Attempting to document Non-CLI Angular 4 app. 

##### **Operating System, Node.js, npm, compodoc version(s)**
Windows 10 (18362)
Node 10.16.x
Compodoc 1.1.9
NPM 6.9.0 (Yarn 1.16.0)

##### **Angular configuration, a `package.json` file in the root folder**
```
{ //omitted description, version, and private fields
  "scripts": {
    "build": "npm run build:dev",
    "build:aot:prod": "npm run clean:dist && npm run clean:aot && cross-env BUILD_AOT=1 npm run webpack -- --config config/webpack.prod.js  --progress --profile --bail",
    "build:aot": "npm run build:aot:prod",
    "build:dev": "npm run clean:dist && npm run webpack -- --config config/webpack.dev.js --progress --profile --watch",
    "build:prod": "npm run clean:dist && npm run webpack -- --config config/webpack.prod.js  --progress --profile --bail",
    "ci:aot": "npm run lint && npm run test && npm run build:aot && npm run e2e",
    "ci:jit": "npm run lint && npm run test && npm run build:prod && npm run e2e",
    "ci:nobuild": "npm run lint && npm test && npm run e2e",
    "ci:testall": "npm run test && npm run build:prod && npm run e2e && npm run build:aot && npm run e2e",
    "ci:travis": "npm run lint && npm run test && npm run build:aot && npm run e2e:travis",
    "ci": "npm run ci:testall",
    "clean:dll": "npm run rimraf -- dll",
    "clean:aot": "npm run rimraf -- compiled",
    "clean:dist": "npm run rimraf -- ../OnCare_MVC_4/Areas/App/build/dist",
    "clean:install": "npm set progress=false && npm install",
    "clean": "npm cache clean --force && npm run rimraf -- node_modules doc coverage dist compiled dll",
    "compodoc":"compodoc",
    "e2e:live": "npm-run-all -p -r server:prod:ci protractor:live",
    "e2e:travis": "npm-run-all -p -r server:prod:ci protractor:delay",
    "e2e": "npm-run-all -p -r server:prod:ci protractor",
    "generate-docs":"compodoc -p app/tsconfig.json",
    "node": "node",
    "postinstall": "npm run webdriver:update",
    "postversion": "git push && git push --tags",
    "preclean:install": "npm run clean",
    "preversion": "npm test",
    "protractor": "protractor",
    "protractor:delay": "sleep 3 && npm run protractor",
    "protractor:live": "protractor --elementExplorer",
    "rimraf": "rimraf",
    "serve-docs":"compodoc -s app/tsconfig.json",
    "server:dev:hmr": "npm run server:dev -- --hotOnly",
    "server:dev": "npm run webpack-dev-server -- --config config/webpack.dev.js --open --progress --profile --watch --content-base t",
    "server:prod": "http-server dist -c-1 --cors",
    "server:prod:ci": "http-server dist -p 3000 -c-1 --cors",
    "server": "npm run server:dev",
    "start:hmr": "npm run server:dev:hmr",
    "start": "npm run server:dev",
    "test": "karma start",
    "tslint": "tslint",
    "typedoc": "typedoc",
    "watch:dev:hmr": "npm run watch:dev -- --hot",
    "watch:dev": "npm run build:dev -- --watch",
    "watch:prod": "npm run build:prod -- --watch",
    "watch:test": "npm run test -- --auto-watch --no-single-run",
    "watch": "npm run watch:dev",
    "webdriver-manager": "webdriver-manager",
    "webdriver:start": "npm run webdriver-manager start",
    "webdriver:update": "webdriver-manager update",
    "webpack-dev-server": "node --max_old_space_size=4096 node_modules/webpack-dev-server/bin/webpack-dev-server.js",
    "webpack": "node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js"
  },
  "dependencies": {
    "@angular/animations": "5.2.9",
    "@angular/common": "4.3.5",
    "@angular/compiler": "4.3.5",
    "@angular/compiler-cli": "4.3.5",
    "@angular/core": "4.3.5",
    "@angular/forms": "4.3.5",
    "@angular/http": "4.3.5",
    "@angular/platform-browser": "4.3.5",
    "@angular/platform-browser-dynamic": "4.3.5",
    "@angular/platform-server": "4.3.5",
    "@angular/router": "4.3.5",
    "@angular/upgrade": "4.3.5",
    "@angularclass/hmr": "~2.1.3",
    "@angularclass/hmr-loader": "^3.0.4",
    "angular-sortablejs": "^2.5.2",
    "angular2-datatable": "^0.6.0",
    "bootstrap": "3.3.7",
    "chart.js": "^2.7.1",
    "core-js": "2.5.0",
    "ie-shim": "0.1.0",
    "intl": "1.2.5",
    "jquery": "3.2.1",
    "jsonwebtoken": "^8.5.1",
    "lodash": "^4.17.11",
    "modernizr": "^3.6.0",
    "moment": "^2.18.1",
    "ng2-charts": "1.6.0",
    "ng2-daterangepicker": "^2.0.12",
    "ng2-scroll-to": "^1.0.7",
    "ng2-select": "1.2.0",
    "ng2-table": "1.3.2",
    "ngx-bootstrap": "1.8.1",
    "ngx-cookie-service": "^2.2.0",
    "ngx-slimscroll": "^3.7.0",
    "optimize-js-plugin": "0.0.4",
    "popper.js": "^1.12.5",
    "reflect-metadata": "^0.1.10",
    "rxjs": "5.4.3",
    "sortablejs": "^1.7.0",
    "systemjs": "^0.20.18",
    "ts-helpers": "1.1.1",
    "xlsx": "^0.11.18",
    "zone.js": "0.8.16"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~4.3.1",
    "@compodoc/compodoc": "^1.0.0-beta.15",
    "@types/bootstrap": "^3.3.36",
    "@types/hammerjs": "^2.0.34",
    "@types/jasmine": "2.5.45",
    "@types/jasminewd2": "2.0.2",
    "@types/jquery": "^3.2.12",
    "@types/lodash": "4.14.103",
    "@types/node": "^7.0.39",
    "@types/source-map": "^0.5.0",
    "@types/uglify-js": "^2.6.28",
    "@types/webpack": "^2.2.16",
    "add-asset-html-webpack-plugin": "^2.1.2",
    "angular2-template-loader": "^0.6.2",
    "assets-webpack-plugin": "^3.5.1",
    "awesome-typescript-loader": "~3.4.1",
    "codelyzer": "~2.1.1",
    "copy-webpack-plugin": "^4.4.1",
    "cross-env": "^5.0.0",
    "css-loader": "^0.28.9",
    "exports-loader": "^0.6.4",
    "expose-loader": "^0.7.3",
    "extract-text-webpack-plugin": "~3.0.0",
    "file-loader": "^0.11.1",
    "find-root": "^1.0.0",
    "friendly-errors-webpack-plugin": "^1.6.1",
    "gh-pages": "^1.0.0",
    "html-webpack-plugin": "^2.28.0",
    "imports-loader": "^0.7.1",
    "inline-manifest-webpack-plugin": "^3.0.1",
    "istanbul-instrumenter-loader": "2.0.0",
    "jasmine-core": "^2.5.2",
    "jasmine-spec-reporter": "4.1.0",
    "karma": "^4.0.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "1.0.1",
    "karma-coverage": "^1.1.1",
    "karma-jasmine": "^1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "karma-mocha-reporter": "^2.2.3",
    "karma-read-json": "1.1.0",
    "karma-remap-coverage": "^0.1.4",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^2.0.4",
    "loaders.css": "0.1.2",
    "napa": "3.0.0",
    "ng-router-loader": "^2.1.0",
    "ngc-webpack": "^3.2.0",
    "node-sass": "^4.5.3",
    "npm-run-all": "^4.0.2",
    "optimize-js-plugin": "0.0.4",
    "parse5": "^3.0.2",
    "preload-webpack-plugin": "^1.2.2",
    "protractor": "^5.1.1",
    "raw-loader": "0.5.1",
    "rimraf": "~2.6.1",
    "sass-loader": "^6.0.3",
    "script-ext-html-webpack-plugin": "^1.8.5",
    "source-map-loader": "^0.2.3",
    "string-replace-loader": "~1.3.0",
    "style-loader": "^0.18.1",
    "to-string-loader": "^1.1.5",
    "ts-node": "^3.3.0",
    "tslib": "^1.7.1",
    "tslint": "~4.5.1",
    "tslint-loader": "^3.5.3",
    "typedoc": "^0.7.1",
    "typescript": "^2.4.2",
    "uglifyjs-webpack-plugin": "^1.1.8",
    "url-loader": "^0.6.2",
    "webdriver-manager": "12.0.6",
    "webpack": "^3.11.0",
    "webpack-dev-middleware": "^2.0.5",
    "webpack-dev-server": "^3.1.14",
    "webpack-dll-bundles-plugin": "^1.0.0-beta.5",
    "webpack-merge": "~4.1.1"
  }
}
```

##### **Compodoc installed globally or locally ?**
Both (as dep, and globally)

##### **If possible sourcecode of the file where it breaks**
From what I can see, the error is occurring here:

```
import * as pages from './pages';
import { DashboardLayoutComponent } from './pages/dashboard/dashboard-layout/dashboard-layout.component';
import { AccountingGuard, DashboardGuard } from './guards';
import { AccountingUserRole } from './enums';

const appRoutes: Routes = [
    {
        path: '',
        component: pages.HubPage,
        children: [
            {
                path: '',
                pathMatch: 'full',
                redirectTo: 'invoice',
            },
```

I'm not sure if this is related to HubPage being imported from the `import * as pages from './pages';` section.

##### **If possible your terminal logs before the error**

> 12:36:36] Analysing routes definitions and clean them if necessary
Unhandled Rejection at: Promise {
  <rejected> Error: Expected to find the value declaration of symbol 'HubPage'.
      at InvalidOperationError.BaseError [as constructor] (C:\Users\chris\Source\Workspaces\Apps.Oncare\feature-Dev-chris\Oncare.Web.App\node_modules\ts-simple-ast\dist\errors\BaseError.js:7:28)
      at new InvalidOperationError (C:\Users\chris\Source\Workspaces\Apps.Oncare\feature-Dev-chris\Oncare.Web.App\node_modules\ts-simple-ast\dist\errors\InvalidOperationError.js:8:28)
      at Object.throwIfNullOrUndefined (C:\Users\chris\Source\Workspaces\Apps.Oncare\feature-Dev-chris\Oncare.Web.App\node_modules\ts-simple-ast\dist\errors\helpers.js:96:15)
      at Symbol.getValueDeclarationOrThrow (C:\Users\chris\Source\Workspaces\Apps.Oncare\feature-Dev-chris\Oncare.Web.App\node_modules\ts-simple-ast\dist\compiler\common\Symbol.js:72:23)
      at RouterParserUtil.cleanFileDynamics (C:\Users\chris\Source\Workspaces\Apps.Oncare\feature-Dev-chris\Oncare.Web.App\node_modules\@compodoc\compodoc\dist\index-cli.js:5445:18)
      at AngularDependencies.getSourceFileDecorators (C:\Users\chris\Source\Workspaces\Apps.Oncare\feature-Dev-chris\Oncare.Web.App\node_modules\@compodoc\compodoc\dist\index-cli.js:7928:46)
      at C:\Users\chris\Source\Workspaces\Apps.Oncare\feature-Dev-chris\Oncare.Web.App\node_modules\@compodoc\compodoc\dist\index-cli.js:7736:31
      at Array.map (<anonymous>)
      at CliApplication.Application.getDependenciesData (C:\Users\chris\Source\Workspaces\Apps.Oncare\feature-Dev-chris\Oncare.Web.App\node_modules\@compodoc\compodoc\dist\index-cli.js:9277:40) } reason: Error: Expected to find the value declaration of symbol 'HubPage'.
    at new InvalidOperationError (C:\Users\chris\Source\Workspaces\Apps.Oncare\feature-Dev-chris\Oncare.Web.App\node_modules\ts-simple-ast\dist\errors\InvalidOperationError.js:8:28)
    at Symbol.getValueDeclarationOrThrow (C:\Users\chris\Source\Workspaces\Apps.Oncare\feature-Dev-chris\Oncare.Web.App\node_modules\ts-simple-ast\dist\compiler\common\Symbol.js:72:23)
    at AngularDependencies.getSourceFileDecorators (C:\Users\chris\Source\Workspaces\Apps.Oncare\feature-Dev-chris\Oncare.Web.App\node_modules\@compodoc\compodoc\dist\index-cli.js:7928:46)
    at C:\Users\chris\Source\Workspaces\Apps.Oncare\feature-Dev-chris\Oncare.Web.App\node_modules\@compodoc\compodoc\dist\index-cli.js:7736:31
    at Array.map (<anonymous>)
    at AngularDependencies.getDependencies (C:\Users\chris\Source\Workspaces\Apps.Oncare\feature-Dev-chris\Oncare.Web.App\node_modules\@compodoc\compodoc\dist\index-cli.js:7725:21)
    at CliApplication.Application.getDependenciesData (C:\Users\chris\Source\Workspaces\Apps.Oncare\feature-Dev-chris\Oncare.Web.App\node_modules\@compodoc\compodoc\dist\index-cli.js:9277:40)
[12:36:41] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

##### **Motivation for or Use Case**
Wanted to auto document an inherited application.

##### **Reproduce the error**
simply running `npm run generate-docs` on the application.

**Comment by cjrutherford** [comment]
Appears to work fine if symbol is destructured from imported name.
