### ISSUE TITLE
[BUG] Generating Compodoc gives an error from the compodo code.

### ISSUE THREAD

**Issue by rvanboxtel** [compodoc/compodoc#867]
I use angular 8.1.3 with NGRX 8. For my application with lazy loaded modules, with this I use index.ts files.

I used the command compodoc -p tsconfig.app.json -s
I have it installed globally so I can use it in multiple projects.
But when it was installed as a dev dependency it causes the same error.

I also reinstalled it, and tried it again. but the outcome remains the same

I know it isn't an issue with my code. because the error occurs at random components.

Output:
Unhandled Rejection at: Promise {
  <rejected> SyntaxError: JSON5: invalid character '.' at 1:241
      at syntaxError (\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1083:17)
      at invalidChar (\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1028:12)
      at Object.afterPropertyValue (\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:654:15)  
      at Object.default (\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:146:37)
      at lex (\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:78:42)
      at Object.parse (\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:25:17)
      at loopInsideModule (\npm\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:5370:52)
      at loopRoutesParser (\npm\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:5403:29)
      at loopRoutesParser (\npm\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:5408:21)
      at RouterParserUtil.constructRoutesTree (\npm\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:5412:9) {
    lineNumber: 1,
    columnNumber: 241
  }
} reason: SyntaxError: JSON5: invalid character '.' at 1:241
    at syntaxError (\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1083:17)
    at invalidChar (\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:1028:12)
    at Object.afterPropertyValue (\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:654:15)    
    at Object.default (\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:146:37)
    at lex (\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:78:42)
    at Object.parse (\npm\node_modules\@compodoc\compodoc\node_modules\json5\lib\parse.js:25:17)
    at loopInsideModule (\npm\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:5370:52)
    at loopRoutesParser (\npm\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:5403:29)
    at loopRoutesParser (\npm\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:5408:21)
    at RouterParserUtil.constructRoutesTree (\npm\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:5412:9) {
  lineNumber: 1,
  columnNumber: 241
}

**Comment by mhamern** [comment]
Same in our project, without the NGRX 8.
