### ISSUE TITLE
Can't run compodoc unicode-trie error

### ISSUE THREAD

**Issue by pipoec** [compodoc/compodoc#874]
I am developing an Ionic project.

I have this on my package.json

`    "compodoc": "./node_modules/.bin/compodoc -p tsconfig.json -w -s"`

```
"devDependencies": {
    "@angular-devkit/architect": "~0.801.2",
    "@angular-devkit/build-angular": "~0.801.2",
    "@angular-devkit/core": "~8.1.2",
    "@angular-devkit/schematics": "~8.1.2",
    "@angular/cli": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/compiler-cli": "~8.1.2",
    "@angular/language-service": "~8.1.2",
    "@compodoc/compodoc": "^1.1.11", (...)
```

and after running npm run compodoc this appears:

```
/Users/(...)/node_modules/unicode-trie/index.js:87
      data = inflate(data, new Uint8Array(uncompressedLength));
                           ^

RangeError: Invalid typed array length: 4034658560
```

I have cleared cache, deleted node modules and run again` npm install `but it is still 
showing that error.

**Operating System, Node.js, npm, compodoc version(s)**
MacOs Catalina v10.15
Node.js : v12.13.0
npm : v6.12.0
compodoc: v1.1.11

**Compodoc installed globally or locally ?**
I installed both.

**If possible your terminal logs before the error**
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'compodoc' ]
2 info using npm@6.12.0
3 info using node@v12.13.0
4 verbose run-script [ 'precompodoc', 'compodoc', 'postcompodoc' ]
5 info lifecycle base-ionic-bayteq@0.0.1~precompodoc: base-ionic-bayteq@0.0.1
6 info lifecycle base-ionic-bayteq@0.0.1~compodoc: base-ionic-bayteq@0.0.1
7 verbose lifecycle base-ionic-bayteq@0.0.1~compodoc: unsafe-perm in lifecycle true
8 verbose lifecycle base-ionic-bayteq@0.0.1~compodoc: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/joseb/Developer/Bayteq/base-angular-ionic/Base-Ionic/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Cellar/mongodb-community-shell/4.2.0/bin
9 verbose lifecycle base-ionic-bayteq@0.0.1~compodoc: CWD: /Users/joseb/Developer/Bayteq/base-angular-ionic/Base-Ionic
10 silly lifecycle base-ionic-bayteq@0.0.1~compodoc: Args: [ '-c', 'compodoc -p tsconfig.json -w -s' ]
11 silly lifecycle base-ionic-bayteq@0.0.1~compodoc: Returned: code: 1  signal: null
12 info lifecycle base-ionic-bayteq@0.0.1~compodoc: Failed to exec compodoc script
13 verbose stack Error: base-ionic-bayteq@0.0.1 compodoc: `compodoc -p tsconfig.json -w -s`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid base-ionic-bayteq@0.0.1
15 verbose cwd /Users/joseb/Developer/Bayteq/base-angular-ionic/Base-Ionic
16 verbose Darwin 19.0.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "compodoc"
18 verbose node v12.13.0
19 verbose npm  v6.12.0
20 error code ELIFECYCLE
21 error errno 1
22 error base-ionic-bayteq@0.0.1 compodoc: `compodoc -p tsconfig.json -w -s`
22 error Exit status 1
23 error Failed at the base-ionic-bayteq@0.0.1 compodoc script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Motivation for or Use Case**
I really want to add compodoc to this project. Please any help would be great.

**Comment by kawyua** [comment]
I ran into the same issue when trying compodoc, what i did was go to unicode-trie repository
https://github.com/foliojs/unicode-trie
In their commit history, I went to the june19, 2019 commit and downloaded their repository at that time. unzipped it then copy and pasted the files over the files in /Users/(...)/node_modules/unicode-trie 
then compodoc worked just fine

**Comment by pipoec** [comment]
Thank you! It worked!
