### ISSUE TITLE
Project local paths defined in tsconfig.json are not getting picked up by compodoc[BUG]

### ISSUE THREAD

**Issue by goldel777** [compodoc/compodoc#885]
Paths local to a project are defined in tsconfig.json. These are not getting picked up by compodoc. 
 Compodoc is reporting that it can not find the file.   

This angular project build and runs without any issue.   There is an auth.component.ts file in:

**projects/myProject/src/app/module/auth/***

I've tried adding /** @ignore */.  Unfortunately this did not help.   

Compodoc will build successfully for all the other projects if I remove this project - this project is the only using paths defined in tsconfig.json to reference files within its own directory structure.

I suspect that the Compodoc is not able disguish between scoped projects defined in tsconfig.json and ones @ annotated paths use to access local files.    Compodoc does find my scoped libararies without any issue.

**In component in **myProject/src/app/app.routing.ts**:**

import { AuthComponent } from **'@auth/auth.component';**

**In tsconfig.json:**

{
  "compileOnSave": false,
  "compilerOptions": {
    "importHelpers": true,
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "noImplicitUseStrict": true,
    "strictNullChecks": false,
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ],
    "baseUrl": "",
    "paths": {
      **"@auth/*": [
        "projects/myProject/src/app/module/auth/*"
      ]**
 },
    "module": "es2015"
  },
  "angularCompilerOptions": {
    "enableIvy": false
  }

**Throws the following error:**

3:12:09]                :     - AppComponent
[13:12:09] parsing        : .../angular/projects/myproject/src/app/app.routing.ts
[13:12:09] Analysing routes definitions and clean them if necessary
Unhandled Rejection at: Promise {myProject/src/app
  <rejected> { Error: File not found: .../angular/projects/myproject/src/app/@auth/auth-routing.module.ts
      at FileNotFoundError.BaseError [as constructor] (...\angular\node_modules\ts-simple-ast\dist\errors\BaseError.js:7:28)
      at new FileNotFoundError (...\angular\node_modules\ts-simple-ast\dist\errors\FileNotFoundError.js:8:28)
      at Project.addExistingSourceFile (...\angular\node_modules\ts-simple-ast\dist\Project.js:188:19)
      at _loop_3 (...\angular\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:5605:33)
      at RouterParserUtil.cleanFileSpreads (...\angular\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:5633:13)
      at AngularDependencies.getSourceFileDecorators (...\angular\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8150:32)
      at ...\angular\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:7960:31
      at Array.map (<anonymous>)
      at AngularDependencies.getDependencies (...\angular\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:7949:21)
      at CliApplication.Application.getDependenciesData (...\angular\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:9498:40)
    filePath:
     '.../angular/projects//@auth/auth-routing.module.ts',
    code: 'ENOENT' } } reason: { Error: File not found: C.../angular/projects/myProject/src/app/@auth/auth-routing.module.ts
    at FileNotFoundError.BaseError [as constructor] (...\angular\node_modules\ts-simple-ast\dist\errors\BaseError.js:7:28)
    at new FileNotFoundError (...\angular\node_modules\ts-simple-ast\dist\errors\FileNotFoundError.js:8:28)
    at Project.addExistingSourceFile (...\angular\node_modules\ts-simple-ast\dist\Project.js:188:19)
    at _loop_3 (...\angular\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:5605:33)
    at RouterParserUtil.cleanFileSpreads (...\angular\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:5633:13)
    at AngularDependencies.getSourceFileDecorators (...\angular\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8150:32)
    at ...\angular\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:7960:31
    at Array.map (<anonymous>)
    at AngularDependencies.getDependencies (...\angular\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:7949:21)
    at CliApplication.Application.getDependenciesData (...\angular\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:9498:40)
  filePath:
   'C.../angular/projects/myProject/src/app/@auth/auth-routing.module.ts',
  code: 'ENOENT' }
[13:12:09] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)

##### **Operating System, Node.js, npm, compodoc version(s)**

Compodoc: 1.1.11

TypeScript version used by Compodoc : 2.9.1

Node.js version : v10.16.3

Operating system : Windows 10

##### **Angular configuration, a `package.json` file in the root folder**

    "@angular-devkit/build-angular": "^0.13.9",
    "@angular/animations": "^7.2.2",
    "@angular/cdk": "^7.2.2",
    "@angular/common": "^7.2.2",
    "@angular/compiler": "^7.2.2",
    "@angular/compiler-cli": "^7.2.15",
    "@angular/core": "^7.2.2",
    "@angular/flex-layout": "^7.0.0-beta.24",
    "@angular/forms": "^7.2.2",
    "@angular/http": "^7.2.15",
    "@angular/material": "^7.2.2",
    "@angular/platform-browser": "^7.2.2",
    "@angular/platform-browser-dynamic": "^7.2.2",
    "@angular/router": "^7.2.2",

Locally 

##### **If possible sourcecode of the file where it breaks**

/**
 * @ignore
 */
import { AuthComponent } from '@auth/auth.component';

This will build and create documents if I remove this project from the projects directory.   Only this project uses the tsconfig.json file to reference files within its directory structure.

I cannot document my project without either removing the @ annotated paths - and there are quite a number of these.  

I would expect that the the program can navigate the import the same angular does.

Run from the angular directory.

npx compodoc -p tsconfig.json  

There are some issues around custom annoatations/scopes.  Not imports.

**Comment by brian428** [comment]
FYI this is caused by a longstanding bug with Compodoc's handling of Routes when they're imported using a TS path alias: https://github.com/compodoc/compodoc/issues/403

**Comment by goldel777** [comment]
Any idea if this will get corrected or not?   I think the compudoc is really great but I'd hate to have to redo one our (larger) legacy projects to get the project documented.
