### ISSUE TITLE
[BUG] TypeError: Cannot read property 'text' of undefined caused by lazy loaded route

### ISSUE THREAD

**Issue by spoilerdo** [compodoc/compodoc#895]
##### **Overview of the issue**

I have a Angular 8 project with lazy loaded routes. But when I start generating the documentation i get the following error:

```
Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'text' of undefined
      at C:\Users\MartijnDormans\OneDrive - Mediaan abs b.v\Project\Front-end\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:5691:55
      at Function.ArrayUtils.find (C:\Users\MartijnDormans\OneDrive - Mediaan abs b.v\Project\Front-end\node_modules\ts-simple-ast\dist\utils\ArrayUtils.js:38:21)
      at Object.getNodeByNameOrFindFunction (C:\Users\MartijnDormans\OneDrive - Mediaan abs b.v\Project\Front-end\node_modules\ts-simple-ast\dist\utils\compiler\getNodeByNameOrFindFunction.js:10:36)    
      at SourceFile.StatementedNode.class_1.getVariableDeclaration (C:\Users\MartijnDormans\OneDrive - Mediaan abs b.v\Project\Front-end\node_modules\ts-simple-ast\dist\compiler\statement\StatementedNode.js:312:28)
      at RouterParserUtil.cleanCallExpressions (C:\Users\MartijnDormans\OneDrive - Mediaan abs b.v\Project\Front-end\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:5688:45)
e.js:312:28)
      at RouterParserUtil.cleanCallExpressions (C:\Users\MartijnDormans\OneDrive - Mediaan abs b.v\Project\Front-end\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:5688:45)
      at AngularDependencies.getSourceFileDecorators (C:\Users\MartijnDormans\OneDrive - Mediaan abs b.v\Project\Front-end\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8151:46)
      at C:\Users\MartijnDormans\OneDrive - Mediaan abs b.v\Project\Front-end\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:7960:31
      at Array.map (<anonymous>)
      at AngularDependencies.getDependencies (C:\Users\MartijnDormans\OneDrive - Mediaan abs b.v\Project\Front-end\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:7949:21)
      at CliApplication.Application.getDependenciesData (C:\Users\MartijnDormans\OneDrive - Mediaan abs b.v\Project\Front-end\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:9498:40)       
} reason: TypeError: Cannot read property 'text' of undefined
    at C:\Users\MartijnDormans\OneDrive - Mediaan abs b.v\Project\Front-end\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:5691:55
    at Function.ArrayUtils.find (C:\Users\MartijnDormans\OneDrive - Mediaan abs b.v\Project\Front-end\node_modules\ts-simple-ast\dist\utils\ArrayUtils.js:38:21)
    at Object.getNodeByNameOrFindFunction (C:\Users\MartijnDormans\OneDrive - Mediaan abs b.v\Project\Front-end\node_modules\ts-simple-ast\dist\utils\compiler\getNodeByNameOrFindFunction.js:10:36)      
    at SourceFile.StatementedNode.class_1.getVariableDeclaration (C:\Users\MartijnDormans\OneDrive - Mediaan abs b.v\Project\Front-end\node_modules\ts-simple-ast\dist\compiler\statement\StatementedNode.js:312:28)
    at RouterParserUtil.cleanCallExpressions (C:\Users\MartijnDormans\OneDrive - Mediaan abs b.v\Project\Front-end\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:5688:45)
    at AngularDependencies.getSourceFileDecorators (C:\Users\MartijnDormans\OneDrive - Mediaan abs b.v\Project\Front-end\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8151:46)
    at C:\Users\MartijnDormans\OneDrive - Mediaan abs b.v\Project\Front-end\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:7960:31
    at Array.map (<anonymous>)
    at AngularDependencies.getDependencies (C:\Users\MartijnDormans\OneDrive - Mediaan abs b.v\Project\Front-end\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:7949:21)
    at CliApplication.Application.getDependenciesData (C:\Users\MartijnDormans\OneDrive - Mediaan abs b.v\Project\Front-end\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:9498:40)
```

When i look into the application-54cd2170.js file i can see at line 5691 the following method:
```
RouterParserUtil.prototype.cleanCallExpressions = function (sourceFile) {
        var file = sourceFile;
        var variableStatements = sourceFile.getVariableDeclaration(function (v) {
            var result = false;
            if (typeof v.compilerNode.type !== 'undefined') {
                result = v.compilerNode.type.typeName.text === 'Routes';
            }
            return result;
        });
        var initializer = variableStatements.getInitializer();
        var _loop_5 = function (callExpr) {
            if (callExpr.wasForgotten()) {
                return "continue";
            }
            callExpr.replaceWithText(function (writer) { return writer.quote(callExpr.getText()); });
        };
        for (var _i = 0, _a = initializer.getDescendantsOfKind(Ast.SyntaxKind.CallExpression); _i < _a.length; _i++) {
            var callExpr = _a[_i];
            _loop_5(callExpr);
        }
        return file;
    };
```

So it has probably something to do with my lazy loaded routes:

```
const routes: Routes = [
  { path: '', loadChildren: () => import('./dashboard/dashboard.module').then(m => m.DashboardModule) },
  { path: 'documents', loadChildren: () => import('./documents/documents.module').then(m => m.DocumentsModule) }];
```

##### **Operating System, Node.js, npm, compodoc version(s)**

Win10, compodoc 1.1.11, npm 6.10.2, node 12.9.1

##### **Angular configuration, a `package.json` file in the root folder**

{
  "name": "front-end",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "start:mock": "ng serve --configuration=mock",
    "compodoc": "compodoc --config .compodocrc",
    "doc": "npx compodoc -p tsconfig.doc.json -s -n \"Function Point documentation\"",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e --configuration=mock"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^8.2.14",
    "@angular/cdk": "^8.1.4",
    "@angular/common": "^8.2.14",
    "@angular/compiler": "^8.2.14",
    "@angular/core": "^8.2.14",
    "@angular/flex-layout": "^8.0.0-beta.27",
    "@angular/forms": "^8.2.14",
    "@angular/material": "^8.1.4",
    "@angular/platform-browser": "^8.2.14",
    "@angular/platform-browser-dynamic": "^8.2.14",
    "@angular/router": "^8.2.14",
    "@azure/msal-angular": "^0.1.4",
    "angular-split": "^3.0.2",
    "hammerjs": "^2.0.8",
    "lodash": "^4.17.15",
    "rxjs": "~6.4.0",
    "rxjs-compat": "^6.5.3",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.803.19",
    "@angular/cli": "^8.3.19",
    "@angular/compiler-cli": "^8.2.14",
    "@angular/language-service": "^8.2.14",
    "@compodoc/compodoc": "^1.1.11",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/lodash": "^4.14.149",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-reporters": "^2.3.2",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "karma-junit-reporter": "^1.2.0",
    "protractor": "~5.4.0",
    "puppeteer": "^1.20.0",
    "ts-node": "~7.0.0",
    "tslint": "^5.20.1",
    "typescript": "~3.5.3"
  }
}

##### **Compodoc installed globally or locally ?**

locally

##### **If possible sourcecode of the file where it breaks**

```
const routes: Routes = [
  { path: '', loadChildren: () => import('./dashboard/dashboard.module').then(m => m.DashboardModule) },
  { path: 'documents', loadChildren: () => import('./documents/documents.module').then(m => m.DocumentsModule) }];

dashboard.module file:

const routes: Routes = [
  { path: '', component: DashboardComponent, canDeactivate: [CanDeactivateDashboardGuard]}
];
```

##### **If possible your terminal logs before the error**

```
[08:34:20] Searching package.json file
[08:34:20] package.json file found
[08:34:20] Processing package.json dependencies
[08:34:20] Searching README.md, CHANGELOG.md, CONTRIBUTING.md, LICENSE.md, TODO.md files
[08:34:20] README.md file found
[08:34:20] Error during C:\Users\MartijnDormans\OneDrive - Mediaan abs b.v\Project\Front-end\CHANGELOG read
[08:34:20] Continuing without CHANGELOG.md file
[08:34:20] Error during C:\Users\MartijnDormans\OneDrive - Mediaan abs b.v\Project\Front-end\CONTRIBUTING read
[08:34:20] Continuing without CONTRIBUTING.md file
[08:34:20] Error during C:\Users\MartijnDormans\OneDrive - Mediaan abs b.v\Project\Front-end\LICENSE read
[08:34:20] Continuing without LICENSE.md file
[08:34:20] Error during C:\Users\MartijnDormans\OneDrive - Mediaan abs b.v\Project\Front-end\TODO read
[08:34:20] Continuing without TODO.md file
[08:34:20] Get dependencies data
```

##### **Motivation for or Use Case**

I think that the new lazy loading syntax is not working for me. So, or I am doing something wrong or the new feature from update 1.1.11 is not working correctly.

##### **Reproduce the error**

Make a project with lazy loaded routes to modules that also contain some routes. See the source code section to reproduce.

##### **Related issues**

I think Issue #889 is related

##### **Suggest a Fix**

I think it has something to do with lazy loading. I don't know how to fix it and it would be much more helpful if there was an option to disable it. So I can still generate the other documentations.

**Comment by Justinapeldoorn** [comment]
I have encountered a similar issue, i get the following stacktrace:
`
Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'text' of undefined
      at D:\repositories\web-twd\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:5691:55
      at Function.ArrayUtils.find (D:\repositories\web-twd\node_modules\ts-simple-ast\dist\utils\ArrayUtils.js:38:21)
      at Object.getNodeByNameOrFindFunction (D:\repositories\web-twd\node_modules\ts-simple-ast\dist\utils\compiler\getNodeByNameOrFindFunction.js:10:36)
      at SourceFile.StatementedNode.class_1.getVariableDeclaration (D:\repositories\web-twd\node_modules\ts-simple-ast\dist\compiler\statement\StatementedNode.js:312:28)
      at RouterParserUtil.cleanCallExpressions (D:\repositories\web-twd\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:5688:45)
      at AngularDependencies.getSourceFileDecorators (D:\repositories\web-twd\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8151:46)
      at D:\repositories\web-twd\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:7960:31
      at Array.map (<anonymous>)
      at AngularDependencies.getDependencies (D:\repositories\web-twd\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:7949:21)
      at CliApplication.Application.getDependenciesData (D:\repositories\web-twd\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:9498:40)
} reason: TypeError: Cannot read property 'text' of undefined
    at D:\repositories\web-twd\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:5691:55
    at Function.ArrayUtils.find (D:\repositories\web-twd\node_modules\ts-simple-ast\dist\utils\ArrayUtils.js:38:21)
    at Object.getNodeByNameOrFindFunction (D:\repositories\web-twd\node_modules\ts-simple-ast\dist\utils\compiler\getNodeByNameOrFindFunction.js:10:36)
    at SourceFile.StatementedNode.class_1.getVariableDeclaration (D:\repositories\web-twd\node_modules\ts-simple-ast\dist\compiler\statement\StatementedNode.js:312:28)
    at RouterParserUtil.cleanCallExpressions (D:\repositories\web-twd\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:5688:45)
    at AngularDependencies.getSourceFileDecorators (D:\repositories\web-twd\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8151:46)
    at D:\repositories\web-twd\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:7960:31
    at Array.map (<anonymous>)
    at AngularDependencies.getDependencies (D:\repositories\web-twd\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:7949:21)
    at CliApplication.Application.getDependenciesData (D:\repositories\web-twd\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:9498:40)
`

**Our routing (also lazy loaded)**
`export const AppRoutes: Routes = [{
    path: '',
    pathMatch: 'full',
    redirectTo: BU
  }, {
    path: BU,
    loadChildren: () => import('./core/twd-bu/twd-bu.module').then(m => m.TwdBuModule)
  }, {
    path: SD,
    loadChildren: () => import('./core/twd-sd/twd-sd.module').then(m => m.TwdSdModule)
  }, {
    path: BD,
    loadChildren: () => import('./core/twd-bd/twd-bd.module').then(m => m.TwdBdModule)
  }
];`

I did get it working however by adding a undefined check in the application-54cd2170.js at line 5690:
` if (typeof v.compilerNode.type !== 'undefined' && **v.compilerNode.type.typeName !== undefined)** {` 

**possible solution**
I did not look in to the problem at all and I lack any context, but my first guess would be to look at `router-parser.util.ts` adding the undefined check for the v.compilerNode.type.typeName at line 692 did the trick for me... But without knowing the context, I don't know which step I'm skipping by adding the undefined check.
