### ISSUE TITLE
Unhandled Rejection at Promise

### ISSUE THREAD

**Issue by sushya90** [compodoc/compodoc#904]
##### **Overview of the issue**

Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'text' of undefined
      at AngularDependencies.getSymboleName (C:\Users\sushant.lawate\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8725:26)
      at visitDecorator (C:\Users\sushant.lawate\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8170:42)
      at Array.forEach (<anonymous>)
      at parseNode (C:\Users\sushant.lawate\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8304:64)
      at C:\Users\sushant.lawate\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8575:13
      at visitNodes (C:\Users\sushant.lawate\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:14786:30)
      at Object.forEachChild (C:\Users\sushant.lawate\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:15012:24)
      at AngularDependencies.getSourceFileDecorators (C:\Users\sushant.lawate\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8155:16)
      at C:\Users\sushant.lawate\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:7960:31
      at Array.map (<anonymous>) } reason: TypeError: Cannot read property 'text' of undefined
    at AngularDependencies.getSymboleName (C:\Users\sushant.lawate\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8725:26)

##### **Operating System, Node.js, npm, compodoc version(s)**

Windows 10
Node.js 10.16.0
npm 6.10.0
compodoc 1.1.11

##### **Angular configuration, a `package.json` file in the root folder**

{
  "name": "angular-io-example",
  "version": "1.0.0",
  "private": true,
  "description": "Example project from an angular.io guide.",
  "scripts": {
    "lint": "tslint ./app/**/*.ts -t verbose",
    "start": "ng serve --host 0.0.0.0 --port 4200",
    "test": "ng test",
    "build-prod": "ng build --prod --configuration=production",
    "build-qa": "ng build --prod --configuration=qa",
    "build-dev": "ng build --prod --configuration=dev",
    "e2e": "ng e2e",
    "ng": "ng"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@agm/core": "^1.0.0-beta.5",
    "@angular/animations": "^7.1.4",
    "@angular/common": "^7.1.4",
    "@angular/compiler": "^7.1.4",
    "@angular/core": "^7.1.4",
    "@angular/forms": "^7.1.4",
    "@angular/http": "^7.1.4",
    "@angular/platform-browser": "^7.1.4",
    "@angular/platform-browser-dynamic": "^7.1.4",
    "@angular/router": "^7.1.4",
    "@angular/upgrade": "^7.1.4",
    "@google/maps": "^0.5.5",
    "@ng-select/ng-select": "^2.20.5",
    "angular-2-dropdown-multiselect": "^1.8.1",
    "angular-in-memory-web-api": "^0.6.0",
    "bootstrap": "^4.1.3",
    "core-js": "^2.5.4",
    "echarts": "^4.2.0-rc.2",
    "html2canvas": "^1.0.0-rc.2",
    "jquery": "^3.3.1",
    "moment": "^2.22.2",
    "moment-timezone": "^0.5.21",
    "mydatepicker": "^2.6.6",
    "ng2-auto-complete": "^0.12.0",
    "ng2-select": "^2.0.0",
    "ng2-tel-input": "^1.0.16",
    "ngx-bootstrap": "^3.1.1",
    "ngx-clipboard": "^11.1.9",
    "ngx-echarts": "^4.0.0",
    "ngx-facebook": "^2.4.0",
    "ngx-pagination": "^4.1.0",
    "rxjs": "^6.0.0",
    "rxjs-compat": "^6.3.3",
    "zone.js": "^0.8.24"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.0",
    "@angular/cli": "^6.2.5",
    "@angular/compiler-cli": "^7.1.4",
    "@angular/platform-server": "^7.1.4",
    "@types/googlemaps": "^3.36.4",
    "@types/jasmine": "~2.8.0",
    "@types/jasminewd2": "^2.0.3",
    "@types/node": "^6.0.45",
    "html-webpack-plugin": "^3.2.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-phantomjs-launcher": "^1.0.2",
    "lodash": "^4.16.2",
    "phantomjs-prebuilt": "^2.1.7",
    "promise-js": "0.0.7",
    "protractor": "~5.3.0",
    "style-loader": "^0.23.1",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.2",
    "to-string-loader": "^1.1.5",
    "ts-node": "^5.0.1",
    "tslint": "^5.9.1",
    "typescript": "3.1.6",
    "webpack-dev-server": "^3.7.1"
  },
  "repository": {}
}

##### **Compodoc installed globally or locally ?**

Globally

##### **If possible your terminal logs before the error**

[16:49:15] parsing        : D:/Sushant Lawate/orbitui/app/src/views/campaigns/campaign/campaign.view/sms.medium/sms.medium.component.ts
[16:49:15] found          : SMSViewComponent
[16:49:15] parsing        : D:/Sushant Lawate/orbitui/app/src/views/campaigns/audiences/audience/detail.targeting/detail.targeting.component.ts
[16:49:15] found          : DetailTargetingComponent
[16:49:15] parsing        : D:/Sushant Lawate/orbitui/app/src/views/campaigns/audiences/audience/facebook.detail.targeting/facebook.detail.targeting.component.ts
[16:49:15] found          : FacebookDetailTargetingComponent
Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'text' of undefined
      at AngularDependencies.getSymboleName (C:\Users\sushant.lawate\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8725:26)
      at visitDecorator (C:\Users\sushant.lawate\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8170:42)
      at Array.forEach (<anonymous>)
      at parseNode (C:\Users\sushant.lawate\AppData\Roaming\npm\node_modules\@compodoc\compodoc\dist\application-54cd2170.js:8304:64)

**Comment by sushya90** [comment]
I have already try previous fixes solution but they didn't getting work.

**Comment by sushya90** [comment]
I have close this issue since not getting any reply.
