### ISSUE TITLE
[BUG]: Error when using environment in Routes definition 

### ISSUE THREAD

**Issue by hudzenko** [compodoc/compodoc#965]
##### **Overview of the issue**

In my routes definitions I have conditional redirectTo statement depends on env boolean property:
`redirectTo: environment.isEnabled ? 'one' : 'other',`

Because of this compodoc throws an error:
```
Unhandled Rejection at: Promise {
  <rejected> Error: Could not find the node's symbol.
      at InvalidOperationError.BaseError [as constructor] (/Users/ava.codes/PhpstormProjects/mona/client/node_modules/ts-simple-ast/dist/errors/BaseError.js:7:28)
      at new InvalidOperationError (/Users/ava.codes/PhpstormProjects/mona/client/node_modules/ts-simple-ast/dist/errors/InvalidOperationError.js:8:28)
      at Object.throwIfNullOrUndefined (/Users/ava.codes/PhpstormProjects/mona/client/node_modules/ts-simple-ast/dist/errors/helpers.js:96:15)
      at Identifier.Node.getSymbolOrThrow (/Users/ava.codes/PhpstormProjects/mona/client/node_modules/ts-simple-ast/dist/compiler/common/Node.js:131:23)
      at RouterParserUtil.cleanFileDynamics (/Users/ava.codes/PhpstormProjects/mona/client/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:5668:18)
      at AngularDependencies.getSourceFileDecorators (/Users/ava.codes/PhpstormProjects/mona/client/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:8152:46)
      at /Users/ava.codes/PhpstormProjects/mona/client/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:7960:31
      at Array.map (<anonymous>)
      at AngularDependencies.getDependencies (/Users/ava.codes/PhpstormProjects/mona/client/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:7949:21)
      at CliApplication.Application.getDependenciesData (/Users/ava.codes/PhpstormProjects/mona/client/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:9498:40) } reason: Error: Could not find the node's symbol.
    at InvalidOperationError.BaseError [as constructor] (/Users/ava.codes/PhpstormProjects/mona/client/node_modules/ts-simple-ast/dist/errors/BaseError.js:7:28)
    at new InvalidOperationError (/Users/ava.codes/PhpstormProjects/mona/client/node_modules/ts-simple-ast/dist/errors/InvalidOperationError.js:8:28)
    at Object.throwIfNullOrUndefined (/Users/ava.codes/PhpstormProjects/mona/client/node_modules/ts-simple-ast/dist/errors/helpers.js:96:15)
    at Identifier.Node.getSymbolOrThrow (/Users/ava.codes/PhpstormProjects/mona/client/node_modules/ts-simple-ast/dist/compiler/common/Node.js:131:23)
    at RouterParserUtil.cleanFileDynamics (/Users/ava.codes/PhpstormProjects/mona/client/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:5668:18)
    at AngularDependencies.getSourceFileDecorators (/Users/ava.codes/PhpstormProjects/mona/client/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:8152:46)
    at /Users/ava.codes/PhpstormProjects/mona/client/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:7960:31
    at Array.map (<anonymous>)
    at AngularDependencies.getDependencies (/Users/ava.codes/PhpstormProjects/mona/client/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:7949:21)
    at CliApplication.Application.getDependenciesData (/Users/ava.codes/PhpstormProjects/mona/client/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:9498:40)
```

Error disappears when I set static redirectTo.
In general it is smth similar https://github.com/compodoc/compodoc/issues/525 but a little bit different.

##### **Operating System, Node.js, npm, compodoc version(s)**

Operating System: macOs Catalina;
Node: v10.16.0;
npm: 6.10.1
compodoc: 1.1.11;

##### **Angular configuration, a `package.json` file in the root folder**

This is private. Can answer any specific info if needed.

##### **Compodoc installed globally or locally ?**

Same error for local and global usage

##### **If possible sourcecode of the file where it breaks**

```
const routes: Routes = [
    {
        path: '',
        component: SomeComponent,
        children: [
            {
                path: '',
                pathMatch: 'full',
                redirectTo: environment.isEnabled ? 'one' : 'other', // this condition brakes compodoc
                // redirectTo: 'rfid',
            },
            {
                path: 'one',
                component: OneComponent,
            },
            {
                path: 'other',
                component: OtherComponent,
            },
        ],
    },
];
```

##### **If possible your terminal logs before the error**

Last log before error:
`[13:06:37] Analysing routes definitions and clean them if necessary`

##### **Motivation for or Use Case**

Because I can not normally use compodoc. Have to temporary change route definition each time to run compodoc

##### **Related issues**

https://github.com/compodoc/compodoc/issues/525

**Comment by hudzenko** [comment]
I understand that this partly kind of not compatible with static code analysis, because it is conditional routing logic. But at least it will be good to have some workaround for that.

In my case I will use redirect guard instead as more complex workaround
