### ISSUE TITLE
[BUG] Compodoc 1.1.11 Issue in Angular 7.2.0 Workspace

### ISSUE THREAD

**Issue by akhilesh85** [compodoc/compodoc#971]
##### **Overview of the issue**

Compodoc 1.1.11 when installed in Angular 7.2.0 workspace gives an Issue. As per the documentation, it is stated that the Compodoc supports the Angular 7.x version.

##### **Operating System, Node.js, npm, compodoc version(s)**

Operating System: Mac OSX Mojave 10.14.6
Node.js: v12.15.0
Npm: 6.13.4
Compodoc Version: 1.1.11

##### **Compodoc installed globally or locally ?**

globally

##### **If possible sourcecode of the file where it breaks**

N/A

##### **If possible your terminal logs before the error**

837B66-T7GTFL:$ compodoc -p ./tsconfig.app.json -e json -d .

/Users/xxxxx/.npm-packages/lib/node_modules/@compodoc/compodoc/node_modules/unicode-trie/index.js:87
      data = inflate(data, new Uint8Array(uncompressedLength));

                           ^
						   
RangeError: Invalid typed array length: 2686059008
    at new Uint8Array (<anonymous>)
    at new UnicodeTrie (/Users/xxxxxx/.npm-packages/lib/node_modules/@compodoc/compodoc/node_modules/unicode-trie/index.js:87:28)
    at Object.<anonymous> (/Users/xxxxx/.npm-packages/lib/node_modules/@compodoc/compodoc/node_modules/linebreak/src/linebreaker.js:9:19)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/xxxxx/.npm-packages/lib/node_modules/@compodoc/compodoc/node_modules/pdfkit/js/pdfkit.js:9:19)

##### **Motivation for or Use Case**

Integrating storybook addons-docs, for Angular workspace storybook requires us to install Compodoc.

https://github.com/storybookjs/storybook/tree/next/addons/docs/angular

##### **Reproduce the error**

1. Install Compodoc latest version in an existing Angular 7 workspace

2. Run Compodoc

##### **Related issues**

No

##### **Suggest a Fix**

N/A

##### **Angular configuration, a `package.json` file in the root folder**

{
 "name": "angular-7-workspace",
  "version": "7.2.0",
  "scripts": {
    "ng": "ng"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "~1.0.0",
    "@angular/animations": "~7.2.0",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/http": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "@degjs/storybook-addon-taffy": "^1.0.4",
    "@ngrx/core": "~1.2.0",
    "@ngrx/data": "~8.0.1",
    "@ngrx/effects": "~8.0.1",
    "@ngrx/entity": "~8.0.1",
    "@ngrx/store": "~8.0.1",
    "@ngx-translate/core": "^12.1.2",
    "@ngx-translate/http-loader": "^4.0.0",
    "@storybook/addon-docs": "^5.3.19",
    "chart.js": "~2.8.0",
    "core-js": "~2.6.5",
    "date-fns": "~1.30.1",
    "hammerjs": "~2.0.8",
    "lodash": "^4.17.15",
    "rxjs": "~6.3.3",
    "swiper": "~3.4.0",
    "tslib": "~1.9.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.13.0",
    "@angular-devkit/build-ng-packagr": "~0.13.9",
    "@angular/cli": "~7.3.8",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/language-service": "~7.2.0",
    "@babel/core": "^7.10.4",
    "@storybook/addon-actions": "^5.3.19",
    "@storybook/addon-links": "^5.3.19",
    "@storybook/addon-notes": "^5.3.19",
    "@storybook/addons": "^5.3.19",
    "@storybook/angular": "^5.3.19",
    "@types/hammerjs": "~2.0.36",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/lodash": "^4.14.145",
    "@types/node": "~8.9.4",
    "babel-loader": "^8.1.0",
    "chokidar-cli": "^1.2.1",
    "codelyzer": "~4.5.0",
    "concurrently": "^4.1.0",
    "fs-extra": "^7.0.1",
    "http-server": "^0.11.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng-packagr": "^4.2.0",
    "npm-run": "^5.0.1",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tsickle": "^0.37.1",
    "tslib": "^1.9.0",
    "tslint": "~5.11.0",
    "typescript": "^3.2.4"
  }
}

**Comment by akhilesh85** [comment]
Hi @vogloblinsky 

Any findings with regard to this issue. I even tried to bump my node version but no luck.

Node: v12.18.0
NPM: v6.14.4

Please let me know.

Regards,
Akhilesh
