### ISSUE TITLE
[BUG] Unhandled Rejection at: Promise { SyntaxError: JSON5: invalid character '(' at 1:94

### ISSUE THREAD

**Issue by javierecr** [compodoc/compodoc#980]
I'm trying to run compodoc on my Angular 9 project and it keep throwing an error

Angular: 9.0.2
NPM: 12.14.0
Compodoc: 1.11.1
Typescript: 3.7.5

Im running `npx compodoc -p tsconfig.json`. Here's the error: 

```
Unhandled Rejection at: Promise {
  <rejected> SyntaxError: JSON5: invalid character '(' at 1:94
      at syntaxError (/Users/javier/Documents/dev/jaque/plato-puesto/node_modules/@compodoc/compodoc/node_modules/json5/lib/parse.js:1083:17)
      at invalidChar (/Users/javier/Documents/dev/jaque/plato-puesto/node_modules/@compodoc/compodoc/node_modules/json5/lib/parse.js:1028:12)
      at Object.value (/Users/javier/Documents/dev/jaque/plato-puesto/node_modules/@compodoc/compodoc/node_modules/json5/lib/parse.js:287:15)
      at lex (/Users/javier/Documents/dev/jaque/plato-puesto/node_modules/@compodoc/compodoc/node_modules/json5/lib/parse.js:78:42)
      at Object.parse (/Users/javier/Documents/dev/jaque/plato-puesto/node_modules/@compodoc/compodoc/node_modules/json5/lib/parse.js:25:17)
      at loopInsideModule (/Users/javier/Documents/dev/jaque/plato-puesto/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:5370:52)
      at loopRoutesParser (/Users/javier/Documents/dev/jaque/plato-puesto/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:5403:29)
      at loopRoutesParser (/Users/javier/Documents/dev/jaque/plato-puesto/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:5408:21)
      at loopRoutesParser (/Users/javier/Documents/dev/jaque/plato-puesto/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:5408:21)
      at loopRoutesParser (/Users/javier/Documents/dev/jaque/plato-puesto/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:5408:21) {
    lineNumber: 1,
    columnNumber: 94
  }
} reason: SyntaxError: JSON5: invalid character '(' at 1:94
    at syntaxError (/Users/javier/Documents/dev/jaque/plato-puesto/node_modules/@compodoc/compodoc/node_modules/json5/lib/parse.js:1083:17)
    at invalidChar (/Users/javier/Documents/dev/jaque/plato-puesto/node_modules/@compodoc/compodoc/node_modules/json5/lib/parse.js:1028:12)
    at Object.value (/Users/javier/Documents/dev/jaque/plato-puesto/node_modules/@compodoc/compodoc/node_modules/json5/lib/parse.js:287:15)
    at lex (/Users/javier/Documents/dev/jaque/plato-puesto/node_modules/@compodoc/compodoc/node_modules/json5/lib/parse.js:78:42)
    at Object.parse (/Users/javier/Documents/dev/jaque/plato-puesto/node_modules/@compodoc/compodoc/node_modules/json5/lib/parse.js:25:17)
    at loopInsideModule (/Users/javier/Documents/dev/jaque/plato-puesto/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:5370:52)
    at loopRoutesParser (/Users/javier/Documents/dev/jaque/plato-puesto/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:5403:29)
    at loopRoutesParser (/Users/javier/Documents/dev/jaque/plato-puesto/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:5408:21)
    at loopRoutesParser (/Users/javier/Documents/dev/jaque/plato-puesto/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:5408:21)
    at loopRoutesParser (/Users/javier/Documents/dev/jaque/plato-puesto/node_modules/@compodoc/compodoc/dist/application-54cd2170.js:5408:21) {
  lineNumber: 1,
  columnNumber: 94
}```

**Comment by BrsJsk** [comment]
I'm having the same issue..

**Comment by BrsJsk** [comment]
If you add
`--disableDependencies --minimal` arguments, it should pass.

**Comment by vogloblinsky** [comment]
Can i have the source code of the file before this error.

**Comment by jgomesmv** [comment]
This issue is still happening on version 1.1.14. In minimal mode as @BrsJsk mentioned it works.
Any update regarding this?
Thanks!

**Comment by matworks-awais** [comment]
Yes this issue still exist.

**Comment by tofikabdullayev** [comment]
same issue here

**Comment by rasmus-e-christensen** [comment]
Same issue here

**Comment by paolagodoy** [comment]
Same issue here
Unhandled Rejection at: Promise {
  <rejected> SyntaxError: JSON5: invalid character '(' at 1:1
      at syntaxError (/node_modules/json5/lib/parse.js:1083:17)
      at invalidChar (/node_modules/json5/lib/parse.js:1028:12)
      at Object.value (/node_modules/json5/lib/parse.js:287:15)

**Comment by emekaelo** [comment]
This issue is still happening in 1.1.21

**Comment by avrahamwn** [comment]
I got the same issue. 
When adding the --disableRoutesGraph flag to the commnd it works, but actually my main goal is to get this specific graph...
If I may guess, the cause to this bug is something related to not using simple string as route pathes. In my case, I use enums and Map objects such as:
```
{
        path: AppRoutePaths.LOGIN,
        component: LoginComponent
},
```

Any help here?

**Comment by emekaelo** [comment]
So sorry for not replying to this way earlier @avrahamwn 
The solution for me was to add an explicit value to the enum properties. In my case the first one had an explicit value of 1 while the second which caused the error had an implicit value of 2 so I had to specify explicitly with `= 2`.

https://github.com/compodoc/compodoc/issues/1124#issuecomment-1048083430 was how I traced the issue.
