### ISSUE TITLE
[BUG] Error thrown when diagram-js is a dependency

### ISSUE THREAD

**Issue by dimarobert** [compodoc/compodoc#983]
**Overview of the issue**

When running `npx compodoc -p tsconfig.json -e json -d .` in an AngularCLI 9 (angular 9.1.9, cli 9.1.7) project that has an npm dependency on [diagram-js](https://github.com/bpmn-io/diagram-js) throws the following error:

```
Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'kind' of undefined
      at isObjectOrObjectArrayTypeReference (<angular_cli_workspace>\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:20709:34)
      at parseNestedTypeLiteral (<angular_cli_workspace>\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:20748:43)
      at parseParameterOrPropertyTag (<angular_cli_workspace>\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:20733:85)
      at parseTag (<angular_cli_workspace>\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:20572:40)
      at <angular_cli_workspace>\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:20447:44
      at Object.scanRange (<angular_cli_workspace>\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:8611:26)
      at parseJSDocCommentWorker (<angular_cli_workspace>\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:20419:25)
      at Object.parseJSDocComment (<angular_cli_workspace>\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:20373:31)
      at addJSDocComment (<angular_cli_workspace>\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:15579:68)
      at createNodeWithJSDoc (<angular_cli_workspace>\node_modules\ts-simple-ast\node_modules\typescript\lib\typescript.js:15906:17) }
```

**Operating System, Node.js, npm, compodoc version(s)**
Operating System: Windows 10
Node.js: v10.16.0
Npm: 6.14.3
Compodoc Version: 1.1.11

**Compodoc installed globally or locally ?**
locally

**If possible sourcecode of the file where it breaks**
N/A

**Additional information**

For me the issue was in the `dist/vendor.js` file, A snippet of the code where it failed:

```js

/***/ "../node_modules/diagram-js/lib/util/SvgTransformUtil.js":
/*!***************************************************************!*\
  !*** ../node_modules/diagram-js/lib/util/SvgTransformUtil.js ***!
  \***************************************************************/
/*! exports provided: transform, translate, rotate, scale */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "transform", function() { return transform; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "translate", function() { return translate; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "rotate", function() { return rotate; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "scale", function() { return scale; });
/* harmony import */ var tiny_svg__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! tiny-svg */ "../node_modules/tiny-svg/dist/index.esm.js");



/**
 * @param {<SVGElement>} element
 * @param {Number} x
 * @param {Number} y
 * @param {Number} angle
 * @param {Number} amount
 */
```

it looked like it failed to parse the ` * @param {<SVGElement>} element` line, the `name` in `parseNestedTypeLiteral` is 
```
IdentifierObject {
  pos: 10462648,
  end: 10462655,
  flags: 65536,
  parent: undefined,
  escapedText: 'element' }
```

I tried to add the `dist/**` glob in an `exclude` array in a custom tsconfig but looking at the source code it looks like only .ts files can be excluded so I was unable to exclude my `dist/vendor.js`
https://github.com/compodoc/compodoc/blob/996db75d52f1cc80aa2db0827426542076b8f38d/src/index-cli.ts#L741

**Comment by vogloblinsky** [comment]
Try providing source folder at the end of the command : ```npx compodoc -p tsconfig.json -e json -d . MY_SOURCE_FOLDER```

**Comment by dimarobert** [comment]
@vogloblinsky thanks! that fixed it. closing.
